### PR TITLE
Fix #1731: Fix size mismatches due to inheritance issues.

### LINKED ISSUE #1731: java.util.AbstractList.sublist returns buggy iterators.
This happens when the list is not extend `RandomAccess`.

### PR DESCRIPTION
**Pull request by nicolasstucki**
Extract `AbstractListView` from `AbstractList` and added `onSizeChanged`
to manage all changes on the size of the view. Override `Iterator`s to
notify changes using the `onSizeChanged` method.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala [hunk 1]
```diff
@@ -320,6 +320,23 @@ trait ListTest[F <: ListFactory] extends CollectionTest[F] {
       expect(al1.get(1)).toEqual("zero")
       expect(al1.get(2)).toEqual("five")
 
+      println(al)
```
Comment (nicolasstucki) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala]: oops

File: javalib/src/main/scala/java/util/AbstractList.scala [hunk 2]
```diff
@@ -109,63 +116,59 @@ abstract class AbstractList[E] protected () extends AbstractCollection[E]
     iter.take(toIndex - fromIndex).foreach(_ => iter.remove())
   }
 
-  protected[this] def checkIndexInBounds(index: Int): Unit = {
+  protected def checkIndexInBounds(index: Int): Unit = {
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/AbstractList.scala]: Why remove `[this]`?

File: javalib/src/main/scala/java/util/AbstractList.scala [hunk 3]
```diff
@@ -109,63 +116,59 @@ abstract class AbstractList[E] protected () extends AbstractCollection[E]
...
-    }
+private abstract class AbstractListView[E](protected val list: List[E],
+    fromIndex: Int, private var toIndex: Int) extends AbstractList[E] {
 
-    override def addAll(c: Collection[_ <: E]): Boolean =
-      addAll(size, c)
+  override def add(index: Int, e: E): Unit = {
+    checkIndexOnBounds(index)
+    list.add(fromIndex + index, e)
+    toIndex += 1
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/AbstractList.scala]: Maybe this, and other updates to `toIndex` in this class, should now call `changeViewSize` instead?

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala [hunk 4]
```diff
@@ -320,6 +320,23 @@ trait ListTest[F <: ListFactory] extends CollectionTest[F] {
...
+      expect(al1Iter.hasNext).toBeTruthy
+      expect(al1Iter.next()).toEqual("five")
+      expect(al1Iter.hasNext).toBeFalsy
+      expect(al1Iter.hasPrevious).toBeTruthy
+      expect(al1Iter.previous()).toEqual("five")
+      expect(al1Iter.hasPrevious).toBeTruthy
+      expect(al1Iter.previous()).toEqual("zero")
+      expect(al1Iter.hasPrevious).toBeTruthy
+      expect(al1Iter.previous()).toEqual("nine")
+      expect(al1Iter.hasPrevious).toBeFalsy
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala]: Why did this fail before the fix? It seems that all of this never changes sizes.

File: javalib/src/main/scala/java/util/AbstractList.scala [hunk 5]
```diff
@@ -253,11 +258,14 @@ private class RandomAccessListIterator[E](list: List[E], private var i: Int,
...
   def add(e: E): Unit = {
     list.add(i, e)
-    end += 1
+    onSizeChanged(1)
     last = -1
     i += 1
   }
 
+  protected def onSizeChanged(delta: Int): Unit =
+    end += delta
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/AbstractList.scala]: Why does this have an "event" name (`on...`) and `changeViewSize` not? Wouldn't it make more sense to call this `changeIterSize`?

**Comment by sjrd** [comment]
The commit message should use the present tense.
It also contains a typo (overloafed)

**Comment by sjrd** [comment]
That's all.

File: javalib/src/main/scala/java/util/AbstractList.scala (hunk 2 above)
Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/AbstractList.scala]: no reason, I'll remove that change.

File: javalib/src/main/scala/java/util/AbstractList.scala (hunk 5 above)
Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/AbstractList.scala]: Because in the views it is used as an event to notify that the size has changed.

Comment (sjrd) [inline javalib/src/main/scala/java/util/AbstractList.scala]: Then, I think the actual change of `end` should not be part of `onSizeChanged`. `end` should first be updated, then `onSizeChanged` should be called. It seems a bit weird that the "default" implementation of an event handler would actually *do* things. Maybe my point of view is still influenced by Delphi's VCL design, though.

**Comment by sjrd** [comment]
The commit message still includes several verbs with past tense.

File: javalib/src/main/scala/java/util/AbstractList.scala (hunk 5 above)
Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/AbstractList.scala]: You are right, because my approach allays requires the call to `super.onSizeChange` when overloading and this may be easily broken by mistake.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala (hunk 4 above)
Comment (nicolasstucki) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala]: It wasn't modification during iteration that showed the bug, it was after executing the `clear` operation. But I'll add tests for modification with the iterator.

File: javalib/src/main/scala/java/util/AbstractList.scala [hunk 6]
```diff
@@ -118,54 +125,61 @@ abstract class AbstractList[E] protected () extends AbstractCollection[E]
...
-      toIndex -= _toIndex - _fromIndex
-    }
+  protected def changeViewSize(delta: Int): Unit =
+    toIndex += delta
+}
+
+private trait SizeChangeEvent {
+  protected var end: Int
 
+  protected def changeSize(delta: Int): Unit = {
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/AbstractList.scala]: It would be good to mark this `@inline` to compensate for the indirections caused by the mixin.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala [hunk 7]
```diff
@@ -287,6 +289,23 @@ trait ListTest[F <: ListFactory] extends CollectionTest[F] {
...
+      def testListIterator(list: ju.List[String], expected: Seq[String]): Unit = {
+        val iter = list.listIterator
+        for (elem <- expected) {
+          expect(iter.hasNext).toBeTruthy
+          expect(iter.next()).toEqual(elem)
+        }
+        if(iter.hasNext)
+          println(iter.next)
+          else
+        expect(iter.hasNext).toBeFalsy
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala]: Indentation issue.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala [hunk 8]
```diff
@@ -287,6 +289,23 @@ trait ListTest[F <: ListFactory] extends CollectionTest[F] {
     }
 
     it("should give a sublist backed up by the original list") {
+      def testListIterator(list: ju.List[String], expected: Seq[String]): Unit = {
+        val iter = list.listIterator
+        for (elem <- expected) {
+          expect(iter.hasNext).toBeTruthy
+          expect(iter.next()).toEqual(elem)
+        }
+        if(iter.hasNext)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/ListTest.scala]: Missing space after `if`

**Comment by sjrd** [comment]
I don't understand this part of the commit message:

> Overloaded `Iterator`s to notify changes using the `onSizeChanged` method.

Did you mean "override"? Even so it's still a bit obscure.

**Comment by sjrd** [comment]
That's all.

**Comment by nicolasstucki** [comment]
retest this please :)

**Comment by nicolasstucki** [comment]
Jenkins retest this please and this time don't timeout. Thanks.

**Comment by sjrd** [comment]
I'm not sure why you're so intent in getting a CI success, since there are still comments that are not addressed anyway?

**Comment by sjrd** [comment]
LGTM
