### PR TITLE
Fix #4710: Specify our javalib extended binary API.

### LINKED ISSUE #4710: Specify the additional binary API of our javalib wrt. the JDK
From the discussion at https://github.com/scala-js/scala-js/pull/4677#discussion_r914132518

As we want to actually separate the `javalib` in its own artifact, the additional API it provides to `scalajs-library` becomes public information. Therefore, we need to actually specify it in some way or another.

Among that API, there are two methods that are effectively already publicly guaranteed to exist: `StackTraceElement.{get,set}ColumnNumber`, defined at
https://github.com/scala-js/scala-js/blob/112def5cb59b942d8b2c4c5791b17ea0c7c4a7dc/javalib/src/main/scala/java/lang/StackTraceElement.scala#L29-L38
and tested at
https://github.com/scala-js/scala-js/blob/112def5cb59b942d8b2c4c5791b17ea0c7c4a7dc/test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/StackTraceElementJSTest.scala#L24-L40

Other than that, there are:
* `Throwable.setStackTraceInternal` (used in `js.JavaScriptException` -- both the one in scalajs-library and the one in the linker-private-library)
  * There's a `getStackTraceInternal` but it's only used by `j.l.StackTrace`, so that one can be made `private[lang]`.
* All the methods in `TypedArrayBufferBridge`

So how do we specify that API?

### PR DESCRIPTION
**Pull request by sjrd**
We introduce a new library `javalibintf`, which is Java-only and contains no implementation. It only defines the extended binary API of our javalib.

There were two areas in which the javalib silently exposed an extended API: TypedArray Buffers, and the column number of StackTraceElements. We now define well-specified APIs as static methods for all these secret APIs.

The APIs specified in Java by javalibintf are implemented in Scala.js by the javalib. They are used from the scalajs-library. The `library` depends on `javalibintf` in the Provided scope, so that it is available at compile-time (and in IDEs) but does not transitively appear in clients of the `library`. This is important because the APIs are weakly typed when it comes to JavaScript types such as `TypedArray`s. We do not want regular user to get access to them too easily.

The `TypedArrayBuffer` API replaces the need for the `TypedArrayBufferBridge` hack in the build.

The `StackTraceElement` API is not currently used anywhere, because we did not have any feature in the `library` using them. So far, only the "reflection" API was specified. We may want to introduce a safer API in the `library` in the future.

We do publish the `javalibintf`, as it may be used by other language implementations. It will also be useful to be able to MiMa-check future versions of the `javalibintf`.

---

~~If #4712 is merged before this PR, we should update the code in `javalibintf/StackTraceElement.scala` to use the new constructor of `java.lang.StackTraceElement`.~~

### CODE REVIEW

**Comment by sjrd** [comment]
Rebased, and adapted the call to the constructor of `StackTraceElement`.

File: javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java [hunk 1]
```diff
@@ -0,0 +1,370 @@
...
+    throw new AssertionError("stub");
+  }
+
+  /**
+   * Wraps a view of a JavaScript {@code ArrayBuffer} as a direct
+   * {@link java.nio.ByteBuffer}.
+   *
+   * <p>The provided {@code array} parameter must be a valid JavaScript
+   * {@code ArrayBuffer}, otherwise the behavior of this method is not
+   * specified.
```
Comment (gzm0) [inline javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java:67]: Also clarify that the ArrayBuffer must have enough space?

**Review by gzm0 — APPROVED** [review]
Just one comment about documentation.

File: javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java (hunk 1 above)
Comment (sjrd) [reply javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java:67]: If it doesn't have enough space, a JavaScript `RangeError` exception is thrown, because `new Int8Array(array, byteOffset, length)` throws a `RangeError`. Do want me to make that explicit?

Comment (sjrd) [reply javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java:67]: Alternatively, we could move "up" the wrapping of the `ArrayBuffer` into an `Int8Array` within the scalajs-library. That would reduce the surface area of the javalib-intf.

**Comment by sjrd** [comment]
Updated with a first commit that gets rid of the `wrapArrayBuffer` overloads in the interface first.

File: javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java (hunk 1 above)
Comment (gzm0) [reply javalibintf/src/main/java/org/scalajs/javalibintf/TypedArrayBuffer.java]: Yes, I think we should do that.

I have also been wondering whether we can remove some of the accessor methods. But I realized I do not sufficiently understand how the whole byte order business works :-/

**Review by gzm0 — APPROVED** [review]
I didn't see you've already changed it :)
