### PR TITLE
Fix #4386: Do not merge dynamic dependencies into public modules

### LINKED ISSUE #4386: js.dynamicImport & ModuleSplitStyle.FewestModules may cause public modules to be imported by Scala.js code
This causes runtime failures, because the relevant (internal) symbols in the public modules are not exported.

Reproduction:

```scala
package helloworld

import scala.scalajs.js
import js.annotation._

object HelloWorld {
  def main(args: Array[String]): Unit = {
    js.dynamicImport {
      println("foo")
    }
  }
}
```

This will fail with: `TypeError: $j_main.$h_O is not a constructor` (because `$j_main` does not export $h_O`).

**Workarounds**

Either switch to `ModuleSplitStyle.SmallestModules` or add the following to your code:

```scala
object A {
  @JSExportTopLevel("foo", "dummy-module")
  def foo(): Unit = println("bar")
}
```

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala [hunk 1]
```diff
@@ -175,51 +176,73 @@ private object MaxModuleAnalyzer {
...
   }
 
-  /** Set of shortest, mutually prefix-free paths. */
-  private final class Paths[H, T] private (
-      private val content: mutable.Map[H, Paths[T, T]]) {
+  /** "Interesting" paths that can lead to a given class.
+   *
+   *  "Interesting" in this context means:
+   *  - All direct paths from a public dependency.
+   *  - All non-empty, mutually prefix free paths, of dynamic import hops.
```
Comment (sjrd) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala:183]:
```suggestion
   *  - All non-empty, mutually prefix-free paths of dynamic import hops.
```
?

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala [hunk 2]
```diff
@@ -175,51 +176,73 @@ private object MaxModuleAnalyzer {
...
+    }
+
+    def tags: (Set[ModuleID], Set[ClassName]) = {
+      /* Remove dynamic paths to class that are also reached by a public module.
+       * However, only do this if there are other tags as well. Otherwise, this
+       * class will end up in a public module, but the dynamically loaded module
+       * will try to import it (but importing public modules is forbidden).
+       */
+      if (direct.size > 1 || direct != dynamic.keySet) {
+        direct.foreach(dynamic.remove(_))
```
Comment (sjrd) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala:206]: Since there are side-effects in this method, `tags` should be declared and called with `()`, so as `def tags()`.

File: sbt-plugin/src/sbt-test/linker/basic-dynamic-import/Main.scala [hunk 3]
```diff
@@ -0,0 +1,12 @@
+package test
+
+import scala.scalajs.js
+
+object Main {
+  // Regression test for #4386. Arguably a bit of an abuse of sbt-test.
```
Comment (sjrd) [inline sbt-plugin/src/sbt-test/linker/basic-dynamic-import/Main.scala:6]: Could we use a linker test instead? Or is it too hard to check that it actually works?

**Review by sjrd — CHANGES_REQUESTED** [review]
Two minor comments, and one question about the scripted test.

File: sbt-plugin/src/sbt-test/linker/basic-dynamic-import/Main.scala (hunk 3 above)
Comment (gzm0) [reply sbt-plugin/src/sbt-test/linker/basic-dynamic-import/Main.scala:6]: I think we'd have to execute the JS we generate to be sure it works. So that would need ES module setup etc. :S Alternatively, we can also drop this test.

Comment (sjrd) [reply sbt-plugin/src/sbt-test/linker/basic-dynamic-import/Main.scala:6]: I suggest we drop the test. I'm a bit reluctant to create a precedent of using scripted tests for things that have in fact nothing to do with the sbt plugin. In Scala Native those have proliferated, and it's a nightmare in terms of test suite execution time.

**Review by sjrd — APPROVED** [review]
