### PR TITLE
Fix many bugs.

### LINKED ISSUE #2246: java.util.Formatter.format("%-s", ...) should throw MissingFormatWidthException.
This is an issue found while cross compiling `FormatterTest` `"should provide 's' conversion"`.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd.

**Comment by sjrd** [comment]
LGTM

**Comment by nicolasstucki** [comment]
Last commit message needs fix

**Comment by sjrd** [comment]
"fix {assert|expect}Throws swallowing exceptions." should come last, since it can only pass CI after all the other fixes are in, can't it?

**Comment by nicolasstucki** [comment]
No, in that one I use filters to avoid executing the tests that would fail.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 1]
```diff
@@ -323,8 +329,6 @@ class JUnitAssertionsTest {
 
     testIfAsserts(assertThat(Float.MaxValue, instanceOf(classOf[Float])))
     testIfAsserts(assertThat(Double.MaxValue, instanceOf(classOf[Double])))
-
-    testIfAsserts(assertThat(0, instanceOf[Int](classOf[Double])), ShallNotPass)
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: Why is this removed?

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 2]
```diff
@@ -355,4 +359,67 @@ class JUnitAssertionsTest {
...
         ShallNotPass)
   }
+
+  @Test def testIfAssertsTest_issue_2252(): Unit = {
+    Try(testIfAsserts(())) match {
+      case Success(_) => // As expected
+
+      case Failure(ex) =>
+        throw new AssertionError("testIfAsserts should not have thrown.").
+            initCause(ex)
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: Why not simply `throw ex`?

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 3]
```diff
@@ -355,4 +359,67 @@ class JUnitAssertionsTest {
...
+        throw ex
+    }
+
+    Try(testIfAsserts(throw new AssertionError)) match {
+      case Success(_) =>
+        fail("testIfAsserts should not succeed with <throw new AssertionError>")
+
+      case Failure(ex: AssertionError)
+        if ex.getMessage == "Assertion should not have failed." =>
+      // As expected
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: 4 spaces before `if`, 2 spaces before `//`

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 4]
```diff
@@ -355,4 +359,67 @@ class JUnitAssertionsTest {
...
+        // As expected
+
+      case Failure(ex: AssertionError)
+          if ex.getMessage == "Assertion should have failed." =>
+        fail("testIfAsserts should have succeed with <throw new AssertionError>")
+
+      case Failure(ex) => throw ex
+    }
+
+    val exept = new Exception
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: Typo: `except`

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala [hunk 5]
```diff
@@ -1,43 +1,50 @@
 package org.scalajs.testsuite.utils
 
+import scala.util.{Failure, Try, Success}
+
 object AssertThrows {
   /** Backport implementation of Assert.assertThrows to be used until JUnit 4.13 is
-   *  released. See org.junit.Assert.scala in jUnitRuntime.
-   */
+    * released. See org.junit.Assert.scala in jUnitRuntime.
+    */
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala]: Spurious change.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala [hunk 6]
```diff
@@ -1,43 +1,50 @@
...
   private def assertThrowsBackport(expectedThrowable: Class[_ <: Throwable],
       runnable: ThrowingRunnable): Unit = {
     expectThrowsBackport(expectedThrowable, runnable)
   }
 
   /** Backport implementation of Assert.expectThrows to be used until JUnit 4.13 is
-   *  released. See org.junit.Assert.scala in jUnitRuntime.
-   */
+    * released. See org.junit.Assert.scala in jUnitRuntime.
+    */
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala]: Spurious change.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala [hunk 7]
```diff
@@ -1,43 +1,50 @@
...
+    } else {
+      result
     }
   }
 
   /** Backport implementation of Assert.ThrowingRunnable to be used until
-   *  JUnit 4.13 is released. See org.junit.Assert.scala in jUnitRuntime.
-   */
+    * JUnit 4.13 is released. See org.junit.Assert.scala in jUnitRuntime.
+    */
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/utils/AssertThrows.scala]: Spurious change.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala (hunk 1 above)
Comment (nicolasstucki) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: It was just wrong on the JVM. It used too pass because of the assertThrows bug.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala (hunk 2 above)
Comment (nicolasstucki) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: For debugging, without it, it is harder to know if the assertion error was thrown unexpectedly.

Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: OK. It suggest it be left at the end of the previous line, in this case. It's too ugly like this ^^

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsTest.scala [hunk 8]
```diff
@@ -98,7 +125,8 @@ class CollectionsTest extends CollectionsTestBase {
       assertTrue(singletonSet.contains(toElem(0)))
       assertEquals(1, singletonSet.size)
       assertEquals(1, singletonSet.iterator.size)
-      checkImmutabilityOfSetApi(singletonSet, toElem(0))
+      checkUnmodifiabilityOfSetApi(singletonSet, toElem(0))
+      checkUnmodifiabilityOfSetApi(singletonSet, toElem(1))
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/CollectionsTest.scala]: Shouldn't a `singleton()` be immutable rather than unmodifiable?

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/niobuffer/BufferFactory.scala [hunk 9]
```diff
@@ -164,8 +164,11 @@ object BufferFactory {
     def allocBuffer(capacity: Int): BufferType =
       baseWrap(new Array[ElementType](capacity))
 
-    override def allocBuffer(pos: Int, limit: Int, capacity: Int): BufferType =
-      baseWrap(new Array[ElementType](capacity), pos, limit-pos)
+    override def allocBuffer(pos: Int, limit: Int, capacity: Int): BufferType = {
+      if (pos > limit)
+        throw new IllegalArgumentException
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/niobuffer/BufferFactory.scala]: Why is this change in the test suite? It should probably be somewhere in the `javalib/`, in whatever method is called by `baseWrap`. Otherwise we're not actually testing the implementation.

**Comment by sjrd** [comment]
That's all.

**Comment by sjrd** [comment]
That's all. LGTM if it's the right commit.

**Comment by nicolasstucki** [comment]
Yes, that change is meant for that commit as part of tests that started failing after the `assertThrows` was fixed. It is completely unrelated to the other `TreeSet` commit.
