### PR TITLE
Fix #1171: Split: Sometimes remove leading empty match

### LINKED ISSUE #1171: String.split / regex discrepancy
Found a small (but significant) bug.

Plain Scala:

``` scala
"abc".split("(?=a)").mkString("[",",","]")
// correctly returns [abc]
```

Plain JS:

``` scala
"abc".split(/(?=a)/)
// correctly returns [abc]
```

Scala.js

``` scala
"abc".split("(?=a)").mkString("[",",","]")
// incorrectly returns [,abc]
```

### PR DESCRIPTION
**Pull request by gzm0**
The conditions were determined experimentally since the JavaDoc is
note precise enough.

### CODE REVIEW

File: test-suite/src/test/scala/scala/scalajs/testsuite/javalib/RegexTest.scala [hunk 1]
```diff
@@ -52,6 +52,23 @@ object RegexTest extends JasmineTest {
       split("", "\n", Array(""))
       split("", "", Array(""))
 
+      // Should remove leading empty match under some conditions - #1171
+      // These tests are "measured" on the JVM since the spec is unclear
+      split("abc", "(?=a)", Array("abc"))
+      split("abc", "(?=b)", Array("a", "bc"))
+      split("abc", "(?=a)|b", Array("", "a", "c"))
+      split("abc", "", Array("", "a", "b", "c"))
+      split("abc", "(?=a)|(?=b)", Array("", "a", "bc"))
```
Comment (sjrd) [inline test-suite/src/test/scala/scala/scalajs/testsuite/javalib/RegexTest.scala]: Well, they now have specifically said it was an intended behavior change.
Bug reported as #2573
