### PR TITLE
Fix #4835: Treat excluded classes for Tagger as special hops.

### LINKED ISSUE #4833: High memory consumption during linking when using `ModuleSplitStyle.SmallModulesFor(...)`
This is based on a [discord discussion](https://discord.com/channels/632150470000902164/635668814956068864/1084860483305222254).

We have a webapp using  ModuleSplitStyle.SmallModulesFor(...). 
Scala 3.2.2, Scalajs 1.13

`fullLinkJS` (and `fastLinkJS`) produces a 7GB HashMap full of 50 million `linker.frontend.modulesplitter.Tagger$DynamicPaths`.
Which makes the compilation painfully slow.

No issues with the default split style `ModuleSplitStyle.FewesModules`, and also no issue with `ModuleSplitStyle.SmallestModules`

A tree that has the issue (not minimized at all) is available here: 
https://github.com/rmgk/reform-scalajs-linker-memory-issue
`sbt fullLinkJS` is enough to trigger the issue. I tested the split style by changing line 36 `build.sbt`.

@gzm0 tagging you as you requested this issue as a reminder (and I don’t think I can assign people) :-)

### LINKED ISSUE #4835: SmallModulesFor splitting style can cause circular dependencies between emitted modules
Minimal example:

```scala
import scala.scalajs.js.annotation._

package helloworld {
  object HelloWorld {
    def main(args: Array[String]): Unit = {
      println(A.baz())
    }

    @JSExportTopLevel("yolo", "mod")
    def exp() = A.baz()
  }

  object A {
    @noinline
    def baz() = app.A.foo() + B.bar()
  }

  object B {
    @noinline
    def bar() = 1
  }
}

package app {
  object A {
    @noinline
    def foo() = helloworld.B.bar() + 1
  }
}
```

Observation:

```
[error] (helloworld2_12 / Compile / fastLinkJS) java.lang.IllegalArgumentException: requirement failed: Must have exactly one root module
```

Which is this assertion here: https://github.com/scala-js/scala-js/blob/44014be9ef5904f3b19052ac5c9861b1020567c4/linker/shared/src/main/scala/org/scalajs/linker/standard/ModuleSet.scala#L47-L48

Disabling it, we can observe that we generate the following modules:

```
app.A$.js.map
internal-30d24927543dc20e4b7b5599dbff65130a4a6a4a.js
main.js
mod.js
```

And the two internal modules depend on each other.

This is essentially the degenerate case described here: https://github.com/scala-js/scala-js/issues/4833#issuecomment-1475252934

The reason this happens is that the SmallModulesFor analyzer abuses dynamic edges to avoid this scenario. But at the same time, dynamic edges analyze possible execution flows to avoid oversplitting.

### PR DESCRIPTION
**Pull request by gzm0**
Previously, we more or less abused the concept of dynamic dependencies to handle them. This was based on the observation that we "must" split modules at those boundaries. See https://github.com/scala-js/scala-js/issues/4327#issuecomment-1059984564

However, as #4835 highlights, that observation ignored one aspect of dynamic dependencies: that when A--dyn-->B, A--static-->C and B--static-->C, by the time we load `B`, we know that `C` has already been loaded, and it is therefore OK to put A and C in the same module but not B.

For the excluded classes for `SmallModulesFor`, we cannot make that assumption. On the contrary, relying on it causes a circular dependency between the A-C module and the B module.

Instead, we now handle hops into excluded classes, from non-excluded classes, as special hops that need to be tracked. In the eventual tagging scheme of a class, we include the number of hops into excluded classes that are done to reach it from a root.

This commit also fixes #4833.

### CODE REVIEW

**Comment by gzm0** [comment]
Alternative to #4846.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala [hunk 1]
```diff
@@ -84,40 +173,47 @@ private class Tagger(infos: ModuleAnalyzer.DependencyInfo,
...
   }
 
-  private def tag(className: ClassName, pathRoot: ModuleID, pathSteps: List[ClassName]): Unit = {
+  private def tag(className: ClassName, pathRoot: ModuleID, pathSteps: List[ClassName],
+      excludedHopCount: Int, fromExcluded: Boolean): Unit = {
+    val isExcluded = excludedClasses.contains(className)
+
+    val newExcludedHopCount =
+      if (isExcluded && !fromExcluded) excludedHopCount + 1
+      else excludedHopCount
```
Comment (sjrd) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala:182]: While I don't think this it invalidates the proof relevance, this is inconsistent with the proof premises, which is
```
∀ (f, c) ∈ E : f ∈ F, c ∈ C ⇒ t(f) < t(c)
```
The way this is computed, what we ensure is instead
```
∀ (c, f) ∈ E : c ∈ C, f ∈ F ⇒ t(c) < t(f)
```
Since changing the proof is probably harder, consider changing the condition instead:
```suggestion
    val newExcludedHopCount =
      if (fromExcluded && !isExcluded) excludedHopCount + 1 // hop from fine to coarse
      else excludedHopCount
```

Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala:182]: Other than that, LGTM.

**Review by sjrd — APPROVED** [review]

**Comment by sjrd** [comment]
Thanks a lot for looking into this :)

**Comment by sjrd** [comment]
@gzm0 Is it fine with you if I go ahead with 1.13.1 when this PR is merged?

**Comment by gzm0** [comment]
> Is it fine with you if I go ahead with 1.13.1 when this PR is merged?

Yep, absolutely.
