### PR TITLE
Fix #4560: Explicitly redirect JS envs outputs to System.{out,err}.

### LINKED ISSUE #4560: Console output (e.g., println) not redirected to sbt client
Was: **Logs of `test` not redirected to sbt client**

## Reproduction Steps

```
# project/build.properties
sbt.version = 1.5.5
```

```scala
// plugins.sbt
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.7.0")
```

```scala
// build.sbt
lazy val example = project.in(file("."))
  .enablePlugins(ScalaJSPlugin)
  .settings(
    scalaVersion := "3.0.2",
    libraryDependencies ++= Seq(
      "org.scalameta" %%% "munit" % "0.7.29" % Test
    ),
    Test / scalaJSLinkerConfig ~= (_.withModuleKind(ModuleKind.CommonJSModule))
  )
```

```scala
// src/test/scala/example/ExampleTest.scala
package example

class ExampleTest extends munit.FunSuite {
  test("test 1") {
    assertEquals("123".size, 3)
  }
}
```

1. Start sbt client with `sbt -client`
2. Run `test`

The output is:
```
sbt:example> test
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 1 s, completed Sep 29, 2021 10:37:06 AM
```

## Expected output

```
sbt:example> test
example.ExampleTest:
  + test 1 0.00s
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 0 s, completed Sep 29, 2021 10:37:16 AM
```

## Notes

We probably need to investigate the code in the `sbt-scalajs` to determine if the cause of the bug is there or in sbt.

### PR DESCRIPTION
**Pull request by sjrd**
For discussion in #4560.

---

When running in server mode, sbt installs alternative streams for `System.out` and `System.err`. However, those alternatives are not used when launching separate processes with the inheritIO mode. By default, JS envs do precisely that, so they bypass the alternative streams set up by sbt.

We now explicitly redirect the outputs of JS envs to `System.out` and `System.err`, so that they take the alternative streams set up by sbt into account.

### CODE REVIEW

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 1]
```diff
@@ -48,6 +50,51 @@ private[sbtplugin] object ScalaJSPluginInternal {
...
+  private final class PipeOutputThread(from: InputStream, to: OutputStream) extends Thread {
+    override def run(): Unit = {
+      // Copied from scala.sys.process.BasicIO.transferFully
+      try {
+        val buffer = new Array[Byte](8192)
+        @tailrec def loop(): Unit = {
+          val byteCount = from.read(buffer)
+          if (byteCount > 0) {
+            to.write(buffer, 0, byteCount)
+            // flush() will throw an exception once the process has terminated
```
[the remark this answers is not in the document]
Comment (sjrd) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Indeed. I addressed that in the main commit.

File: test-adapter/src/main/scala/org/scalajs/testing/adapter/TestAdapter.scala [hunk 2]
```diff
@@ -135,21 +134,26 @@ final class TestAdapter(jsEnv: JSEnv, input: Seq[Input], config: TestAdapter.Con
 
 object TestAdapter {
   final class Config private (
-      val logger: Logger
+      val runConfig: RunConfig
```
[the remark this answers is not in the document]
Comment (sjrd) [reply test-adapter/src/main/scala/org/scalajs/testing/adapter/TestAdapter.scala]: I have added a second commit which should correspond to your suggestion of not exposing `RunConfig` in the `TestAdapter` config.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 3]
```diff
@@ -567,13 +550,46 @@ private[sbtplugin] object ScalaJSPluginInternal {
...
         enhanceNotInstalledException(resolvedScoped.value, log) {
           Await.result(run.future, Duration.Inf)
         }
+
+        /* Wait for the pipe output threads to be done, to make sure that we
+         * do not finish the `run` task before *all* output has been
+         * transferred to System.out and System.err.
+         */
+        for (pipeOutputThread <- pipeOutputThreads)
+          pipeOutputThread.join()
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:592]: Good catch! I also thought that we might need to provide this guarantee.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 4]
```diff
@@ -567,13 +550,46 @@ private[sbtplugin] object ScalaJSPluginInternal {
         log.debug(s"with JSEnv ${env.name}")
 
         val input = jsEnvInput.value
-        val config = baseRunConfig.withLogger(sbtLogger2ToolsLogger(log))
+
+        /* The list of threads that are piping output to System.out and
+         * System.err. This is not an AtomicReference or any other thread-safe
+         * structure because the `onOutputStream` callback is always called
+         * within the thread that calls `env.start()`.
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:557]: Hum, nothing to my knowledge in `JSEnv`'s spec guarantees this.

That being said, I think it is OK if this is a `var`, but its a bit more complicated:
- `onOutputStream` is guaranteed to be called exactly once.
- `pipeOutputThreads` is only read once the run is completed (while the `JSEnv` interface does not explicitly specify that the call to `onOutputStream` must happen before that, anything else is just plain unreasonable).

This explanation is missing an argument that there is an actual (chain) of memory barriers between the write(s) to `pipeOutputThreads` and the subsequent read. But that's probably OK...

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 5]
```diff
@@ -567,13 +550,46 @@ private[sbtplugin] object ScalaJSPluginInternal {
...
+          .withInheritOut(false)
+          .withInheritErr(false)
+          .withOnOutputStream { (out, err) =>
+            for ((optInput, output) <- List(out -> System.out, err -> System.err)) {
+              for (input <- optInput) {
+                val pipeOutputThread = new PipeOutputThread(input, output)
+                pipeOutputThreads ::= pipeOutputThread
+                pipeOutputThread.start()
+              }
+            }
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:578]: Consider:

```scala
pipeOutputThreads = (
  out.map(pipe(_, System.out)).toList ++
  err.map(pipe(_, System.err)).toList
)
```

Where `pipe` is a helper.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+     * don't have the try/catch around `flush()` because we do not use this
+     * method for stdin (only for stdout and stderr).
+     */
+    try {
+      val buffer = new Array[Byte](8192)
+      @tailrec def loop(): Unit = {
+        val byteCount = from.read(buffer)
+        if (byteCount > 0) {
+          to.write(buffer, 0, byteCount)
+          to.flush()
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala:32]: Why do we flush here? Isn't it `to`'s "Problem" when it flushes?

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+          loop()
+        }
+      }
+      loop()
+    } catch {
+      case _: InterruptedIOException => ()
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala:38]: When does this happen and why do we want to swallow the exception (rather than propagating up)?

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala [hunk 8]
```diff
@@ -0,0 +1,42 @@
...
+    }
+    from.close()
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala:40]: Is there a reason this is not in a `finally` block?

File: test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala [hunk 9]
```diff
@@ -15,14 +15,35 @@ package org.scalajs.testing.adapter
...
-  private val run = jsenv.startWithCom(input, config, handleMessage)
+  private val run: JSComRun = {
+    /* #4560 Explicitly redirect out/err to System.out/System.err, instead of
+     * relying on `inheritOut` and `inheritErr`, so that streams installed with
+     * `System.setOut` and `System.setErr` are always taken into account.
+     * sbt installs such alternative outputs when it runs in server mode.
+     *
+     * We never wait for these threads to finish. In theory, tasks that use the
+     * test adapter may complete before all output has been transferred to
+     * `System.out` and `System.err`.
```
Comment (gzm0) [inline test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala:34]: While that is fair from an execution schedule POV, it may swallow errors. Probably calling `reportFailure` as defined on the `TestAdapter` is a good stop-gap solution (maybe wrap with a different error).

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala (hunk 3 above)
Comment (gzm0) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:592]: On second read, this also has an error swallowing problem: If the `run` method of the `PipeOutputThread` throws (for whatever reason), we will simply consider the thread "done" here (`join` will not re-throw the exception).

**Review by gzm0 — CHANGES_REQUESTED** [review]
I think the second approach is better, at least for now.

It surfaces an error reporting problem though, that we probably should fix. I'm wondering if we should use Future's (with `blocking`) instead of threads. (OTOH that might put us at the mercy of the execution context supporting that :-/)

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala (hunk 3 above)
Comment (sjrd) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: I think this is actually the desired behavior. The uncaught exception will be printed to `System.err`, and then the thread will be `join`ed. The task will succeed, but I don't think that's a real issue.

File: test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala (hunk 9 above)
Comment (sjrd) [reply test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala:34]: Like for `run`, I don't see this as a real issue. If piping of the stdout/stderr streams fails, there will be an error printed on stderr. That seems enough to me (especially given the very low likelihood that any error *would* happen in there that would not also involve a failure of the process and hence an exception being thrown through a different channel).

**Review by sjrd — COMMENTED** [review]
Updated.

I believe I have addressed all the comments, except the error swallowing, which I argue is not actually an issue here (see the comments).

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala (hunk 6 above)
Comment (gzm0) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/PipeOutputThread.scala]: Ah, fair enough. Not sure we have a guarantee that the write call returns as soon as the other end of the pipe flushes, but I guess that's the best we can do.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala (hunk 3 above)
Comment (gzm0) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: >  but I don't think that's a real issue.

Wouldn't this be an issue for automated execution? Primarily CI comes to mind. Say for example a piper thread cannot allocate the memory block.

File: test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala (hunk 9 above)
Comment (gzm0) [reply test-adapter/src/main/scala/org/scalajs/testing/adapter/JSEnvRPC.scala:34]: Similar argument: For human/interactive use, this is absolutely fine. However, for CI or other automated use, such behavior is very hostile.

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala (hunk 3 above)
Comment (sjrd) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Not being able to allocate the memory block would be a fatal error. Even Futures don't catch that, and rather they will typically let the errors be sent to the console. If that is our failure model, I'm sure we have loads of places in the existing codebase with problems like that.

If you feel we must, I can make sure to rethrow here any exception that arises in the piper threads. However, for the TestAdapter case, I don't see any solution: we don't have any place (I think) where we know that the tests are done, and that we should sync up with the piper threads. And in fact, even with the status quo of using redirectIO, I'm not sure we have any guarantee that stuff sent to the console will always be printed before the tasks ends, do we?

Comment (sjrd) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Perhaps a stronger argument is that is already better than for Scala/JVM. For Scala/JVM, with `fork := true`, sbt uses unmonitored piping threads to forward stdout and stderr. It doesn't monitor exceptions in them, and does not even try to `join()` them.

Being somehow better than Scala/JVM at managing this seems like a stretch goal to me, and if it complicates our code, we should not aim that high.

The same applies for the testing infrastructure.

Comment (gzm0) [reply sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Sad but true...

**Review by gzm0 — APPROVED** [review]

**Comment by sjrd** [comment]
Thanks.

I just noticed. The PR wasn't really ready for merging; it should have been squashed first. Should I rollback the commits on master and recreate a squashed commit, or do we leave it as is?

**Comment by gzm0** [comment]
Oh... Right. I'd rollback master, since there is nothing else on it yet.

**Comment by sjrd** [comment]
Done. Resubmitted as #4595.
