### PR TITLE
Fix #2376: PhantomJSEnv does not escape JS code

### LINKED ISSUE #2376: PhantomJSEnv does not properly escape JS code in webpage
The following code will fail:

```javascript
console.log("<script></script>");
```

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd. Needs rebase on master.

**Comment by sjrd** [comment]
This can now be rebased on top of master.

**Comment by gzm0** [comment]
Rebased.

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala [hunk 1]
```diff
@@ -322,23 +322,18 @@ class PhantomJSEnv(
...
-        case _ =>
-          writer.write("""<script type="text/javascript">""" + "\n")
-          writer.write(s"// Virtual File: ${file.path}\n")
-          writer.write(file.content)
-          writer.write("</script>\n")
-      }
+      val realFile = codeCache.materialize(file)
+      val fname = htmlEscape(fixFileURI(realFile.toURI).toASCIIString)
+      writer.write(
+        s"""<script type="text/javascript" src="$fname"></script>""" + "\n")
```
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: 4 spaces

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala [hunk 2]
```diff
@@ -493,13 +488,14 @@ class PhantomJSEnv(
...
     protected def writeCodeLauncher(code: VirtualJSFile, out: Writer): Unit = {
-      out.write("""<script type="text/javascript">""" + "\n")
-      out.write("// Phantom.js code launcher\n")
-      out.write(s"// Origin: ${code.path}\n")
-      out.write("window.addEventListener('load', function() {\n")
-      out.write(code.content)
-      out.write("}, false);\n")
-      out.write("</script>\n")
+      // Create a file with the launcher function.
+      val launcherFile = new MemVirtualJSFile("phantomjs_launcher.js")
```
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: Consider using `-` instead of `_` so that we keep being uniform about this across the codebase.

**Comment by sjrd** [comment]
That's all.

**Comment by gzm0** [comment]
Updated

**Comment by sjrd** [comment]
LGTM

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala [hunk 3]
```diff
@@ -322,23 +322,18 @@ class PhantomJSEnv(
 
   protected trait AbstractPhantomRunner extends AbstractExtRunner {
 
+    protected[this] val codeCache = new VirtualFileMaterializer
```
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: We have a binary incompatibility problem because of this:
```
[info] Scala.js JS Envs: found 2 potential binary incompatibilities while checking against /localhome/jenkins/scala-js-sbt-homes/sbt-home/local/org.scala-js/scalajs-js-envs_2.10/0.6.9/jars/scalajs-js-envs_2.10.jar 
[error]  * method codeCache()org.scalajs.jsenv.VirtualFileMaterializer in trait org.scalajs.jsenv.phantomjs.PhantomJSEnv#AbstractPhantomRunner does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("org.scalajs.jsenv.phantomjs.PhantomJSEnv#AbstractPhantomRunner.codeCache")
[error]  * synthetic method org$scalajs$jsenv$phantomjs$PhantomJSEnv$AbstractPhantomRunner$_setter_$codeCache_=(org.scalajs.jsenv.VirtualFileMaterializer)Unit in trait org.scalajs.jsenv.phantomjs.PhantomJSEnv#AbstractPhantomRunner does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("org.scalajs.jsenv.phantomjs.PhantomJSEnv#AbstractPhantomRunner.org$scalajs$jsenv$phantomjs$PhantomJSEnv$AbstractPhantomRunner$_setter_$codeCache_=")
```

**Comment by gzm0** [comment]
Updated and rebased

**Comment by sjrd** [comment]
LGTM

**Comment by gzm0** [comment]
Jenkins, test this please

**Comment by gzm0** [comment]
Updated.

**Comment by sjrd** [comment]
LGTM
