### PR TITLE
Fix #1520: Unicode support for URI

### LINKED ISSUE #1520: java.net.URI does not support Unicode
`new java.net.URI("http://cs.dbpedia.org/resource/Víno")` fails with `Uncaught java.net.URISyntaxException: Malformed URI in http://cs.dbpedia.org/resource/Víno at -1`. It works fine on the JVM.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd, @betehess.

**Comment by gzm0** [comment]
retest this please

**Comment by sjrd** [comment]
Suggested additional tests:
```scala
new URI("http://booh/%E3a")
  -> path = "?a"
  -> rawPath = "/%E3a"
new URI("http://booh/%e3a")
  -> path = "?a"
  -> rawPath = "/%e3a" // lowercase e is kept
new URI("http://booh/%E3%81a")
  -> path = "?a" // %E3%81 is considered as 1 malformed
  -> rawPath = "/%E3%81a"
new URI("http://booh/%E3%81a")
  -> path = "??a" // %E3%E3 is considered as 2 malformed
  -> rawPath = "/%E3%E3a"
```
I think you should get all of those for free from the UTF-8 decoder, if it is setup to REPLACE on error.

File: javalib/src/main/scala/java/net/URI.scala [hunk 1]
```diff
@@ -601,39 +614,91 @@ object URI {
...
+    outBuf.toString
+  }
+
+  private val quoteStr: js.Function1[String, String] = { (str: String) =>
+    val buf = StandardCharsets.UTF_8.encode(str)
+
+    var res = ""
+    while (buf.hasRemaining) {
+      val c = buf.get & 0xff
+      res += f"%%$c%02X"
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: I'd use this occasion to get rid of this unnecessary inefficient incantation:
```scala
res += (if (c <= 0xf) "%0" else "%") + Integer.toHexString(c).toUpperCase
```
since now, we're more likely to encode quite a few characters per URI construction.

File: javalib/src/main/scala/java/net/URI.scala [hunk 2]
```diff
@@ -601,39 +614,91 @@ object URI {
...
+      inBuf.get match {
+        case '%' =>
+          if (!byteBuf.hasRemaining)
+            decode(false)
 
-    if (c > 127)
-      throw new URISyntaxException(null, "Only ASCII allowed in URIs")
-    else
-      f"%%$c%02x"
+          inBuf.get(cBuf) // get two chars
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: What if you reach the end of the string/buffer? JVM says:
```scala
scala> new URI("http://booh/%E")
java.net.URISyntaxException: Malformed escape pair at index 12: http://booh/%E

scala> new URI("http://booh/%Ep")
java.net.URISyntaxException: Malformed escape pair at index 12: http://booh/%Ep
```

File: javalib/src/main/scala/java/net/URI.scala [hunk 3]
```diff
@@ -601,39 +614,91 @@ object URI {
...
+          val hexStr = new String(cBuf)
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: This is horribly inefficient compared to the not-so-complex `cBuf(0).toString + cBuf(1).toString`.

File: javalib/src/main/scala/java/net/URI.scala [hunk 4]
```diff
@@ -601,39 +614,91 @@ object URI {
 
   // Quote helpers
 
-  private val quoteChar: js.Function1[String, String] = { (str: String) =>
-    require(str.length == 1)
+  private def decodeComponent(str: String): String = {
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: Maybe we should fast-path the case where `str` doesn't contain any `%`. Because the charset machinery is quite heavy and rarely needed. Something like:
```scala
if (str.forall(_ != '%')) str
else {
  ...
}
```

File: javalib/src/main/scala/java/net/URI.scala [hunk 5]
```diff
@@ -601,39 +614,91 @@ object URI {
...
-      throw new URISyntaxException(null, "Only ASCII allowed in URIs")
-    else
-      f"%%$c%02x"
+          inBuf.get(cBuf) // get two chars
+          val hexStr = new String(cBuf)
+          val v = Integer.parseInt(hexStr, 16)
+          byteBuf.put(v.toByte)
+
+        case c =>
+          decode(true)
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: This goes through a round of `decode` for every non-percent character, and the round is quite heavy. This should be called only if some boolean flag says that the last iteration of the loop was dealing with a `%`.

File: javalib/src/main/scala/java/net/URI.scala [hunk 6]
```diff
@@ -601,39 +614,91 @@ object URI {
...
+          outBuf.put(c)
+      }
+    }
+
+    decode(true)
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: Same here.

File: javalib/src/main/scala/java/net/URI.scala [hunk 7]
```diff
@@ -643,25 +708,45 @@ object URI {
...
-    str.jsReplace(illegalQuoteRe, quoteChar)
+    str.jsReplace(illegalQuoteRe, quoteStr)
+  }
+
+  /** matches characters not in ASCII
+   *
+   *  Note: It is important that the match is maximal, since we might encounter
+   *  surrogates that need to be encoded in one shot.
+   */
+  private val nonASCIIQuoteRe = new RegExp("[^\u0000-\u007F]*", "g")
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: Erm, `+` instead of `*`?

File: javalib/src/main/scala/java/net/URI.scala [hunk 8]
```diff
@@ -601,39 +614,91 @@ object URI {
...
+        decoder.reset()
+        byteBuf.clear()
+      } else {
+        byteBuf.compact()
+      }
+    }
 
-    val c = str.head.toInt
+    while (inBuf.hasRemaining) {
+      inBuf.get match {
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: `get` is a side-effecting function, it should be called with `()`.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/URITest.scala [hunk 9]
```diff
@@ -316,6 +316,44 @@ object URITest extends JasmineTest {
         new URI("http://example.com/asdf%6A").hashCode)
     }
 
+    it("should allow UTF-8") {
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/URITest.scala]: <del>UTF-8</del> <ins>non-ASCII characters</ins>

**Comment by sjrd** [comment]
That's all.

**Comment by gzm0** [comment]
This test case is wrong:
```scala
new URI("http://booh/%E3%81a")
  -> path = "??a" // %E3%E3 is considered as 2 malformed
  -> rawPath = "/%E3%E3a"
```

See this REPL session:

```scala
scala> import java.nio._
import java.nio._

scala> import charset._
import charset._

scala> val buf = ByteBuffer.wrap(Array(0xe3.toByte, 0xe3.toByte))
buf: java.nio.ByteBuffer = java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]

scala> StandardCharsets.UTF_8.decode(buf)
res4: java.nio.CharBuffer = �
```

**Comment by sjrd** [comment]
Not it's not wrong:
```
C:\Users\Sepi>scala
Welcome to Scala version 2.11.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_31).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import java.net.URI
import java.net.URI

scala> new URI("http://booh/%E3%E3a")
res0: java.net.URI = http://booh/%E3%E3a

scala> res0.getPath
res1: String = /??a

scala> res0.getRawPath
res2: String = /%E3%E3a

scala>
```
Your REPL session exposes another weird stuff of the UTF-8 decoder: an BufferUnderflow takes precedence over the malformedness. So, because it is at the end of the buffer, the first 0xe3 "swallows" the second because it cannot read 3 bytes (only 2) and then reports an Underflow with the rest of the buffer (i.e., 2 bytes).

**Comment by sjrd** [comment]
Hum, or they fixed it in JDK 8? Because I get this for your session:
```
scala> import java.nio._, charset._
import java.nio._
import charset._

scala> val buf = ByteBuffer.wrap(Array(0xe3.toByte, 0xe3.toByte))
buf: java.nio.ByteBuffer = java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]

scala> StandardCharsets.UTF_8.decode(buf)
res3: java.nio.CharBuffer = ??

scala>
```

**Comment by gzm0** [comment]
Crap... merge hold this. If this is the case, my strategy of decoding is entirely wrong...

**Comment by gzm0** [comment]
```
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~utopic1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by gzm0** [comment]
This doesn't make sense... what should I feed into the decoder, if I encounter something like `http://booh/%E3%E3ä`? Do I have to decode `ä` first?

**Comment by sjrd** [comment]
What does it give you with the REPL session I suggest? Maybe they fixed charset between 7 and 8, and that would have had implications on the way URI works. But in that case your strategy is still valid.

**Comment by gzm0** [comment]
Your REPL session gives me the same. So it really depends on whether you have that additional `a` or not. I am suspecting that URI does not use the Charset encoders under the hood due to historical reasons.

**Comment by sjrd** [comment]
Ah. Well, I suggest you keep your strategy as is. And then we'll have to update Charsets to behave like JDK 8, and then everything should be consistent (with JDK 8). I think?

**Comment by sjrd** [comment]
I'll try and find evidence that this was an intended change in JDK 8.

**Comment by gzm0** [comment]
Ok. How should I document the test in question?

**Comment by sjrd** [comment]
Say that there is a mismatch in the way malformed UTF-8 sequences are handled, but that we don't care, because they're malformed anyway ;)

**Comment by gzm0** [comment]
Ok. I'll open a ticket for this.

**Comment by sjrd** [comment]
Looks like I found it: https://bugs.openjdk.java.net/browse/JDK-6795537

**Comment by gzm0** [comment]
Oh, this is OpenJDK only? So our encoder is buggy as well?

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js/issues/1537

**Comment by gzm0** [comment]
Sweet.

**Comment by gzm0** [comment]
Ok. Fixed and ready to go.

File: javalib/src/main/scala/java/net/URI.scala [hunk 10]
```diff
@@ -601,39 +614,99 @@ object URI {
...
+        if (endOfInput) {
+          decoder.reset()
+          byteBuf.clear()
+        } else {
+          byteBuf.compact()
+        }
+      }
+
+      def flush() = {
+        if (byteBuf.position > 0) decode(true)
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: This condition is too restrictive. `decode(..., endOfInput = true)` is supposed to be called at the end of all decoding operations, in case the decoder does buffering. An explicit boolean flag would fix this.

And while we're here, `decode(true)` should be on its own line, since it is a side-effecting `then` part.

File: javalib/src/main/scala/java/net/URI.scala [hunk 11]
```diff
@@ -601,39 +614,99 @@ object URI {
...
+            flush()
+            outBuf.put(c)
+        }
+      }
 
-    if (c > 127)
-      throw new URISyntaxException(null, "Only ASCII allowed in URIs")
-    else
-      f"%%$c%02x"
+      flush()
```
Comment (sjrd) [inline javalib/src/main/scala/java/net/URI.scala]: Alternatively, always call `decode(true)` here (but not in `case c =>`), although that forces one round of decoding.

**Comment by sjrd** [comment]
That's all.

File: javalib/src/main/scala/java/net/URI.scala (hunk 10 above)
Comment (gzm0) [inline javalib/src/main/scala/java/net/URI.scala]: Aargh... I even thought of that, when I wrote it first...

**Comment by gzm0** [comment]
Updated

**Comment by sjrd** [comment]
LGTM :-)
