### PR TITLE
Fix #1899: Fix public members of anonymous js.Any classes.

### LINKED ISSUE #1899: Some members of new js.Object {...} are not visible from JavaScript
See the following change to the example project to reproduce the bug https://github.com/bbarker/scala-js-example-app/commit/23abe08739188a7cb99d18c5d183fa2bce008e10

In particular, note the difference in behavior depending on which `def getObj():...` is commented out.

### PR DESCRIPTION
**Pull request by nicolasstucki**
The fix requires an additional phase (<del>`prepwaspublicbeforetyper`</del> `jspretyper`)
between `parser` and `namer` that adds @WasPublicBeforeTyper annotations
on every public `ValDef` or `DefDef` of anonymous classes.
The `jsinterop` will additionally fix the methods that should be public
in the js.Any anonymous classes.

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+package org.scalajs.core.compiler
+
+import scala.tools.nsc
+import nsc._
+
+/**
+ * @author Nicolas Stucki
+ */
+abstract class PrepWasPublicBeforeTyper extends plugins.PluginComponent with transform.Transform
+    with Compat210Component {
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: `extends` should already be on the next line.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+  import global._
+
+  val phaseName = "prepwaspublicbeforetyper"
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: This name is long. Doesn't it destroy the output of `-Xshow-phases`?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+
+package org.scalajs.core.compiler
+
+import scala.tools.nsc
+import nsc._
+
+/**
+ * @author Nicolas Stucki
+ */
+abstract class PrepWasPublicBeforeTyper extends plugins.PluginComponent with transform.Transform
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: This class should have a doc-comment explaining what it does. Showing the kind of snippets it transforms, and how it transforms them.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+        val newTree =
+          treeCopy.ClassDef(tree, tree.mods, tree.name, tree.tparams, newImpl)
+        super.transform(newTree)
+
+      case _ => super.transform(tree)
+    }
+  }
+
+  private def needsAnnotations(classDef: ClassDef): Boolean = {
+    classDef.name.toString == "$anon" &&
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: Can we find this magical constant somewhere in `nme`?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+    classDef.impl.body.exists {
+      case vdef: ValDef => needsAnnotations(vdef)
+      case ddef: DefDef => needsAnnotations(ddef)
+      case _ => false
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: Align the arrows.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+    ddef.mods.isPublic && ddef.name != nme.CONSTRUCTOR
+
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(anonymousClassMethodWasPublicAnnotations)
+
+  private lazy val anonymousClassMethodWasPublicAnnotations: List[Tree] = {
+    val runtimePackage =
+      Select(Select(Ident(newTermName("scala")), newTermName("scalajs")), newTermName("runtime"))
+    val cls = Select(runtimePackage, newTypeName("WasPublicBeforeTyper"))
+    List(Apply(Select(New(cls), nme.CONSTRUCTOR), Nil))
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: I think it's risky to reuse Trees. I suggest making this a `def` to create new Trees every time. (the `newTermName`s could be cached, though)

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+
+  private def needsAnnotations(ddef: DefDef): Boolean =
+    ddef.mods.isPublic && ddef.name != nme.CONSTRUCTOR
+
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(anonymousClassMethodWasPublicAnnotations)
+
+  private lazy val anonymousClassMethodWasPublicAnnotations: List[Tree] = {
+    val runtimePackage =
+      Select(Select(Ident(newTermName("scala")), newTermName("scalajs")), newTermName("runtime"))
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: Start from `_root_`. I think there's a `nme` for that. (There's also a `nme` for `scala`)

File: library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala [hunk 8]
```diff
@@ -0,0 +1,5 @@
+package scala.scalajs.runtime
+
+import scala.annotation.StaticAnnotation
+
+class WasPublicBeforeTyper extends StaticAnnotation
```
Comment (sjrd) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: This should receive some Scaladoc telling not to use it. Something similar to what we have for `@RawJSType`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala (hunk 3 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: That doc should also explain that we do this to work around SI-something from scalac.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala (hunk 2 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: consider prefixing this with `js` like all phases we have.

File: library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala (hunk 8 above)
Comment (gzm0) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: Also, this should not be static: We don't want this to be retained in `.class` files.

Comment (gzm0) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: And: Is `runtime` really the right location for this? This is as little runtime as it gets...

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala (hunk 2 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: How about: `jspretyper` (and the class then: `PreTyperComponent`). I think it is a good idea to keep the class name general. If we need more pre typer transforms, we won't add another phase, will we?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 9]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+      case vddef: ValOrDefDef if needsCleanUp(vddef) =>
+        vddef.symbol.filterAnnotations(!_.matches(WasPublicBeforeTyperClass))
+        vddef
+
+      case member =>
+        member
+    }
+
+    treeCopy.Template(template, template.parents, template.self, newBody)
+  }
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: What is preventing you to do this when you match a `DefDef` / `ValDef` in the main transformer? It seems you are reimplementing a transform here...

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 10]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
     }
 
+  private def needsFixOrCleanup(template: Template): Boolean = {
+    val body = template.body
+    if (body == null) {
+      false
+    } else {
+      body.exists { member =>
+        val sym = member.symbol
+        if (sym != null) sym.hasAnnotation(WasPublicBeforeTyperClass)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Are there really `null` `body`s and `symbol`s? Wouldn't they be `EmptyTree` and `NoSymbol`, respectively?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 11]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+  }
+
+  private def fixPublicBeforeTyper(template: Template): Template = {
+    val body = template.body
+
+    def needsCleanUp(vddef: ValOrDefDef): Boolean =
+      vddef.symbol.hasAnnotation(WasPublicBeforeTyperClass)
+
+    val accessorsNeedFix = body.collect {
+      case vdef: ValDef if needsCleanUp(vdef) => vdef.name.toString.trim
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: No operation in `nme` to do that?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 12]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+    }.toSet
+
+    def needsFix(ddef: DefDef): Boolean = {
+      lazy val isAccessorThatNeedsFix = {
+        val accessorName = ddef.name.toString
+        val fieldName = {
+          if (accessorName.endsWith("_$eq"))
+            accessorName.substring(0, accessorName.length - 4)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: No operation in `nme` to do that?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 13]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+    def needsCleanUp(vddef: ValOrDefDef): Boolean =
+      vddef.symbol.hasAnnotation(WasPublicBeforeTyperClass)
+
+    val accessorsNeedFix = body.collect {
+      case vdef: ValDef if needsCleanUp(vdef) => vdef.name.toString.trim
+    }.toSet
+
+    def needsFix(ddef: DefDef): Boolean = {
+      lazy val isAccessorThatNeedsFix = {
+        val accessorName = ddef.name.toString
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Try not to convert to string. Work with names instead.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 14]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+      sym.isPrivate && isJSAny(template.symbol.owner) &&
+      (sym.isAccessor && isAccessorThatNeedsFix) ||
+        sym.hasAnnotation(WasPublicBeforeTyperClass)
+    }
+
+    val newBody = body.map {
+      case ddef: DefDef if needsFix(ddef) =>
+        val sym = ddef.symbol
+        sym.filterAnnotations(!_.matches(WasPublicBeforeTyperClass))
+        sym.resetFlag(Flag.PRIVATE)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Removing `private` should only be done for members of `js.Any` classes. We don't want to meddle with Scala anonymous classes.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 15]
```diff
@@ -957,6 +963,64 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+    def needsFix(ddef: DefDef): Boolean = {
+      lazy val isAccessorThatNeedsFix = {
+        val accessorName = ddef.name.toString
+        val fieldName = {
+          if (accessorName.endsWith("_$eq"))
+            accessorName.substring(0, accessorName.length - 4)
+          else
+            accessorName
+        }
+        accessorsNeedFix(fieldName)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Instead of collecting field names, can't we collect the field symbols, and simply use `ddef.symbol.accessed`?

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 14 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: However, the annotation should be removed from all classes (`js.Any` and non-`js.Any`).

**Comment by sjrd** [comment]
That's all, I think.

Did you measure how much longer does it take to compile the Scala lib after this change?

**Comment by gzm0** [comment]
Oh, another thing: You will need to adapt the checkfiles of the partests that list the compiler phases. There is a list with comments at the end of `Whitelisted.txt`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala (hunk 2 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepWasPublicBeforeTyper.scala]: I like `jspretyper`, I will use it.

File: library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala (hunk 8 above)
Comment (nicolasstucki) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: It is just because we did not have any other good locations to put it. It probably should be in its own library that is only used by the plugin, but this is a bit of overkill. Maybe in the future we could take out stuff that is only used by the plugin.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 10 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: They should, but I was getting both :(

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 14 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: The `if needsFix(ddef)` is checking that `isJSAny(template.symbol.owner)`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 15 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Yes, that works :)

**Comment by nicolasstucki** [comment]
@gzm0 how do I run partests that have `#partest`?
I assume that I'm missing a flag or simply running it from the wrong place.

For example `neg/t7494-no-options` which I would update to: 
```
error: Error: ploogin takes no options
    phase name  id  description
    ----------  --  -----------
        parser   1  parse source into ASTs, perform simple desugaring
    jspretyper   2
         namer   3  resolve names, attach symbols to named trees
packageobjects   4  load package objects
         typer   5  the meat and potatoes: type the trees
     jsinterop   6
        patmat   7  translate match expressions
superaccessors   8  add super accessors in traits and nested classes
    extmethods   9  add extension methods for inline classes
       pickler  10  serialize symbol tables
     refchecks  11  reference/override checking, translate nested objects
       uncurry  12  uncurry, translate function values to anonymous classes
     tailcalls  13  replace tail calls by jumps
    specialize  14  @specialized-driven class and method specialization
 explicitouter  15  this refs to outer pointers
       erasure  16  erase types, add interfaces for traits
   posterasure  17  clean up erased inline classes
      lazyvals  18  allocate bitmaps, translate lazy vals into lazified defs
    lambdalift  19  move nested functions to top level
  constructors  20  move field definitions into constructors
       flatten  21  eliminate inner classes
         mixin  22  mixin composition
        jscode  23
       cleanup  24  platform-specific cleanups, generate reflective calls
    delambdafy  25  remove lambdas
         icode  26  generate portable intermediate code
#partest !-optimise
           jvm  27  generate JVM bytecode
       ploogin  28  A sample phase that does so many things it's kind of hard...
      terminal  29  the last phase during a compilation run
#partest -optimise
       inliner  27  optimization: do inlining
inlinehandlers  28  optimization: inline exception handlers
      closelim  29  optimization: eliminate uncalled closures
      constopt  30  optimization: optimize null and other constants
           dce  31  optimization: eliminate dead code
           jvm  32  generate JVM bytecode
       ploogin  33  A sample phase that does so many things it's kind of hard...
      terminal  34  the last phase during a compilation run
#partest
```

Fails with:
```
> partestSuite/testOnly -- --showDiff neg/t7494-no-options
...
!! 1 - neg/t7494-no-options                      [output differs]
% diff /Users/nastucki/GitHub/scala-js/partest/fetchedSources/2.11.7/test/files/neg/t7494-no-options-neg.log /Users/nastucki/GitHub/scala-js/partest-suite/target/scala-2.11/test-classes/scala/tools/partest/scalajs/2.11.7/neg/t7494-no-options.check
@@ -27,6 +27,17 @@ superaccessors   8  add super accessors in traits and nested classes
        cleanup  24  platform-specific cleanups, generate reflective calls
     delambdafy  25  remove lambdas
          icode  26  generate portable intermediate code
+#partest !-optimise
            jvm  27  generate JVM bytecode
        ploogin  28  A sample phase that does so many things it's kind of hard...
       terminal  29  the last phase during a compilation run
+#partest -optimise
+       inliner  27  optimization: do inlining
+inlinehandlers  28  optimization: inline exception handlers
+      closelim  29  optimization: eliminate uncalled closures
+      constopt  30  optimization: optimize null and other constants
+           dce  31  optimization: eliminate dead code
+           jvm  32  generate JVM bytecode
+       ploogin  33  A sample phase that does so many things it's kind of hard...
+      terminal  34  the last phase during a compilation run
+#partest
...
```

**Comment by gzm0** [comment]
That the diff contains the "pragmas" is a known bug. Are you sure your whitespace is correct? You might not need a newline at the end of the file (or have two of them).

**Comment by nicolasstucki** [comment]
I only inserted one line (with the new phase), that one has no problems in the diff as you can see. I was quite careful to not add spaces while editing the phase numbers. If I add a new line at the end it will be part of the diff, therefore it looks like the end of the file is fine. I also tried to remove the lines that should be removed by the "pragmas" but then it got weirder output.

With:
```
error: Error: ploogin takes no options
    phase name  id  description
    ----------  --  -----------
        parser   1  parse source into ASTs, perform simple desugaring
    jspretyper   2
         namer   3  resolve names, attach symbols to named trees
packageobjects   4  load package objects
         typer   5  the meat and potatoes: type the trees
     jsinterop   6
        patmat   7  translate match expressions
superaccessors   8  add super accessors in traits and nested classes
    extmethods   9  add extension methods for inline classes
       pickler  10  serialize symbol tables
     refchecks  11  reference/override checking, translate nested objects
       uncurry  12  uncurry, translate function values to anonymous classes
     tailcalls  13  replace tail calls by jumps
    specialize  14  @specialized-driven class and method specialization
 explicitouter  15  this refs to outer pointers
       erasure  16  erase types, add interfaces for traits
   posterasure  17  clean up erased inline classes
      lazyvals  18  allocate bitmaps, translate lazy vals into lazified defs
    lambdalift  19  move nested functions to top level
  constructors  20  move field definitions into constructors
       flatten  21  eliminate inner classes
         mixin  22  mixin composition
        jscode  23
       cleanup  24  platform-specific cleanups, generate reflective calls
    delambdafy  25  remove lambdas
         icode  26  generate portable intermediate code
           jvm  27  generate JVM bytecode
       ploogin  28  A sample phase that does so many things it's kind of hard...
      terminal  29  the last phase during a compilation run
```

I get 
```
...
!! 1 - neg/t7494-no-options                      [output differs]
% diff /Users/nastucki/GitHub/scala-js/partest/fetchedSources/2.11.7/test/files/neg/t7494-no-options-neg.log /Users/nastucki/GitHub/scala-js/partest-suite/target/scala-2.11/test-classes/scala/tools/partest/scalajs/2.11.7/neg/t7494-no-options.check

[error] Failed: Total 4, Failed 2, Errors 0, Passed 2
```

Even tried copying the log and replace of the check with it and I get the same.

**Comment by sjrd** [comment]
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/3246/

**Comment by gzm0** [comment]
@nicolasstucki could you solve the partest problem?

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 16]
```diff
@@ -0,0 +1,121 @@
...
+
+package org.scalajs.core.compiler
+
+import scala.tools.nsc
+import nsc._
+
+/** This `jspretyper` phase prepares a fix for issue SI-9487 in the case of
+ *  anonymous classes that extend js.Any.
+ *
+ *  The issue SI-9487 transforms durring `typer` some public method definitions
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: during

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Also consider: During `typer`, Scalac transforms some [...] (SI-9487).
Or: Due to a bug (SI-9487), Scalac transfroms [...] during typer.

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 17]
```diff
@@ -0,0 +1,121 @@
...
+ *  of a quite specific syntactic form of anonymous classes int private methods.
+ *  This affects both methods and field accessors. This phase identifies any
+ *  anonymous class and add a `@WasPublicBeforeTyper` annotation on its public
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: adds

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 18]
```diff
@@ -0,0 +1,121 @@
...
+ *  methods and fields. After the `typer` in `jsinterop` the anonymous classes
+ *  are fixed if they are js.Any using the annotations as reference.
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: if they extend js.Any

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 19]
```diff
@@ -0,0 +1,121 @@
...
+ *  Additionally in `jsinterop` all the `@WasPublicBeforeTyper` are removed.
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: .. `@WasPublicBeforeTyper` annotations are removed

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 20]
```diff
@@ -0,0 +1,121 @@
...
+        val newTree =
+          treeCopy.ClassDef(tree, tree.mods, tree.name, tree.tparams, newImpl)
+        super.transform(newTree)
+
+      case _ => super.transform(tree)
+    }
+  }
+
+  private def needsAnnotations(classDef: ClassDef): Boolean = {
+    classDef.name.toString == "$anon" &&
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Use `ANON_CLASS_NAME`

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 21]
```diff
@@ -0,0 +1,121 @@
...
+  override protected def newTransformer(unit: CompilationUnit): Transformer =
+    new PreTyperTransformer(unit)
+
+  class PreTyperTransformer(unit: CompilationUnit) extends Transformer {
+    override def transform(tree: Tree): Tree = tree match {
+      case tree: ClassDef if needsAnnotations(tree) =>
+        val newBody = tree.impl.body.map {
+          case vdef: ValDef if needsAnnotations(vdef) =>
+            treeCopy.ValDef(vdef, withWasPublic(vdef.mods), vdef.name,
+                vdef.tpt, vdef.rhs)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: The `rhs` needs a transform as well here (nested anonymous classes).

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 22]
```diff
@@ -0,0 +1,121 @@
...
+
+          case ddef: DefDef if needsAnnotations(ddef) =>
+            treeCopy.DefDef(ddef, withWasPublic(ddef.mods), ddef.name,
+                ddef.tparams, ddef.vparamss, ddef.tpt, ddef.rhs)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: The `rhs` needs a transform as well here (nested anonymous classes).

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 23]
```diff
@@ -0,0 +1,121 @@
...
+
+  private def needsAnnotations(ddef: DefDef): Boolean =
+    ddef.mods.isPublic && ddef.name != nme.CONSTRUCTOR
+
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(anonymousClassMethodWasPublicAnnotations)
+
+  private lazy val anonymousClassMethodWasPublicAnnotations: List[Tree] = {
+    val runtimePackage =
+      Select(Select(Ident(newTermName("scala")), newTermName("scalajs")), newTermName("runtime"))
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Use `nme.scala_`.

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Use `nme.runtime`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 24]
```diff
@@ -0,0 +1,121 @@
...
+    val cls = Select(runtimePackage, newTypeName("WasPublicBeforeTyper"))
+    List(Apply(Select(New(cls), nme.CONSTRUCTOR), Nil))
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Create definitions for `newTermName("scalajs")` and `newTermName("WasPublicBeforeTyper")` (since this is going to become a def).

**Comment by nicolasstucki** [comment]
There are still some nightly tests failing

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 14 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: So I guess my second comment applies. Currently you don't remove the annotation from Scala classes.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 25]
```diff
@@ -966,6 +968,80 @@ object ExportsTest extends JasmineTest {
       expect(jsPackage.ExportObjSetterNamed_=().x).toBe(1)
     }
 
+    it("should export js.Function values of new js.Object{...} - #1899") {
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: should expose public members of ...

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 26]
```diff
@@ -966,6 +968,80 @@ object ExportsTest extends JasmineTest {
...
+
+      // Test that the bug is fixed for js.Any classes.
+
+      def getObj(): js.Object = new js.Object {
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: It would also be good to test with an anonymous subclass of a strict subclass of `js.Object`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 27]
```diff
@@ -0,0 +1,125 @@
...
+            treeCopy.DefDef(ddef, withWasPublic(ddef.mods), ddef.name,
+                ddef.tparams, ddef.vparamss, ddef.tpt, transform(ddef.rhs))
+
+          case member => member
+        }
+        val newImpl =
+          treeCopy.Template(tree.impl, tree.impl.parents, tree.impl.self, newBody)
+        val newTree =
+          treeCopy.ClassDef(tree, tree.mods, tree.name, tree.tparams, newImpl)
+        super.transform(newTree)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: You don't need `super.transform` anymore now.

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 28]
```diff
@@ -0,0 +1,125 @@
...
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(List(anonymousClassMethodWasPublicAnnotation))
+
+  private val scalajs = newTermName("scalajs")
+  private val wasPublicBeforeTyper = newTypeName("WasPublicBeforeTyper")
+
+  private def anonymousClassMethodWasPublicAnnotation: Tree = {
+    val runtimePackage =
+      Select(Select(Ident(nme.scala_), scalajs), nme.runtime)
+    val cls = Select(runtimePackage,wasPublicBeforeTyper)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Space after `,`[

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 29]
```diff
@@ -957,6 +963,63 @@ abstract class PrepJSInterop extends plugins.PluginComponent
...
+    val needsFix: DefDef => Boolean = {
+      if (isInJSAny) {
+        new Function1[DefDef, Boolean] {
+          val accessorsNeedFix = body.collect {
+            case vdef: ValDef if needsCleanUp(vdef) => vdef.symbol
+          }.toSet
+          def apply(ddef: DefDef): Boolean = {
+            val sym = ddef.symbol
+            sym.isPrivate &&
+            (sym.isAccessor && accessorsNeedFix(ddef.symbol.accessed)) ||
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Replace `accessorsNeedFix(...)` by `sym.accessed.hasAnnotation(WasPublicBeforeTyper)`.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 9 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: I have read through this again. There is really no reason I can see that you do not do this in the main `case ddef: DefDef =>` in the main transform. Could you please clarify why you did implement this in your own transform?

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 30]
```diff
@@ -966,6 +968,141 @@ object ExportsTest extends JasmineTest {
...
+        def checkOriginalY2() = y2
+        def checkOriginalY3() = y3
+      }
+
+      testExposure(getJSObj())
+      testExposure(getJSObj2())
+      testExposure(getJSObj3())
+      testExposure(getJSObj4())
+
+      // Test that non js.Any classes where unaffectedd by the fix.
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: Typo: were

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala (hunk 27 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: I need it to transform members that have not been transformed yet by `case member => member`. But I will remove it from there and use `case member => transform(member)` instead.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala (hunk 29 above)
Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: That does not work because when I reach the accessor method the annotation has been erased. Note that the members are processed in order and that variable definitions come before their accessors. Alternatively I could do the transformation in two passes, first handle the methods and then the variables.

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: Oh, I see. Btw. I still do not understand why we need to remove the annotations. They will not be retained in the `.class` files anyways.

Comment (nicolasstucki) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: I will do it in two phases, the code will be cleaner.

**Comment by sjrd** [comment]
> Btw. I still do not understand why we need to remove the annotations. They will not be retained in the .class files anyways.

Principle of least garbage, I guess? They'll still be retained in the Scala symbol table. But it's true that the symbol table for anonymous classes cannot be accessed anyway. Except by macros ... but then macros have already been processed at this point, so they saw the annotations anyway.

We try leaving them be, I guess.

**Comment by gzm0** [comment]
> We try leaving them be, I guess.

It seems that if we are concerned about efficiency and we'll need two passes to remove them (current code is essentially a hand-implemented transformer pass), it might be worthwhile to at least consider to leave them.

I really wouldn't worry about annotations breaking subsequent phases. This is probably one of the few things scalac is resilient to :P

**Comment by nicolasstucki** [comment]
If we decide to leave them, I could implement the transformation directly on each method instead of each template. This will remove an additional pass on the template.

**Comment by nicolasstucki** [comment]
It has been decided, I will not clear the annotations.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala [hunk 31]
```diff
@@ -957,6 +963,38 @@ abstract class PrepJSInterop extends plugins.PluginComponent
       case ctor: MethodSymbol if ctor.isPrimaryConstructor => ctor
     }
 
+  private def needsFixOrCleanup(template: Template): Boolean = {
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSInterop.scala]: This method is not used anymore :)

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 32]
```diff
@@ -0,0 +1,123 @@
...
+
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(List(anonymousClassMethodWasPublicAnnotation))
+
+  private val scalajs = newTermName("scalajs")
+  private val wasPublicBeforeTyper = newTypeName("WasPublicBeforeTyper")
+
+  private lazy val anonymousClassMethodWasPublicAnnotation: Tree = {
+    val runtimePackage =
+      Select(Select(Ident(nme.scala_), scalajs), nme.runtime)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: Should prefix that even by a `Select(Ident(nme.ROOTPKG), ...`. Otherwise this can be broken if there is something named `scala` in scope.

**Comment by sjrd** [comment]
The commit message has obsolete stuff (it says annotations will be removed).

That's all.

**Comment by gzm0** [comment]
> It has been decided, I will not clear the annotations.

This sounds like you have found more background than what we discussed on this PR. Could you please share it with this PR thread?

**Comment by nicolasstucki** [comment]
@gzm0 we decided to keep the annotations around as you suggested because as you said they will be erased automatically later on. Additionally this allowed the implementation of the fix to be much simpler, now we only need to take the `ddef` from ` case ddef: DefDef if enclosingOwner is OwnerKind.RawJSType =>` (a case that already existed as a `ValOrDefDef`) and fix them directly there if needed. We don't have to worry about `Template`s and `ValDef`s anymore.

**Comment by gzm0** [comment]
Ok. Thanks for clarifying.

**Comment by sjrd** [comment]
Is there still an issue in the partests?

**Comment by nicolasstucki** [comment]
I'll execute them locally to check again.

**Comment by nicolasstucki** [comment]
The partests are not passing, but I just found out why. There are some whitespaces missing at the end of some lines in the check files.

**Comment by sjrd** [comment]
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/3314/

**Comment by nicolasstucki** [comment]
The partests are failing on `run/macro-term-declared-in-trait` with the following diff: 
```scala
@@ -3,7 +3,8 @@ prefix = Expr[Nothing]({
     def <init>(): <$anon: Base> = {
       $anon.super.<init>();
       ()
-    }
+    };
+    <empty>
   };
   new $anon()
 })
```

If the tree is not transformed by `PreTyperComponent` the issue disappears.
```scala
class PreTyperTransformer(unit: CompilationUnit) extends Transformer {
  override def transform(tree: Tree): Tree = tree
}
```
From the other side, if the phase is trivialized to an empty transformation the issue is still there:
```scala
class PreTyperTransformer(unit: CompilationUnit) extends Transformer {
  override def transform(tree: Tree): Tree = super.transform(tree)
}
```

I will probably have to have more cases in my transformation to avoid cleaning the empty trees during this transformation.

**Comment by nicolasstucki** [comment]
I fixed the partest issue using this [case](https://github.com/scala-js/scala-js/commit/c40b6f1b382571c7d2358013418cc702567f1472#diff-a7084dd83dcc67fe8ad7289d5d9c2a88R92). No other changes.

@sjrd could you re-run the partests to make sure that there is no rogue configuration where it fails.

**Comment by sjrd** [comment]
Weird ... OK.

**Comment by sjrd** [comment]
Nightly here: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/3317/

**Comment by nicolasstucki** [comment]
Good, all partests succeeded.

File: library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala [hunk 33]
```diff
@@ -0,0 +1,3 @@
+package scala.scalajs.runtime
+
+class WasPublicBeforeTyper extends scala.annotation.Annotation
```
Comment (gzm0) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: I still do not understand why this is in `runtime`. If this is in `runtime`, so should `ExposedJSMember`.

Comment (sjrd) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: True. Let's put in in `js.annotation` like everything else, then.

Comment (nicolasstucki) [inline library/src/main/scala/scala/scalajs/runtime/WasPublicBeforeTyper.scala]: Done

**Comment by sjrd** [comment]
LGTM

**Comment by gzm0** [comment]
Woooot!! Now I actually have something new to present in Japan :P

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 34]
```diff
@@ -0,0 +1,132 @@
...
+
+  private def withWasPublic(mods: Modifiers): Modifiers =
+    mods.withAnnotations(List(anonymousClassMethodWasPublicAnnotation))
+
+  private val scalajs = newTermName("scalajs")
+  private val wasPublicBeforeTyper = newTypeName("WasPublicBeforeTyper")
+
+  private lazy val anonymousClassMethodWasPublicAnnotation: Tree = {
+    val runtimePackage = Select(Select(Select(Select(Ident(nme.ROOTPKG),
+        nme.scala_), scalajs), TermName("js")), nme.annotation)
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: `newTermName`

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala [hunk 35]
```diff
@@ -0,0 +1,132 @@
...
+ *  anonymous classes that extend js.Any.
+ *
+ *  During `typer`, due to a bug (SI-9487), Scalac transfroms some public method
+ *  definitions of a quite specific syntactic form of anonymous classes into
+ *  private methods. This affects both methods and field accessors. This phase
+ *  identifies any anonymous class and adds a `@WasPublicBeforeTyper` annotation
+ *  on its public methods and fields. After the `typer` in `jsinterop` the
+ *  anonymous classes are fixed if they extend js.Any using the annotations as
+ *  reference. Additionally in `jsinterop` all the `@WasPublicBeforeTyper`
+ *  annotations are removed.
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: The last sentence is obsolete and should be removed.

**Comment by sjrd** [comment]
Also typo in the commit message: missing 'n' in anonymous.

File: compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala (hunk 34 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PreTyperComponent.scala]: This should be a val as well

**Comment by nicolasstucki** [comment]
Dear Jenkins, retest this please.

**Comment by sjrd** [comment]
LGTM

**Comment by nicolasstucki** [comment]
Dear Jenkins, retest this please.

**Comment by nicolasstucki** [comment]
Dear Jenkins, retest this please.
