### PR TITLE
Fix #5244: Disable Closure by default, and deprecate support for it.

### LINKED ISSUE #5244: RFC: Disable the Closure Compiler by default, and deprecate it
I suggest we disable the Google Closure Compiler by default, and that we deprecate its support.

GCC, as we call it, has never added support for ECMAScript modules the way we need it to. Therefore, it is already disabled by default when targeting ES modules. Since that is the recommended configuration to be used with modern bundlers, effectively it shouldn't be too widespread anymore.

We are currently stuck on an old version of GCC, from 2022. More recent versions of GCC have dropped support for JDK 8. In fact, even if we drop JDK 8 to jump to 17 (which will be required by Scala 3.8.0, coming soon), we will still be stuck on a version from 2024. Our inability to keep up with it is, I believe, a liability. For example, it is blocking #5205.

When it works, GCC still produces a smaller output than our linker in `Minify` mode + regular JS minifiers like Rollup. So that would be a regression for situations where a `Script` or `CommonJS` output is still used. But it shouldn't be too much.

WDYT? Are you still relying on GCC? Would the code size regression have an impact on your codebase (after all the bundling steps are through)? You can test the impact today with
```scala
Compile/fullLinkJS/scalaJSLinkerConfig ~= { _.withClosureCompiler(false) }
```
(If you are using `ESModule`, no need to test: it won't have any effect.)

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: linker/shared/src/test/scala/org/scalajs/linker/LibrarySizeTest.scala [hunk 1]
```diff
@@ -117,15 +114,11 @@ object LibrarySizeTest {
...
-      val (expectedFullLinkSize, fullLinkTolerance) =
-        if (fullLinkConfig.closureCompiler) (expectedFullLinkSizeWithClosure, 100)
-        else (expectedFullLinkSizeWithoutClosure, 500)
-
       def roughlyEquals(expected: Int, actual: Int, tolerance: Int): Boolean =
         actual >= expected - tolerance && actual <= expected + tolerance
 
       if (!roughlyEquals(expectedFastLinkSize, fastSize, 500) ||
-          !roughlyEquals(expectedFullLinkSize, fullSize, fullLinkTolerance)) {
+          !roughlyEquals(expectedFullLinkSize, fullSize, 250)) {
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/LibrarySizeTest.scala:121]: Shouldn't this be 500? Given the order of magnitudes involved, I think it makes sense to halve this, but feels like it should be in a separate commit.

File: project/Build.scala [hunk 2]
```diff
@@ -2082,9 +2079,9 @@ object Build {
             if (!useMinifySizes) {
```
Comment (gzm0) [inline project/Build.scala:2079]: Does this still make sense? IIUC this only tests non-optimized semantics with the minifier on (in addition, the full link numbers now are the same). Not sure this is super useful.

Fine to remove in a follow-up PR.

Comment (sjrd) [reply project/Build.scala:2079]: It's not super important anymore. I'll probably remove it in a follow-up PR, indeed.

File: linker/shared/src/test/scala/org/scalajs/linker/LibrarySizeTest.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/LibrarySizeTest.scala:121]: Switched to 500 in the main commit, and added a separate commit that tightens it to 250.
