### PR TITLE
Fix #1452: PhantomJS sometimes doesn't shut down properly.

### LINKED ISSUE #1452: PhantomJS doesn't shut down properly on Linux
Hi, [details are here](https://groups.google.com/forum/#!topic/scala-js/Y6k10K5YyKI), basically what happens is that utest suite fails and PhantomJS OS process still exists which results in unpredictable errors when you run test suite again. This is the first run that ends with error : 
```
[info] Compiling 1 Scala source to /.../js/target/scala-2.11/test-classes...
[info] Fast optimizing /.../js/target/scala-2.11/app-test-fastopt.js
Uncaught failure in async execution: utest.AssertionError: assert(p == expectedPosition)

  /tmp/phantomjs-launcher4242163106310882054.js:9 in onError


  /tmp/phantomjs-launcher4242163106310882054.js:11 in onError
  file:///.../js/target/scala-2.11/app-test-fastopt.js:94303 (in function "doWriteLine__p4__T__V")

  /tmp/phantomjs-launcher4242163106310882054.js:13
[trace] Stack trace suppressed: run last js/test:test for the full output.
[error] Could not run test ....EditorSuite: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) org.scalajs.jsenv.ComJSEnv$ComClosedException: Phantom.js isn't connected
```
Then you have to go and kill the process for the next run to work correctly : 
```
ps aux | grep phantom
user     7310  0.2  0.7 1739472 61520 pts/1   Sl+  12:50   0:00 phantomjs /tmp/phantomjs-launcher7268336573458704946.js
kill -9 7310
```

Otherwise your suite probably fails on some IndexedDB issues or something that doesn't allow for running multiple PhantomJS instances...

When I'm chasing test issues I'm constantly running suite and killing PhantomJS afterwards. 

The solution would be checking whether PhantomJS process isn't already running before starting tests. It seems to be much easier that checking whether the process shut down properly.

NOTE: It might be specific to my test suite, but I didn't figure out the reason, I'm closing all resources I'm using when error occurs, like IndexedDb. Dunno why the process hangs out.

### PR DESCRIPTION
**Pull request by sjrd**
In fact, I believe this could have applied as well to other environments. Anyway, now the whole shutdown process protects against any exception that is being thrown, and still proceeds with terminating all the VMs. Any thrown exception is recorded and rethrown at the end.

### CODE REVIEW

**Comment by sjrd** [comment]
@gzm0 I could use a review of that one, if you have some time to spare.

**Comment by sjrd** [comment]
Hum it seems that with this change, the JS version of the `multiTest` test in `sbt-plugin-test` fails to terminate. One (or more) of the slaves don't close properly. But the tests succeed:
```
[info] Success: sbttest.multitest.test.LibTest
[info] Success: sbttest.multitest.test.TrivialTest
java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:107)
	at org.scalajs.testadapter.ScalaJSRunner.org$scalajs$testadapter$ScalaJSRunner$$stopSlaves(ScalaJSRunner.scala:155)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$1.apply$mcV$sp(ScalaJSRunner.scala:69)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$1.apply(ScalaJSRunner.scala:69)
	at org.scalajs.testadapter.ScalaJSRunner$$anonfun$1.apply(ScalaJSRunner.scala:69)
	at scala.util.Try$.apply(Try.scala:161)
	at org.scalajs.testadapter.ScalaJSRunner.done(ScalaJSRunner.scala:69)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:547)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1$$anonfun$16.apply(Defaults.scala:545)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:545)
	at sbt.Defaults$$anonfun$allTestGroupsTask$1.apply(Defaults.scala:543)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (multiTestJS/test:executeTests) java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
```
I'm not sure I understand what *should* cause the slaves to terminate themselves :-s

**Comment by gzm0** [comment]
The slaves should stop, because the JVM side closes the Com. (in the `stopSlaves` method). This (should) free the message callback, which in turn allows the slave to terminate. This implicit stopping removes the need for an explicit stopping command.

**Comment by gzm0** [comment]
Consider adding a method `awaitOrStop` to [AsyncJSRunner][1] and using it instead. It will be much less code, almost not alter the original code and probably more understandable.

Also, it will not create even more thread just to block on other threads that block on processes :)

[1]: https://github.com/scala-js/scala-js/blob/9e9759be400858d15a0a12c641da1b64a33fe5be/js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala

**Comment by sjrd** [comment]
Bah, I'm stupid. Running the `receiveLoop` in a `Future` deadlocks things, because the handler synchronizes on the `ScalaJSRunner`, but `stopSlaves` is itself in a `synchronized` block on the `ScalaJSRunner`. Hum ... Need to figure this out.

**Comment by sjrd** [comment]
Updated.

@gzm0 I don't see how an `awaitOrStop` can let me avoid another layer of waiting threads. Not if I want the timeouts to run in parallel as they do now.

**Comment by gzm0** [comment]
You can wait in "parallel" by setting a deadline first for all VMs `VMTimeout.fromNow` and take the remaining time when you await.

**Comment by sjrd** [comment]
I still have to handle the slaves' dying messages (in `receiveLoop`) in parallel, though. Because if the first slave deadlocks, I don't get to handle the messages of the other slaves, which could very well terminate properly.

**Comment by gzm0** [comment]
Hmmm... Indeed... we'll probably have to introduce a timeout on the messages as well... :( Yay asynchronous systems...

File: test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala [hunk 1]
```diff
@@ -61,28 +63,37 @@ final class ScalaJSRunner private[testadapter] (
...
-
-    stopSlaves()
-
-    master.send("runnerDone")
-    val summary = ComUtils.receiveResponse(master) {
-      case ("ok", summary) => summary
+  def done(): String = {
+    synchronized {
+      ensureNotDone()
     }
```
Comment (gzm0) [inline test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala]: You cannot split the synchronized block as this can expose race conditions to the framework user. (If two threads call done, one of them must throw).

**Comment by gzm0** [comment]
That's all

File: test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala (hunk 1 above)
Comment (sjrd) [inline test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala]: I was afraid of that. But wasn't there already another place where we assumed `done()` would be called by sbt exactly once? Under that assumption (which may or may not be valid), it's ok to split it, isn't it? So if we assume it somewhere else, what's the point of being resilient here? (Of course if we don't assume that anywhere else, I'll find another way).

Comment (gzm0) [inline test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala]: If there is such an assumption, we have to verify it (and as far as I can see, `ensureNotDone` does so). It is [incorrect (discouraged?) behavior][1] for the test framework to not throw an exception. One of the things that are actually specified in the test framework.

[1]: https://github.com/harrah/test-interface/blob/master/src/main/java/sbt/testing/Runner.java#L70

Comment (sjrd) [inline test-adapter/src/main/scala/org/scalajs/sbttestadapter/ScalaJSRunner.scala]: Ah ok. So yes, I have to make that work.

**Comment by gzm0** [comment]
Oh... this also doesn't parallelize the stopping of the slaves and the master anymore...

**Comment by sjrd** [comment]
> Oh... this also doesn't parallelize the stopping of the slaves and the master anymore...

No, that's right, it doesn't. But before it didn't parallelize the stopping of the slaves wrt each other. So overall it's a win. I'll see whether I can fix the thing wrt to the master anyway, though.

**Comment by gzm0** [comment]
I'd do this:

```scala
ensureNotDone()

val slaveClosing: Try[Unit] = stopSlaves()

val masterClosing = Try {
    master.send("runnerDone")
    val summary = ComUtils.receiveResponse(master) {
      case ("ok", summary) => summary
    }
    master.close()
}

val deadline = VMTermTimeout.fromNow

// Await all JS VMs
val slaveStopping = slaves.values.map(s => Try(s.awaitOrStop(deadline)))
val masterStopping = Try(master.await(deadline))

// Cleanup
master = null
slaves.clear()

framework.runDone()

// Throw stuff if necessary.
summary
```

Further, add a timeout in `receiveResponse` (with default). Since we should do this for all messages anyway. Some timeouts must be higher though (for test runs).

**Comment by gzm0** [comment]
Of course it did. `slaves.foreach(_.close())` only instructs them to stop... doesn't do much more

**Comment by sjrd** [comment]
I agree with you code.

> Further, add a timeout in receiveResponse (with default). Since we should do this for all messages anyway. Some timeouts must be higher though (for test runs).

What could I possibly set as timeout for messages happening during test execution? I can't impose an arbitrary limit on the time spent for one's test suite to run, can I?

**Comment by gzm0** [comment]
Indeed. Probably it is better to only introduce the deadline when closing...

**Comment by gzm0** [comment]
> I can't impose an arbitrary limit on the time spent for one's test suite to run, can I?

Actually, in any serious asynchronous system, you have no choice. But maybe we can let this slip unless someone encounters issues. Because configuring the test-adapter is a nightmare (i.e. a config-file based solution is probably the only option).

**Comment by sjrd** [comment]
Updated.

**Comment by sjrd** [comment]
Bah, now I have a race somewhere, it seems.
https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/26430/console

**Comment by gzm0** [comment]
You still create threads to wait on the slaves. This is not necessary.

**Comment by gzm0** [comment]
1. Add an overload to `ComJSEnv.receive` that takes a timeout
2. Add an overload to `ComUtils.receiveLoop` (and dependencies) that take timeouts. (consider using an infinite duration instead)
3. In places where you want receive timeout, pass it to the receive loop. A fixed timeout per message iteration makes much more sense anyway.
4. Close does not need a timeout since it is not asynchronous

**Comment by gzm0** [comment]
I really don't think we gain anything in making the message teardown parallel (we have to synchronize anyway).

**Comment by sjrd** [comment]
OK I will try that tomorrow.

**Comment by gzm0** [comment]
If I get a chance today, I can at least outline it.

**Comment by sjrd** [comment]
This is not looking good: how I am suppose to honor a timeout in `ComNodeRunner`
https://github.com/scala-js/scala-js/blob/master/js-envs/src/main/scala/org/scalajs/jsenv/nodejs/NodeJSEnv.scala#L177-L188
I'd have to spawn a thread there and then wait. So I have only moved the thread problem.

But it's worse here: what if it times out here? I have corrupted my input stream in the sense that, should the underlying VM *not* be blocked but only slow, I still can't reliably re-call `receive()` later.

**Comment by gzm0** [comment]
> how I am suppose to honor a timeout in ComNodeRunner

You can set a [socket timeout][1].

> But it's worse here: what if it times out here? I have corrupted my input stream in the sense that, should the underlying VM not be blocked but only slow, I still can't reliably re-call receive() later.

Welcome to the beauties of distributed systems. If you need a timeout because you assume that nodes can hang (and you hence cannot see the failure), after the timeout expires, you must fail (if you assume channels are not lossy).
This is inherent to having individual processes. (You could talk to Rachid, maybe there is a better option, but I doubt it)...

[1]: http://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#setSoTimeout(int)

**Comment by sjrd** [comment]
Ah, socket timeout, right. OK, let's go implement that ...

**Comment by sjrd** [comment]
Updated with a wip with timeouts, but it doesn't work for Node.js: it deadlocks somewhere in its jsEnvs/test.

**Comment by sjrd** [comment]
Ah ... I didn't expect that to pass. Maybe it only fails on Windows?

File: js-envs/src/main/scala/org/scalajs/jsenv/Utils.scala [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+package org.scalajs.jsenv
+
+import scala.concurrent.duration._
+
+private[jsenv] object Utils {
+  final class OptDeadline private (
+      val deadline: Deadline /* nullable */) extends AnyVal {
+    def millisLeft: Int =
+      if (deadline == null) 0
+      else (deadline.timeLeft.toMillis.toInt max 1)
```
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/Utils.scala]: Why not 0? Also, you need to ceil to Int.Max, before converting to Int for proper clamping.

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala [hunk 3]
```diff
@@ -249,9 +253,9 @@ class PhantomJSEnv(
       loop("")
     }
 
-    private def receiveFrag(): String = {
+    private def receiveFrag(deadline: OptDeadline): String = {
       while (recvBuf.isEmpty && !mgr.isClosed)
-        wait()
+        wait(deadline.millisLeft)
```
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: This takes a Long, and not an Int. You are converting the millis toInt and then toLong...
Also, you need to check if the deadline expired in the outer loop. Otherwise it will loop anyways (IIUC `wait` does not throw, if it wakes up because of time).

File: js-envs/src/main/scala/org/scalajs/jsenv/Utils.scala (hunk 2 above)
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/Utils.scala]: Because 0 means Infinite. If the deadline is present but overdue, the best approximation we can have is 1 ms, not Infinite.

File: js-envs/src/main/scala/org/scalajs/jsenv/rhino/RhinoJSEnv.scala [hunk 4]
```diff
@@ -452,9 +453,11 @@ object RhinoJSEnv {
       notify()
     }
 
-    def recvJVM(): String = synchronized {
+    def recvJVM(timeout: Duration): String = synchronized {
+      val deadline = OptDeadline(timeout)
+
       while (js2jvm.isEmpty && ensureOpen(_closedJS))
-        wait()
+        wait(deadline.millisLeft)
```
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/rhino/RhinoJSEnv.scala]: Same here.

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala (hunk 3 above)
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: Ah, indeed.

**Comment by sjrd** [comment]
Updated, and with a proper commit message. I have the same problem running JSEnvTests on Windows on master anyway. It seems the `intervalSendTest` loops or deadlocks. But if I set a timeout of 2.seconds in the `receive()` call of that test, then it crashes with that timeout exceeded. This seems to be the manifestation of another bug with `setInterval` not working properly on Windows and Node.js.

But that should not prevent this PR from getting in, I think.

**Comment by sjrd** [comment]
@gzm0 Should I squash the commits? Or first have a commit introducing the *possibility* of using timeouts, then a commit with the fix, directly using these timeouts?

**Comment by gzm0** [comment]
I think squashing is fine. But I'd like to review this one if you don't mind.

**Comment by sjrd** [comment]
Updated. In the end I made two commits anyway, because the support for timeouts is useful and testable in isolation, and non trivial.

Review by @gzm0

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala [hunk 5]
```diff
@@ -241,13 +243,15 @@ class PhantomJSEnv(
...
+    def receive(timeout: Duration): String = synchronized {
       if (recvBuf.isEmpty && !awaitConnection())
         throw new ComJSEnv.ComClosedException("Phantom.js isn't connected")
 
+      val deadline = OptDeadline(timeout)
+
       @tailrec
       def loop(acc: String): String = {
-        val frag = receiveFrag()
+        val frag = receiveFrag(deadline)
```
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: This is not consistent with how the NodeJS channel handles timeouts (it looses previous fragments, if a timeout happens). You need to make a decision here:

1. If a timeout occurs, the channel is bad, nothing can be done anymore
2. If a timeout occurs, the next call to receive will give the message the call before has timeout out.

File: js-envs/src/test/scala/org/scalajs/jsenv/test/TimeoutComTests.scala [hunk 6]
```diff
@@ -57,6 +58,33 @@ trait TimeoutComTests extends TimeoutTests with ComTests {
...
+
+    for (i <- 1 to 2) {
+      com.send(s"Hello World: $i")
+      try {
+        com.receive(900.millis)
+        fail("Expected TimeoutException to be thrown")
+      } catch {
+        case _: TimeoutException =>
+      }
+      assertEquals(s"Got: Hello World: $i", com.receive(3000.millis))
```
Comment (gzm0) [inline js-envs/src/test/scala/org/scalajs/jsenv/test/TimeoutComTests.scala]: If you increase the size of the reply, this test might fail with PhantomJS.

**Comment by gzm0** [comment]
The changes in ComUtils should go in the second commit, as they are entirely private to the adapter.

File: js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala (hunk 5 above)
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/phantomjs/PhantomJSEnv.scala]: Ah right. I meant to implement 2. I overlooked this case.

**Comment by sjrd** [comment]
> The changes in ComUtils should go in the second commit, as they are entirely private to the adapter.

Ah indeed.

File: js-envs/src/test/scala/org/scalajs/jsenv/test/TimeoutComTests.scala (hunk 6 above)
Comment (sjrd) [inline js-envs/src/test/scala/org/scalajs/jsenv/test/TimeoutComTests.scala]: Yep, although in practice it still won't, because sending the fragments will happen in a very short time frame compared to the setTimeouts. So it's basically untestable, unfortunately.

**Comment by sjrd** [comment]
Updated.

File: js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala [hunk 7]
```diff
@@ -38,12 +38,25 @@ trait AsyncJSRunner {
...
   final def await(atMost: Duration): Unit = Await.result(future, atMost)
 
+  /** Await completion of the started Run for the duration specified by
+   *  [[atMost]], or force it to stop if the timeout expires.
+   */
+  final def awaitOrStop(atMost: Duration): Unit = {
+    try {
+      await(atMost)
+    } catch {
+      case th: Throwable =>
```
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: Only if we time out. Not on any failure.

**Comment by gzm0** [comment]
That's all. Sorry it took so long.

File: js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala (hunk 7 above)
Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: No we also need to stop the vm on any other failure. The point of this method is: I want you to stop, no matter what, but I give you a chance to do so gracefully first.

Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: Ah but the ScalaDoc is wrong. It'll change the ScalaDoc.

**Comment by sjrd** [comment]
Updated.

> That's all. Sorry it took so long.

No worries ;-) We can only blame the time zones ^^

File: js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala (hunk 7 above)
Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: No. If the `future` **terminates** with an exception, you must not call stop, but throw that exception. An example is when the VM terminates with a non-zero exit code.

Comment (sjrd) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: It doesn't really matter, though, does it? Won't `stop` be a no-op if the vm has already stopped? In that case, the exception is properly thrown again. And if there is an exception that *doesn't* stop it, well the `stop` will stop it anyway, and still throw the right exception.

Comment (gzm0) [inline js-envs/src/main/scala/org/scalajs/jsenv/AsyncJSRunner.scala]: Ok. Agreed. But then you have to change the documentation of `stop` explicitly to say that it **must** be a no-op if the runner is completed (and verify that this is actually the case).

Further, consider using a finally block in this case.

**Comment by sjrd** [comment]
Updated.

**Comment by gzm0** [comment]
LGTM

**Comment by gzm0** [comment]
お疲れ様

**Comment by sjrd** [comment]
ありがとうございます (probably there should be some kanji's in there, but I'm not at that level yet ^^)
