### PR TITLE
Fix #4794: Fix the stability of our compilation and linking pipeline.

### LINKED ISSUE #4794: The output of the compiler/linker is not stable
Under some circumstances, the output of our compiler and/or linker is not stable. In other words, compiling and linking the exact same codebase twice may lead to different results. The results as *equivalent*, but the files are not byte-to-byte the same. This is not good for multi-module outputs, which relies on byte-to-byte equality to avoid changing the timestamp of output files.

### PR DESCRIPTION
**Pull request by sjrd**
There were a few places where our compilation and linking pipeline made non-deterministic decisions that had an influence on the generated code. This is bad for multi-module output, which avoids rewriting files that have not changed. It is also bad for our development, when we want to precisely track the effect that our changes (to the library, code and/or linker) have on the generated code.

We fix the various sources of non-determinism, and add a smoke test for stability in the CI.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala [hunk 1]
```diff
@@ -399,45 +399,75 @@ trait GenJSExports[G <: Global with Singleton] extends SubComponent {
...
       // Verify stuff about caseDefinitions
       assert({
-        val argcs = caseDefinitions.values.flatten.toList
+        val argcs = caseDefinitions.map(_._2).flatten
         argcs == argcs.distinct &&
         argcs.forall(_ <= maxArgc)
       }, "every argc should appear only once and be lower than max")
 
+      def sameElementSet[A](xs: List[A], ys: List[A]): Boolean =
+        xs.size == ys.size && xs.forall(ys.contains(_))
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala:452]: This is only correct if the lists contain distinct elements. I guess for all usages this is correct, but feels a bit brittle. Does it hurt performance significantly if we just do `xs.toSet == ys.toSet` (and maybe even inline at call site)?

File: Jenkinsfile [hunk 2]
```diff
@@ -156,6 +156,13 @@ def Tasks = [
         ++$scala testingExample$v/testHtmlJSDom  &&
     sbtretry ++$scala testSuiteJVM$v/test testSuiteExJVM$v/test &&
     sbtretry ++$scala testSuite$v/test &&
+    sbtretry ++$scala \
+        testSuite$v/saveForStabilityTest \
+        testSuite$v/checkStability \
+        testSuite$v/forceRelinkForStabilityTest \
+        testSuite$v/checkStability \
+        testSuite$v/clean \
+        testSuite$v/checkStability &&
```
Comment (gzm0) [inline Jenkinsfile:165]: Have you considered using a scripted test for this?

Seems like that might be simpler: https://www.scala-sbt.org/1.x/docs/Testing-sbt-plugins.html#step+4%3A+write+a+script

**Review by gzm0 — CHANGES_REQUESTED** [review]
Some minor comments.

Also: It might be worth filing this as a bug to keep a reference. Stability is clearly something I'd expect from a compiler.

File: ir/shared/src/main/scala/org/scalajs/ir/Names.scala [hunk 3]
```diff
@@ -300,6 +301,57 @@ object Names {
 
     override def hashCode(): Int = _hashCode
 
+    def compareTo(that: MethodName): Int = {
+      @tailrec
+      def compareTypeRefs(x: TypeRef, y: TypeRef): Int = x match {
```
[the remark this answers is not in the document]
Comment (sjrd) [reply ir/shared/src/main/scala/org/scalajs/ir/Names.scala:306]: I can make it a `Comparable`, yes. It probably makes sense.

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 1 above)
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala:452]: If the lists contain duplicates, we have bigger problems here. ;)

File: Jenkinsfile (hunk 2 above)
Comment (sjrd) [reply Jenkinsfile:165]: I could use scripted, but it's harder to make it generic wrt. the `scalaVersion`.

Also, this is easier to reproduce by hand for iterative development.

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 1 above)
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: I specialized it to testing for a `List[Exported]` against `varArgMeths`, with a comment reminding that they are distinct.

File: Jenkinsfile (hunk 2 above)
Comment (sjrd) [reply Jenkinsfile:165]: Perhaps more importantly: in a scripted test I would not have access to the entire `test-suite`. And I want to test with the entire test suite because that's the only thing that contains "a bit of everything". In a scripted tests, I'd have to manually reproduce a codebase causing all kinds of sources of instability, which would defeat the purpose.

File: ir/shared/src/main/scala/org/scalajs/ir/Types.scala [hunk 4]
```diff
@@ -170,7 +170,29 @@ object Types {
    *  type refs that are used in method signatures, and which therefore dictate
    *  JVM/IR overloading.
    */
-  sealed abstract class TypeRef {
+  sealed abstract class TypeRef extends Comparable[TypeRef] {
+    final def compareTo(that: TypeRef): Int = this match {
+      case thiz: PrimRef =>
+        that match {
+          case that: PrimRef => Character.compare(thiz.charCode, that.charCode)
+          case _          => -1
```
Comment (gzm0) [inline ir/shared/src/main/scala/org/scalajs/ir/Types.scala:178]: Align?

**Review by gzm0 — APPROVED** [review]

**Review by gzm0 — APPROVED** [review]
