### PR TITLE
Fix #4413: Handle JS symbols and bigints in `systemIdentityHashCode`.

### LINKED ISSUE #4413: hashCode() and identityHashCode() don't work for JS symbols and bigints
All of the following crash:
```scala
    println(System.identityHashCode(js.Symbol.forKey("foobar")))
    println(js.Symbol.forKey("foobar").hashCode())
    
    println(System.identityHashCode(js.BigInt(543)))
    println(js.BigInt(543).hashCode())
```
For symbols, it results in a `TypeError` because we attempt to put a `symbol` key in a `WeakMap`, which is not allowed.

For bigints, it results in a "Maximum call stack exceeded" (a stack overflow, basically), because `hashCode()` delegates to `identityHashCode()`, which delegates back to `hashCode()`, etc.

### PR DESCRIPTION
**Pull request by sjrd**
By spec, for values that are not Scala objects nor primitives corresponding to a hijacked class, `x.hashCode()` resolves to `j.l.Object.hashCode()`, which delegates to `System.identityHashCode()`.

Previously, the implementation of the latter would jump back to `j.l.Object.hashCode()` for JS `bigint`s, and crash with a `TypeError` for `symbol`s.

The main cause of these issues is that we thought we could delegate back to `j.l.Object.hashCode()` for all primitives, because they are supposed to be covered by hijacked classes. We had forgotten `symbol`s, though, and anyway it does not work because not all JS primitives are covered by a hijacked class.

In this commit, we break this cycle. `systemIdentityHashCode` never delegates back to `j.l.Object.hashCode()` anymore. Instead, it separately handles every type of primitive in JavaScript with a dedicated hash code implementation. For strings and numbers, we reuse `j.l.String.hashCode()` and `j.l.Double.hashCode()`, because we can. For other values, we have an inline implementation.

### CODE REVIEW

**Comment by sjrd** [comment]
In JavaScript, for ES 2015, this yields:
```js
var $lastIDHash = 0;
var $idHashCodeMap = new WeakMap();
function $systemIdentityHashCode(obj) {
  switch ((typeof obj)) {
    case "string": {
      return $f_T__hashCode__I(obj)
    }
    case "number": {
      return $f_jl_Double__hashCode__I(obj)
    }
    case "bigint": {
      var biHash = 0;
      if ((obj < BigInt(0))) {
        obj = (~obj)
      };
      while ((obj !== BigInt(0))) {
        biHash = (biHash ^ Number(BigInt.asIntN(32, obj)));
        obj = (obj >> BigInt(32))
      };
      return biHash
    }
    case "boolean": {
      return (obj ? 1231 : 1237)
    }
    case "undefined": {
      return 0
    }
    case "symbol": {
      var description = obj.description;
      return ((description === (void 0)) ? 0 : $f_T__hashCode__I(description))
    }
    default: {
      if ((obj === null)) {
        return 0
      } else {
        var hash = $idHashCodeMap.get(obj);
        if ((hash === (void 0))) {
          hash = (($lastIDHash + 1) | 0);
          $lastIDHash = hash;
          $idHashCodeMap.set(obj, hash)
        };
        return hash
      }
    }
  }
}
```

File: test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala [hunk 1]
```diff
@@ -41,4 +43,75 @@ class ObjectJSTest {
...
+     *
+     * By-spec, however, hashCode() delegates to System.identityHashCode() for
+     * bigints, since they are not Scala objects nor primitives that correspond
+     * to a hijacked class (except for those that fit in a Long when we
+     * implement Longs as bigints). So the values here must be equal to those
+     * in `SystemJSTest.identityHashCodeOfBigInts()`.
+     *
+     * When we do implement Longs as bigints, the hashCode() of bigints that
+     * fit in a Long must conform to j.l.Long.hashCode(). That is however
+     * indepently tested in `LongTest.hashCodeTest()`.
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala:91]: Do you think it would be worth having a test testing this more explicitly? (IIUC, right now this is only tested implicitly by having the same values in the `test` calls, easy to forget that they need to stay in sync IMO).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 2]
```diff
@@ -1009,14 +1010,78 @@ private[emitter] object CoreJSLib {
...
+          def genReturnSymbolHashCode(): Tree = {
+            /* Hash the `description` field of the symbol, which is either
+             * `undefined` or a string.
+             */
+
+            Block(
+              const(description, genIdentBracketSelect(obj, "description")),
+              Return(If(description === Undefined(), 0,
+                  genHijackedMethodApply(BoxedStringClass, description)))
+            )
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1073]: Recursively call `$systemIdentityHashCode` on `description`?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 3]
```diff
@@ -1009,14 +1010,78 @@ private[emitter] object CoreJSLib {
...
+              If(obj < biLit(0), obj := ~obj),
+              While(obj !== biLit(0), Block(
+                biHash := biHash ^ Apply(NumberRef, asInt32(obj) :: Nil),
+                obj := (obj >> biLit(32))
+              )),
+              Return(biHash)
+            )
+          }
+
+          def genReturnSymbolHashCode(): Tree = {
```
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1064]: I have, but as you say, that would leak memory in a non-recoverable way. (even finalizers don't work; we can't watch for a `symbol` to be garbage-collected, since it's a primitive)

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1073]: I thought about that, but I don't see why doing it instead of the above. The current code has the advantage that it's obvious there's no loop.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 4]
```diff
@@ -1009,14 +1010,78 @@ private[emitter] object CoreJSLib {
...
-            Switch(typeof(obj),
-                List("string", "number", "bigint", "boolean").map(str(_) -> Skip()) :+
-                str("undefined") -> Return(genCallHelper("dp_" + genName(hashCodeMethodName), obj)),
-                defaultImpl)
+            Switch(typeof(obj), List(
+              str("string") -> genReturnHijackedMethodApply(BoxedStringClass),
+              str("number") -> genReturnHijackedMethodApply(BoxedDoubleClass),
+              str("bigint") -> genReturnBigIntHashCode(),
+              str("boolean") -> Return(If(obj, 1231, 1237)),
+              str("undefined") -> Return(0),
```
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1082]: No, nothing bad can happen. `System.identityHashCode(x)` doesn't have to be the same as `x.hashCode()` (and on the JVM it's never the case). We happen to use the same values because that way we don't have to invent (and justify) other hash code computations, but this is an implementation detail.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 5]
```diff
@@ -1009,14 +1010,78 @@ private[emitter] object CoreJSLib {
...
+              str("symbol") -> genReturnSymbolHashCode()
+            ), defaultImpl)
```
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1084]: We can't. In ES 5.1 and ES 2015, `typeof` is allowed to return any string (except the above which are reserved for primitives) for exotic host objects:
ES 5.1: https://262.ecma-international.org/5.1/#sec-11.4.3
ES 2015: https://262.ecma-international.org/6.0/#sec-typeof-operator

This is not the case in the most recent JS versions anymore ([see here](https://262.ecma-international.org/11.0/#sec-typeof-operator)), but we should not rely on that since we target ES 5.1/2015.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala (hunk 1 above)
Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala:91]: They don't *have* to stay in sync. They will *have no choice* but to stay in sync, because the underlying implementation is the same (out of necessity). It's not possible to write an implementation that would behave differently here and in `LongTest.hashCodeTest()`.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/SystemTest.scala [hunk 6]
```diff
@@ -168,28 +168,14 @@ class SystemTest {
     val list2 = List(1, 3, 5)
     assertEquals(list2, list1)
     assertEquals(list2.hashCode(), list1.hashCode())
-    assertNotEquals(System.identityHashCode(list1), System.identityHashCode(list2))
+    if (!executingInJVM)
```
[the remark this answers is not in the document]
Comment (sjrd) [reply test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/SystemTest.scala:171]: Because the JVM does not guarantee that two objects allocated one after the other have different id hash codes. (We don't guarantee that either, but our implementation happens to always satisfy that, so we can test it that way for JS only.)

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1064]: Actually, if the properties we create on the object are non-enumerable, wouldn't that essentially be a weak map? Now whether the VM actually GCs that is a different story...

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 2 above)
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1073]: Good point.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala (hunk 1 above)
Comment (gzm0) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala:91]: I see. Then I find this comment confusing. Maybe just remove it?

Also there's a typo: "indepently"

**Review by gzm0 — APPROVED** [review]
LGTM modulo the typo.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:1064]: Unfortunately not. Even non-enumerable properties can be listed with `getOwnPropertyDescriptors`.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala (hunk 1 above)
Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/javalib/lang/ObjectJSTest.scala]: > Then I find this comment confusing. Maybe just remove it?

Yes, indeed. I removed it.
