### PR TITLE
Fix #5044: Handle the IllegalArgumentExceptions in jlr.Array.newInstance.

### LINKED ISSUE #5044: jl.reflect.Array.newInstance() does not throw the IllegalArgumentExceptions it is supposed to.
`jl.reflect.Array.newInstance()` is supposed to throw an `IllegalArgumentException` if one of the following conditions happen:

* the component class is `classOf[Unit]`
* for the multi-dimensions overload, the argument array is empty.

Currently both backends behave arbitrarily in those situations.

### PR DESCRIPTION
**Pull request by sjrd**
The case of an empty array of dimensions for the multi-dimensions overload is handled in user-space. The case of `classOf[Unit]` is handled in the backends, since not doing so leaves the door open for user-space IR to break the fundamental invariant that there is no array of `void`.

In the JS backend, we follow the strategy of int/long div/mod to emit the target method only if `IllegalArgumentException.<init>()` is reachable. In the Wasm backend, since we do not have that infrastructure, for now we add an unconditional dependency on that constructor, like we do for `jl.Class.<init>()`.

### CODE REVIEW

**Review by gzm0 — CHANGES_REQUESTED** [review]
TBH: I find the refactor confusing.

The way I think about this is that the approximation / usage happens in the CoreJSLib, not the GlobalKnowledge: Since `ArithmeticException` isn't present, we know that no division by zero can be present.

Note that the converse is not true: Just because `ArithmeticException` is present, does not necessarily mean a division by zero is present.

So I feel the refactoring actually wrongly names what the GlobalKnowledge provides (would this information come from the analysis, that would be something different of course).

I feel the existing comment in wasmemitter/Emitter actually re-inforces this way of looking at it:

```
// TODO Ideally we should not require these, but rather adapt to their absence
```

I have no comments on the second commit.

File: linker/shared/src/main/scala/org/scalajs/linker/analyzer/Infos.scala [hunk 1]
```diff
@@ -667,21 +670,16 @@ object Infos {
...
-                builder.addInstantiatedClass(ArithmeticExceptionClass,
-                    StringArgConstructorName)
-              }
-
               op match {
                 case Int_/ | Int_% =>
                   rhs match {
                     case IntLiteral(r) if r != 0 =>
-                    case _                       => addArithmeticException()
+                    case _                       => builder.addUsedIntLongDivModByMaybeZero()
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/analyzer/Infos.scala:680]: Just TBC: This refactoring can make sense.

**Comment by sjrd** [comment]
All right, I see your point.

I downplayed the first commit. Now it is only checking the specific constructor, but otherwise the naming is unchanged.

**Review by gzm0 — APPROVED** [review]
