### PR TITLE
Fix #4408: Compute the list of dispatchers that we need.

### LINKED ISSUE #4408: The CharSequence hack in FunctionEmitter is unsound
It turns out [the `CharSequence` hack in `FunctionEmitter`](https://github.com/scala-js/scala-js/blob/b3b964ccdf2dd79038eaca98ce89fa9f8fbdcf8a/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala#L2184-L2204) is unsound. Who would have thought?

The following program reproduces the issue:
```scala
package helloworld

import scala.scalajs.js

object HelloWorld {
  def main(args: Array[String]): Unit = {
    test("hello")
    test(new java.lang.StringBuilder("hello"))
  }

  @noinline def test(sequence: CharSequence): Unit = {
    js.Dynamic.global.console.log(sequence.subSequence(2, 4).toString())
  }
}
```
The issue cannot be reproduced in the test suite because there are too many implementations of `CharSequence`.

The output is
```
ll
C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\main.js:1518
  return $as_T($thiz.substring(beginIndex, endIndex))
                     ^

TypeError: $thiz.substring is not a function
    at $f_T__substring__I__I__T (C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\file:\C:\Users\sjrdo\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\_String.scala:373:17)
    at $c_Lhelloworld_HelloWorld$.test__jl_CharSequence__V (C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\file:\C:\Users\sjrdo\Documents\Projets\scalajs\javalanglib\src\main\scala\java\lang\_String.scala:364:14)
    at $c_Lhelloworld_HelloWorld$.main__AT__V (C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\file:\C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\src\main\scala\helloworld\HelloWorld.scala:24:9)
    at $s_Lhelloworld_HelloWorld__main__AT__V (C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\file:\C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\src\main\scala\helloworld\HelloWorld.scala:20:8)
    at C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\main.js:1846:1
    at C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-fastopt\main.js:1847:4
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at [stdin]:8:25
    at Script.runInThisContext (vm.js:132:18)
```
The first call succeeds, but the second one fails. This happens because we attempt to call `$f_T__substring__I__I__T` on the `j.l.StringBuilder`. The compiled code of `test` is:
```js
$c_Lhelloworld_HelloWorld$.prototype.test__jl_CharSequence__V = (function(sequence) {
  var $$x1 = console;
  var this$1 = $f_T__substring__I__I__T(sequence, 2, 4);
  $$x1.log(this$1)
});
```
How does that happen? Because of multi-inlining. When the optimizer sees the call
```scala
sequence.subSequence;I;I;Ljava.lang.CharSequence(2, 4)
```
it looks for possible implementations of `subSequence`. There are exactly 2: one in `String`, and one in `StringBuilder`. It turns out that both those implementations delegate to a `substring` method, with the same arguments, returning a `String`. That triggers multi-inlining.

Since we're multi-inlining, the receiver type is (correctly) not refined, and we end up with
```scala
sequence.substring;I;I;Ljava.lang.String(2, 4)
```
where `sequence` is a `CharSequence`.

When we get to the `FunctionEmitter`, this enters the `CharSequence` hack, which assumes that this must be a call on a `String`, and emits JS code to call the hijacked class method `$f_T__substring__I__I__T`.

---

In theory, this can happen with any other hijacked class, but in practice it doesn't. That's because, for all the methods in all the other hijacked classes, there is a second hijacked class where that method also exists and does something different. Since all hijacked classes are instantiated, multi-inlining never happens.

---

How to fix it? Well, first we need to remove the hack, which means that `FunctionEmitter` would emit a call to a dispatcher if it ends up in the above situation. That's still no good because we don't have dispatchers for the dozens of methods in `String`. There are two ways out of this:
* the workaround way: prevent multi-inlining when one of the targets is in a hijacked class
* the real fix way: actually declare dispatchers for all the methods of all hijacked classes, including `String`.

The second way is better, but we cannot rely on having a hard-coded list of all the methods of `String`, like we currently do for the dispatcher. So we would actually have to dynamically list all reachable methods in hijacked classes, and generate dispatchers for those.

### PR DESCRIPTION
**Pull request by sjrd**
Instead of hard-coding the list of methods of hijacked classes that need dispatchers, along with the hijacked classes that define them, we compute the above information from the class hierarchy.

It turns out that the required information was already in the global knowledge, except it was exposed in a weaker form. So this change does not make incremental runs more sensitive.

These changes allow to get rid of the `CharSequence` hack in `FunctionEmitter`, which was unsound.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 1]
```diff
@@ -725,6 +725,37 @@ private[emitter] object CoreJSLib {
...
+        BoxedBooleanClass,
+        BoxedUnitClass,
+        BoxedCharacterClass
+      ) ::: (
+        if (allowBigIntsForLongs) List(BoxedLongClass) else Nil
+      ) ::: List(
+        BoxedCharacterClass
+      )
+
+      val allOrderedHijackedClasses = List(
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:752]: This list already exists as `ClassEmitter#RuntimeSubclassesOfDouble`. In fact there is very similar code in `genSingleInstanceTests`. Consolidate? (Including removal of `Long` and small numbers?).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 2]
```diff
@@ -725,6 +725,37 @@ private[emitter] object CoreJSLib {
...
+        BoxedDoubleClass,
+        BoxedStringClass,
+        BoxedBooleanClass,
+        BoxedUnitClass,
+        BoxedCharacterClass
+      ) ::: (
+        if (allowBigIntsForLongs) List(BoxedLongClass) else Nil
+      ) ::: List(
+        BoxedCharacterClass
+      )
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:750]: I do not understand why we need this explicit list. IIUC, we already partition these based on whether they have a `typeOf` test anyways.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 3]
```diff
@@ -828,6 +828,13 @@ object Emitter {
               StringArgConstructorName)
         },
 
+        // See systemIdentityHashCode in CoreJSLib
+        callMethod(BoxedBooleanClass, hashCodeMethodName),
+        callMethod(BoxedDoubleClass, hashCodeMethodName),
+        callMethod(BoxedLongClass, hashCodeMethodName),
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:834]: Make this conditional on `useBigIntForLong`? (IIUC, if it is an object, we simply give it a normal identity hash code).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala [hunk 4]
```diff
@@ -16,43 +16,35 @@ import org.scalajs.ir.Names._
...
+   * `FunctionEmitter.hijackedMethodsInheritedFromObject`.
+   *
+   * In theory, we should compute those from the Class Hierarchy. However, that
+   * would require dealing with incremental runs, which would be overkill since
+   * these things are in fact known to be static.
+   */
+
+  val finalizeMethodName = MethodName("finalize", Nil, VoidRef)
+  val notifyMethodName = MethodName("notify", Nil, VoidRef)
+  val notifyAllMethodName = MethodName("notifyAll", Nil, VoidRef)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala:49]: Simply move these to `FunctionEmitter#hijackedMethodsInheritedFromObject`? That way we don't duplicate the comment, and we can remove the comments about "good reasons". (IMO these being at the start of the file is quite confusing).

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala]: Indeed. I've consolidated all of that.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala]: We do partition, but if there is only one with a `typeof` test (or 0), we take the full list again, so it's still better that the ones with `typeof` come first.

**Review by sjrd — COMMENTED** [review]
Updated.

**Comment by sjrd** [comment]
FTR, this is the diff of the reversi in 2.11 (the one that was bumped upwards):
```js
-fastopt.js./reversi-fastopt.js examples/reversi/.2.11/target/scala-2.11/reversi-
--- ../reversi-fastopt.js       2021-02-03 09:49:49.979528200 +0100
+++ examples/reversi/.2.11/target/scala-2.11/reversi-fastopt.js 2021-02-03 11:04:13.217031200 +0100
@@ -162,33 +162,32 @@
     }
   }
 }
-function $dp_getClass__jl_Class(instance) {
-  return instance.getClass__jl_Class()
-}
-function $dp_clone__O(instance) {
-  return instance.clone__O()
-}
-function $dp_notify__V(instance) {
-  return instance.notify__V()
-}
-function $dp_notifyAll__V(instance) {
-  return instance.notifyAll__V()
-}
-function $dp_finalize__V(instance) {
-  return instance.finalize__V()
-}
 function $dp_toString__T(instance) {
   return ((instance === (void 0)) ? "undefined" : instance.toString())
 }
 function $dp_equals__O__Z(instance, x0) {
-  if (((!(!(instance && instance.$classData))) || (instance === null))) {
-    return instance.equals__O__Z(x0)
-  } else if (((typeof instance) === "number")) {
-    return $f_jl_Double__equals__O__Z(instance, x0)
-  } else if ((instance instanceof $Char)) {
-    return $f_jl_Character__equals__O__Z(instance, x0)
-  } else {
-    return $c_O.prototype.equals__O__Z.call(instance, x0)
+  switch ((typeof instance)) {
+    case "string": {
+      return $f_T__equals__O__Z(instance, x0)
+    }
+    case "number": {
+      return $f_jl_Double__equals__O__Z(instance, x0)
+    }
+    case "boolean": {
+      return $f_jl_Boolean__equals__O__Z(instance, x0)
+    }
+    case "undefined": {
+      return $f_jl_Void__equals__O__Z(instance, x0)
+    }
+    default: {
+      if (((!(!(instance && instance.$classData))) || (instance === null))) {
+        return instance.equals__O__Z(x0)
+      } else if ((instance instanceof $Char)) {
+        return $f_jl_Character__equals__O__Z(instance, x0)
+      } else {
+        return $c_O.prototype.equals__O__Z.call(instance, x0)
+      }
+    }
   }
 }
 function $dp_hashCode__I(instance) {
@@ -216,35 +215,33 @@
     }
   }
 }
-function $dp_compareTo__O__I(instance, x0) {
-  return instance.compareTo__O__I(x0)
-}
-function $dp_length__I(instance) {
-  return instance.length__I()
-}
-function $dp_charAt__I__C(instance, x0) {
-  return instance.charAt__I__C(x0)
-}
-function $dp_subSequence__I__I__jl_CharSequence(instance, x0, x1) {
-  return instance.subSequence__I__I__jl_CharSequence(x0, x1)
-}
-function $dp_byteValue__B(instance) {
-  return instance.byteValue__B()
-}
-function $dp_shortValue__S(instance) {
-  return instance.shortValue__S()
-}
-function $dp_intValue__I(instance) {
-  return instance.intValue__I()
+function $dp_indexOf__I__I(instance, x0) {
+  if (((typeof instance) === "string")) {
+    return $f_T__indexOf__I__I(instance, x0)
+  } else {
+    return instance.indexOf__I__I(x0)
+  }
 }
-function $dp_longValue__J(instance) {
-  return instance.longValue__J()
+function $dp_indexOf__I__I__I(instance, x0, x1) {
+  if (((typeof instance) === "string")) {
+    return $f_T__indexOf__I__I__I(instance, x0, x1)
+  } else {
+    return instance.indexOf__I__I__I(x0, x1)
+  }
 }
-function $dp_floatValue__F(instance) {
-  return instance.floatValue__F()
+function $dp_lastIndexOf__I__I(instance, x0) {
+  if (((typeof instance) === "string")) {
+    return $f_T__lastIndexOf__I__I(instance, x0)
+  } else {
+    return instance.lastIndexOf__I__I(x0)
+  }
 }
-function $dp_doubleValue__D(instance) {
-  return instance.doubleValue__D()
+function $dp_substring__I__I__T(instance, x0, x1) {
+  if (((typeof instance) === "string")) {
+    return $f_T__substring__I__I__T(instance, x0, x1)
+  } else {
+    return instance.substring__I__I__T(x0, x1)
+  }
 }
 function $intDiv(arg0, arg1) {
   if ((arg1 === 0)) {
@@ -5483,7 +5480,7 @@
 $h_jl_StringBuilder.prototype = $c_jl_StringBuilder.prototype;
 $c_jl_StringBuilder.prototype.append__jl_CharSequence__I__I__jl_StringBuilder = (function(s, start, end) {
   var this$1 = ((s === null) ? "null" : s);
-  var s$1 = $f_T__substring__I__I__T(this$1, start, end);
+  var s$1 = $dp_substring__I__I__T(this$1, start, end);
   this.jl_StringBuilder__f_java$lang$StringBuilder$$content = (("" + this.jl_StringBuilder__f_java$lang$StringBuilder$$content) + s$1);
   return this
 });
```
The only annoying thing is that we create dispatchers for all the reachable methods of `String`, even when they're only called in places where we can directly call the `$f_` method. GCC gets rid of the unused static functions.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 5]
```diff
@@ -725,6 +725,37 @@ private[emitter] object CoreJSLib {
     private def defineDispatchFunctions(): Tree = {
       val instance = varRef("instance")
 
+      val methodsInRepresentativeClasses = globalKnowledge
+        .methodsInRepresentativeClasses()
+        .filter(_._2 != toStringMethodName) // toString() is special
+        .groupBy(_._2)
+        .map(kv => (kv._1, kv._2.map(_._1)))
+        .toList
+        .sortBy(_._1.nameString) // sort for determinism
```
[the remark this answers is not in the document]
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:734]: That's a fair argument. But why is a merged form of this computation slower than what we do now in `KnowledgeGuardian`? AFAICT it boils down to:
- Iterate over all method / class pairs
- Put them into a O(1) datastructure.

If we start talking about allocations etc. this can really go both ways IMO (because of tuples), and we should not speculate but measure.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 6]
```diff
@@ -828,6 +828,15 @@ object Emitter {
               StringArgConstructorName)
         },
 
+        // See systemIdentityHashCode in CoreJSLib
+        callMethod(BoxedBooleanClass, hashCodeMethodName),
+        callMethod(BoxedDoubleClass, hashCodeMethodName),
+        callMethod(BoxedStringClass, hashCodeMethodName),
+        callMethod(BoxedUnitClass, hashCodeMethodName),
+        cond(config.esFeatures.allowBigIntsForLongs) {
+          callMethod(BoxedLongClass, hashCodeMethodName)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:837]: Hmmm... looking at the implementation of `SystemIdentityHashCode`, it seems it will cause an infinite loop if:
- `!useBigIntsForLong`
- The hash of a `BigInt` is taken.

(this is unrelated to this PR).

File: project/Build.scala [hunk 7]
```diff
@@ -1667,14 +1667,14 @@ object Build {
...
-                fullLink = 107000 to 108000,
+                fullLink = 108000 to 109000,
                 fastLinkGz = 66000 to 67000,
                 fullLinkGz = 28000 to 29000,
             ))
 
           case "2.12.12" =>
             Some(ExpectedSizes(
-                fastLink = 781000 to 782000,
+                fastLink = 780000 to 781000,
```
Comment (gzm0) [inline project/Build.scala:1677]: I think this is the first change that has different directions based on the scala version :P

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 8]
```diff
@@ -786,12 +793,8 @@ private[emitter] object CoreJSLib {
         }
 
         defineDispatcher(methodName, args, {
-          val maybeWithoutLong =
-            if (allowBigIntsForLongs) implementingHijackedClasses
-            else implementingHijackedClasses.filter(_ != BoxedLongClass)
-
           val (classesWithTypeof, otherClasses) =
-            maybeWithoutLong.partition(hijackedClassNameToTypeof(_).isDefined)
+            targetHijackedClasses.partition(hijackedClassNameToTypeof(_).isDefined)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:797]: Shall we use `span` here then?

**Comment by gzm0** [comment]
> The only annoying thing is that we create dispatchers for all the reachable methods of String, even when they're only called in places where we can directly call the $f_ method. 

I was thinking about this as well. And the only solution I could find is introduce abstract methods in the IR. When the optimizer multi-inlines, it would need to *add* abstract methods to the target classes. Then the emitter could emit dispatchers based on the abstract methods. (It would also get the post optimizer IR closer to typechecking).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala]: Hum, yes, I guess you're right; it's not clear where the benefit is. I've moved the computation to `KnowledgeGuardian` (although I did not filter out `toString` there, because that would not make sense).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala (hunk 6 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:837]: Yes, I think `SystemIdentityHashCode` is broken in some way. I'll investigate that after this PR.

**Comment by sjrd** [comment]
> > The only annoying thing is that we create dispatchers for all the reachable methods of String, even when they're only called in places where we can directly call the $f_ method.
> 
> I was thinking about this as well. And the only solution I could find is introduce abstract methods in the IR. When the optimizer multi-inlines, it would need to _add_ abstract methods to the target classes. Then the emitter could emit dispatchers based on the abstract methods. (It would also get the post optimizer IR closer to typechecking).

It would also be solved by the infrastructure that #4337 had added, since we would know whether the hijacked class methods are ever called in a non-statified context.

Changing how we deal with abstract methods seems like a much bigger change, though.

**Review by gzm0 — APPROVED** [review]
