### PR TITLE
Fix #4855: Avoid case-insensitive clashes for internal module IDs.

### LINKED ISSUE #4855: Linker emits modules with colliding names on case-insensitive filesystems
So first of all, this almost definitely a user error. But maybe it's in scope to provide a more helpful error?

I have a reproducer in https://github.com/armanbilge/sandbox/commit/e5e14fd627666c2450eb918322e03affd1a43d2a, but it will only work on a case-insensitive file system (such as macOS).

```
sbt:sandbox> app/run
[info] Running Main.
TypeError: $j_Main.$s_LMain__main__AT__V is not a function
    at file:///Users/armanbilge/code/sandbox/app/target/scala-2.12/app-fastopt/Main.js:4:9
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[error] org.scalajs.jsenv.ExternalJSRun$NonZeroExitException: exited with code 1
[error] 	at org.scalajs.jsenv.ExternalJSRun$$anon$1.run(ExternalJSRun.scala:200)
[error] stack trace is suppressed; run last app / Compile / run for the full output
[error] (app / Compile / run) org.scalajs.jsenv.ExternalJSRun$NonZeroExitException: exited with code 1
[error] Total time: 0 s, completed Apr 20, 2023, 3:18:12 PM
```

You can encounter this when using:
1. a case-insensitive file system
2. two classes with the same case-insensitive name in different compilation units e.g. `object Foo` vs `object foo`
3. some form of small modules that causes both classes to be emitted in their own file

The "different compilation units" bit is actually pretty important. In the same compilation unit, scalac would warn about this. In different compilation units on the JVM, the classes can peacefully co-exist on the same classpath by living in different folders/jars. But in Scala.js, because all the files are emitted by the linker into the same folder, we can run into trouble.

### PR DESCRIPTION
**Pull request by sjrd**
~~Just making sure the test will fail the Windows build currently.~~

When an internal module contains a single class, we name it after the class name. This is supposed to give unambiguous module IDs. However, it is not good enough on case-insensitive file systems, as we can have two classes whose names differ only in case.

To avoid the issue, we prefix uppercase (and titlecase) characters with a '-' and potentially a code point value.

We have a similar issue for digest-based module IDs. Their 'internal-' prefix must also be protected for collision in a case-insensitive way. For that, we can directly compare with the IDs to avoid using `compareToIgnoreCase`.

---

Note that this significantly increases our Windows CI build time. That's because it's quite memory-constrained (from the available VMs) and the SmallModules splitter takes more memory, so it suffers from GC trashing. However, we only have a single Windows job with few tasks, so it remains overall faster than the Jenkins build.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 1]
```diff
@@ -0,0 +1,157 @@
...
+   *  the IDs in [[avoid]] nor of the public module IDs.
+   */
+  def makeFromDigestGenerator(avoid: Iterable[ModuleID]): FromDigestGenerator = {
+    val DashIndex = 8
+    var prefix = "internal-"
+    for (moduleID <- avoid.iterator ++ publicModuleIDs.iterator) {
+      val id = moduleID.id
+      while (id.length() >= prefix.length() &&
+          id.charAt(DashIndex) == '-' && // fast exit
+          id.substring(0, prefix.length()).equalsIgnoreCase(prefix)) {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:127]: I'm concerned that `equalsIgnoreCase` is inconsistent with the logic in `forClassName`. Notably:

- This completely ignores surrogates (works on Chars, not code points)
- It's unclear to me how this handles title case

**Review by gzm0 — CHANGES_REQUESTED** [review]
I have two higher level concern with this approach:

- I'm insufficiently familiar with the unicode standard to assess correctness of this. If necessary, I'll do the required reading, but I'd be more comfortable with a more obviously correct solution :-/
- This solution seems to assume that there is a case insensitive comparison that "dominates" all others. Is that a reasonable assumption?

Have you considered a solution where the Emitter compares the resulting filenames instead (using a comparison method provided by OutputDirectoryImpl)?

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:127]: This is OK because we only ever compare against an ASCII string of the form `internal---`. There is no supplementary code point that is equal ignoring case to these ASCII characters. `forClassName` has to deal with all possible code points.

**Comment by sjrd** [comment]
> I have two higher level concern with this approach:
> 
>     * I'm insufficiently familiar with the unicode standard to assess correctness of this. If necessary, I'll do the required reading, but I'd be more comfortable with a more obviously correct solution :-/

Basically everything there is to know is about case folding and is described in the reference file https://unicode.org/Public/UNIDATA/CaseFolding.txt

>     * This solution seems to assume that there is a case insensitive comparison that "dominates" all others. Is that a reasonable assumption?

Case folding (but not case conversions) is *almost* locale-independent. It only has exceptions for Turkish, but in a way that makes *fewer* pairs equivalent, so it should indeed be dominated by the default case folding.

> Have you considered a solution where the Emitter compares the resulting filenames instead (using a comparison method provided by OutputDirectoryImpl)?

I don't think that would be better. It would make our choice of module names dependent on the target file system, which is a bit problematic from a reproducible build stand point. Not to mention the cost of synchronous calls to the filesystem to figure it out.

**Comment by gzm0** [comment]
> I don't think that would be better. It would make our choice of module names dependent on the target file system, which is a bit problematic from a reproducible build stand point. Not to mention the cost of synchronous calls to the filesystem to figure it out.

Fair. Not sure sync calls are an issue, I'd expect a filesystem implementation to be able to compare paths w/o syscalls. But having different output on different platforms is definitely not ideal (especially if it is avoidable).

**Comment by sjrd** [comment]
Rebased and hopefully made more obvious with lots of comments and a simpler rule for non-ASCII characters.

**Comment by gzm0** [comment]
I haven't forgotten about this. My current state: I'm not convinced about the refactoring in the first commit (IMHO it causes too much unnecessary coupling), but I need some more thinking to figure out exactly why and propose something better.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 2]
```diff
@@ -62,22 +88,79 @@ private[modulesplitter] final class InternalModuleIDGenerator(
...
+      val cp = originalNameString.codePointAt(i)
+      if (cp < 0x80) {
+        // ASCII
+        if (cp == '-' || (cp >= 'A' && cp <= 'Z'))
+          builder.append('-')
+        builder.append(cp.toChar)
+        i += 1
+      } else {
+        // Non-ASCII
+        new java.util.Formatter(builder).format("-u%06x", Integer.valueOf(cp))
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:123]: Why do we need `Integer.valueOf`? Shouldn't the compiler do that for us?

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 3]
```diff
@@ -62,22 +88,79 @@ private[modulesplitter] final class InternalModuleIDGenerator(
...
+     *
+     * All these cases are handled by `equalsIgnoreCase`.
+     */
+    val DashIndex = 8
+    var prefix = "internal-"
+    for (moduleID <- avoid.iterator ++ publicModuleIDs.iterator) {
+      val id = moduleID.id
+      while (id.length() >= prefix.length() &&
+          id.charAt(DashIndex) == '-' && // fast exit
+          id.substring(0, prefix.length()).equalsIgnoreCase(prefix)) {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:159]: I feel this is a bit an odd mix between fast and short: If we've identified a conflict, we'll re check the "fast exit" every time and we'll also re-compare the beginning of the prefix every time (even though we just appended a dash).

Have you considered:

```scala
for (moduleID <- avoid.iterator ++ publicModuleIDs.iterator) {
  val id = moduleID.id
  val idLen = id.length()
  val pLen = prefix.length()
  if (idLen >= pLen &&
      id.charAt(DashIndex) == '-' && // fast exit
      id.substring(0, pLen).equalsIgnoreCase(prefix)) {
    // append dashes until there is no prefix conflict anymore.
    val lastDash = id.lastIndexOf('-', pLen)
    prefix += "-" * (lastDash + 1 - pLen) // TODO: check for off-by-one
  }
}

```

**Review by gzm0 — CHANGES_REQUESTED** [review]

**Comment by sjrd** [comment]
Rebased only. I somehow missed that you had reviewed this. I will take care of it tomorrow.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:123]: It's a quirk of using Java `Object...` varargs parameters. Normally `Object` in a Java signature is interpreted as `Any`, but not if it is an `Object[]` (which an `Object...` is underneath). In that case it's still `AnyRef`, and an `Int` does not conform to `AnyRef`.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 4]
```diff
@@ -15,8 +15,16 @@ package org.scalajs.linker.frontend.modulesplitter
 import org.scalajs.ir.Names.{ClassName, ObjectClass}
 import org.scalajs.linker.standard.ModuleSet.ModuleID
 
-/** Helpers to create internal ModulesIDs */
-private object ModuleIDs {
+/** Generator for internal module IDs. */
+private[modulesplitter] final class InternalModuleIDGenerator(
```
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala]: Yes, indeed. It ends up being better with two separate classes.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala [hunk 5]
```diff
@@ -158,18 +158,19 @@ import org.scalajs.linker.standard.ModuleSet.ModuleID
  *  Therefore, G' is acyclic.
  */
 private class Tagger(infos: ModuleAnalyzer.DependencyInfo,
+    internalModIDGenerator: InternalModuleIDGenerator.FromDigestGenerator,
     excludedClasses: scala.collection.Set[ClassName] = Set.empty) {
   import Tagger._
 
   private[this] val allPaths = mutable.Map.empty[ClassName, Paths]
 
-  final def tagAll(internalModuleIDPrefix: String): scala.collection.Map[ClassName, ModuleID] = {
```
[the remark this answers is not in the document]
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/Tagger.scala:166]: I reverted to passing it as a parameter. There probably was a reason while I was working on it, but not anymore.

**Comment by sjrd** [comment]
Updated.

**Comment by sjrd** [comment]
Ping @gzm0 ?

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+  /** Generator based on digests. */
+  final class ForDigests private (internalModuleIDPrefix: String) {
+    def this(avoid: Iterable[ModuleID]) =
+      this(freeInternalPrefix(avoid))
+
+    def this(info: ModuleAnalyzer.DependencyInfo, moreToAvoid: Iterable[ModuleID]) =
+      this(info.publicModuleDependencies.keys ++ moreToAvoid)
+
+    def this(info: ModuleAnalyzer.DependencyInfo) =
+      this(info, Nil)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:143]: Similar comment here: I'd remove the second two secondary constructors and just inline them at the call site.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 7]
```diff
@@ -97,9 +159,55 @@ private[modulesplitter] object InternalModuleIDGenerator {
...
+     *
+     * - Only '-' is equal to '-'
+     * - Only 'i ı I İ' are equal to 'i'
+     * - Only ASCII letters are equal to the other letters of "internal"
+     *
+     * All these cases are handled by `equalsIgnoreCase`.
+     */
+
+    val BasePrefix = "internal"
+    val BasePrefixLen = 8
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:175]: Replace `8` with `BasePrefix.length`?

**Review by gzm0 — CHANGES_REQUESTED** [review]

**Comment by sjrd** [comment]
Updated. Removing the convenience constructors made me realize that we did not need to pull the creation of the generators as far back as I did. So the first commit has now a smaller diff.

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+package org.scalajs.linker.frontend.modulesplitter
+
+import org.scalajs.ir.Names.{ClassName, ObjectClass}
+import org.scalajs.linker.standard.ModuleSet.ModuleID
+
+/** Generators for internal module IDs. */
+private[modulesplitter] object InternalModuleIDGenerator {
+
+  /** Generator based on `ClassName`s. */
+  final class ForClassNames(publicModuleIDs: Iterable[ModuleID]) {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala:43]: Nit: `publicModuleIDs` -> `avoid`?

**Review by gzm0 — APPROVED** [review]

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala (hunk 8 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGenerator.scala]: Oops, yes, good catch.
