### PR TITLE
Fix #3058: Use the proper type for the "thisLocalVar" of tailrec.

### LINKED ISSUE #3058: Wrong IR type for `this` local of @tailrec methods in the presence of self type in 2.12
With a combination of:

* Scala 2.12
* An `@tailrec` method
* In a class or trait that has a self-type

the codegen produces code with invalid IR.

Reproduction (`Parent` can be a `class` or a `trait`):
```scala
trait Parent { this: Child =>
  @tailrec final def bar(i: Int, acc: Int): Int = {
    println(s"bar($i, $acc)")
    if (i <= count)
      bar(i + 1, acc + i)
    else
      acc
  }
}

class Child extends Parent {
  def count: Int = 5
}

object HelloWorld extends js.JSApp {
  def main(): Unit = {
    val obj = new Child
    println(obj.bar(1, 0))
  }
}
```
gives the IR error:
```
[error] HelloWorld.scala(13:7:VarRef): Variable _$this of type ClassType(Lhelloworld_Parent) typed as ClassType(Lhelloworld_Child)
```
The tree that we receive from scalac is properly typed with `_$this` of type `Child` (the self-type), but we erroneously assume `currentClassType` for the type of `_$this` in some places (in the `VarDef` and in `genThis()`), rather than using the type of the symbol.

### PR DESCRIPTION
**Pull request by sjrd**
In Scala 2.12, if a tail-recursive method is in a class or trait with a self-type, the type of the `_$this` local variable is the self type. We previously assumed it was always the current class type, which produced invalid IR in that case.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala [hunk 1]
```diff
@@ -1959,14 +1962,15 @@ abstract class GenJSCode extends plugins.PluginComponent
...
-      thisLocalVarIdent.fold[js.Tree] {
+      thisLocalVarInfo.fold[js.Tree] {
         if (tryingToGenMethodAsJSFunction) {
           throw new CancelGenMethodAsJSFunction(
               "Trying to generate `this` inside the body")
         }
         js.This()(currentClassType)
-      } { thisLocalIdent =>
-        js.VarRef(thisLocalIdent)(currentClassType)
+      } { thisLocalInfo =>
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: `case (thisLocalIdent, thisLocalTpe) =>`?

Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: I hesitated. Done.
