### PR TITLE
Fix #5131: Overhaul justifications for caching in Emitter.genClass.

### LINKED ISSUE #5131: Linker not noticing instance test changes
In some cases, the linker fails to update a file and this can result in Javascript errors which always go away after clean and re-linking. Here's one example where this might happen:

Make sure to use small modules in the build:
```sbt
scalaJSLinkerConfig ~= {
    _.withModuleKind(ModuleKind.ESModule)
      .withModuleSplitStyle(
        ModuleSplitStyle.SmallModulesFor(List("hello_world")))
  }
```

Use whichever version of Scala and SBT (I've reproduced it on many versions), and the latest ScalaJS. 

Declare the following in a file:

```scala
package hello_world
trait A
case class B() extends A
case class C() extends A
```

And this is your main method in a different file:
```scala
package hello_world
@main
def main(): Unit =
    val ls = Seq(new B(), new C())
    println(ls.collect { case a: B => a })
```

Now link it by running fastLinkJS from sbt - so far everything will work;
Then change `B` to `C` in the last line, the code should look like this: `println(ls.collect { case a: C => a })`
Then run fastLinkJS again. 
At this point the resulting JS is broken. It no longer prints a console log message, and it instead shows a JS error. 
What's broken specifically is in the generated C.js code - it is missing the function starting with `$as_`, which is expected from the file which I will abbreviate as $$anon$1.js.

(The bug didn't reproduce when I declared the trait and classes in the same file as the main method; however, it reproduces when all of A, B, C are classes (B, C must extend A), even with parameters)

The problem can be narrowed down to the code here: https://github.com/scala-js/scala-js/blob/main/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala#L696-L701
This code is not updating `changed` in the case where `linkedClass.hasInstanceTests` changes, while nothing in the class itself changes. Note that we're not modifying the implementation of the case class C, we're only modifying its caller, so the linker incorrectly assumes that the class has not changed and doesn't check anything referencing it. I couldn't find a specific part where the code was wrong, it's more that this check needs to be added to prevent this bug, and I don't know what is the best way to do this.

A seemingly much less important case of the same bug: If I'm doing an instance test, then I remove it without making changes to the file declaring the referenced instance, then a different js file will be constructed by the emitter, but `changed` will be false so it won't replace the old file. This doesn't break anything, it only leaves in unused code. To reproduce follow the same steps as above, but check the generated JS code for B, and you'll see that it has instance check functions that are unused and that will go away if cleaned and re-linked.

Also I am not sure whether `classEmitter.needInstanceTests` can toggle in other situations with `changed` remaining false - I don't know what `.isAncestorOfHijackedClass` will be because I don't know what a hijacked class is, and I did not dig into it, it just seemed suspicious that this might possibly happen. Food for thought for someone more familiar with the codebase than I am.

### PR DESCRIPTION
**Pull request by sjrd**
Previously, we were missing a number of cases where we should have set the `changed` flag to true.

That flag is used to decide if a module needs to be rewritten. Previously, we failed to notice cases where *only* one of the `Analysis` flags changed (`hasInstances`, `hasRuntimeTypeInfo` and `hasInstanceTests`). In those cases, all the *cached trees* are kept. The only thing that changes is the subset thereof that is actullay included. That does not require invalidation of the caches, but it does require rewriting the module.

Likewise, we failed to invalidate the module if only the *set* of static-like methods retained by the analysis changed.

Overall, it had become quite tricky to follow what we are allowed to use where. This commit overhauls how we track everything.

First, we include the `kind` of the class in its cache identity, because too many things depend on it. If it changes, it is likely that everything will be invalidated anyway.

Other than that, dangerous variables, whose uses must be justified, are clearly marked with `foo_!` names.

Boolean decisions whose outcome is never cached are tracked separately; if any of them changes, we marked `changed` to `true`. This particular change is what fixes https://github.com/scala-js/scala-js/issues/5131.

Finally, we add dedicated tracking of the set of generated static-like methods, like we do for instance methods.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 1]
```diff
@@ -901,20 +906,48 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
       _fullClassChangeTracker.foreach(_.startRun())
     }
 
-    def getCache(version: Version): (DesugaredClassCache, Boolean) = {
+    def getCache(version: Version, hasInstances: Boolean, hasRuntimeTypeInfo: Boolean,
+        hasInstanceTests: Boolean): (DesugaredClassCache, Boolean) = {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:910]: I'm wondering if what is called `FullClassChangeTracker` is not better suited for this purpose? IIUC, it does exactly what we need here for the full class (which is not cached).

Maybe we could rename it to `ModuleChangeTracker` and explicitly document it as "change tracker for uncached trees".

This would also allow to pass it to `needInstanceTests` instead of `classCache`.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 2]
```diff
@@ -424,8 +424,12 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
       x._1
     }
 
-    val classTreeCache =
-      extractChanged(classCache.getCache(linkedClass.version))
+    val classTreeCache = extractChanged {
+      classCache.getCache(linkedClass.version,
+          hasInstances = linkedClass.hasInstances,
+          hasRuntimeTypeInfo = linkedClass.hasRuntimeTypeInfo,
+          hasInstanceTests = linkedClass.hasInstanceTests)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:431]: The fact that the usage of this is hidden behind `needInstanceTests` bothers me quite a bit.

Have you considered passing the necessary linking info individually?
IIUC this would get us almost to the state where `linkedClass` as a whole doesn't escape `genClass` anymore. (`extractInlineableInit` and `needStaticInitialization` would need to be adjusted, but it seems to be trivial).

That in turn would allow us to annotate all fields we pass from `linkedClass` with where they are invalidated, hopefully reducing the overall likelihood of errors.

I might spend some time annotating all usages to avoid problems like this.

**Review by gzm0 — CHANGES_REQUESTED** [review]

**Comment by sjrd** [comment]
I gave a shot at a revamp. @gzm0 WDYT?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 3]
```diff
@@ -411,27 +411,49 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
+     * cache.
+     *
+     * Note that it is *not* safe to use uncachedDecisions in *cached*
+     * decision-making!
+     */
+    val uncachedDecisions = extractChanged(classCache.getUncachedDecisions(linkedClass_!))
+
+    // Delegate justifications for those two to their use sites
+    val (linkedInlineableInit_!, linkedMethods_!) =
+      classEmitter.extractInlineableInit(linkedClass_!)(classCache)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:456]: How do we make sure the results of this are only used in places that are guarded by the `classCache`?

IIUC, the results may depend on global knowledge.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 4]
```diff
@@ -482,17 +501,36 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
+       * addition to *inputs* in the LinkedClass.
+       *
+       * Nevertheless, since it tracks the class version, we are allowed to
+       * use the following facts for uncached decision-making.
+       */
+
+      val hasJSSuperClass = linkedClass_!.jsSuperClass.isDefined
+
+      /* The optimizer cannot remove the class initializer, so this is covered
+       * by the class version as well.
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:518]: - It's not clear to me why addition or removal of a class initializer must trigger a class version bump. At least taken at face value, it's just a method, and we version these separately.
- Reliance on the optimizer's behavior is quite brittle IMO.

Are there major downsides to just putting this into `UncachedDecisions`?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 5]
```diff
@@ -544,51 +578,58 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
+                useESClass, // always safe
                 jsConstructorDef // part of ctor version
-              )(moduleContext, ctorCache, linkedClass.pos).map(prePrint(_, memberIndent)))
+              )(moduleContext, ctorCache, linkedClass_!.pos) // pos invalidated by class version
+                .map(prePrint(_, memberIndent))
+          )
         } else {
-          val ctorVersion = linkedInlineableInit.fold {
-            Version.combine(linkedClass.version)
+          val ctorVersion = linkedInlineableInit_!.fold { // versioning
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:600]: I wonder if we should move calculation of this version to `extractInlineableInit` (and return a 3-tuple).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 6]
```diff
@@ -482,17 +501,36 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
-    val isJSClass = kind.isJSClass
-
     // Class definition
-    if (linkedClass.hasInstances && kind.isAnyNonNativeClass) {
-      val isJSClassVersion = Version.fromByte(if (isJSClass) 1 else 0)
+    if (uncachedDecisions.hasInstances && kind.isAnyNonNativeClass) {
+      /* Decision-making in this scope is governed by the `fullClassChangeTracker`
+       * below instead of the uncachedDecisions. It is actually called at the
+       * end of the block, because it needs to track *produced* js.Trees in
+       * addition to *inputs* in the LinkedClass.
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:509]: Maybe we can clarify this a bit more? IIUC there are 2 reasons we need do this:

- Shape of the class (ES class or not)
- Method set.

Note the second one points to a problem: How do we make sure we trigger "changed" if the static method set changes?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 7]
```diff
@@ -606,76 +647,66 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
       // Normal methods
       val memberMethodsWithGlobals = for {
-        method <- linkedMethodsAndBridges
+        method <- linkedMethodsAndBridges_! // explicitly versioned below, by member
         if method.flags.namespace == MemberNamespace.Public
       } yield {
         val methodCache =
           classCache.getMemberMethodCache(method.methodName)
 
-        val version = Version.combine(isJSClassVersion, method.version)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:618]: Nice!

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 8]
```diff
@@ -997,6 +1025,15 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
     }
   }
 
+  // case class to get automatic equals()
+  private case class UncachedDecisions(
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:1029]: I'm wondering if we should bit-pack this (feel we have done this for less in the past :P).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 9]
```diff
@@ -462,7 +481,7 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
     }
 
     // Static-like methods
-    for (methodDef <- linkedMethods) {
+    for (methodDef <- linkedMethods_!) { // versioning per member inside
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:484]: Method set is not tracked? (This looks like a bug which we should be able to reproduce on HEAD).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 10]
```diff
@@ -606,76 +647,66 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
+        linkedMethods_! ++ bridges_!
       } else {
-        linkedMethods
+        linkedMethods_!
       }
 
       // Normal methods
       val memberMethodsWithGlobals = for {
-        method <- linkedMethodsAndBridges
+        method <- linkedMethodsAndBridges_! // explicitly versioned below, by member
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:657]: - Needs justification how method set is tracked.
- Maybe `method_!`?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala [hunk 11]
```diff
@@ -606,76 +647,66 @@ final class Emitter(config: Emitter.Config, prePrinter: Emitter.PrePrinter) {
...
+                isJSClass, // always safe
+                useESClass, // always safe
                 method // invalidated by method.version
             )(moduleContext, methodCache).map(prePrint(_, memberIndent))))
       }
 
       // Exported Members
       val exportedMembersWithGlobals = for {
-        (member, idx) <- linkedClass.exportedMembers.zipWithIndex
+        (member, idx) <- linkedClass_!.exportedMembers.zipWithIndex // explicitly versioned below, by member
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:674]: - Needs justification how method set is tracked.
- Maybe `member_!`?

**Review by gzm0 — CHANGES_REQUESTED** [review]
The overhaul looks very nice.

I have left some suggestions for improvement. Unfortunately, IIUC, it also surfaced an issue with static methods (which in some sense is a good thing: seems the justification works).

I'm OK with leaving a TODO / fixme in the code for that to get this shipped.

Do you agree that the first commit should probably disappear / be refactored? (obviously we want to keep the test, but IIUC the changes in Emitter all are undone in the last commit).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala (hunk 5 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala:620]: I don't think so. It would obscure the reason why the other "invalidated by class version" are correct (`superClass, `pos`).

**Review by sjrd — COMMENTED** [review]
Updated with a fix to the set of static-like methods, and more justifications.

I think I have addressed all the comments so far.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala (hunk 4 above)
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/Emitter.scala]: The comment is clear now. IIUC, proposals like https://github.com/scala-js/scala-js/issues/1593 could break this.

However, let's maybe not block this PR on this: it clearly improves that status quo and it seems this can be easily fixed later.

**Review by gzm0 — APPROVED** [review]
Just one optional comment.

**Comment by sjrd** [comment]
Squashed the last two commits (without change) before merging.
