### PR TITLE
Fix #4352: Unify error handling in java.util.Formatter.

### LINKED ISSUE #4352: `j.u.Formatter` exceptions throwing order is not JVM compliant
There are 5 exceptions that can be thrown in `j.u.Formatter`, on the JVM they're boing thrown in given order: 
 * `UnknownFormatConversionException`
 * `MissingFormatWidthException` 
 * `IllegalFormatFlagsException`
 * `FormatFlagsConversionMismatchException` 
 * `IllegalFormatConversionException`
 
 Following tests would fail in Scala.Js: 
 ```
   locally {
      // compare FormatFlagsConversionMismatchException and
      // IllegalFormatConversionException
      val f = new Formatter()
      assertThrows(classOf[FormatFlagsConversionMismatchException],
                   f.format("%,e", 1.toByte.asInstanceOf[Object]))
    }

    locally {
      // compare IllegalFormatFlagsException and
      // FormatFlagsConversionMismatchException
      val f = new Formatter()
      assertThrows(classOf[IllegalFormatFlagsException],
                   f.format("%+ ,e", 1f.asInstanceOf[Object]))
    }

    locally {
      // compare MissingFormatWidthException and
      // IllegalFormatFlagsException
      val f = new Formatter()
      assertThrows(classOf[MissingFormatWidthException],
                   f.format("%+ -e", 1f.asInstanceOf[Object]))
    }

    locally {
      // compare UnknownFormatConversionException and
      // MissingFormatWidthException
      val f = new Formatter()
      assertThrows(classOf[UnknownFormatConversionException],
                   f.format("%-F", 1f.asInstanceOf[Object]))
    }
 ```
 More test cases can be ported from `formatFor.*ExceptionThrowingOrder` tests in [ScalaNative DefaultFormatterTest](https://github.com/scala-native/scala-native/blob/master/unit-tests/src/test/scala/java/util/DefaultFormatterTest.scala)

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 1]
```diff
@@ -157,24 +157,97 @@ final class Formatter private (private[this] var dest: Appendable,
...
+
+        if (flags.hasAnyOf(LeftAlign | ZeroPad) && width == -1)
+          throwMissingFormatWidthException(fullFormatSpecifier)
+
+        // 4. IllegalFormatFlagsException
+
+        checkIllegalFormatFlags(flags)
+
+        // 5. IllegalFormatPrecisionException
+
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:236]: `illegalFlags.hasAnyOf`?

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala [hunk 2]
```diff
@@ -25,6 +25,7 @@ import java.util._
 class FormatterTest {
   import FormatterTest._
 
+  @noinline
```
Comment (gzm0) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala:28]: Why are these necessary with this commit?

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala [hunk 3]
```diff
@@ -758,6 +769,182 @@ class FormatterTest {
...
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%, j", 5)
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%, j", null)
+
+    // IllegalFormatPrecisionException
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%.3j", 5)
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%.3j", null)
+
+    // FormatFlagsConversionMismatchException
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%#j", 5)
+    expectFormatterThrows(classOf[UnknownFormatConversionException], "%#j", null)
```
Comment (gzm0) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala:809]: I do not fully understand why the tests here deviate form the pattern:

1. Expect exception that has precedence
2. Remove that error in the pattern and check the other exception is thrown.

IMO this pattern is extremely helpful to make sure the test suite actually tests something.

**Review by gzm0 — COMMENTED** [review]
Only minor stuff.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 4]
```diff
@@ -749,6 +769,44 @@ final class Formatter private (private[this] var dest: Appendable,
...
+    throw new DuplicateFormatFlagsException(flag.toString())
+
+  private def throwUnknownFormatConversionException(conversion: Char): Nothing =
+    throw new UnknownFormatConversionException(conversion.toString())
+
+  private def throwUnknownFormatConversionException(conversion: String): Nothing =
+    throw new UnknownFormatConversionException(conversion)
+
+  private def throwIllegalFormatPrecisionException(precision: Int): Nothing =
+    throw new IllegalFormatPrecisionException(precision)
```
[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:771]: Yes, it's for consistency. Same for some others. I have added a comment.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala (hunk 2 above)
Comment (sjrd) [reply test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala]: They're not. I forgot to remove them. Done now.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala (hunk 3 above)
Comment (sjrd) [reply test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/FormatterTest.scala:817]: To me it didn't make sense, because I'd have to use a known conversion to provoke the issue, and the test is about the precedence for unknown conversions. But I guess that's fine. I've added additional tests to fit the pattern.

**Review by sjrd — COMMENTED** [review]
Updated.

**Review by gzm0 — APPROVED** [review]
