### PR TITLE
Fix #1201: Correct regex support.

### LINKED ISSUE #1201: Regex differences
_(Continuing discussion from #1198)_

There are differences between how regex behaves on the JVM vs generated JS. Some things shouldn't be too hard to fix, others will be near impossible without either creative hacks or switching to a bundled regex engine. It would also be beneficial to have a document somewhere stating the differences so that devs are aware. If you don't object, let's use this issue to at least start compiling a list of differences and see what (if anything) to do about it.

Off the top of my head we've got:
- Look-behinds (`(?<=)`, `(?<!)`). JS regex doesn't support this.
- Java-style quotes/literals. `Pattern.quote` uses `\Q` and `\E` which doesn't work in JS.
- Java-style character sets, example: `/[\p{S}\p{P}]/`.

I'll add more as I think of them.

A semi-fix for `Pattern.quote` would be to use the a regex escaping function from a mature JS library, Google Closure's is short and sweet. Handling `\Q..\E` on the other hand would be harder.

Funny story about `[\p{S}\p{P}]`, I actually needed that in my JS so I wrote a little converter for that kind of regex so that it would work in Scala.js. I replaced it with `[\u0021-\u002f\u003a-\u0040\\[-\u0060\u007b-\u007e\u00a1-\u00a9\u00ab\u00ac\u00ae-\u00b1\u00b4\u00b6-\u00b8\u00bb\u00bf\u00d7\u00f7\u02c2-\u02c5\u02d2-\u02df\u02e5-\u02eb\u02ed\u02ef-\u02ff\u0375\u037e\u0384\u0385\u0387\u03f6\u0482\u055a-\u055f\u0589\u058a\u058f\u05be\u05c0\u05c3\u05c6\u05f3\u05f4\u0606-\u060f\u061b\u061e\u061f\u066a-\u066d\u06d4\u06de\u06e9\u06fd\u06fe\u0700-\u070d\u07f6-\u07f9\u0830-\u083e\u085e\u0964\u0965\u0970\u09f2\u09f3\u09fa\u09fb\u0af0\u0af1\u0b70\u0bf3-\u0bfa\u0c7f\u0d79\u0df4\u0e3f\u0e4f\u0e5a\u0e5b\u0f01-\u0f17\u0f1a-\u0f1f\u0f34\u0f36\u0f38\u0f3a-\u0f3d\u0f85\u0fbe-\u0fc5\u0fc7-\u0fcc\u0fce-\u0fda\u104a-\u104f\u109e\u109f\u10fb\u1360-\u1368\u1390-\u1399\u1400\u166d\u166e\u169b\u169c\u16eb-\u16ed\u1735\u1736\u17d4-\u17d6\u17d8-\u17db\u1800-\u180a\u1940\u1944\u1945\u19de-\u19ff\u1a1e\u1a1f\u1aa0-\u1aa6\u1aa8-\u1aad\u1b5a-\u1b6a\u1b74-\u1b7c\u1bfc-\u1bff\u1c3b-\u1c3f\u1c7e\u1c7f\u1cc0-\u1cc7\u1cd3\u1fbd\u1fbf-\u1fc1\u1fcd-\u1fcf\u1fdd-\u1fdf\u1fed-\u1fef\u1ffd\u1ffe\u2010-\u2027\u2030-\u205e\u207a-\u207e\u208a-\u208e\u20a0-\u20ba\u2100\u2101\u2103-\u2106\u2108\u2109\u2114\u2116-\u2118\u211e-\u2123\u2125\u2127\u2129\u212e\u213a\u213b\u2140-\u2144\u214a-\u214d\u214f\u2190-\u23f3\u2400-\u2426\u2440-\u244a\u249c-\u24e9\u2500-\u26ff\u2701-\u2775\u2794-\u2b4c\u2b50-\u2b59\u2ce5-\u2cea\u2cf9-\u2cfc\u2cfe\u2cff\u2d70\u2e00-\u2e2e\u2e30-\u2e3b\u2e80-\u2e99\u2e9b-\u2ef3\u2f00-\u2fd5\u2ff0-\u2ffb\u3001-\u3004\u3008-\u3020\u3030\u3036\u3037\u303d-\u303f\u309b\u309c\u30a0\u30fb\u3190\u3191\u3196-\u319f\u31c0-\u31e3\u3200-\u321e\u322a-\u3247\u3250\u3260-\u327f\u328a-\u32b0\u32c0-\u32fe\u3300-\u33ff\u4dc0-\u4dff\ua490-\ua4c6\ua4fe\ua4ff\ua60d-\ua60f\ua673\ua67e\ua6f2-\ua6f7\ua700-\ua716\ua720\ua721\ua789\ua78a\ua828-\ua82b\ua836-\ua839\ua874-\ua877\ua8ce\ua8cf\ua8f8-\ua8fa\ua92e\ua92f\ua95f\ua9c1-\ua9cd\ua9de\ua9df\uaa5c-\uaa5f\uaa77-\uaa79\uaade\uaadf\uaaf0\uaaf1\uabeb\ufb29\ufbb2-\ufbc1\ufd3e\ufd3f\ufdfc\ufdfd\ufe10-\ufe19\ufe30-\ufe52\ufe54-\ufe66\ufe68-\ufe6b\uff01-\uff0f\uff1a-\uff20\uff3b-\uff40\uff5b-\uff65\uffe0-\uffe6\uffe8-\uffee\ufffc\ufffd]`

### PR DESCRIPTION
**Pull request by sjrd**
This PR correctly implements `java.util.regex` by compiling Java regexes down to JavaScript RegExp's that do the same thing.

Until now, we basically passed regexes through to JavaScript's `RegExp`, not caring at all whether the behavior was going to be as specified or not. This could result in:
* `SyntaxError`s, for features not supported by JS
* or worse, regexes that successfully compile, but behave differently than their spec

In this commit, we compile everything we can compile, and throw `PatternSyntaxException`s for things that we cannot faithfully compile.

Some features require the underlying JS `RegExp` to support ES 2018:
* the `MULTILINE` and `UNICODE_CHARACTER_CLASS` flags
* look-behind assertions
* `\p{}` classes for Unicode properties

In addition, `UNICODE_CASE` requires support for the `u` flag, which is ES 2015. `CANON_EQ` is never supported.

Everything else is supported in all cases. Even correct handling of surrogate pairs is supported in ES 5.1, which does not support the `u` flag.

---

My main open question is: what do we do about the features that require ES 2018 support? As currently implemented, they will throw `PatternSyntaxException`s at run-time if the JS engine does not support the required features. This could result in surprises if the developers test using a recent Node.js version, but then deploy in environments that are not guaranteed to support ES 2018. This can even happen in unexpected situations, for example the `MULTILINE` flag requires look-behind assertions, even though JS' `RegExp` has a support for an `m` flag even in ES 5.1. The problem is that JS' notion of `m` is not equivalent to Java's notion of `MULTILINE`, so we can't delegate to it.

Of course, run-time errors depending on newer ES features can already happen, but never through usage of JDK APIs. It can happen through direct usages of JavaScript APIs, even some declared in our standard library, but they are marked as such in the Scaladoc.

I don't think we have precedent for JDK features that are conditional on ES features. How should we address that? Possible ideas are:

* Do nothing, and accept that run-time crashes may happen; developers should test under the environments that they care about.
* Provide an opt-in link-time config to enable the ES 2018-dependent features; if it is not set, we would unconditionally throw `PatternSyntaxException`s for features that would need the ES 2018 features.
* Not provide those features at all (I don't think this is a good idea)

@gzm0 WDYT?

---

To-do

* [x] Flesh out the open question above
* [x] More tests (what I have so far is quite decent, but there really are a *lot* of possible combinations that need testing)
* [x] Clean up, especially the compilation of `[...]` character classes
* [x] Better document the implementation

### CODE REVIEW

**Comment by nightscape** [comment]
Might be a stupid idea, but could one maybe transform the string to match in such a way that it can be more simply matched by a JS regex?

**Comment by japgolly** [comment]
If this has a non-negligible impact on resulting JS sizes, can we please also have a setting to opt-out of this new behaviour?

**Comment by sjrd** [comment]
> Might be a stupid idea, but could one maybe transform the string to match in such a way that it can be more simply matched by a JS regex?

I had thought about that to implement support for `CANON_EQ`, but it doesn't work, because it also changes the captured substrings, and that is not correct behavior. So no, we cannot do that. Anyway, the only other feature for which it might help would be ASCII case insensitive, but that's not really hard to implement by transforming the pattern instead, so we don't gain anything.

> If this has a non-negligible impact on resulting JS sizes, can we please also have a setting to opt-out of this new behaviour?

I haven't looked at the code size impact yet. Given the size of the implementation in Scala (1.5 kLoC), I guess it will be 3-4 kB of fastOpt code. But no, we won't be able to have a switch to disable the behavior. This is no different from any other method of the JDK. If you don't want its code size, don't use it and use `js.RegExp` instead. Just like if you don't want the Unicode database embedded in your program, don't use `c.isDigit` but `c >= '0' && c <= '9'`.

**Comment by sjrd** [comment]
With the current state of this PR, where I have made some effort not to produce unreasonable code by accident, the size increases are of
* about 100 kB for fastOpt
* about 17 kB for fullOpt

Looks like I was quite off the mark for my wild estimation above. That said, I don't think it fundamentally changes the problem. As I've been working on this, I noticed how broken blindly using `js.RegExp` was; virtually nothing behaves the same except the most simple combinators. Even simple things like `\s` or `.` are incorrect.

**Comment by gzm0** [comment]
> I don't think we have precedent for JDK features that are conditional on ES features. How should we address that? Possible ideas are:

I think we should chose safety before generating stuff that doesn't work. Basically:

1. Introduce `ESFeatures.useECMAScript20{16-21}` and `LinkingInfo.assumingES20{16-21}` (maybe parametrize?)
2. Use these to link-time DCE the JDK autodetect.
3. Throw when we cannot translate a construct, have a nice error message if an ES feature upgrade could allow the translation.

(our usual approach here is auto-detect and polyfill; that is OK IMO as long as we actually polyfill, which here is probably not up for discussion).

So if somebody ends up using a feature, they simply need to acknowledge in their build once that they are OK with that ES version.

> Looks like I was quite off the mark for my wild estimation above. That said, I don't think it fundamentally changes the problem. 

While I agree with this reasoning, I think there is another point we need to consider: For all practical intents and purposes, bumping the codesize of a thing by that much is a backwards incompatible change (this is also where the argument is imprecise IMO: for most javalib stuff, we just add new things, so use it or leave it, existing things remain unchanged or get bugfixes that don't affect actual usage for the worse).

With such a big bump, maintainers of codebases that heavily relied on regexes (and have worked "just fine" for ~7 years), would now be faced with the choice of either:
- Stalling Scala.js upgrades (nobody wants that, not us, not our users).
- Investing a considerable amount of effort to migrate off Java regexes (possible, but might involve *a lot* of new wrapper classes etc. if code is cross compiling).

I do not think we should leave our users in this situation.

I do not have a solution for this right now (that doesn't involve dependency hellscape for at least one side of the equation), so I'll keep thinking.

**Comment by sjrd** [comment]
> With such a big bump, maintainers of codebases that heavily relied on regexes (and have worked "just fine" for ~7 years), would now be faced with the choice of either:

Supposedly, a codebase such that adjusting to js.RegExp would be a significant cost is also a large enough codebase that 17 kB won't make a real difference, would it?

I'm more worried about the actual *correctness* issues, in terms of breaking changes. It's not impossible that there are codebases that actually really on `Pattern` behaving like JavaScript, and not as documented in the JavaDoc. Unlike our other fixes to JDK stuff, this one has been *documented* to behave as it does for 7 years. 😕

**Comment by gzm0** [comment]
> Supposedly, a codebase such that adjusting to js.RegExp would be a significant cost is also a large enough codebase that 17 kB won't make a real difference, would it?

Hmmm... That's a good point. Although I'm not sure that's the case. So for example, a case I was concerned about is usage of `Pattern` in some larger data structures / across library interfaces / underpinning of a library. For example, the scalalib itself is actually an example here:

```scala
// from the doc of scala.util.matching.Regex
val date = raw"(\d{4})-(\d{2})-(\d{2})".r

"2004-01-20" match {
  case date(year, month, day) => s"$year was a good year for PLs."
}
```

Will have to be transformed into:

```scala
val date = new JSExtractor(new js.RegExp("(\d{4})-(\d{2})-(\d{2})"))

"2004-01-20" match {
  case date(year, month, day) => s"$year was a good year for PLs."
}

class JSExtractor(...) {
  def unapply(...) = ...
}
```

But I have no clue how to quantify cost of transformation with library size :-/

> Unlike our other fixes to JDK stuff, this one has been documented to behave as it does for 7 years

That is true. OTOH though, as the referenced bugs on this PR prove, it has been considered a bug by many and so far, no fix towards the Java behavior has been filed as a bug / regression.

**Comment by sjrd** [comment]
> I think we should chose safety before generating stuff that doesn't work. Basically:
> 
> 1. Introduce `ESFeatures.useECMAScript20{16-21}` and `LinkingInfo.assumingES20{16-21}` (maybe parametrize?)
> 2. Use these to link-time DCE the JDK autodetect.
> 3. Throw when we cannot translate a construct, have a nice error message if an ES feature upgrade could allow the translation.
> 
> (our usual approach here is auto-detect and polyfill; that is OK IMO as long as we actually polyfill, which here is probably not up for discussion).
> 
> So if somebody ends up using a feature, they simply need to acknowledge in their build once that they are OK with that ES version.

I pushed new commits that implement that strategy.

As a bonus, this brings the fullOpt increase down from 17 KB to 15 kB in the default configuration (producing ES 2015 code). That's because the code dealing with `\p{}` character classes, including the `predefinedCharacterClass` map, can be dead-code-eliminated. (which is actually quite remarkable)

**Comment by sjrd** [comment]
Anything that has new configuration will require a minor version bump. Since we don't have anything else in flight that can go in a patch release, I suggest we release 1.5.1 now.

@gzm0 If you agree, I prepared a version commit here: https://github.com/sjrd/scala-js/commit/3746189c5a0fedca3cfb0f34082b100473b4aafa

**Comment by sjrd** [comment]
After a session of trying to optimize for code size, I am down to:

* 70 kB increase in fastOpt
* 13 kB increase in fullOpt

See you after the Easter break for the next episode :p

**Comment by sjrd** [comment]
> While I agree with this reasoning, I think there is another point we need to consider: For all practical intents and purposes, bumping the codesize of a thing by that much is a backwards incompatible change (this is also where the argument is imprecise IMO: for most javalib stuff, we just add new things, so use it or leave it, existing things remain unchanged or get bugfixes that don't affect actual usage for the worse).
> 
> With such a big bump, maintainers of codebases that heavily relied on regexes (and have worked "just fine" for ~7 years), would now be faced with the choice of either:
> 
> * Stalling Scala.js upgrades (nobody wants that, not us, not our users).
> * Investing a considerable amount of effort to migrate off Java regexes (possible, but might involve _a lot_ of new wrapper classes etc. if code is cross compiling).
> 
> I do not think we should leave our users in this situation.
> 
> I do not have a solution for this right now (that doesn't involve dependency hellscape for at least one side of the equation), so I'll keep thinking.

I've been thinking about this, but I don't see any way out.

We cannot have a configuration option to switch from JDK semantics to JS semantics, because it's not monotonic. All our link-time settings are monotonic in the sense that if one library requires a value A for a setting and another library requires a value B, there is one of A and B that guarantees everything that the other guarantees. So you can pick the stronger one for an application that uses both libraries, and things will work. For the JVM/JS regex semantics, neither is stronger than the other; some things work in one guaranteed way on the JVM, and work in another guaranteed way in JS. So if you use two libraries that rely on the two possible values of that config, you *cannot* reconcile them.

For the same reason, we cannot have a separate library that offers the other semantics.

We could offer a library that provides an API similar to `scala.util.matching.Regex` but that wraps a `js.RegExp` (let's say it's called `JSRegex`). But that still does not solve cases where you want to use an API that takes an `s.u.m.Regex` as a parameter, and what you want to give is a `JSRegex`.

I thought about having a roundabout way to create an `s.u.m.Regex` instance that actually wraps a `js.RegExp`, but its API is too tightly integrated with `j.u.r.Pattern` to allow that. Neither using a subclass nor using a source override can get us there.

The closest I've come to a solution is to offer a side API to create a `j.u.r.Pattern` directly from a `js.RegExp`, without going through `compile()`. We do that kind of stuff for `java.nio.Buffer`s and TypedArrays. However, there is no public API to create an `s.u.m.Regex` from a `j.u.r.Pattern` anyway. The only public API is to take a `regex: String`, and it is `Regex` that calls `Pattern.compile()`, so if the goal is to reuse the API of `Regex`, we're still stuck.

---

AFAICT, there is no solution but to the bite the code size increase bullet. We can try to make that increase as small as possible; the current state of this PR is at 12.5 kB, but I have reached the point of diminishing returns, and it seems I will never get below 12 kB, let alone less than that.

**Comment by gzm0** [comment]
That seems to summarize it quite well indeed.

The only thing we might discuss at this point is whether this warrants a major version bump (not because of the code size, but because of the semantics that change). Essentially we get to chose whether we
1. cleanly separate old-regex and new-regex things (but causing bootstrapping effort) or
2. we allow them to coexist (but potentially causing subtle bugs, e.g. in an old library linked with a newer javalib).

I'm frankly unsure. 1 seems like the "do not compromise right thing to do". 2 seems like it might be "just fine", but also feels like it bears much more unknowns.

**Comment by sjrd** [comment]
Right, that is a valid point.

1. IMO, if it comes to requiring a major version bump, then it's not worth it. We can keep it under wraps and bring it back next time we have to bump the major version for another reason. And probably that would only be worth it for a broken assumption about ECMAScript (like the global object/global scope problem we had in 0.6.x).
2. My intuition is that it would be fine if there are (next to) no *library* out there that require the JS semantics. Libraries are problematic because they can cause diamond dependency-related issues. Applications don't have that problem: they can fix their regexes if and when they upgrade their Scala.js version. Usually we try Google+GitHub Search to identify whether some stuff is used in the wild, but here it is going to be tough because we would be looking for things that are not specific to JS.

**Comment by gzm0** [comment]
Yeah, I pretty much agree with that assessment :-/

So basically, what we are looking for are Scala libraries that
1. Do not cross-compile (otherwise they already deal with the semantic skew).
2. Use Java/Scala regexes instead of JS regexes (in a non-compatible manner).

I think this actually gives us a reasonable starting point: We can get 1 by searching maven for things with `_sjs1` that don't have the equivalent without the suffix. Once we have that list, we can figure out if/how to assess 2.

**Comment by sjrd** [comment]
> I think this actually gives us a reasonable starting point: We can get 1 by searching maven for things with `_sjs1` that don't have the equivalent without the suffix. Once we have that list, we can figure out if/how to assess 2.

Indeed! I asked adpi2 and he came up with this Scaladex voodoo request:
https://index.scala-lang.org/search?q=*+AND+targetType%3Ajs+NOT+jvm+AND+scalaJsVersion%3A1.x

**Comment by gzm0** [comment]
Hah, nice! Does scaladex have an API? At that point, it might be feasible to clone these from github and search for scala/java regex :)

**Comment by gzm0** [comment]
(we might also want to exclude facades, they shouldn't contain code)

**Comment by sjrd** [comment]
I went through the ~100 projects by hand to search `regex` in the GitHub search, which covers both Scala's `Regex` and Java's `regex.Pattern`. I identified 3 repos that need investigating:
* https://github.com/getshaka-org/shaka-router/blob/5ec4739b1c053eed88e9ef4d63a8aa54f5bec25a/src/main/scala/org/getshaka/shaka/router/Router.scala
* https://github.com/gemini-hlsw/lucuma-ui/blob/14d49176505c7d1808eb3ee4a54ef1892d4614be/modules/ui/src/main/scala/lucuma/ui/optics/ChangeAuditor.scala#L363
* https://github.com/japgolly/scalajs-react/search?q=regex

However, that doesn't cover code that uses `.r` and, due to type inference, never writes down the `regex` word. For that, the GitHub search is not helpful. We would need to script the cloning and `git grep -P '\.r\b'` or something like that.

**Comment by sjrd** [comment]
And here is a .txt file with all the GitHub links, which can be used to write a script:
https://gist.github.com/sjrd/daa9232116110d669d09e4ae8d78c39b

**Comment by sjrd** [comment]
And here's the output of the script:
```
$ while read in; do git clone "$in.git"; done < ../js-libraries.txt
[...]
$ grep -r -P '\.r\b' --include '*.scala' .
./api-framework/src/main/scala/com/lkroll/roll20/api/Attribute.scala:  val rowIdPattern = raw"repeating_[a-zA-Z]+_([-a-zA-Z0-9]+)_.*".r;
./api-framework/src/main/scala/com/lkroll/roll20/api/AttributeContext.scala:    val pattern = s"""repeating_${sectionName}_[-a-zA-Z0-9]+_.*""".r;
./gpp-ui/modules/ui/src/main/scala/lucuma/ui/optics/ChangeAuditor.scala:    val regex = s"(.*\\.\\d{0,$n}[1-9]*)+0*".r
./gpp-ui/modules/ui/src/main/scala/lucuma/ui/optics/ChangeAuditor.scala:      val regex    = s"0{0,$newPos}(\\d+)".r
./lucuma-ui/modules/ui/src/main/scala/lucuma/ui/optics/ChangeAuditor.scala:    val regex = s"(.*\\.\\d{0,$n}[1-9]*)+0*".r
./lucuma-ui/modules/ui/src/main/scala/lucuma/ui/optics/ChangeAuditor.scala:      val regex    = s"0{0,$newPos}(\\d+)".r
./scala-js-nodejs/core/src/main/scala/io/scalajs/nodejs/internal/CompilerSwitches.scala:  private val nodejsVersionPattern = "^nodeJs([0-9]{1,2})\\.([0-9]{1,2})\\.([0-9]{1,2})$".r
./scalajs-benchmark/benchmark/src/main/scala/japgolly/scalajs/benchmark/gui/GuiUtil.scala:  private val numberFmt = """^-?(\d[,.]?)+(?:[,.]\d+)?$""".r.pattern
./scalajs-benchmark/benchmark/src/main/scala/japgolly/scalajs/benchmark/gui/IntEditor.scala:  private val illegalChars = "[^0-9-]+".r
./scalajs-benchmark/benchmark/src/main/scala/japgolly/scalajs/benchmark/gui/package.scala:      val r = "[ ,]".r
./scalajs-benchmark/benchmark/src/main/scala/japgolly/scalajs/benchmark/gui/ReactChart.scala:      val dr = (to.r - from.r).toDouble
./scalajs-benchmark/benchmark/src/main/scala/japgolly/scalajs/benchmark/gui/ReactChart.scala:        val r = fix(x.pct * dr + from.r)
./scalajs-benchmark/project/Lib.scala:  private val verRegex = """^(\d+)\.(\d+)\.(\d+)-?(.+)?$""".r
./scalajs-facades/project/PropTypeInfo.scala:  private val stringEnumValueRE = "'(.*)'".r
./scalajs-facades/project/PropTypeInfo.scala:  private val litEnumValueRE = """(true|false|-?\d+\.\d+|-?\d+)""".r
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:  private val regexEscape1 = """([-()\[\]{}+?*.$\^|,:#<!\\])""".r
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:  private val regexEscape2 = """\x08""".r
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    val kvRegex = "^([^=]+)(?:=(.*))?$".r
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    val needingEncoding = """[~!'()]|%[02]0""".r
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    rewritePathR("^(.*?)\\?.*$".r, m => redirectToPath(m group 1)(SetRouteVia.HistoryReplace))
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    rewritePathR("^(.*?)/+$".r, m => redirectToPath(m group 1)(SetRouteVia.HistoryReplace))
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    rewritePathR("^/+(.*)$".r, m => redirectToPath(m group 1)(SetRouteVia.HistoryReplace))
./scalajs-react/extra/src/main/scala/japgolly/scalajs/react/extra/router/Dsl.scala:    rewritePathR("^/*(.*?)/+$".r, m => redirectToPath(m group 1)(SetRouteVia.HistoryReplace))
./scalajs-react/gh-pages/src/main/scala/ghpages/examples/ReuseExample.scala:  val numberRegex = "^-?\\d+$".r
./scalajs-react/gh-pages/src/main/scala/ghpages/secret/tests/AsyncTest.scala:    val idRegex = "(\"id\":\\d+)".r
./scalajs-react/gh-pages-macros/src/main/scala/ghpages/GhPagesMacros.scala:  val trimRight = "\\s+$".r
./scalajs-react/gh-pages-macros/src/main/scala/ghpages/GhPagesMacros.scala:    val r = s"""\n[ \t]*//[ \t]*${Pattern quote marker}[ \t]*""".r
./scalajs-react/test/src/main/scala/japgolly/scalajs/react/test/ReactTestUtils.scala:  private val reactDataAttrRegex = """\s+data-react\S*?\s*?=\s*?".*?"""".r
./scalajs-react/test/src/main/scala/japgolly/scalajs/react/test/ReactTestUtils.scala:  private val reactTextCommentRegex = """<!-- /?react-text[: ].*?-->""".r
./scalajs-react/test/src/test/scala/japgolly/scalajs/react/extra/router/Router2Test.scala:    val alphaOnly = "^([a-zA-Z]+)$".r
./scalajs-react/test/src/test/scala/japgolly/scalajs/react/extra/router/RouterP2Test.scala:    val alphaOnly = "^([a-zA-Z]+)$".r
./scalajs-react/test/src/test/scala/japgolly/scalajs/react/test/TestUtil.scala:  private val reactRubbish = """\s+data-react\S*?\s*?=\s*?".*?"|<!--(?:.|[\r\n])*?-->""".r
./scalajs-react-common/test/src/main/scala/react/common/TestUtils.scala:    """\s+data-react\S*?\s*?=\s*?".*?"|<!--(?:.|[\r\n])*?-->""".r
./scalajs-react-material-ui/demo/src/main/scala/io/kinoplan/demo/components/Layout.scala:            MainMenu(props.router, props.r)
./scalajs-react-material-ui/demo/src/main/scala/io/kinoplan/demo/components/Layout.scala:            props.r.render()
./scalajs-react-material-ui/demo/src/main/scala/io/kinoplan/demo/modules/MainMenu.scala:              ChildMenu(props.router, props.r, ChildMenuItem.demos)
./scalajs-react-material-ui/demo/src/main/scala/io/kinoplan/demo/modules/MainMenu.scala:              ChildMenu(props.router, props.r, ChildMenuItem.labs)
./scalajs-react-semantic-ui/demo/src/main/scala/react/semanticui/demo/Layout.scala:            p.r.render()
./scalajs-react-semantic-ui/project/JSDOMNodeJSEnv.scala:  private val tmpSuffixRE = """[a-zA-Z0-9-_.]*$""".r
./shaka-router/src/main/scala/org/getshaka/shaka/router/Router.scala:  private val HashRegex = raw".*#(\S+)".r.anchored
./shaka-router/src/main/scala/org/getshaka/shaka/router/Router.scala:      .map(paramStates => Route(frs.r, component, paramStates))
./shaka-router/src/main/scala/org/getshaka/shaka/router/Router.scala:      .getOrElse(Route(frs.r, component, buildParamStates(frs)))
./sjavatime/sjavatime/shared/src/main/scala/java/time/Instant.scala:      val pattern = """(^[-+]?)(\d*)-(\d*)-(\d*)T(\d*):(\d*):(\d*).?(\d*)Z""".r
./sjavatime/sjavatime/shared/src/main/scala/java/time/LocalDate.scala:      val pattern = """(^[-+]?)(\d*)-(\d*)-(\d*)""".r
```
Modulo the precise set of characters matched by `.`, almost all of the above behave the same in JS and JVM (because they're not in multiline mode).

The one at
https://github.com/japgolly/scalajs-react/blob/5c7b8f21d02acd0c5779ca65a36749431897d5c5/test/src/main/scala/japgolly/scalajs/react/test/ReactTestUtils.scala#L331
which is `"""\s+data-react\S*?\s*?=\s*?".*?"""".r`, behaves differently because `\s` and `\S` do not match the exact same set of characters. @japgolly Is that one an issue?
* In JS, `\s` matches `[ \t\n\x0B\f\r\xA0\uFEFF]` and any Unicode “Space_Separator” code point (JS specifies the list as `<TAB> <VT> <FF> <SP> <NBSP> <ZWNBSP> <USP> <LF> <CR> <LS> <PS>`)
* In JVM, it only matches `[ \t\n\x0B\f\r]` (i.e., the ASCII ones)

There is also `"""\s+data-react\S*?\s*?=\s*?".*?"|<!--(?:.|[\r\n])*?-->""".r` with the same potential issue.

For completeness, the difference between JS and JVM for `.` is that:
* In JS, `.` matches everything but `[\n\r\u2028\u2029]`.
* In JVM, it matches everything but `[\n\r\x85\u2028\u2029]`. (there is `\x85` in addition)

**Comment by japgolly** [comment]
> """\s+data-react\S*?\s*?=\s*?".*?"""".r, behaves differently because \s and \S do not match the exact same set of characters. @japgolly Is that one an issue?

No, that's not an issue, either interpretation would work for that regex's indented purpose.

What's weird is that there are more unicode space chars that exist but aren't in your whitelist above. From memory \u3000 is a full-width space and there are other kinds of unicode spaces too.

**Comment by sjrd** [comment]
> No, that's not an issue, either interpretation would work for that regex's indented purpose.

Cool, thanks!

> What's weird is that there are more unicode space chars that exist but aren't in your whitelist above. From memory \u3000 is a full-width space and there are other kinds of unicode spaces too.

Yes, `\u3000` and the others are part of "any Unicode “Space_Separator” code point" which the JS spec puts under `<USP>`. They're all the code points with general category `Zs`.

**Comment by sjrd** [comment]
I've added a test with all the (non-duplicated) regexes found above, to make sure that they at least still parse (including in ES 5.1!) and do something sensible.

**Comment by sjrd** [comment]
@gzm0 This PR is now ready for review. It's a big one, so take your time. It's been broken for 7 years; it can wait a bit more 😅

**Comment by japgolly** [comment]
Wow. You did it @sjrd!! That's amazing, nice work! :tada:

**Comment by sjrd** [comment]
@gzm0 Do you think you might be able to give an overall "OK for the concept" by the end of next week? Not a review nor even reading the readme, just about the concept of compiling down to JS RegExp, accepting the code size hit and the semantics change, and using `esVersion` has a gatekeeper of which features are enabled or not.

I'll be talking about this, among other things, in my ScalaCon talk two weeks for now, and it would be nice to be able to say "it will eventually get in" even if we don't know when. ;)

**Comment by gzm0** [comment]
> Do you think you might be able to give an overall "OK for the concept" by the end of next week? 

Absolutely. The overall concept looks good. Codesizes are in the acceptable, the analysis for backwards compatibility is adequate. So I expect this to land in pretty much this form from a higher level POV.

My pending review is already looking at much more detailed things. (if you prefer I can release what I have, but some things might drastically change again, since I couldn't look at everything yet).

**Comment by sjrd** [comment]
> 
> 
> > Do you think you might be able to give an overall "OK for the concept" by the end of next week?
> 
> Absolutely. The overall concept looks good. Codesizes are in the acceptable, the analysis for backwards compatibility is adequate. So I expect this to land in pretty much this form from a higher level POV.

OK cool thank you :)

> (if you prefer I can release what I have, but some things might drastically change again, since I couldn't look at everything yet).

No, it's fine. There's no need to release anything partial. ;)

**Comment by gzm0** [comment]
I'm going to continue review under the assumption that nothing in this PR changed. GitHub says, the following have changed: 
- javalib/src/main/scala/java/util/regex/GroupStartMapper.scala
- javalib/src/main/scala/java/util/regex/Pattern.scala

I'll assume that these are marked as changed because of the big rebase. @sjrd if you actually changed something in these, please LMK.

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 1]
```diff
@@ -0,0 +1,1645 @@
...
+    // scalastyle:off return
+
+    val impossiblePattern = "[^\\d\\D]"
+
+    // State that crosses functions
+    val state = new CharacterClassState(asciiCaseInsensitive)
+    import state._
+
+    // State that is only used in this function
+    var conjunction = ""
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1467]: Put this in `CharacterClassState` / `CharacterClassBuilder`?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 2]
```diff
@@ -0,0 +1,1645 @@
...
+  }
+
+  private def compileCharacterClass(): String = {
+    // scalastyle:off return
+
+    val impossiblePattern = "[^\\d\\D]"
+
+    // State that crosses functions
+    val state = new CharacterClassState(asciiCaseInsensitive)
+    import state._
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1464]: I just saw that... I don't see the value of this. Either:
- Put all the state locally.
- Create a character class builder that protects its internal state.

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 3]
```diff
@@ -0,0 +1,1645 @@
...
+            case _ =>
+              parseSingleCodePointEscape()
+          }
+
+        case _ =>
+          pIndex += charCount(dispatchCP)
+          dispatchCP
+      }
+
+      if (startCodePoint != -1) {
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1550]: IMO this makes the control flow quite hard to understand. Is there any reasonable way we can put range parsing in a helper and invoke it in case we hit a CP escape or a normal character?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 4]
```diff
@@ -0,0 +1,1645 @@
...
+  }
+
+  private def compileGroup(): String = {
+    val pattern = this.pattern // local copy
+    val len = pattern.length()
+
+    val start = pIndex
+
+    if (start + 1 == len || pattern.charAt(start + 1) != '?') {
+      pIndex = start + 1
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1591]: Add a comment: "Capturing group"?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 5]
```diff
@@ -0,0 +1,1645 @@
...
+      groupNumberMap.push(compiledGroupCount)
+      "(" + compileInsideGroup() + ")"
+    } else {
+      if (start + 2 == len)
+        parseError("Unclosed group")
+
+      val c1 = pattern.charAt(start + 2)
+
+      if (c1 == ':' || c1 == '=' || c1 == '!') {
+        pIndex = start + 3
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1603]: Add a comment: "Non-capturing or look-ahead"?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 6]
```diff
@@ -0,0 +1,1645 @@
...
+        pattern.substring(start, start + 3) + compileInsideGroup() + ")"
+      } else if (c1 == '<') {
+        if (start + 3 == len)
+          parseError("Unclosed group")
+
+        val c2 = pattern.charAt(start + 3)
+
+        if (isLetter(c2)) {
+          val nameStart = start + 3
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1612]: Add a comment: "Named capturing group"?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 7]
```diff
@@ -0,0 +1,1645 @@
...
+  import Pattern._
+
+  /** Whether the result `Pattern` must be sticky. */
+  private var sticky: Boolean = false
+
+  /** The parse index, within `pattern`. */
+  private var pIndex: Int = 0
+
+  /** The number of capturing groups in the original pattern. */
+  private var originalGroupCount: Int = 0
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:655]: Isn't this just `groupNumberMap.length`?

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 8]
```diff
@@ -0,0 +1,1645 @@
...
+          compiledGroupCount += 1
+          groupNumberMap.push(compiledGroupCount)
+          if (namedGroups.contains(name))
+            parseError(s"named capturing group <$name> is already defined")
+          namedGroups(name) = originalGroupCount
+          "(" + compileInsideGroup() + ")"
+        } else {
+          requireES2018Features("Look-behind group")
+          if (c2 != '=' && c2 != '!')
+            parseError("Unknown look-behind group")
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1630]: I'd put this error before the feature error. (basically: say I don't know what you want rather then, guess and say I can't give you what you want and once you could, say, actually, I don't know what you want).

**Review by gzm0 — CHANGES_REQUESTED** [review]
Review for everything except RegexEngineTest. IMO this is meaningful on its own, so I'm sending it.

**Review by sjrd — COMMENTED** [review]
Updated. I think I have addressed all the comments so far, except in the readme. I need to do a second pass for the readme.

**Comment by sjrd** [comment]
> @sjrd if you actually changed something in these, please LMK.

I'm pretty sure that, besides rebases, the only thing that has changed over the last month or so is the following diff:
https://github.com/scala-js/scala-js/compare/24ce7cbb67416f1a04f0d39622002b8b9ea23272..b1aa90d795231f4caa446666947884c4b90cd189

**Review by sjrd — COMMENTED** [review]
Updated. Now I think I have addressed all the comments in the readme as well.

**Comment by sjrd** [comment]
@gzm0 I see that you've marked a lot of comments as Resolved, but haven't submitted a new review. Is it just that you accidentally left a Pending Review without submitting it, or you truly haven't finished it yet?

**Comment by gzm0** [comment]
I'm not done yet. Unfortunately resolved state is not part of the review batch (but I absolutely need it, otherwise I have no clue what I still need to look at :P).

**Comment by sjrd** [comment]
Ah ah, yes, that makes sense :)

File: javalib/src/main/scala/java/util/regex/README.md [hunk 9]
```diff
@@ -0,0 +1,322 @@
...
+
+Therefore, it seems wise to keep the JavaScript behavior, and not try to replicate the JVM behavior at great cost (if that is even possible within our constrains).
+
+## Implementation strategy
+
+Java regexes are compiled to JS regexes in one pass, using a recursive descent approach.
+There is a state variable `pIndex` which indicates the position inside the original `pattern`.
+Compilation methods parse a subexpression at `pIndex`, advance `pIndex` past what they parsed, and return the result of the compilation.
+
+Parsing is always done at the code point level, and not at the individual `Char` level.
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/README.md:95]: ~~I think this might need expanding (or maybe a footnote): It is unclear what happens if there are lone surrogates.~~

Seems like the "handling unicode section" below explains this, maybe reference it in a paren?

File: javalib/src/main/scala/java/util/regex/README.md [hunk 10]
```diff
@@ -0,0 +1,322 @@
...
+
+So far, we have assumed that the underlying RegExp supports the 'u' flag, which we test with `supportsUnicode`.
+In this section, we cover how the compilation is affected when it is not supported.
+This can only happen when we target ES 5.1.
+
+The ECMAScript specification is very precise about how patterns and strings are interpreted when the 'u' flag is enabled.
+It boils down to:
+
+* First, the pattern and the input, which are strings of 16-bit UTF-16 code units, are decoded into a *list of code points*, using the WTF-16 encoding.
+  This means that surrogate pairs become single supplementary code points, while lone surrogates (and other code units) become themselves as code points.
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/README.md:244]: become themselves code points (no "as").

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 11]
```diff
@@ -0,0 +1,1759 @@
...
+          3
+        } else if (property.startsWith("script=")) {
+          7
+        } else if (property.startsWith("In") || property.startsWith("blk=") || property.startsWith("block=")) {
+          parseError("Blocks are not supported in \\p Unicode character families")
+        } else {
+          // Error
+          parseError(s"Unknown Unicode character class '$property'")
+        }
+        CompiledCharClass.posP("sc=" + canonicalizeScriptName(property.substring(scriptPrefixLen)))
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:1579]: Tying this back to your rebuttal in: https://github.com/scala-js/scala-js/pull/4455#discussion_r651064387 (which I agree with in principle). What will happen if somebody gives an invalid script name? (e.g. `\p{sc=frobber}`)?

**Review by gzm0 — CHANGES_REQUESTED** [review]
Second round except for the tests. I'll start on them now :)

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 12]
```diff
@@ -0,0 +1,1759 @@
...
+    private var conjunction = ""
+    private var thisConjunct = ""
+    private var thisSegment = ""
+
+    def finish(): String = {
+      val conjunct = conjunctResult()
+      if (conjunction == "") conjunct else s"(?:$conjunction$conjunct)"
+    }
+
+    def finishConjunct(): Unit = {
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/regex/PatternCompiler.scala:525]: I think this is misnamed: It doesn't *finish* the conjunct, it starts a new one. Maybe call it `beginConjunct`? (also not 100% accurate, I realize, because it need not be called for a single conjunct :-/)

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala [hunk 13]
```diff
@@ -492,18 +512,31 @@ private[regex] object PatternCompiler {
...
-  private final class CharacterClassState(asciiCaseInsensitive: Boolean) {
-    var thisConjunct = ""
-    var thisSegment = ""
+  private final class CharacterClassBuilder(asciiCaseInsensitive: Boolean, isNegated: Boolean) {
+    private var conjunction = ""
+    private var thisConjunct = ""
+    private var thisSegment = ""
+
+    def finish(): String = {
+      val conjunct = conjunctResult()
```
[the remark this answers is not in the document]
Comment (gzm0) [reply javalib/src/main/scala/java/util/regex/PatternCompiler.scala:521]: See my comment below about `finishConjunct` :P

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: javalib/src/main/scala/java/util/regex/PatternCompiler.scala (hunk 12 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/regex/PatternCompiler.scala:525]: `finishConjunctAndStartNewOne()`? Or `finishNonLastConjunct()`? Or `startNewConjunct()` (the "new" suggesting that it's not the first one)?

**Review by sjrd — COMMENTED** [review]
Updated.

**Comment by sjrd** [comment]
That `LibrarySizeTest` seems to be very sensitive to the environment. The results on Windows are significantly different than on Linux. I'm not sure why yet. :-s

**Comment by sjrd** [comment]
It turns out the issues were related to the version of Scala being used.
Note the first two commits in the PR, which are new (and if you want I can submit them as a separate, preliminary PR).

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/regex/RegexEngineTest.scala [hunk 14]
```diff
@@ -0,0 +1,2415 @@
...
+    val solutionWithPossessiveQuantifier = compile("(x+x+)++y")
+    assertNotMatches(solutionWithPossessiveQuantifier, input)
+
+    val solutionWithAtomicGroup = compile("(?>(x+x+)+)y")
+    assertNotMatches(solutionWithAtomicGroup, input)
+  }
+
+  /** Tests for regexes that we found in the public Scala.js libraries at the
+   *  time of switching from the JS `RegExp` behavior to the JVM `Pattern`
+   *  behavior.
```
Comment (gzm0) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/regex/RegexEngineTest.scala:2013]: Maybe drop a line that you used these for manual testing? Like this its kind of confusing (at least to me). Because IIRC the main concern with existing regexes never was that they work but that they work the same way (which this doesn't test).

**Review by gzm0 — CHANGES_REQUESTED** [review]
Finish line :) Only minor stuff on the tests. Everything else LGTM.

**Review by sjrd — COMMENTED** [review]
Updated.

Adding more tests for comments, following your review, made me realize that comments are also supposed to work in character classes. So there is one more comment that implements that.

**Review by gzm0 — APPROVED** [review]

**Comment by sjrd** [comment]
Thanks! 🎉 
Rebased and squashed.
