### PR TITLE
Fix #4402: Allow native JS (module) classes not to have a native load spec.

### LINKED ISSUE #4402: Extending a native inner class complains that it has no JS native load spec
The following code works fine:
```scala
import scala.scalajs.js

@js.native
trait Outer extends js.Object {
  @js.native
  class InnerClass extends js.Object
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    val outer = js.Dynamic.literal(
      InnerClass = js.constructorOf[js.Date]
    ).asInstanceOf[Outer]
    println(new outer.InnerClass)
  }
}
```
and prints the current date/time.

However, if I add
```scala
    class Subclass extends outer.InnerClass

    println(new Subclass)
```
to the main method, then the linker reports a linking error:
```
[error] helloworld.Outer$InnerClass is a native class but does not have a JSNativeLoadSpec
[error]   called from helloworld.HelloWorld$.main([java.lang.String)void
[error]   called from static helloworld.HelloWorld.main([java.lang.String)void
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   helloworld.HelloWorld$
[error] There were linking errors
```
Indeed, `InnerClass` is encoded as a `native js class` but without JS native load spec:
```scala
> helloworld2_12/scalajsp helloworld.Outer$InnerClass
native js class helloworld.Outer$InnerClass extends scala.scalajs.js.Object {
}
```
It is correct that it doesn't have a native load spec, since it must be accessed as a field of an `outer` variable. It should be marked as an `abstract js type` instead of a `native js class`.

The same goes for an inner native JS `object`, although I'm not sure how to write a failing test for those.

### PR DESCRIPTION
**Pull request by sjrd**
A native load spec is only required if there is a "call site" for that class with `LoadJSConstructor`, `LoadJSModule` or as `superClass` of a JS class without `jsSuperClass` tree.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analysis.scala [hunk 1]
```diff
@@ -176,6 +176,7 @@ object Analysis {
       subClassInfo: ClassInfo, from: From)
       extends Error
 
+  @deprecated("not used anymore", since = "1.5.0")
   final case class MissingJSNativeLoadSpec(info: ClassInfo, from: From) extends Error
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analysis.scala:180]: Simply remove this? This is in an unstable package.

File: linker/shared/src/main/scala/org/scalajs/linker/checker/IRChecker.scala [hunk 2]
```diff
@@ -185,10 +187,7 @@ private final class IRChecker(unit: LinkingUnit, logger: Logger) {
 
     classDef.kind match {
       case ClassKind.NativeJSClass | ClassKind.NativeJSModuleClass =>
-        if (classDef.jsNativeLoadSpec.isEmpty) {
-          reportError(
-              i"Native JS type ${classDef.name} must have a jsNativeLoadSpec")
-        }
+        () // may or may not have a native load spec
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/checker/IRChecker.scala:190]: While you are here, maybe add `isJSNativeClass` to `ClassKind`, use it in `Analyzer` (it already has that locally) and here?

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala [hunk 3]
```diff
@@ -755,6 +769,14 @@ object NestedJSClassTest {
   class TriplyNestedClass_Issue4114 extends TriplyNestedObject_Issue4114.middle.InnerClass {
     def foo(x: String): String = x
   }
+
+  @js.native
+  trait OuterNativeTrait_Issue4402 extends js.Object {
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala:774]: Add a test for native classes as well?

**Review by gzm0 — CHANGES_REQUESTED** [review]
This is so cool! Only nits.

**Comment by gzm0** [comment]
Also: The `AnalyzerTest` that tests the error case you removed fails :)

File: linker/shared/src/main/scala/org/scalajs/linker/checker/IRChecker.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/checker/IRChecker.scala:190]: I'm not sure. There is nothing in common between a `NativeJSClass` and a `NativeJSModuleClass` other than having a `jsNativeLoadSpec`. It's not a very useful test. I already have trouble remembering which test does what, I'd rather not have another one which is not even that widespread.

**Comment by sjrd** [comment]
Updated.

I've also replaced the `AnalyzerTest` by an `IRCheckerTest`.

**Comment by gzm0** [comment]
The CI failure is because a class that does not have any definitions is assigned to a module. This results in an empty module.

Basically, the reverse of this assertion fails: https://github.com/scala-js/scala-js/blob/92c453ddfadfe0e2d350f6361c14828e0f58c158/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala#L74-L75

I'd recommend actually adding the reverse assertion in the `Some` case.

The reason this happens is that the analyzer introduces a static dependency, when none is needed. Likely, this is buggy:

https://github.com/scala-js/scala-js/blob/92c453ddfadfe0e2d350f6361c14828e0f58c158/linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala#L1026-L1035

**Comment by sjrd** [comment]
> The CI failure is because a class that does not have any definitions is assigned to a module. This results in an empty module.
> [...]
> The reason this happens is that the analyzer introduces a static dependency, when none is needed. Likely, this is buggy:
> 
> https://github.com/scala-js/scala-js/blob/92c453ddfadfe0e2d350f6361c14828e0f58c158/linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala#L1026-L1035

Thanks! That was spot on. It's fixed now.

> Basically, the reverse of this assertion fails:
> 
> https://github.com/scala-js/scala-js/blob/92c453ddfadfe0e2d350f6361c14828e0f58c158/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala#L74-L75
> 
> I'd recommend actually adding the reverse assertion in the `Some` case.

So, I tried that, but it first failed because there are classes that have "no definitions" but still need a module. For example, an abstract Scala class that contains no field or method itself, but its children are instantiated.

It turns out the `LinkedClass.hasAnyDefinitions` was only used for that assertion, so I tried moving it locally to the method and have it take into account the above case:
```diff
diff --git a/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala b/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala
index 190227ae3..445076a89 100644
--- a/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala
+++ b/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/ModuleSplitter.scala
@@ -69,13 +69,26 @@ final class ModuleSplitter private (analyzer: ModuleAnalyzer) {
       builders.getOrElseUpdate(moduleID, new ModuleBuilder(moduleID))

     for (classDef <- unit.classDefs) {
+      val shouldHaveModule = {
+        import classDef._
+        (kind.isAnyNonNativeClass && hasInstances) ||
+        fields.nonEmpty ||
+        methods.nonEmpty ||
+        exportedMembers.nonEmpty ||
+        hasInstanceTests ||
+        hasRuntimeTypeInfo
+      }
+
       analysis.moduleForClass(classDef.className) match {
         case None =>
-          assert(!classDef.hasAnyDefinitions,
-              s"${classDef.fullName} was not put in a module but has definitions")
+          assert(!shouldHaveModule,
+              s"${classDef.fullName} was not put in a module but it should have")
           abstractClasses += classDef

         case Some(moduleID) =>
+          assert(shouldHaveModule,
+              s"${classDef.fullName} was put in a module but it should not have")
+
           val builder = getBuilder(moduleID)
           builder.classDefs += classDef

diff --git a/linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala b/linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala
index f2fec452c..adaefb8ae 100644
--- a/linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala
+++ b/linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala
@@ -68,14 +68,6 @@ final class LinkedClass(
     }
   }

-  def hasAnyDefinitions: Boolean = {
-    fields.nonEmpty ||
-    methods.nonEmpty ||
-    exportedMembers.nonEmpty ||
-    hasInstanceTests ||
-    hasRuntimeTypeInfo
-  }
-
   def fullName: String = className.nameString

   private[linker] def refined(
diff --git a/project/BinaryIncompatibilities.scala b/project/BinaryIncompatibilities.scala
index 50ed423e4..c8e627b10 100644
--- a/project/BinaryIncompatibilities.scala
+++ b/project/BinaryIncompatibilities.scala
@@ -8,6 +8,9 @@ object BinaryIncompatibilities {
   )

   val Linker = Seq(
+    // !!! Breaking in linker.standard.*, OK in minor version
+    exclude[DirectMissingMethodProblem](
+        "org.scalajs.linker.standard.LinkedClass.hasAnyDefinitions"),
   )

   val LinkerInterface = Seq(
```
However, that still failed in the `NoModule` case, because of the fast-path at
https://github.com/scala-js/scala-js/blob/fa29893daf637a342fe6104eda0f0a0023dbf437/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala#L36-L38
which gives a module to *all* classes:
https://github.com/scala-js/scala-js/blob/fa29893daf637a342fe6104eda0f0a0023dbf437/linker/shared/src/main/scala/org/scalajs/linker/frontend/modulesplitter/MaxModuleAnalyzer.scala#L100-L104
I wasn't sure how to address that without killing the fast-path, so I left the assertions alone, in the end.

File: linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala [hunk 4]
```diff
@@ -1025,12 +1021,10 @@ private final class Analyzer(config: CommonPhaseConfig,
 
         if (!isNativeJSClass) {
           for (clazz <- superClass) {
-            clazz.jsNativeLoadSpec match {
-              case None =>
-                staticDependencies += clazz.className
-              case Some(loadSpec) =>
-                addLoadSpec(externalDependencies, loadSpec)
-            }
+            if (clazz.isAnyClass)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala:1024]: Could we invert this an use `isNativeJSClass`? `isAnyClass` isn't really meaningful IMHO.

**Review by gzm0 — APPROVED** [review]
Just a nti.

File: linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala (hunk 4 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/analyzer/Analyzer.scala]: Done.

**Review by gzm0 — APPROVED** [review]
