### PR TITLE
Fix #4469: Report a better error when node is not installed

### LINKED ISSUE #4469: Better error message when executing tests with Node missing
I was running some tests via the ScalaJSJUnitPlugin, and got this error:

```
org.scalajs.testing.common.RPCCore$ClosedException: org.scalajs.testing.adapter.JSEnvRPC$RunTerminatedException
```

Which was fixed by installing Node. A better error message if Node is not installed would probably be nice.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
This currently looks like this (if I configure the build to try and run "frobber"):

```
sbt:Scala.js> helloworld2_12/run
[info] Running helloworld.HelloWorld. Hit any key to interrupt.
[error] java.lang.Exception: failed to start frobber; did you install it?
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:106)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:551)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:534)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: org.scalajs.jsenv.ExternalJSRun$FailedToStartException: failed to start command List(frobber)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:147)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[error] 	at org.scalajs.sbtplugin.Run$.runInterruptible(Run.scala:44)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$58(ScalaJSPluginInternal.scala:551)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:551)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:534)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: java.io.IOException: Cannot run program "frobber": error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[error] 	at org.scalajs.sbtplugin.Run$.runInterruptible(Run.scala:44)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$58(ScalaJSPluginInternal.scala:551)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:551)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:534)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] Caused by: java.io.IOException: error=2, No such file or directory
[error] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[error] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[error] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[error] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[error] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[error] 	at org.scalajs.sbtplugin.Run$.runInterruptible(Run.scala:44)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$58(ScalaJSPluginInternal.scala:551)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:551)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:534)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] stack trace is suppressed; run last helloworld2_12 / Compile / run for the full output
[error] (helloworld2_12 / Compile / run) java.lang.Exception: failed to start frobber; did you install it?
[error] Total time: 1 s, completed Jul 11, 2021, 8:49:30 PM
```

Needless to say, this is not ideal. However, I haven't figured out a way to make sbt suppress the stack trace while still making it available. IMO, `MessageOnlyException` is not an option here. I have tried `logger.trace(t)` before throwing a `MessageOnlyException`, but the trace still shows...

**Comment by sjrd** [comment]
I guess we could log the trace with `debug` level, then throw a `MessageOnlyException`?

**Comment by gzm0** [comment]
> I guess we could log the trace with debug level

How do you do that? `trace` does not take a level. And converting to a string is just ugly :(

**Comment by sjrd** [comment]
I was thinking about converting to a string, yes. Definitely not pretty, but at least the output should be reasonable, which is what we care about, at the end of the day.

**Comment by gzm0** [comment]
OK, so this looks like this:

```
sbt:Scala.js> helloworld2_12/run
[info] Running helloworld.HelloWorld.
[error] failed to start frobber; did you install it? (run `last` for the full stack trace)
[error] (helloworld2_12 / Compile / run) failed to start frobber; did you install it? (run `last` for the full stack trace)
[error] Total time: 1 s, completed Jul 15, 2021, 8:28:03 PM
```

What is not nice about it, is that it requires `last helloworld2_12/run`, not just `last` to show the trace:

```
sbt:Scala.js> last helloworld2_12/run
[info] Running helloworld.HelloWorld.
[debug] with JSEnv Node.js
[debug] Starting process: frobber
[debug] org.scalajs.jsenv.ExternalJSRun$FailedToStartException: failed to start command List(frobber)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:147)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:553)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:537)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[debug] Caused by: java.io.IOException: Cannot run program "frobber": error=2, No such file or directory
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:553)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:537)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[debug] Caused by: java.io.IOException: error=2, No such file or directory
[debug] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[debug] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[debug] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.start(NodeJSEnv.scala:39)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54(ScalaJSPluginInternal.scala:553)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSConfigSettings$54$adapted(ScalaJSPluginInternal.scala:537)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] failed to start frobber; did you install it? (run `last` for the full stack trace)
[error] (helloworld2_12 / Compile / run) failed to start frobber; did you install it? (run `last` for the full stack trace)
```

IDK what the state of the art is for sbt to deal with these kind of things.

**Comment by sjrd** [comment]
> What is not nice about it, is that it requires `last helloworld2_12/run`, not just `last` to show the trace:

That is weird. It thought that `last` was always an alias of `last <whatever you executed last time>`.

> IDK what the state of the art is for sbt to deal with these kind of things.

Not sure either. Perhaps it's worth a question in https://github.com/sbt/sbt/discussions ?

**Comment by gzm0** [comment]
Asked about this on sbt/sbt: https://github.com/sbt/sbt/discussions/6601

**Comment by gzm0** [comment]
Looks like this:

```
sbt:Scala.js> testSuiteEx2_12 / test
[error] failed to start frobber; did you install it? (run `last ProjectRef(uri("file:/home/tos/gh/scala-js/"), "testSuiteEx2_12") / Test / loadedTestFrameworks` for the full stack trace)
[error] (testSuiteEx2_12 / Test / loadedTestFrameworks) failed to start frobber; did you install it? (run `last ProjectRef(uri("file:/home/tos/gh/scala-js/"), "testSuiteEx2_12") / Test / loadedTestFrameworks` for the full stack trace)
[error] Total time: 1 s, completed Jul 27, 2021, 12:22:29 PM
```

The `last` invocation is now correct:

```
sbt:Scala.js> last ProjectRef(uri("file:/home/tos/gh/scala-js/"), "testSuiteEx2_12") / Test / loadedTestFrameworks
[debug] Starting process: frobber
[debug] org.scalajs.testing.common.RPCCore$ClosedException: org.scalajs.testing.adapter.JSEnvRPC$RunTerminatedException
[debug] 	at org.scalajs.testing.common.RPCCore.helpClose(RPCCore.scala:223)
[debug] 	at org.scalajs.testing.common.RPCCore.call(RPCCore.scala:164)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.loadFrameworks(TestAdapter.scala:57)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$6(ScalaJSPluginInternal.scala:638)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$4(ScalaJSPluginInternal.scala:638)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[debug] Caused by: org.scalajs.testing.adapter.JSEnvRPC$RunTerminatedException
[debug] 	at org.scalajs.testing.adapter.JSEnvRPC.$anonfun$new$1(JSEnvRPC.scala:38)
[debug] 	at org.scalajs.testing.adapter.JSEnvRPC.$anonfun$new$1$adapted(JSEnvRPC.scala:38)
[debug] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[debug] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[debug] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[debug] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[debug] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[debug] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[debug] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[debug] Caused by: org.scalajs.jsenv.ExternalJSRun$FailedToStartException: failed to start command List(frobber)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:147)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.$anonfun$startWithCom$1(NodeJSEnv.scala:47)
[debug] 	at org.scalajs.jsenv.nodejs.ComRun$.start(ComSupport.scala:214)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.startWithCom(NodeJSEnv.scala:46)
[debug] 	at org.scalajs.testing.adapter.JSEnvRPC.<init>(JSEnvRPC.scala:25)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.startManagedRunner(TestAdapter.scala:129)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:120)
[debug] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.getRunnerForThread(TestAdapter.scala:120)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.loadFrameworks(TestAdapter.scala:56)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$6(ScalaJSPluginInternal.scala:638)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$4(ScalaJSPluginInternal.scala:638)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[debug] Caused by: java.io.IOException: Cannot run program "frobber": error=2, No such file or directory
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.$anonfun$startWithCom$1(NodeJSEnv.scala:47)
[debug] 	at org.scalajs.jsenv.nodejs.ComRun$.start(ComSupport.scala:214)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.startWithCom(NodeJSEnv.scala:46)
[debug] 	at org.scalajs.testing.adapter.JSEnvRPC.<init>(JSEnvRPC.scala:25)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.startManagedRunner(TestAdapter.scala:129)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:120)
[debug] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.getRunnerForThread(TestAdapter.scala:120)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.loadFrameworks(TestAdapter.scala:56)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$6(ScalaJSPluginInternal.scala:638)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$4(ScalaJSPluginInternal.scala:638)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[debug] Caused by: java.io.IOException: error=2, No such file or directory
[debug] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[debug] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
[debug] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
[debug] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.startProcess(ExternalJSRun.scala:144)
[debug] 	at org.scalajs.jsenv.ExternalJSRun$.start(ExternalJSRun.scala:40)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.internalStart(NodeJSEnv.scala:63)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.$anonfun$startWithCom$1(NodeJSEnv.scala:47)
[debug] 	at org.scalajs.jsenv.nodejs.ComRun$.start(ComSupport.scala:214)
[debug] 	at org.scalajs.jsenv.nodejs.NodeJSEnv.startWithCom(NodeJSEnv.scala:46)
[debug] 	at org.scalajs.testing.adapter.JSEnvRPC.<init>(JSEnvRPC.scala:25)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.startManagedRunner(TestAdapter.scala:129)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.$anonfun$getRunnerForThread$1(TestAdapter.scala:120)
[debug] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:895)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.getRunnerForThread(TestAdapter.scala:120)
[debug] 	at org.scalajs.testing.adapter.TestAdapter.loadFrameworks(TestAdapter.scala:56)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$6(ScalaJSPluginInternal.scala:638)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.enhanceNotInstalledException(ScalaJSPluginInternal.scala:103)
[debug] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestSettings$4(ScalaJSPluginInternal.scala:638)
[debug] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] failed to start frobber; did you install it? (run `last ProjectRef(uri("file:/home/tos/gh/scala-js/"), "testSuiteEx2_12") / Test / loadedTestFrameworks` for the full stack trace)
[error] (testSuiteEx2_12 / Test / loadedTestFrameworks) failed to start frobber; did you install it? (run `last ProjectRef(uri("file:/home/tos/gh/scala-js/"), "testSuiteEx2_12") / Test / loadedTestFrameworks` for the full stack trace)
sbt:Scala.js> 
```

**Comment by gzm0** [comment]
@AugustNagro, PTAL at the error reporting.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 1]
```diff
@@ -84,6 +85,33 @@ private[sbtplugin] object ScalaJSPluginInternal {
     }
   }
 
+  private object FailedToStartCmd {
+    def unapply(t: Throwable): Option[String] = {
+        val causeChain = Iterator
```
Comment (sjrd) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:90]: There are 2 spaces too many here, and in the entire block.

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 2]
```diff
@@ -84,6 +85,33 @@ private[sbtplugin] object ScalaJSPluginInternal {
...
+          .iterate(t)(_.getCause())
+          .takeWhile(_ != null)
+
+        causeChain.collectFirst {
+          case ExternalJSRun.FailedToStartException(cmd :: Nil, _) =>
```
Comment (sjrd) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala:95]: I'm pretty sure that this should at least be
```suggestion
          case ExternalJSRun.FailedToStartException(cmd :: _, _) =>
```
Otherwise it cannot match anything where there are arguments to the process.

**Review by sjrd — CHANGES_REQUESTED** [review]

**Comment by AugustNagro** [comment]
Looks great @gzm0 thanks for making this.

**Review by sjrd — APPROVED** [review]
