### PR TITLE
Fix #2162: Unify error handling in the Analyzer.

### LINKED ISSUE #2162: Unify error handling in Analyzer
There are three ways the analyzer currently handles errors (i.e. bad state on the classpath, not bad internal state):

- Populate `errors`
- `sys.error("Fatal error: could not find java.lang.Object on the classpath")`
- Throw `CyclicDependencyException`

This is a strange interface and we should unify it taking advantage of the binary compat break.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0 

The fatal error cases were tested locally.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala [hunk 1]
```diff
@@ -87,11 +124,20 @@ final class BaseLinker(semantics: Semantics, esLevel: ESLevel, considerPositions
...
+      val fatal = !bypassLinkingErrors || analysis.errors.exists {
+        case _: Analysis.MissingJavaLangObjectClass => true
+        case _: Analysis.CycleInInheritanceChain    => true
+        case _                                      => false
+      }
 
-    if (analysis.errors.nonEmpty && !bypassLinkingErrors)
-      sys.error("There were linking errors")
+      val linkingErrLevel = if (fatal) Level.Error else Level.Warn
+      analysis.errors.foreach(logError(_, logger, linkingErrLevel))
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: Shouldn't the error level be individual for each error message?

Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: It's arguable. 

But anyway, in practice it wouldn't change anything, because either you get fatal errors, or you get non fatal errors. There is no way you can get a mix of both.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala [hunk 2]
```diff
@@ -165,6 +173,7 @@ private final class Analyzer(semantics: Semantics,
   private class ClassInfo(data: Infos.ClassInfo) extends Analysis.ClassInfo {
     private[this] var _linking = false
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: Drop this and use `_linkingFrom` instead.

Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: I can't. That's what I tried initially, but I failed to discover cycles and it went into infinite loop. There is a time during which `_linking` is `true` but `_linkingFrom` needs to stay `null`.

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: :P No, not really. The problem is more that `_linkingFrom == null` can mean two things then:

- I'm not linking
- I'm a linking root

Not being able to distinguish these cases is problematic. Not because we can't detect cycles, but because we can't reconstruct the cycles.

I think it would be cleaner if you made `_linkingFrom` an `Option` and then essentially have proper tri-state (with the `null`).

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: Or, don't condition on `_linkingFrom` at all anymore. (why do you need the `_linkingFrom == null` check)?

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala [hunk 3]
```diff
@@ -182,22 +191,29 @@ private final class Analyzer(semantics: Semantics,
...
+          _linking = true
           linkClassesImpl()
-        } catch {
-          case CyclicDependencyException(chain) =>
-            throw CyclicDependencyException(encodedName :: chain)
+        } else {
+          def makeCycle(from: ClassInfo, acc: List[ClassInfo]): List[ClassInfo] = {
+            if (from == linkingFrom) from :: acc
+            else makeCycle(from._linkingFrom, from :: acc)
+          }
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: I don't think this does the right thing. It walks up the dependency tree that has already been established and then checks for the `linkingFrom`. There is no guarantee we reach that:

Consier: `A <- B <- C <- B`. When we reach `B` for the second time, we get the following invocation order:

```
makeCycle(B, Nil)
makeCycle(A, B :: Nil)
makeCycle(null, A :: B :: Nil)
NPE
```

The proper invocation is `makeCycle(linkingFrom, Nil)` and the abort condition is `from eq this`:

```
makeCycle(C, Nil)
makeCycle(B, C :: Nil)
--> B :: C :: Nil
```

This is probably also the reason why you need to set `_linkingFrom` even if `_linking`. You can then "detect" loops if the loop involves the root linking node.

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: Hmmm... I'm thinking of this the complete wrong way... My initial class hierarchy doesn't make sense... `B` has two different parents.
Need to think more.

Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: I guess this algorithm is just too complicated. I suggest to revert back to the throwing thing, but just catch it one last time in the top-level `Analyzer.linkClasses`, and from there, create exactly one `CycleInInheritanceChain` error to put in `_errors`. It's fatal anyway, so we don't really care that we won't discover *other* potential cycles on the classpath.

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/analyzer/Analyzer.scala]: That's probably easier. Optionally you could also have `linkClasses` an `Option[List[ClassInfo]]` so we don't have to use exceptions for control flow... But I think in this case its actually ok.

**Comment by sjrd** [comment]
Updated.

**Comment by gzm0** [comment]
LGTM
