### PR TITLE
Fix #4801: Rebase the super JS type as seen from the this type in JS super call.

### LINKED ISSUE #4801: Delegating to the implementation of a calculated super class causes Internal error
```scala
@js.native
trait OuterNativeTrait_Issue4402 extends js.Object {
  @js.native
  class InnerClass extends js.Object {
    def foo(): Unit = js.native
  }
}

object Mytest {
  def createSubclass(superclass: js.Function) = {
    val outer = js.Dynamic.literal(InnerClass = superclass).asInstanceOf[OuterNativeTrait_Issue4402]

    class Subclass extends outer.InnerClass {
      override def foo(): Unit = super.foo()
    }
  }
}
```

Fails with

```
scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala:24:20: Internal error: unable to find the outer accessor symbol of class Subclass
      override def foo(): Unit = super.foo()
                   ^
```

### PR DESCRIPTION
**Pull request by sjrd**
When doing a super call to a method of a path-dependent JS super class, the `superClass.tpe_*` is only valid as seen from the super class' thisType. We need to rebase it with `asSeenFrom` to be in the context of the current class' thisType.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala [hunk 1]
```diff
@@ -394,6 +394,21 @@ abstract class ExplicitLocalJS[G <: Global with Singleton](val global: G)
       }
     }
 
+    /** Wraps with the contextural super JS class value for super calls. */
```
Comment (ekrich) [inline compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala:397]:
```suggestion
    /** Wraps with the contextual super JS class value for super calls. */
```

File: compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala [hunk 2]
```diff
@@ -394,6 +394,21 @@ abstract class ExplicitLocalJS[G <: Global with Singleton](val global: G)
...
 
+    /** Wraps with the contextual super JS class value for super calls. */
+    private def wrapWithContextualSuperJSClassValue(superClass: Symbol)(
+        tree: Tree): Tree = {
+      /* #4801 We need to interpret the superClass type as seen from the
+       * current class' thisType.
+       */
+      val jsClassTypeInSuperClass = superClass.tpe_*
+      val jsClassTypeAsSeenFromThis =
+        jsClassTypeInSuperClass.asSeenFrom(currentClass.thisType, superClass)
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala:405]: Just to check my understanding: This "translates" the type from `OuterNativeClass_Issue4402#InnerClass` to the path dependent type `outer.InnerClass`.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala [hunk 3]
```diff
@@ -900,6 +906,8 @@ object NestedJSClassTest {
 
   class DynamicInnerClass_Issue4402(arg: String) extends js.Object {
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala:907]: It's a bit ugly that we have issue4402 here in the name but not issue4801. Maybe it makes sense to just comment how the test tests the relevant issues?

**Review by gzm0 — APPROVED** [review]
LGTM. All comments optional.

File: compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala (hunk 2 above)
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/ExplicitLocalJS.scala:422]: To be more precise, it translates the type from `OuterNativeClass_Issue4402.this.InnerClass` (which is path-dependent on the outer `this` value) into the path-dependent type `outer.InnerClass`. I have expanded the comment above to make it clearer.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala (hunk 3 above)
Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala:909]: I was not sure what's best to do here. I added `_Issue4801` to the method name, `methodSuper_Issue4801`, as it is effectively that method that tests this issue. Does that make sense?

Comment (gzm0) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/NestedJSClassTest.scala:909]: SG

**Review by gzm0 — APPROVED** [review]
