### PR TITLE
Fix #4539: Fix the format of the mapSourceURI option of the scalalib.

### LINKED ISSUE #4539: The source map URI of the scalalib is broken
I messed up in https://github.com/scala-js/scala-js/commit/f659f7a36b3be724e616dce42094f7648d04ee93. The `mapSourceURI` option specific to the `scalalib` lost its `-P:scalajs:` prefix. Somehow this did not cause a hard error, nor did I notice the issue while testing manually at the time of doing the change. But now the manual source map tests fail to point to the scala/scala repo for the stdlib sources.

This is unfortunately a blocker for 1.7.0.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: project/Build.scala [hunk 1]
```diff
@@ -1303,7 +1303,7 @@ object Build {
           val option = mapSourceURISetting(
               (artifactPath in fetchScalaSource).value,
               s"https://raw.githubusercontent.com/scala/scala/v${scalaVersion.value}/src/library/")
-          option +: prev
+          s"-P:scalajs:$option" +: prev
```
Comment (gzm0) [inline project/Build.scala:1306]: Instead of just fixing this here, I suggest the following:

Add:

```scala
def scalaJSCompilerOption(o: String): Seq[String] =
  if (isGeneratingForIDE) Nil
  else Seq(s"-P:scalajs:$o")
```

And replace all usages of `addScalaJSCompilerOption` with that function and the relevant sbt incantation.

(e.g. `scalacOptions ++= scalaJSCompilerOption("fixClassOf")`)

This
- is only minorly more verbose
- gets rid of all the `Def.setting` complexity
- allows you to use the helper all the time (so even in the case here).
- allows you to use it in `mapSourceURISetting`

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: project/Build.scala (hunk 1 above)
Comment (sjrd) [reply project/Build.scala]: Done.

**Review by gzm0 — APPROVED** [review]
