### PR TITLE
FF ONLY Merge 0.6.x into master, May 13

### LINKED ISSUE #3458: Bad interactions in JSDOMNodeJSEnv error handling on JSDom 10-12
I can't get a run of utest 0.6.4 or even 0.6.5 with the opcode change, of scalajs-react tests to complete with SJS 0.6.25. I constantly one of the following errors which kills all subsequent tests. I've had to downgrade SJS to 0.6.24

```
org.scalajs.testcommon.RPCCore$ClosedException
	at org.scalajs.testcommon.RPCCore.helpClose(RPCCore.scala:193)
	at org.scalajs.testcommon.RPCCore.close(RPCCore.scala:185)
	at org.scalajs.testadapter.ComJSEnvRPC.org$scalajs$testadapter$ComJSEnvRPC$$super$close(ComJSEnvRPC.scala:50)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:50)
Caused by: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner$class.receive(AbstractNodeJSEnv.scala:284)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.jsenv.ComJSRunner$class.receive(ComJSRunner.scala:15)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner$class.receive(AbstractNodeJSEnv.scala:274)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.jsenv.ComJSRunner$class.receive(ComJSRunner.scala:15)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
```

or

```
org.scalajs.testcommon.RPCCore$ClosedException
	at org.scalajs.testcommon.RPCCore.helpClose(RPCCore.scala:193)
	at org.scalajs.testcommon.RPCCore.close(RPCCore.scala:185)
	at org.scalajs.testadapter.ComJSEnvRPC.org$scalajs$testadapter$ComJSEnvRPC$$super$close(ComJSEnvRPC.scala:50)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:50)
Caused by: org.scalajs.jsenv.ComJSEnv$ComClosedException: JSCom has been closed
	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner$class.receive(AbstractNodeJSEnv.scala:284)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.jsenv.ComJSRunner$class.receive(ComJSRunner.scala:15)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.scalajs.jsenv.nodejs.AbstractNodeJSEnv$NodeComJSRunner$class.receive(AbstractNodeJSEnv.scala:274)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.jsenv.ComJSRunner$class.receive(ComJSRunner.scala:15)
	at org.scalajs.jsenv.nodejs.JSDOMNodeJSEnv$ComDOMNodeRunner.receive(JSDOMNodeJSEnv.scala:62)
	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
```

### LINKED ISSUE #4034: Incorrect handling of negative 0
The following snippet produces different results on Scala.js and on the JVM:

```scala
val float = 0.0f
println(String.format("%.1f", -float))     // prints 0.0 on Scala.js, -0.0 on JVM
println(String.format("%.1f", -1 * float)) // prints -0.0 on both Scala.js and JVM
```

From the JS output, it looks like the first print is being constant folded incorrectly to `0.0` instead of `-0.0` in Scala.js. The second print is being constant folded correctly to `-0.0`:

```js
this$9.java$lang$JSConsoleBasedPrintStream$$printString__T__V((x$1 + "\n"));
const args$1 = $makeNativeArrayWrapper($d_O.getArrayOf(), [0.0]);
const x$2 = $m_jl_String$().format__T__AO__T("%.1f", args$1);
const this$11 = $m_s_Console$();
const this$12 = this$11.out__Ljava_io_PrintStream();
this$12.java$lang$JSConsoleBasedPrintStream$$printString__T__V((x$2 + "\n"));
const args$2 = $makeNativeArrayWrapper($d_O.getArrayOf(), [(-0)]);
const x$3 = $m_jl_String$().format__T__AO__T("%.1f", args$2);
```

I can try to prevent constant folding from taking place by placing the negation in a function:

```scala
def negate1(x: Float): Float = -x
def negate2(x: Float): Float = -1 * x
```

However, this also results in an incorrect translation. Both `-x` and `-1 * x` are translated to `Math.fround(0.0 - x)`, which produces an incorrect result when `x` is `0.0`.

```js
const $p_Lcom_test_Test__negate1$1__F__F = (function($thiz, x) {
  return $fround((0.0 - x))
});
const $p_Lcom_test_Test__negate2$1__F__F = (function($thiz, x) {
  return $fround((0.0 - x))
});
```

I am using Scala.js 1.0.1 on Scala 2.13.2.

### LINKED ISSUE #4038: scala.Symbol.toString() changed in 2.13.x, invalidating our override
The upstream commit https://github.com/scala/scala/commit/904e3a5d2b9616b9c533d77d0c51652b138e8659 changed `scala.Symbol.toString()`. This change breaks `testSuiteJVM/test`, since we are testing for the old `toString()`.

We need to adapt the test, and consequently our implementation in the override at https://github.com/scala-js/scala-js/blob/master/scalalib/overrides/scala/Symbol.scala.

### PR DESCRIPTION
**Pull request by sjrd**
```
$ git checkout -b merge-0.6.x-into-master-may-13
Switched to a new branch 'merge-0.6.x-into-master-may-13'
```
```
$ export mb=$(git merge-base scalajs/0.6.x scalajs/master)
```
```
$ git log --graph --oneline --decorate $mb..scalajs/0.6.x | cat
* 01a8c8090 (scalajs/0.6.x) Towards 0.6.34.
* db0899064 (tag: v0.6.33) Version 0.6.33.
*   ad064987c Merge pull request #4040 from sjrd/fix-double-negate-zero
|\
| * 40e323acc Fix #4034: Encode -x as -1.0 * x instead of 0.0 - x.
* |   b9bd9cf74 Merge pull request #4039 from sjrd/fix-symbol-tostring
|\ \
| |/
|/|
| * 0b6356707 Fix #4038: Update Symbol.toString() to match 2.13.3+.
| * 411847dab Copy the override for Symbol.scala to 2.13/ and 2.13.{0-2}/.
* |   ce84c646a Merge pull request #4036 from sjrd/fix-react-development-mode-in-jsdom
|\ \
| |/
|/|
| * f4ecc8930 [no-master] Fix #3458: Hack around React's dev mode error triggering hack.
|/
*   24f9ed9c8 Merge pull request #4023 from sjrd/scala-2.12.11-2.13.2
|\
| * e4aecce9f Upgrade to Scala 2.13.2.
| * a9034e012 Fix a few deprecated procedure syntax occurrences in constructors.
| * 6aea56055 Make compiler tests compatible with Scala 2.13.2+.
| * 553ed1140 Upgrade to Scala 2.12.11.
* 4550a1845 Merge pull request #4025 from MaximeKjaer/gitignore-node-modules
* 042719b7a Gitignore node_modules
```
```
$ git merge --no-commit 24f9ed9c8
CONFLICT (modify/delete): tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala deleted in HEAD and modified in 24f9ed9c8. Version 24f9ed9c8 of tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala left in tree.
CONFLICT (modify/delete): tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/BasicLinkerBackend.scala deleted in HEAD and modified in 24f9ed9c8. Version 24f9ed9c8 of tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/BasicLinkerBackend.scala left in tree.
CONFLICT (modify/delete): tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala deleted in HEAD and modified in 24f9ed9c8. Version 24f9ed9c8 of tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala left in tree.
Auto-merging scripts/publish.sh
CONFLICT (content): Merge conflict in scripts/publish.sh
CONFLICT (modify/delete): scripts/assemble-cli.sh deleted in HEAD and modified in 24f9ed9c8. Version 24f9ed9c8 of scripts/assemble-cli.sh left in tree.
Auto-merging project/Build.scala
CONFLICT (content): Merge conflict in project/Build.scala
CONFLICT (file location): compiler/src/test/scala/org/scalajs/core/compiler/test/util/VersionDependentMessages.scala added in 24f9ed9c8 inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to compiler/src/test/scala/org/scalajs/nscplugin/test/util/VersionDependentMessages.scala.
Auto-merging compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
CONFLICT (content): Merge conflict in compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
Auto-merging compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
CONFLICT (content): Merge conflict in compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
Auto-merging ci/checksizes.sh
CONFLICT (content): Merge conflict in ci/checksizes.sh
Auto-merging Jenkinsfile
CONFLICT (content): Merge conflict in Jenkinsfile
Auto-merging .gitignore
CONFLICT (content): Merge conflict in .gitignore
Automatic merge failed; fix conflicts and then commit the result.
```
```
$ git st
UU .gitignore
UU Jenkinsfile
UU ci/checksizes.sh
UU compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
UU compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
UA compiler/src/test/scala/org/scalajs/nscplugin/test/util/VersionDependentMessages.scala
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BuglistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-list.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-01.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-02.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-04.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-08.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-09.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-10.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Meter.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/MeterCaseClass.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/anyval-box-types.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/bugs.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/caseClassHash.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/deeps.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/dynamic-anyval.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/impconvtimes.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/imports.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/interpolation.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/interpolationMultiline1.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/issue192.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-static.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-toplevel.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-whitebox-decl.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/misc.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/promotion.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/runtime.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/spec-self.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/structural.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t0421-new.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t0421-old.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t1503.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t3702.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t4148.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t4617.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5356.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5552.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5629b.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5866.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6662.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t7657.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t7763.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t8570a.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t8764.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t9387b.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t9656.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/try-catch-unify.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/virtpatmat_switch.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/virtpatmat_typetag.check
UU project/Build.scala
A  scala-test-suite/src/test/resources/2.12.11/BlacklistedTests.txt
A  scala-test-suite/src/test/resources/2.12.11/WhitelistedTests.txt
A  scala-test-suite/src/test/resources/2.13.2/BlacklistedTests.txt
A  scala-test-suite/src/test/resources/2.13.2/WhitelistedTests.txt
DU scripts/assemble-cli.sh
UU scripts/publish.sh
DU tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala
DU tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/BasicLinkerBackend.scala
DU tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala
```
```
$ git rm -f scripts/assemble-cli.sh
rm 'scripts/assemble-cli.sh'
```
The changes in `tools/` are on secondary constructors that do not exist in master anymore, so we just remove the files:
```
$ git rm -rf tools/
rm 'tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala'
rm 'tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/closure/ClosureLinkerBackend.scala'
rm 'tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/BasicLinkerBackend.scala'
rm 'tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/BasicLinkerBackend.scala'
rm 'tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala'
rm 'tools/shared/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackend.scala'
```
Now fix all the other conflicts, adapt a few more things like `MultiScalaProject` with the new Scala versions, make sure most things work.
```diff
$ git diff | cat
diff --cc .gitignore
index 8abf7c12d,49696008c..000000000
--- a/.gitignore
+++ b/.gitignore
@@@ -9,8 -9,4 +9,9 @@@ target
  /.idea/
  /.idea_modules/
  bin/
+ /node_modules/
 +
 +# metals files/directories
 +/.bloop/
 +/.metals/
 +/project/metals.sbt
diff --cc Jenkinsfile
index 9e8816153,c135a47d9..000000000
--- a/Jenkinsfile
+++ b/Jenkinsfile
@@@ -393,10 -426,25 +393,10 @@@ def otherJavaVersions = [
  def allJavaVersions = otherJavaVersions.clone()
  allJavaVersions << mainJavaVersion

- def mainScalaVersion = "2.12.10"
- def mainScalaVersions = ["2.11.12", "2.12.10", "2.13.1"]
+ def mainScalaVersion = "2.12.11"
 -def mainScalaVersions = ["2.10.2", "2.11.12", "2.12.11", "2.13.2"]
++def mainScalaVersions = ["2.11.12", "2.12.11", "2.13.2"]
  def otherScalaVersions = [
 -  "2.10.3",
 -  "2.10.4",
 -  "2.10.5",
 -  "2.10.6",
 -  "2.10.7",
 -  "2.11.0",
 -  "2.11.1",
 -  "2.11.2",
 -  "2.11.4",
 -  "2.11.5",
 -  "2.11.6",
 -  "2.11.7",
 -  "2.11.8",
 -  "2.11.11",
    "2.11.12",
 -  "2.12.0",
    "2.12.1",
    "2.12.2",
    "2.12.3",
@@@ -415,19 -465,24 +417,19 @@@ mainScalaVersions.each { scalaVersion -
    allJavaVersions.each { javaVersion ->
      quickMatrix.add([task: "main", scala: scalaVersion, java: javaVersion])
    }
 +  quickMatrix.add([task: "test-suite-ecma-script2015", scala: scalaVersion, java: mainJavaVersion, testSuite: "testSuite"])
    quickMatrix.add([task: "test-suite-ecma-script5", scala: scalaVersion, java: mainJavaVersion, testSuite: "testSuite"])
 -  quickMatrix.add([task: "test-suite-ecma-script6", scala: scalaVersion, java: mainJavaVersion, testSuite: "testSuite"])
 -  if (!scalaVersion.startsWith("2.10.")) {
 -    quickMatrix.add([task: "test-suite-ecma-script5", scala: scalaVersion, java: mainJavaVersion, testSuite: "scalaTestSuite"])
 -    quickMatrix.add([task: "test-suite-ecma-script6", scala: scalaVersion, java: mainJavaVersion, testSuite: "scalaTestSuite"])
 -  }
 +  quickMatrix.add([task: "test-suite-ecma-script2015", scala: scalaVersion, java: mainJavaVersion, testSuite: "scalaTestSuite"])
 +  quickMatrix.add([task: "test-suite-ecma-script5", scala: scalaVersion, java: mainJavaVersion, testSuite: "scalaTestSuite"])
    quickMatrix.add([task: "bootstrap", scala: scalaVersion, java: mainJavaVersion])
 -  if (!scalaVersion.startsWith("2.10.")) {
 -    quickMatrix.add([task: "partest-fastopt", scala: scalaVersion, java: mainJavaVersion])
 -  }
 +  quickMatrix.add([task: "partest-fastopt", scala: scalaVersion, java: mainJavaVersion])
  }
 +quickMatrix.add([task: "test-suite-ecma-script5-force-polyfills", scala: mainScalaVersion, java: mainJavaVersion, testSuite: "testSuite"])
  allJavaVersions.each { javaVersion ->
-   quickMatrix.add([task: "tools-sbtplugin", scala: "2.12.10", java: javaVersion])
 -  quickMatrix.add([task: "tools-cli-stubs-sbtplugin", scala: "2.12.11", sbt_version_override: "", java: javaVersion])
++  quickMatrix.add([task: "tools-sbtplugin", scala: "2.12.11", java: javaVersion])
 +  quickMatrix.add([task: "tools", scala: "2.11.12", java: javaVersion])
  }
 -quickMatrix.add([task: "tools-cli-stubs", scala: "2.10.7", sbt_version_override: "0.13.17", java: mainJavaVersion])
 -quickMatrix.add([task: "partestc", scala: "2.11.0", java: mainJavaVersion])
 -quickMatrix.add([task: "sbtplugin-test", toolsscala: "2.10.7", sbt_version_override: "0.13.17", java: mainJavaVersion])
 -quickMatrix.add([task: "sbtplugin-test", toolsscala: "2.12.11", sbt_version_override: "", java: mainJavaVersion])
 +quickMatrix.add([task: "partestc", scala: "2.12.1", java: mainJavaVersion])

  // The 'full' matrix
  def fullMatrix = quickMatrix.clone()
diff --cc ci/checksizes.sh
index d57567e4d,5a27dd25c..000000000
mode 100755,100755..100644
--- a/ci/checksizes.sh
+++ b/ci/checksizes.sh
@@@ -8,13 -8,16 +8,13 @@@ case $FULLVER i
    2.11.12)
      VER=2.11
      ;;
-   2.12.10)
+   2.12.11)
      VER=2.12
      ;;
-   2.13.1)
+   2.13.2)
      VER=2.13
      ;;
-   2.12.1|2.12.2|2.12.3|2.12.4|2.12.5|2.12.6|2.12.7|2.12.8|2.12.9|2.13.0)
 -  2.10.3|2.10.4|2.10.5|2.10.6|2.10.7|2.11.0|2.11.1|2.11.2|2.11.4|2.11.5|2.11.6|2.11.7|2.11.8|2.11.11|2.12.0|2.12.1|2.12.2|2.12.3|2.12.4|2.12.5|2.12.6|2.12.7|2.12.8|2.12.9|2.12.10|2.13.0|2.13.1)
++  2.12.1|2.12.2|2.12.3|2.12.4|2.12.5|2.12.6|2.12.7|2.12.8|2.12.9|2.12.10|2.13.0|2.13.1)
      echo "Ignoring checksizes for Scala $FULLVER"
      exit 0
      ;;
@@@ -33,23 -36,29 +33,23 @@@ REVERSI_PREOPT_GZ_SIZE=$(stat '-c%s' "$
  REVERSI_OPT_GZ_SIZE=$(stat '-c%s' "$REVERSI_OPT.gz")

  case $FULLVER in
 -  2.10.2)
 -    REVERSI_PREOPT_EXPECTEDSIZE=529000
 -    REVERSI_OPT_EXPECTEDSIZE=120000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=71000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=31000
 -    ;;
    2.11.12)
 -    REVERSI_PREOPT_EXPECTEDSIZE=526000
 -    REVERSI_OPT_EXPECTEDSIZE=121000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=71000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=31000
 +    REVERSI_PREOPT_EXPECTEDSIZE=435000
 +    REVERSI_OPT_EXPECTEDSIZE=94000
 +    REVERSI_PREOPT_GZ_EXPECTEDSIZE=59000
 +    REVERSI_OPT_GZ_EXPECTEDSIZE=27000
      ;;
-   2.12.10)
+   2.12.11)
 -    REVERSI_PREOPT_EXPECTEDSIZE=715000
 -    REVERSI_OPT_EXPECTEDSIZE=164000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=88000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=38000
 +    REVERSI_PREOPT_EXPECTEDSIZE=409000
 +    REVERSI_OPT_EXPECTEDSIZE=90000
 +    REVERSI_PREOPT_GZ_EXPECTEDSIZE=54000
 +    REVERSI_OPT_GZ_EXPECTEDSIZE=25000
      ;;
-   2.13.1)
+   2.13.2)
 -    REVERSI_PREOPT_EXPECTEDSIZE=794000
 -    REVERSI_OPT_EXPECTEDSIZE=190000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=107000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=48000
 +    REVERSI_PREOPT_EXPECTEDSIZE=556000
 +    REVERSI_OPT_EXPECTEDSIZE=122000
 +    REVERSI_PREOPT_GZ_EXPECTEDSIZE=74000
 +    REVERSI_OPT_GZ_EXPECTEDSIZE=35000
      ;;
  esac

diff --cc compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
index 80f9c6af7,2521e3c24..000000000
--- a/compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
+++ b/compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
@@@ -10,12 -10,13 +10,13 @@@
   * additional information regarding copyright ownership.
   */

 -package org.scalajs.core.compiler.test
 +package org.scalajs.nscplugin.test

 -import org.scalajs.core.compiler.test.util._
 -import org.scalajs.core.compiler.test.util.VersionDependentMessages.methodSig
 +import org.scalajs.nscplugin.test.util._
- import org.junit.Test
++import org.scalajs.nscplugin.test.util.VersionDependentMessages.methodSig

  import org.junit.Assume._
+ import org.junit.Test

  // scalastyle:off line.size.limit

@@@ -217,32 -247,17 +218,32 @@@ class JSExportTest extends DirectTest w
        @JSExport
        def ub(x: Box[Int]): Int = x.x
      }
 -    """.fails() // No error test, Scala version dependent error messages
 +    """ hasErrors
-     """
++    s"""
 +      |newSource1.scala:8: error: double definition:
-       |def $js$exported$meth$ub(x: Confl.this.Box[String]): Any at line 6 and
-       |def $js$exported$meth$ub(x: Confl.this.Box[Int]): Any at line 8
-       |have same type after erasure: (x: Confl#Box)Object
++      |def ${"$js$exported$meth$ub"}(x: Confl.this.Box[String]): Any at line 6 and
++      |def ${"$js$exported$meth$ub"}(x: Confl.this.Box[Int]): Any at line 8
++      |have same type after erasure: ${methodSig("(x: Confl#Box)", "Object")}
 +      |      @JSExport
 +      |       ^
 +    """

      """
      class Confl {
        @JSExport
 -      def rtType(x: scala.scalajs.js.prim.Number) = x
 +      def rtType(x: js.Any) = x

        @JSExport
 -      def rtType(x: Double) = x
 +      def rtType(x: js.Dynamic) = x
      }
 -    """.fails() // Error message depends on Scala version
 +    """ hasErrors
-     """
++    s"""
 +      |newSource1.scala:7: error: Cannot disambiguate overloads for exported method rtType with types
-       |  (x: scala.scalajs.js.Any)Object
-       |  (x: scala.scalajs.js.Dynamic)Object
++      |  ${methodSig("(x: scala.scalajs.js.Any)", "Object")}
++      |  ${methodSig("(x: scala.scalajs.js.Dynamic)", "Object")}
 +      |      @JSExport
 +      |       ^
 +    """

      """
      class Confl {
@@@ -284,14 -299,7 +285,14 @@@
        @JSExport
        def foo(x: Double, y: String)(z: String*) = x
      }
 -    """.fails() // Error message depends on Scala version
 +    """ hasErrors
-     """
++    s"""
 +      |newSource1.scala:6: error: Cannot disambiguate overloads for exported method foo with types
-       |  (x: Double, y: String, z: Int)Object
-       |  (x: Double, y: String, z: Seq)Object
++      |  ${methodSig("(x: Double, y: String, z: Int)", "Object")}
++      |  ${methodSig("(x: Double, y: String, z: Seq)", "Object")}
 +      |      @JSExport
 +      |       ^
 +    """

      """
      class A {
@@@ -301,14 -309,7 +302,14 @@@
        @JSExport
        def a(x: Any) = 2
      }
 -    """.fails() // Error message depends on Scala version
 +    """ hasErrors
-     """
++    s"""
 +      |newSource1.scala:7: error: Cannot disambiguate overloads for exported method a with types
-       |  (x: Object)Object
-       |  (x: scala.scalajs.js.Any)Object
++      |  ${methodSig("(x: Object)", "Object")}
++      |  ${methodSig("(x: scala.scalajs.js.Any)", "Object")}
 +      |      @JSExport
 +      |       ^
 +    """

    }

diff --cc compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
index 065b0e7c4,8c9265cf3..000000000
--- a/compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
+++ b/compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
@@@ -10,9 -10,10 +10,10 @@@
   * additional information regarding copyright ownership.
   */

 -package org.scalajs.core.compiler.test
 +package org.scalajs.nscplugin.test

 -import org.scalajs.core.compiler.test.util._
 -import org.scalajs.core.compiler.test.util.VersionDependentMessages.methodSig
 +import org.scalajs.nscplugin.test.util._
++import org.scalajs.nscplugin.test.util.VersionDependentMessages.methodSig

  import org.junit.Test
  import org.junit.Ignore
diff --cc project/Build.scala
index 1756f8721,159d2a796..000000000
--- a/project/Build.scala
+++ b/project/Build.scala
@@@ -135,17 -64,14 +135,17 @@@ object Build
    val shouldPartest = settingKey[Boolean](
      "Whether we should partest the current scala version (and fail if we can't)")

 -  val previousVersion = "0.6.32"
 -  val previousSJSBinaryVersion =
 -    ScalaJSCrossVersion.binaryScalaJSVersion(previousVersion)
 -  val previousBinaryCrossVersion =
 -    CrossVersion.binaryMapped(v => s"sjs${previousSJSBinaryVersion}_$v")
 +  val packageMinilib = taskKey[File]("Produces the minilib jar.")
 +
 +  val previousVersion = "1.0.1"
 +  val previousBinaryCrossVersion = CrossVersion.binaryWith("sjs1_", "")
 +
 +  val scalaVersionsUsedForPublishing: Set[String] =
-     Set("2.11.12", "2.12.10", "2.13.1")
++    Set("2.10.7", "2.11.12", "2.12.11", "2.13.2")
 +  val newScalaBinaryVersionsInThisRelease: Set[String] =
 +    Set()

    def hasNewCollections(version: String): Boolean = {
 -    !version.startsWith("2.10.") &&
      !version.startsWith("2.11.") &&
      !version.startsWith("2.12.")
    }
@@@ -586,426 -546,346 +586,426 @@@

 -          // Files must be Jars, non-files must be dirs
 -          val (jars, dirs) = cp.filter(_.exists).partition(_.isFile)
 -          val irFiles = dirs.flatMap(dir => (dir ** "*.sjsir").get)
 +  lazy val linkerPrivateLibrary: Project = (project in file("linker-private-library")).enablePlugins(
 +      MyScalaJSPlugin
 +  ).settings(
 +      commonSettings,
-       scalaVersion := "2.12.10",
++      scalaVersion := "2.12.11",
 +      fatalWarningsSettings,
 +      name := "Scala.js linker private library",
 +      publishArtifact in Compile := false,
 +      delambdafySetting,
 +      cleanIRSettings
 +  ).withScalaJSCompiler2_12.withScalaJSJUnitPlugin2_12.dependsOn(
 +      library.v2_12, jUnitRuntime.v2_12 % "test", testBridge.v2_12 % "test",
 +  )

  [...]

 +  lazy val plugin: Project = Project(id = "sbtPlugin", base = file("sbt-plugin"))
 +      .enablePlugins(ScriptedPlugin).settings(
 +      commonSettings,
 +      publishIvySettings,
 +      fatalWarningsSettings,
 +      name := "Scala.js sbt plugin",
 +      normalizedName := "sbt-scalajs",
 +      bintrayProjectName := "sbt-scalajs-plugin", // "sbt-scalajs" was taken
 +      sbtPlugin := true,
-       crossScalaVersions := Seq("2.12.10"),
++      crossScalaVersions := Seq("2.12.11"),
 +      scalaVersion := crossScalaVersions.value.head,
 +      sbtVersion := "1.0.0",
 +      scalaBinaryVersion :=
 +        CrossVersion.binaryScalaVersion(scalaVersion.value),
 +      previousArtifactSetting,
 +      mimaBinaryIssueFilters ++= BinaryIncompatibilities.SbtPlugin,

diff --cc scripts/publish.sh
index a8a89c7bf,5a314b544..000000000
mode 100755,100755..100644
--- a/scripts/publish.sh
+++ b/scripts/publish.sh
* Unmerged path compiler/src/test/scala/org/scalajs/nscplugin/test/util/VersionDependentMessages.scala
diff --git a/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala b/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala
index feee0fabb..9a1a3ae49 100644
--- a/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala
+++ b/js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala
@@ -77,7 +77,7 @@ private[test] class RunTests(config: JSEnvSuiteConfig, withCom: Boolean) {

   @Test // Failed in Phantom - #2053
   def utf8Test: Unit = {
-    withRun("""console.log("\u1234")""") {
+    withRun("console.log('\u1234')") {
       _.expectOut("\u1234\n")
         .closeRun()
     }
diff --git a/project/MultiScalaProject.scala b/project/MultiScalaProject.scala
index fd30cbe3a..d714772fd 100644
--- a/project/MultiScalaProject.scala
+++ b/project/MultiScalaProject.scala
@@ -79,8 +79,8 @@ object MultiScalaProject {

   private final val versions = Map[String, Seq[String]](
     "2.11" -> Seq("2.11.12"),
-    "2.12" -> Seq("2.12.1", "2.12.2", "2.12.3", "2.12.4", "2.12.5", "2.12.6", "2.12.7", "2.12.8", "2.12.9", "2.12.10"),
-    "2.13" -> Seq("2.13.0", "2.13.1"),
+    "2.12" -> Seq("2.12.1", "2.12.2", "2.12.3", "2.12.4", "2.12.5", "2.12.6", "2.12.7", "2.12.8", "2.12.9", "2.12.10", "2.12.11"),
+    "2.13" -> Seq("2.13.0", "2.13.1", "2.13.2"),
   )

   private final val ideVersion = "2.12"
diff --git a/sbt-plugin/src/sbt-test/incremental/change-config-and-source/build.sbt b/sbt-plugin/src/sbt-test/incremental/change-config-and-source/build.sbt
index 7d21f37e8..bf4c73f7f 100644
--- a/sbt-plugin/src/sbt-test/incremental/change-config-and-source/build.sbt
+++ b/sbt-plugin/src/sbt-test/incremental/change-config-and-source/build.sbt
@@ -1,4 +1,4 @@
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/incremental/change-config/build.sbt b/sbt-plugin/src/sbt-test/incremental/change-config/build.sbt
index 7d21f37e8..bf4c73f7f 100644
--- a/sbt-plugin/src/sbt-test/incremental/change-config/build.sbt
+++ b/sbt-plugin/src/sbt-test/incremental/change-config/build.sbt
@@ -1,4 +1,4 @@
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/incremental/fix-compile-error/build.sbt b/sbt-plugin/src/sbt-test/incremental/fix-compile-error/build.sbt
index 101143b73..397565971 100644
--- a/sbt-plugin/src/sbt-test/incremental/fix-compile-error/build.sbt
+++ b/sbt-plugin/src/sbt-test/incremental/fix-compile-error/build.sbt
@@ -1,4 +1,4 @@
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/linker/concurrent-linker-use/build.sbt b/sbt-plugin/src/sbt-test/linker/concurrent-linker-use/build.sbt
index cb04a2909..55e3e3cb2 100644
--- a/sbt-plugin/src/sbt-test/linker/concurrent-linker-use/build.sbt
+++ b/sbt-plugin/src/sbt-test/linker/concurrent-linker-use/build.sbt
@@ -11,7 +11,7 @@ lazy val concurrentUseOfLinkerTest = taskKey[Any]("")
 name := "Scala.js sbt test"

 version := scalaJSVersion
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/linker/custom-linker/build.sbt b/sbt-plugin/src/sbt-test/linker/custom-linker/build.sbt
index da78023e9..ca561b7a6 100644
--- a/sbt-plugin/src/sbt-test/linker/custom-linker/build.sbt
+++ b/sbt-plugin/src/sbt-test/linker/custom-linker/build.sbt
@@ -13,14 +13,14 @@

 inThisBuild(Def.settings(
   version := scalaJSVersion,
-  scalaVersion := "2.12.10",
+  scalaVersion := "2.12.11",
 ))

 lazy val check = taskKey[Any]("")

 lazy val customLinker = project.in(file("custom-linker"))
   .settings(
-    scalaVersion := "2.12.10", // needs to match sbt's version
+    scalaVersion := "2.12.11", // needs to match sbt's version
     libraryDependencies += "org.scala-js" %% "scalajs-linker" % scalaJSVersion,
   )

diff --git a/sbt-plugin/src/sbt-test/linker/no-root-dependency-resolution/build.sbt b/sbt-plugin/src/sbt-test/linker/no-root-dependency-resolution/build.sbt
index b3a409b3b..39cba6f0d 100644
--- a/sbt-plugin/src/sbt-test/linker/no-root-dependency-resolution/build.sbt
+++ b/sbt-plugin/src/sbt-test/linker/no-root-dependency-resolution/build.sbt
@@ -1,7 +1,7 @@
 name := "Scala.js sbt test"

 version in ThisBuild := scalaJSVersion
-scalaVersion in ThisBuild := "2.12.10"
+scalaVersion in ThisBuild := "2.12.11"

 // Disable the IvyPlugin on the root project
 disablePlugins(sbt.plugins.IvyPlugin)
diff --git a/sbt-plugin/src/sbt-test/linker/non-existent-classpath/build.sbt b/sbt-plugin/src/sbt-test/linker/non-existent-classpath/build.sbt
index 090619d1d..772fdf819 100644
--- a/sbt-plugin/src/sbt-test/linker/non-existent-classpath/build.sbt
+++ b/sbt-plugin/src/sbt-test/linker/non-existent-classpath/build.sbt
@@ -1,5 +1,5 @@
 version := scalaJSVersion
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/settings/cross-version/build.sbt b/sbt-plugin/src/sbt-test/settings/cross-version/build.sbt
index 00c69b8fd..79c164dfa 100644
--- a/sbt-plugin/src/sbt-test/settings/cross-version/build.sbt
+++ b/sbt-plugin/src/sbt-test/settings/cross-version/build.sbt
@@ -3,7 +3,7 @@ import org.scalajs.sbtplugin.ScalaJSCrossVersion
 val check = taskKey[Unit]("Run checks of this test")

 version := scalaJSVersion
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 lazy val js = project.enablePlugins(ScalaJSPlugin).settings(
     check := {
diff --git a/sbt-plugin/src/sbt-test/settings/module-init/build.sbt b/sbt-plugin/src/sbt-test/settings/module-init/build.sbt
index 3aab6bbe9..e4a40f228 100644
--- a/sbt-plugin/src/sbt-test/settings/module-init/build.sbt
+++ b/sbt-plugin/src/sbt-test/settings/module-init/build.sbt
@@ -3,7 +3,7 @@ import org.scalajs.linker.interface.ModuleInitializer
 val check = taskKey[Unit]("Run checks of this test")

 version := scalaJSVersion
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/settings/source-map/build.sbt b/sbt-plugin/src/sbt-test/settings/source-map/build.sbt
index 9591a89ab..a13771a6d 100644
--- a/sbt-plugin/src/sbt-test/settings/source-map/build.sbt
+++ b/sbt-plugin/src/sbt-test/settings/source-map/build.sbt
@@ -3,7 +3,7 @@ import org.scalajs.linker.interface.ModuleInitializer
 val check = taskKey[Unit]("Run checks of this test")

 version := scalaJSVersion
-scalaVersion := "2.12.10"
+scalaVersion := "2.12.11"

 enablePlugins(ScalaJSPlugin)

diff --git a/sbt-plugin/src/sbt-test/testing/multi-framework/build.sbt b/sbt-plugin/src/sbt-test/testing/multi-framework/build.sbt
index c5e8b00c6..a39ca48b0 100644
--- a/sbt-plugin/src/sbt-test/testing/multi-framework/build.sbt
+++ b/sbt-plugin/src/sbt-test/testing/multi-framework/build.sbt
@@ -1,5 +1,5 @@
 inThisBuild(version := scalaJSVersion)
-inThisBuild(scalaVersion := "2.12.10")
+inThisBuild(scalaVersion := "2.12.11")

 lazy val root = project.in(file(".")).
   aggregate(multiTestJS, multiTestJVM)
```
```
$ git add -u
```
```
$ git st
M  .gitignore
M  Jenkinsfile
M  ci/checksizes.sh
M  compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
M  compiler/src/test/scala/org/scalajs/nscplugin/test/NonNativeJSTypeTest.scala
A  compiler/src/test/scala/org/scalajs/nscplugin/test/util/VersionDependentMessages.scala
M  js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BuglistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-list.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-01.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-02.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-04.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-08.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-09.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Course-2002-10.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/Meter.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/MeterCaseClass.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/anyval-box-types.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/bugs.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/caseClassHash.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/deeps.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/dynamic-anyval.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/impconvtimes.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/imports.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/interpolation.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/interpolationMultiline1.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/issue192.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-static.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-toplevel.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/macro-bundle-whitebox-decl.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/misc.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/promotion.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/runtime.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/spec-self.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/structural.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t0421-new.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t0421-old.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t1503.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t3702.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t4148.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t4617.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5356.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5552.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5629b.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5866.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6662.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t7657.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t7763.sem
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t8570a.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t8764.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t9387b.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t9656.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/try-catch-unify.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/virtpatmat_switch.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/virtpatmat_typetag.check
M  project/Build.scala
M  project/MultiScalaProject.scala
M  sbt-plugin/src/sbt-test/incremental/change-config-and-source/build.sbt
M  sbt-plugin/src/sbt-test/incremental/change-config/build.sbt
M  sbt-plugin/src/sbt-test/incremental/fix-compile-error/build.sbt
M  sbt-plugin/src/sbt-test/linker/concurrent-linker-use/build.sbt
M  sbt-plugin/src/sbt-test/linker/custom-linker/build.sbt
M  sbt-plugin/src/sbt-test/linker/no-root-dependency-resolution/build.sbt
M  sbt-plugin/src/sbt-test/linker/non-existent-classpath/build.sbt
M  sbt-plugin/src/sbt-test/settings/cross-version/build.sbt
M  sbt-plugin/src/sbt-test/settings/module-init/build.sbt
M  sbt-plugin/src/sbt-test/settings/source-map/build.sbt
M  sbt-plugin/src/sbt-test/testing/multi-framework/build.sbt
A  scala-test-suite/src/test/resources/2.12.11/BlacklistedTests.txt
A  scala-test-suite/src/test/resources/2.12.11/WhitelistedTests.txt
A  scala-test-suite/src/test/resources/2.13.2/BlacklistedTests.txt
A  scala-test-suite/src/test/resources/2.13.2/WhitelistedTests.txt
```
```
$ git commit
[merge-0.6.x-into-master-may-13 d53c43dbd] Merge '0.6.x' into 'master'.
```
Now trying out some heavy stuff like `partestSuite/testOnly -- --fastOpt`, triggering a few more things to change:
```
$ cp partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.10/neg/*.check partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/
$ cp partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.10/run/*.check partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/
```
Transferring two more things from Whitelisted to Blacklisted, as they were already in 2.12.10.

Then also checking `checksizes` for 2.12.11 and 2.13.2, adapting the files.
```diff
$ git diff | cat
diff --git a/ci/checksizes.sh b/ci/checksizes.sh
index 9a98f833c..e0ac5d7e4 100755
--- a/ci/checksizes.sh
+++ b/ci/checksizes.sh
@@ -40,16 +40,16 @@ case $FULLVER in
     REVERSI_OPT_GZ_EXPECTEDSIZE=27000
     ;;
   2.12.11)
-    REVERSI_PREOPT_EXPECTEDSIZE=409000
-    REVERSI_OPT_EXPECTEDSIZE=90000
-    REVERSI_PREOPT_GZ_EXPECTEDSIZE=54000
-    REVERSI_OPT_GZ_EXPECTEDSIZE=25000
+    REVERSI_PREOPT_EXPECTEDSIZE=616000
+    REVERSI_OPT_EXPECTEDSIZE=121000
+    REVERSI_PREOPT_GZ_EXPECTEDSIZE=76000
+    REVERSI_OPT_GZ_EXPECTEDSIZE=32000
     ;;
   2.13.2)
-    REVERSI_PREOPT_EXPECTEDSIZE=556000
-    REVERSI_OPT_EXPECTEDSIZE=122000
-    REVERSI_PREOPT_GZ_EXPECTEDSIZE=74000
-    REVERSI_OPT_GZ_EXPECTEDSIZE=35000
+    REVERSI_PREOPT_EXPECTEDSIZE=689000
+    REVERSI_OPT_EXPECTEDSIZE=150000
+    REVERSI_PREOPT_GZ_EXPECTEDSIZE=90000
+    REVERSI_OPT_GZ_EXPECTEDSIZE=41000
     ;;
 esac

diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
index 11d1eeebe..a584a29ea 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
@@ -147,6 +147,10 @@ run/t11255

 run/t4426.scala

+# Using sys.exit / System.exit
+
+run/verify-ctor.scala
+
 # Using Await

 run/t7336.scala
@@ -1052,6 +1056,7 @@ run/t10490
 run/t10490-2
 run/t10889
 run/t3899
+run/t11373

 # Using scala-script
 run/t7791-script-linenums.scala
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
index ca4af2364..4ca1c094c 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
@@ -2638,7 +2638,6 @@ run/t4570.scala
 run/t5612.scala
 run/t1110.scala
 run/t2636.scala
-run/verify-ctor.scala
 run/t3647.scala
 run/t4560.scala
 run/t6632.scala
@@ -3410,7 +3409,6 @@ neg/t9963.scala
 neg/warn-unused-locals.scala
 run/pr7593.scala
 run/t10870.scala
-run/t11373
 run/t11665.scala
 pos/t7216.scala
 pos/t8855.scala
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
index b7ce23da2..3fce708aa 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
@@ -11,20 +11,22 @@ superaccessors   8  add super accessors in traits and nested classes
     extmethods   9  add extension methods for inline classes
        pickler  10  serialize symbol tables
      refchecks  11  reference/override checking, translate nested objects
-       uncurry  12  uncurry, translate function values to anonymous classes
-        fields  13  synthesize accessors and fields, add bitmaps for lazy vals
-     tailcalls  14  replace tail calls by jumps
-    specialize  15  @specialized-driven class and method specialization
- explicitouter  16  this refs to outer pointers
-       erasure  17  erase types, add interfaces for traits
-   posterasure  18  clean up erased inline classes
-    lambdalift  19  move nested functions to top level
-  constructors  20  move field definitions into constructors
-       flatten  21  eliminate inner classes
-         mixin  22  mixin composition
-        jscode  23  generate JavaScript code from ASTs
-       cleanup  24  platform-specific cleanups, generate reflective calls
-    delambdafy  25  remove lambdas
-           jvm  26  generate JVM bytecode
-       ploogin  27  A sample phase that does so many things it's kind of hard...
-      terminal  28  the last phase during a compilation run
+xplicitinnerjs  12  make references to inner JS classes explicit
+       uncurry  13  uncurry, translate function values to anonymous classes
+        fields  14  synthesize accessors and fields, add bitmaps for lazy vals
+     tailcalls  15  replace tail calls by jumps
+    specialize  16  @specialized-driven class and method specialization
+xplicitlocaljs  17  make references to local JS classes explicit
+ explicitouter  18  this refs to outer pointers
+       erasure  19  erase types, add interfaces for traits
+   posterasure  20  clean up erased inline classes
+    lambdalift  21  move nested functions to top level
+  constructors  22  move field definitions into constructors
+       flatten  23  eliminate inner classes
+         mixin  24  mixin composition
+        jscode  25  generate JavaScript code from ASTs
+       cleanup  26  platform-specific cleanups, generate reflective calls
+    delambdafy  27  remove lambdas
+           jvm  28  generate JVM bytecode
+       ploogin  29  A sample phase that does so many things it's kind of hard...
+      terminal  30  the last phase during a compilation run
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
index 56b74a312..c12c66481 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
@@ -12,19 +12,21 @@ superaccessors   8  add super accessors in traits and nested classes
     extmethods   9  add extension methods for inline classes
        pickler  10  serialize symbol tables
      refchecks  11  reference/override checking, translate nested objects
-       uncurry  12  uncurry, translate function values to anonymous classes
-        fields  13  synthesize accessors and fields, add bitmaps for lazy vals
-     tailcalls  14  replace tail calls by jumps
-    specialize  15  @specialized-driven class and method specialization
- explicitouter  16  this refs to outer pointers
-       erasure  17  erase types, add interfaces for traits
-   posterasure  18  clean up erased inline classes
-    lambdalift  19  move nested functions to top level
-  constructors  20  move field definitions into constructors
-       flatten  21  eliminate inner classes
-         mixin  22  mixin composition
-        jscode  23  generate JavaScript code from ASTs
-       cleanup  24  platform-specific cleanups, generate reflective calls
-    delambdafy  25  remove lambdas
-           jvm  26  generate JVM bytecode
-      terminal  27  the last phase during a compilation run
+xplicitinnerjs  12  make references to inner JS classes explicit
+       uncurry  13  uncurry, translate function values to anonymous classes
+        fields  14  synthesize accessors and fields, add bitmaps for lazy vals
+     tailcalls  15  replace tail calls by jumps
+    specialize  16  @specialized-driven class and method specialization
+xplicitlocaljs  17  make references to local JS classes explicit
+ explicitouter  18  this refs to outer pointers
+       erasure  19  erase types, add interfaces for traits
+   posterasure  20  clean up erased inline classes
+    lambdalift  21  move nested functions to top level
+  constructors  22  move field definitions into constructors
+       flatten  23  eliminate inner classes
+         mixin  24  mixin composition
+        jscode  25  generate JavaScript code from ASTs
+       cleanup  26  platform-specific cleanups, generate reflective calls
+    delambdafy  27  remove lambdas
+           jvm  28  generate JVM bytecode
+      terminal  29  the last phase during a compilation run
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
index cde255e3b..4bfb4500d 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
@@ -11,19 +11,21 @@ superaccessors   8  add super accessors in traits and nested classes
     extmethods   9  add extension methods for inline classes
        pickler  10  serialize symbol tables
      refchecks  11  reference/override checking, translate nested objects
-       uncurry  12  uncurry, translate function values to anonymous classes
-        fields  13  synthesize accessors and fields, add bitmaps for lazy vals
-     tailcalls  14  replace tail calls by jumps
-    specialize  15  @specialized-driven class and method specialization
- explicitouter  16  this refs to outer pointers
-       erasure  17  erase types, add interfaces for traits
-   posterasure  18  clean up erased inline classes
-    lambdalift  19  move nested functions to top level
-  constructors  20  move field definitions into constructors
-       flatten  21  eliminate inner classes
-         mixin  22  mixin composition
-        jscode  23  generate JavaScript code from ASTs
-       cleanup  24  platform-specific cleanups, generate reflective calls
-    delambdafy  25  remove lambdas
-           jvm  26  generate JVM bytecode
-      terminal  27  the last phase during a compilation run
+xplicitinnerjs  12  make references to inner JS classes explicit
+       uncurry  13  uncurry, translate function values to anonymous classes
+        fields  14  synthesize accessors and fields, add bitmaps for lazy vals
+     tailcalls  15  replace tail calls by jumps
+    specialize  16  @specialized-driven class and method specialization
+xplicitlocaljs  17  make references to local JS classes explicit
+ explicitouter  18  this refs to outer pointers
+       erasure  19  erase types, add interfaces for traits
+   posterasure  20  clean up erased inline classes
+    lambdalift  21  move nested functions to top level
+  constructors  22  move field definitions into constructors
+       flatten  23  eliminate inner classes
+         mixin  24  mixin composition
+        jscode  25  generate JavaScript code from ASTs
+       cleanup  26  platform-specific cleanups, generate reflective calls
+    delambdafy  27  remove lambdas
+           jvm  28  generate JVM bytecode
+      terminal  29  the last phase during a compilation run
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
index d8be421e5..5d521dc8a 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
@@ -12,20 +12,22 @@ superaccessors   8  add super accessors in traits and nested classes
     extmethods   9  add extension methods for inline classes
        pickler  10  serialize symbol tables
      refchecks  11  reference/override checking, translate nested objects
-       uncurry  12  uncurry, translate function values to anonymous classes
-        fields  13  synthesize accessors and fields, add bitmaps for lazy vals
-     tailcalls  14  replace tail calls by jumps
-    specialize  15  @specialized-driven class and method specialization
- explicitouter  16  this refs to outer pointers
-       erasure  17  erase types, add interfaces for traits
-   posterasure  18  clean up erased inline classes
-    lambdalift  19  move nested functions to top level
-  constructors  20  move field definitions into constructors
-       flatten  21  eliminate inner classes
-         mixin  22  mixin composition
-        jscode  23  generate JavaScript code from ASTs
-       cleanup  24  platform-specific cleanups, generate reflective calls
-    delambdafy  25  remove lambdas
-           jvm  26  generate JVM bytecode
-       ploogin  27  A sample phase that does so many things it's kind of hard...
-      terminal  28  the last phase during a compilation run
+xplicitinnerjs  12  make references to inner JS classes explicit
+       uncurry  13  uncurry, translate function values to anonymous classes
+        fields  14  synthesize accessors and fields, add bitmaps for lazy vals
+     tailcalls  15  replace tail calls by jumps
+    specialize  16  @specialized-driven class and method specialization
+xplicitlocaljs  17  make references to local JS classes explicit
+ explicitouter  18  this refs to outer pointers
+       erasure  19  erase types, add interfaces for traits
+   posterasure  20  clean up erased inline classes
+    lambdalift  21  move nested functions to top level
+  constructors  22  move field definitions into constructors
+       flatten  23  eliminate inner classes
+         mixin  24  mixin composition
+        jscode  25  generate JavaScript code from ASTs
+       cleanup  26  platform-specific cleanups, generate reflective calls
+    delambdafy  27  remove lambdas
+           jvm  28  generate JVM bytecode
+       ploogin  29  A sample phase that does so many things it's kind of hard...
+      terminal  30  the last phase during a compilation run
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
index 6f30cc507..1c8e0882d 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
@@ -1,7 +1,7 @@
 void
 int
-class scala.runtime.BoxedUnit
-class scala.runtime.BoxedUnit
+class java.lang.Void
+class java.lang.Void
 class java.lang.Byte
 class java.lang.Byte
 5
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
index a3b8b64a4..962df2f4f 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
@@ -1,3 +1,3 @@
-[Lscala.runtime.BoxedUnit
+[Ljava.lang.Void
 undefined
 undefined
diff --git a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
index 654ef1bee..b86fc66f7 100644
--- a/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
+++ b/partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
@@ -50,5 +50,5 @@ Checking if void matches void
 Some(undefined)
 Checking if void matches byte
 None
-Checking if class scala.runtime.BoxedUnit matches void
+Checking if class java.lang.Void matches void
 Some(undefined)
```
```
$ git add .
```
```
$ git st
M  ci/checksizes.sh
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/BlacklistedTests.txt
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/WhitelistedTests.txt
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-additional.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-missing.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t6446-show-phases.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/neg/t7494-no-options.check
A  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/classof.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5568.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t5680.check
M  partest-suite/src/test/resources/scala/tools/partest/scalajs/2.12.11/run/t6318_primitives.check
```
```
$ git amend
[merge-0.6.x-into-master-may-13 80d22a1be] Merge '0.6.x' into 'master'.
 Date: Wed May 13 16:23:41 2020 +0200
```

---

Arrived here, I haven't gone all the way to the tip of scalajs/0.6.x. However, since this was difficult enough, I'm stopping here for this PR. One that one is on master, I'll do another merge with the last mile.

### CODE REVIEW

File: js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala [hunk 1]
```diff
@@ -77,7 +77,7 @@ private[test] class RunTests(config: JSEnvSuiteConfig, withCom: Boolean) {
 
   @Test // Failed in Phantom - #2053
   def utf8Test: Unit = {
-    withRun("""console.log("\u1234")""") {
+    withRun("console.log('\u1234')") {
```
Comment (gzm0) [inline js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala:80]: Where does this change come from?

File: project/Build.scala [hunk 2]
```diff
@@ -141,7 +141,7 @@ object Build {
   val previousBinaryCrossVersion = CrossVersion.binaryWith("sjs1_", "")
 
   val scalaVersionsUsedForPublishing: Set[String] =
-    Set("2.11.12", "2.12.10", "2.13.1")
+    Set("2.10.7", "2.11.12", "2.12.11", "2.13.2")
```
Comment (gzm0) [inline project/Build.scala:144]: 2.10.x here looks wrong.

File: js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala (hunk 1 above)
Comment (sjrd) [reply js-envs-test-kit/src/main/scala/org/scalajs/jsenv/test/RunTests.scala:80]: It caused a fatal warning (error) in 2.13.2.

File: project/Build.scala (hunk 2 above)
Comment (sjrd) [reply project/Build.scala]: Indeed, fixed.

(also updated a 2.13.1 to 2.13.2 in the sbt plugin tests to fix the CI)

**Comment by sjrd** [comment]
> Oh dear. Did this trigger #4045? ;)

Not really. I've had a mind to open #4045 since the release of scalajs-react 1.7.0. But the changes here are really annoying, and I was anticipating them, so in a sense it contributed to that.
