### PR TITLE
Fix #4416: Remove stale methods from the Emitter's caches.

### LINKED ISSUE #4416: Incremental runs lead to GCC reporting a JSC_UNDEFINED_VARIABLE
Initially reported in mdoc at https://github.com/scalameta/mdoc/issues/454. mdoc uses the linker incrementally as a matter of course:

* For each `.md` file, it gathers all the snippets in a single (virtual) .scala source file, with each one in a separate `@JSExportTopLevel def` inside one `object`.
* It links the result for each file, and keeps the linker hot between `.md` files.

Clearly, this exercises the incremental linker in a fairly reproducible way, which led to the above issue to be deterministic.

I managed to further minimize the above report so that it does not depend on mdoc at all, reproducing it in our hello world project.

First, in the build, comment out `scalaJSUseMainModuleInitializer := true` in the helloworld project. Then, open sbt.

Paste the following code in `HelloWorld.scala`, save, and run `helloworld2_12/fullOptJS`:
```scala
object mdocjs {
  @_root_.scala.scalajs.js.annotation.JSExportTopLevel("mdoc_js_run1")
  def mdoc_js_run1(): Unit = {
    import scala.util.Success
    Success("foo")
  }

  @_root_.scala.scalajs.js.annotation.JSExportTopLevel("mdoc_js_run2")
  def mdoc_js_run2(): Unit = {
    import scala.util.Success
    Success("bar")
  }
}
```
Repeat with the following code (do not exit or reload sbt in-between):
```scala
object mdocjs {
  @_root_.scala.scalajs.js.annotation.JSExportTopLevel("mdoc_js_run1")
  def mdoc_js_run1(): Unit = {
    println("b")
  }
}
```
Repeat once more with the following code:
```scala
object mdocjs {
  @_root_.scala.scalajs.js.annotation.JSExportTopLevel("mdoc_js_run1")
  def mdoc_js_run1(): Unit = {
    println("c1")
  }

  @_root_.scala.scalajs.js.annotation.JSExportTopLevel("mdoc_js_run2")
  def mdoc_js_run2(): Unit = {
    println("c2")
  }
}
```
The last invocation triggers the error:
```
sbt:Scala.js> helloworld2_12/fullOptJS
[info] Compiling 1 Scala source to C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\classes ...
[info] Done compiling.
[info] Full optimizing C:\Users\sjrdo\Documents\Projets\scalajs\examples\helloworld\.2.12\target\scala-2.12\helloworld-opt
[error] JSC_UNDEFINED_VARIABLE. variable $c_s_util_Success is undeclared at file:///C:/Users/sjrdo/Documents/Projets/scalajs/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala line 11 : 11
[error] Closure: 1 error(s), 0 warning(s)
[error] There were errors when applying the Google Closure Compiler
[error] (helloworld2_12 / Compile / fullLinkJS) There were errors when applying the Google Closure Compiler
```
I have not tried to minimize this further than the above yet. One thing to try would be to get rid of the dependency on `println` and `Success`, so that we would only need the `minilib` to reproduce it in the linker tests.

### PR DESCRIPTION
**Pull request by sjrd**
Previously, we forgot to reset the `_cacheUsed` flag of non-static-like methods in the Emitter's caches. This caused them never to be removed even if they were not used in a run.

The fix is beneficial anyway for memory consumption, but it should not have been necessary for correctness. The issue happened because the `IncOptimizer` can reuse past values of `version` for a given method, if it was removed in a run and then reappeared. This observation raises a larger question about whether that is valid (and therefore should be accounted for in subsequent phases like the Emitter), but that is left for a later fix.

### CODE REVIEW

**Comment by sjrd** [comment]
The Jenkins build is green, but for some reason GitHub did not register that.

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 1]
```diff
@@ -187,79 +187,222 @@ class IncrementalTest {
...
       config: StandardConfig = StandardConfig())(
       implicit ec: ExecutionContext): Future[Unit] = {
 
-    val outputInc = MemOutputDirectory()
-    val outputBatch = MemOutputDirectory()
+    require(steps >= 2, s"require at least 2 steps but got $steps")
+
+    val inputSequence =
+      List.tabulate(steps)(step => (stepToClassDefs(step), stepToModuleInitializers(step)))
+    testIncrementalSequence(contextMessage, inputSequence, config)
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:341]: Does it make sense to do that if afterwards you keep a step counter anyways?

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 2]
```diff
@@ -187,79 +187,222 @@ class IncrementalTest {
...
+      List(
+        classDef(FooClass, kind = ClassKind.ModuleClass, superClass = Some(ObjectClass),
+            memberDefs = trivialCtor(FooClass) :: stepDependentMembers),
+
+        mainTestClassDef(Block(stepDependentMainStats))
+      )
+    }
+
+    def moduleInitializers(step: Int): List[ModuleInitializer] =
+      MainTestModuleInitializers
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:239]: Inline this below?

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 3]
```diff
@@ -187,79 +187,222 @@ class IncrementalTest {
...
-    testIncremental(classDefs(_), _ => MainTestModuleInitializers)
+    testIncrementalBidirectional(classDefs(_), _ => MainTestModuleInitializers)
+  }
+
+  @Test
+  def testStaleMethodBodyAfterItReappears_Issue4416(): AsyncResult = await {
+    val FooClass = ClassName("Foo$")
+
+    val run1 = m("run1", Nil, VoidRef)
+    val run2 = m("run2", Nil, VoidRef)
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:198]: These names seem a bit misleading...

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 4]
```diff
@@ -187,79 +187,222 @@ class IncrementalTest {
...
+      List(
+        classDef(FooClass, superClass = Some(ObjectClass),
+            memberDefs = trivialCtor(FooClass) :: stepDependentMembers),
+
+        mainTestClassDef(Block(stepDependentMainStats))
+      )
+    }
+
+    def moduleInitializers(step: Int): List[ModuleInitializer] =
+      MainTestModuleInitializers
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:299]: Same here: Inline?

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRBuilder.scala [hunk 5]
```diff
@@ -134,4 +134,5 @@ object TestIRBuilder {
     MethodIdent(name)
 
   def int(x: Int): IntLiteral = IntLiteral(x)
+  def str(x: String): StringLiteral = StringLiteral(x)
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRBuilder.scala:137]: Same comment then in the other PR to use this more widely :)

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:341]: I'm not sure I understand the question. Do you mean the decomposition between `testIncrementalSteps` and `testIncrementalSequence`? So suggesting to re-inline the behavior of `testIncrementalSequence` into `testIncrementalSteps`?

Comment (gzm0) [reply linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:341]: Yeah, that's what I meant. If we'll keep an iteration variable anyways, we might as well use it :)

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRBuilder.scala (hunk 5 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRBuilder.scala:137]: Since it's done in the other PR, I'll leave this one as is. I'll rebase this one once #4418 is merged, so this line will disappear from this commit.

**Comment by sjrd** [comment]
Updated.

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 6]
```diff
@@ -187,79 +187,207 @@ class IncrementalTest {
...
+    testIncrementalSteps("issue 4416 static variant", steps = 3, classDefs(_),
+        _ => MainTestModuleInitializers)
   }
 
 }
 
 object IncrementalTest {
 
-  def testIncremental(
+  type Input = (Seq[ClassDef], List[ModuleInitializer])
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:304]: This seems unused now.

**Review by gzm0 — APPROVED** [review]
Only a nit.

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala [hunk 7]
```diff
@@ -187,79 +187,207 @@ class IncrementalTest {
...
       classDefs: Boolean => Seq[ClassDef],
       moduleInitializers: Boolean => List[ModuleInitializer],
       config: StandardConfig = StandardConfig())(
       implicit ec: ExecutionContext): Future[Unit] = {
+
+    def testOneDirection(contextMessage: String, forward: Boolean): Future[Unit] = {
+      testIncrementalSteps(contextMessage, steps = 2,
+          step => classDefs(step == 0), step => moduleInitializers(step == 0),
+          config)
+    }
```
Comment (sjrd) [inline linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala:316]: Oops, this doesn't take the `forward` parameter into account.

File: linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala (hunk 6 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/IncrementalTest.scala]: Fixed.
