### PR TITLE
Fix #2474: Check conflicting top-level exports

### LINKED ISSUE #2474: 2+ top-level exports with the same name cause trouble at run-time
What works, exporting case class
~~~ scala
// Scala
package foo
@JSExport
case class Point(
  @(JSExport @field) x: Double,
  @(JSExport @field) y: Double)
~~~
~~~ javascript
// javascript
var p = foo.Point(1,2);
~~~

What also works, export factory methods in acc. object
~~~ scala
// Scala
package foo
@JSExport
class Point(
  @(JSExport @field) val x: Double,
  @(JSExport @field) val y: Double)

@JSExport
object Point {
  @JSExport
  def create(x: Double, y: Double): Point =  new Point(x, y)
}
~~~
~~~ javascript
// javascript
var p = foo.Point().create(1,2);
~~~

What doens't works, combining both:
~~~ scala
// Scala
@JSExport
case class Point(
  @(JSExport @field) val x: Double,
  @(JSExport @field) val y: Double)

@JSExport
object Point {
  @JSExport
  def create(x: Double, y: Double): Point = new Point(x, y)
}
~~~
~~~ javascript
// javascript
var p = foo.Point(1,2);
var p = foo.Point().create(1,2);  // ERROR: uncaught exception: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.Double
~~~
Calling `Point()` will iso creating the object `Point`, try to call the constructor (or factory method) of the case class `Point`, and thus miss the required arguments.

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala [hunk 1]
```diff
@@ -137,6 +137,9 @@ final class BaseLinker(semantics: Semantics, esLevel: ESLevel, considerPositions
       assemble(infoInput, getTree, analysis)
     }
 
+    // Make sure we don't export to the same name twice.
+    checkConflictingExports(linkResult, logger, bypassLinkingErrors)
+
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: A quick note in case you wonder: It would be nicest to do this in the analysis of course. However, we do not have the names we actually export something under in the Infos, so we can't.
This is maybe something we should consider for 1.0.0. Simply having an analyzer error would be much cleaner.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala [hunk 2]
```diff
@@ -61,6 +61,12 @@ final class LinkedClass(
   def encodedName: String = name.name
   def isExported: Boolean = classExports.nonEmpty
 
+  /** Names this class / module is exported under */
+  def exportNames: List[String] = classExports.collect {
+    case ConstructorExportDef(name, _, _) => name
+    case ModuleExportDef(name)            => name
+  }
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala]: There's also `JSClassExportDef`

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala (hunk 1 above)
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: Yes, I agree.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala [hunk 3]
```diff
@@ -61,6 +61,12 @@ final class LinkedClass(
   def encodedName: String = name.name
   def isExported: Boolean = classExports.nonEmpty
 
+  /** Names this class / module is exported under */
+  def exportNames: List[String] = classExports.collect {
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala]: Consider calling this `topLevelExportNames`. This makes it clear that instance methods exports are not included. It also suggests that we can reuse that when we support exporting top-level functions.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala [hunk 4]
```diff
@@ -434,4 +437,32 @@ final class BaseLinker(semantics: Semantics, esLevel: ESLevel, considerPositions
...
+      name -> classDef
+    }
+
+    val level = if (bypassLinkingErrors) Level.Warn else Level.Error
+    val errors = for {
+      (name, namesAndClasses) <- namesAndClasses.groupBy(_._1)
+      if namesAndClasses.size > 1
+    } yield {
+      logger.log(level, s"Conflicting top-level exports to $name:")
+      logger.log(level, s"The following classes/objects all export to $name:")
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: Those two lines of error message that repeat the essential information `$name` might confuse users as two separate errors. Consider simply adding "from the following classes:" at the end of the first message.

Not sure about this.

**Comment by sjrd** [comment]
That's all.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala (hunk 3 above)
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/LinkedClass.scala]: Good point.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala (hunk 4 above)
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: I though of it as well. Simplified.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala (hunk 1 above)
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/BaseLinker.scala]: #2528

**Comment by gzm0** [comment]
Updated

**Comment by gzm0** [comment]
I manually checked that this actually fails and reports the right classes.

**Comment by sjrd** [comment]
LGTM
