### PR TITLE
Fix #2751: Fix the definition of `js.Date` for invalid dates.

### LINKED ISSUE #2751: js.Date functions can return NaN, so they should be typed as Double
**Was: On Firefox, (some) js.Date functions can return -0, which cause CCEs**

Reproducible with `testSuite/testHtmlFastOpt` with Firefox. Also:
```scala
    import js.DynamicImplicits._

    val utc = java.util.Date.UTC(0, 0, 0, 0, 0, 0)
    val date = new js.Date(utc)

    println("getUTCDate = " + date.getUTCDate())
    println("getUTCMonth = " + date.getUTCMonth())
    println("getUTCFullYear = " + date.getUTCFullYear())

    val dyndate = date.asInstanceOf[js.Dynamic]
    val h = dyndate.getUTCHours()
    println(js.typeOf(h))
    println(h)
    println(1.0 / h)

    println("getUTCHours = " + date.getUTCHours())
    println("getUTCMinutes = " + date.getUTCMinutes())
    println("getUTCSeconds = " + date.getUTCSeconds())
```
gives:
```
getUTCDate = 31
getUTCMonth = 11
getUTCFullYear = 1899
number
0
-Infinity
uncaught exception: scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: 0 is not an instance of java.lang.Integer
```

### PR DESCRIPTION
**Pull request by sjrd**
For invalid dates, created from a string that cannot be parsed, the methods of `js.Date` return `NaN`. Therefore, they must be typed as `Double`s. By extension, this covers up for Firefox returning -0 for some valid date as well, instead of +0 like everyone else.

In the process, we fix the behavior of `j.u.Date.parse` for invalid inputs.

### CODE REVIEW

File: library/src/main/scala/scala/scalajs/js/Date.scala [hunk 1]
```diff
@@ -48,141 +48,144 @@ class Date extends js.Object {
    *
    * MDN
    */
-  def getFullYear(): Int = js.native
+  def getFullYear(): Double = js.native
```
Comment (gzm0) [inline library/src/main/scala/scala/scalajs/js/Date.scala]: I think the `js.Date` class deserves a general comment on why all the members here are typed as `Double`. IMO the MDN comment is *very* misleading: "that represents a single moment in time" is *not* the only thing it does (apparently). It can also represent an invalid time. We should document this.

Comment (sjrd) [reply library/src/main/scala/scala/scalajs/js/Date.scala]: Done.
