### PR TITLE
Fix #2401: Allow package objects to have non named native classes.

### LINKED ISSUE #2401: Allow native objects in package objects without @JSName
These two snippets are equivalent:

1:
```scala
package foo.bar

import scalajs.js

@js.native
object Ah extends js.Object
```

2:
```scala
package foo

import scalajs.js

package object bar {
  @js.native
  object Ah extends js.Object
}
```

Yet the second snippet fails compilation with
```
[error] ah.scala:7: Native JS objects inside non-native objects must have an @JSName annotation
[error]   object Ah extends js.Object
```

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeObjectInPackage.scala [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+import scala.scalajs.js.annotation.JSName
+
+package object jsNativeObjectInPackage {
+  @js.native
+  object Foo extends js.Object
+
+  @js.native
+  @JSName("Bar")
+  object Baz extends js.Object
+}
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeObjectInPackage.scala]: You don't seem to use `Foo` nor `Baz` in the tests.
Also, you should test classes.

File: test-suite/js/src/test/resources/ScalaJSDefinedTestNatives.js [hunk 2]
```diff
@@ -50,4 +50,6 @@
     }
   };
   $g.ConstructorDefaultParam = ConstructorDefaultParam;
+  $g.Foo = {};
+  $g.Bar = {};
```
Comment (sjrd) [inline test-suite/js/src/test/resources/ScalaJSDefinedTestNatives.js]: This enters JS' global scope. They should have longer names that won't clash with anything.

**Comment by sjrd** [comment]
That's all.

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSInteropTest.scala [hunk 3]
```diff
@@ -597,6 +597,21 @@ class JSInteropTest extends DirectTest with TestHelpers {
...
+    """.hasNoWarns
+
+    """
+    package object A {
+      @js.native
+      class B extends js.Object
+    }
+    """.hasNoWarns
+
     """
```
Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSInteropTest.scala]: You should add tests for `class`es here, too.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeInPackage.scala [hunk 4]
```diff
@@ -0,0 +1,70 @@
+package org.scalajs.testsuite.jsinterop
+
+import org.junit.Test
+import org.junit.Assert._
+
+import scala.scalajs.js
+import scala.scalajs.js.annotation.JSName
+
+package object jsNativeInPackage {
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeInPackage.scala]: Uh oh. I just realized this package object has the same name as the class below except for the case. This will make Windows go berserk.

You should rename the package object (and, btw, give it an all-lowercase name). I suggest `packageobjectwithnatives`.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeInPackage.scala [hunk 5]
```diff
@@ -0,0 +1,70 @@
...
+    assertEquals("foo", gJSNativeClassInPackageFoo.foo())
+    assertEquals("foo", new JSNativeClassInPackageFoo().foo())
+  }
+
+  @Test def testClassJSName(): Unit = {
+    val gJSNativeClassInPackageBarCtr = global.JSNativeClassInPackageBar
+    val gJSNativeClassInPackageBazCtr = global.JSNativeClassInPackageBaz
+    assertFalse(js.isUndefined(gJSNativeClassInPackageBarCtr))
+    assertTrue(js.isUndefined(gJSNativeClassInPackageBazCtr))
+
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/JSNativeInPackage.scala]: Another one:
```scala
assertSame(js.constructorOf[JSNativeClassInPackageBaz], gJSNativeClassInPackageBarCtr)
```

**Comment by sjrd** [comment]
That's all.

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSInteropTest.scala (hunk 3 above)
Comment (nicolasstucki) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSInteropTest.scala]: Isn't that the test for `class`:
```scala
package object A {
  @js.native
  class B extends js.Object
}
```

Or do you have another test in mind?

Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSInteropTest.scala]: Er no you're right. I was just being blind, I guess ^^

**Comment by sjrd** [comment]
LGTM
