### PR TITLE
Fix #1878: Make comparison between Int and Float work on Floats.

### LINKED ISSUE #1878: Comparing Int to Float should cast the Int to a Float
When comparing an `Int` and a `Float`, such as `x < y` with `x: Int` and `y: Float`, our compiler generates wrong code. It upcasts both `x` and `y` to `Double` and performs a `Double` comparison. In Scala/JVM, the `Int` is converted to a `Float` and then the comparison is on `Float`s.

This *can* cause different results, for example `(Int.MaxValue - 1) < Int.MaxValue.toFloat`. The JVM says `false`, but the current version of Scala.js says `true`.

### PR DESCRIPTION
**Pull request by sjrd**
Previously, such comparisons would work at the Double level,
contrary to their specification. This can cause discrepancies in
the rare cases where the imprecision of casting the Int to Float
makes it equal to the other operand.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0.

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala [hunk 1]
```diff
@@ -2469,44 +2469,57 @@ abstract class GenJSCode extends plugins.PluginComponent
...
+             * so we can first eliminate the Long case by converting to Double.
+             */
+            val notLong =
               if (kind == LongKind) js.UnaryOp(js.UnaryOp.LongToDouble, tree)
               else tree
 
-            if (resultType != jstpe.FloatType) fromLong
-            else if (kind == FloatKind) fromLong
-            else js.UnaryOp(js.UnaryOp.DoubleToFloat, fromLong)
+            if (opType != jstpe.FloatType) notLong
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Could we make this `opType == jstpe.DoubleType` instead? Seems easier to understand.

Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Argh... Of course we can't, since we might not be handling a double at all...

**Comment by gzm0** [comment]
LGTM
