### PR TITLE
Fix #1718: Validate the regex directly in Pattern.compile().

### LINKED ISSUE #1718: Pattern.compile doesn't validate regex
In Java/Scala, `Pattern.compile` fails immediately on invalid regex.
In ScalaJS, it isn't until the pattern is used that it fails.
```scala
// Doesn't throw in ScalaJS
val p = Pattern.compile("*")
```

To mimic JVM behaviour here (because I need to validate user-entered regex immediately), I just do this as a workaround:
```scala
// Throws an exception
p.matcher("").matches()
```

### PR DESCRIPTION
**Pull request by sjrd**
Since this requires the creation of a `js.RegExp` at the time `Pattern.compile()` is called anyway, we also store that native `RegExp` in the `Pattern` instance. `RegExp`'s for the `Matcher`s are created from that model `RegExp`, instead of from pattern and flags every time. This *might* be optimized in JS VMs to reuse the internally compiled representation for the regex.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
LGTM

**Comment by gzm0** [comment]
This changes the behavior of `flags()`. IIUC it should also return the in-pattern flags (see #997).

**Comment by gzm0** [comment]
Oh... I see.. No it's actually OK... But why on earth does `Pattern` have a `compile` method in the non-static context???

**Comment by sjrd** [comment]
Er ... `compile()` *is* in the companion object, so in a static context. 

And there's a test asserting that `flags` includes the ones mentioned in the pattern, so I could not have broken that. (I had checked.)

**Comment by gzm0** [comment]
> Er ... compile() is in the companion object, so in a static context.

I must have been drunk...

> And there's a test asserting that flags includes the ones mentioned in the pattern, so I could not have broken that. (I had checked.)

Yeah, I found the test later. It would have amazed me if I hadn't written a test for that when I introduced the flag hack :P

**Comment by sjrd** [comment]
Updated. I had to work around a bug in PhantomJS 1.x, see https://github.com/scala-js/scala-js/pull/1741/files#diff-180072e950a6b3db11ffd0d53d383c7fR22

File: javalib/src/main/scala/java/util/regex/Pattern.scala [hunk 1]
```diff
@@ -82,11 +85,33 @@ object Pattern {
...
+      }
+    }
+
+    val jsFlags = {
+      var f = "g"
+      if ((flags1 & CASE_INSENSITIVE) != 0)
+        f += "i"
+      if ((flags1 & MULTILINE) != 0)
+        f += "m"
+      f
```
Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: Should write it in the same format as above (without the `var`):
```scala
val jsFlags = {
  "g" +
  (if ((flags1 & CASE_INSENSITIVE) != 0) "i" else "") +
  (if ((flags1 & MULTILINE) != 0) "m" else "")
}
```

Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/regex/Pattern.scala]: Could also create a function that tests if the flag is on. Something that would be used like `containsFlag(flags1, CASE_INSENSITIVE)`. I see at least 3 places where it would be used.

**Comment by nicolasstucki** [comment]
Thats all. Otherwise LGTM

**Comment by sjrd** [comment]
Updated.

**Comment by nicolasstucki** [comment]
LGTM
