### PR TITLE
Fix #3228: Disable reflective instantiation for nested modules.

### LINKED ISSUE #3228: Linking error with an @EnableReflectiveInstantiation object inside a class
The following code causes a linking error:
```scala
class Foo {
  @EnableReflectiveInstantiation
  object Bar
}
```
The error is:
```
[error] Cannot access module for non-module helloworld.Foo$Bar$
[error]   called from helloworld.Foo$Bar$.<clinit>()
[error]   called from core module analyzer
```
This happens because, as a nested `object`, `Bar` is not really a module class, but the codegen for `@EnableReflectiveInstantiation` believes `Bar$` is a module class, producing the following erroneous IR:
```scala
class Lhelloworld_Foo$Bar$ extends O {
  def init___Lhelloworld_Foo($$outer: Lhelloworld_Foo) {
    this.O::init___()
  }
  static def clinit___() {
    mod:sjs_reflect_Reflect$.registerLoadableModuleClass__T__jl_Class__sjs_js_Function0__V("helloworld.Foo$Bar$", classOf[Lhelloworld_Foo$Bar$], (lambda<>() = {
      mod:Lhelloworld_Foo$Bar$
    }))
  }
}
```

### PR DESCRIPTION
**Pull request by sjrd**
We were using `sym.isModuleClass` to identify module classes when generating the reflective instantiation code, but that also matches nested objects. Now, nested objects are not compiled as module classes (only static objects are) because there is one instance per enclosing instance. This caused linking errors as soon as the codebase contained a nested object with `@EnableReflectiveInstantiation`.

Since non-static objects are not really *loadable* as per the API of `Reflect` (we would need a reference to the enclosing instance), we fix this issue by not registering non-static objects at all.

### CODE REVIEW

**Comment by sjrd** [comment]
Supersedes #3229.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/library/ReflectTest.scala [hunk 1]
```diff
@@ -307,4 +317,11 @@ object ReflectTest {
   }
 
   trait TraitDisable extends Accessors
+
+  // Regression cases
+
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/library/ReflectTest.scala]: Link to issue if you classify this as a regression case?

Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/library/ReflectTest.scala]: It's in the associated test method name, isn't it?

Comment (gzm0) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/library/ReflectTest.scala]: Indeed:-/
