### PR TITLE
Fix #1976: Fix Int and Long literals in ir.Printers

### LINKED ISSUE #1976: The IR printer does not print {Int|Long}Literal correctly

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

**Comment by sjrd** [comment]
LGTM

**Comment by gzm0** [comment]
Is it absolutely, 100% impossible to write a test for this? It seems we are running into printer issues a lot of times (i.e. more than we should) and simple regression unit tests could mitigate this.

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala [hunk 1]
```diff
@@ -681,10 +681,19 @@ object Printers {
...
+            print(')')
+          }
+
+        case LongLiteral(value) =>
+          if (value >= 0) {
+            print(value.toString)
+          } else {
+            print('(')
+            print(value.toString)
             print(')')
```
Comment (gzm0) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Maybe we should append an `L` here?

Comment (nicolasstucki) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Appending an `L` would append the value rather than the string representation. Couldn't it?

Comment (gzm0) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Oh, yes. Probably. I mean that the end result should show an "L". No matter how you achieve it :)
(probably just adding `print('L')` is easiest).
It might just be nice to see the distinction between an int literal and a long literal. Just like in the IR we also print things like `+[int]`.

Comment (nicolasstucki) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: In that case I would assume that we would also add them to floats and doubles. I believe that a change of representation like this should be in another commit.

Comment (gzm0) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Indeed. But we should maybe think about whether we should change it @sjrd?

Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Yes, we could add `f` to floats, `d` to doubles and `L` to longs. But indeed it should be in a different commit.

**Comment by nicolasstucki** [comment]
Then let me add a second commit to this PR.

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala (hunk 1 above)
Comment (nicolasstucki) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Then let me add a second commit to this PR.

**Comment by gzm0** [comment]
I think you meant "suffix".

**Comment by gzm0** [comment]
Otherwise LGTM

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala [hunk 2]
```diff
@@ -681,33 +681,43 @@ object Printers {
...
+            print(value.toString)
           } else {
             print('(')
-            print(value)
+            print(value.toString)
             print(')')
           }
 
+        case LongLiteral(value) =>
+          if (value < 0.0f)
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: `0L` or just `0`, but certainly not `0.0f` here ;)

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala [hunk 3]
```diff
@@ -681,33 +681,43 @@ object Printers {
...
+            print('(')
+          print(value.toString)
+          print('L')
+          if (value < 0.0f)
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: Same.

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala [hunk 4]
```diff
@@ -681,33 +681,43 @@ object Printers {
...
+            print(')')
+
         case FloatLiteral(value) =>
           if (value == 0.0f && 1.0f / value < 0.0f) {
             print("(-0)")
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: `(-0f)` with an `f` too.

File: ir/src/main/scala/org/scalajs/core/ir/Printers.scala [hunk 5]
```diff
@@ -681,33 +681,43 @@ object Printers {
...
             print(value.toString)
-            print(')')
+            print('f')
+            if (value < 0.0f)
+              print(')')
           }
 
         case DoubleLiteral(value) =>
           if (value == 0.0 && 1.0 / value < 0.0) {
             print("(-0)")
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Printers.scala]: `(-0d)` with a `d` too.

**Comment by sjrd** [comment]
That's all.

**Comment by sjrd** [comment]
LGTM
