### PR TITLE
Fix #4831: Correctly compare fieldDefs in KnowledgeGuardian.

### LINKED ISSUE #4831: emitter.KnowledgeGuardian incorrectly compares field defs
https://github.com/scala-js/scala-js/blob/54c9aa32a56a049d7bfb91ae935125c6a553ae71/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala#L313

As a result, field def askers always get invalidated if the fields do not have reference equality.

Discovered during #4824.

### PR DESCRIPTION
**Pull request by sjrd**
Previously, we compared the essentially compared the nodes for identity, which causes spurious invalidations in some cases.

We cannot completely compare them structurally, because the name of `JSFieldDef`s can be arbitrary `Tree`s, which we cannot efficiently compare. Therefore, we use an elaborate combination of the version of the class, a flag for whether there is any JS field, and the list of non-JS field names. See the comment for the new method `computeFieldDefsVersion` for details.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala [hunk 1]
```diff
@@ -353,6 +358,36 @@ private[emitter] final class KnowledgeGuardian(config: Emitter.Config) {
...
+     *  `Tree`s, which are not efficiently comparable.
+     */
+    private def computeFieldDefsVersion(linkedClass: LinkedClass): FieldDefsVersion = {
+      val hasAnyJSField = linkedClass.fields.exists(_.isInstanceOf[JSFieldDef])
+      val hasAnyJSFieldVersion = Version.fromInt(if (hasAnyJSField) 1 else 0)
+      val version = Version.combine(linkedClass.version, hasAnyJSFieldVersion)
+
+      val scalaFieldNames = linkedClass.fields.collect {
+        case FieldDef(_, FieldIdent(name), _, _) => name
+      }
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala:383]: Any reason we don't fold this into the overall version? Seems like:

- It would give simpler interface
- Wouldn't need custom code for comparison.
- Likely have a lower memory footprint (likely hardly matters TBH, but still).

We might need to add a `fromUTF8String` factory to `Version` for this, but that seems a like reasonable thing anyways.

**Review by gzm0 — CHANGES_REQUESTED** [review]
All-in-all I think I prefer this approach. WDYT? Just some implementation comments.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/KnowledgeGuardian.scala:380]: Ah indeed. It had not cross my mind, for some reason.

Updated.

**Review by gzm0 — APPROVED** [review]
