### PR TITLE
Fix #2998: Finish the new Linker API.

### LINKED ISSUE #2998: New Linker API
This is a summary extracted from the discussion in #2969, along with some small refinements I came up with while actually trying to implement that stuff.

## Goal

We want a new, simplified Linker API with one core "feature": a decomposition into 3 levels of API stability:

1. Super-stable API: always backward source and binary compatible across minor versions (except in the event of a catastrophic failure :P). It provides a reference point for people who "just want to link" their codebase, possibly with some configuration, but only configs that are meant to be supported "forever".
2. Stable-ish API: the API used by people who want to write their own linker plugins, or to compose some custom linkers, etc. It also exposes some less-stable configs. That API is supposed to stay backward source and binary compatible across minor releases unless maintaining compatibility would prevent progress. It should not be broken without a reasonably good reason.
3. Unstable, private-ish API: some things that we can freely break in minor releases, but that are technically *public* because they can be useful for some tools, e.g., the IR checker.

## Super-stable API, in `org.scalajs.core.tools.linker`

It is trimmed down to the bare minimum. The complete API surface looks like this:
```scala
abstract class Linker private[linker] () {
  def link(irFiles: Seq[VirtualScalaJSIRFile],
      moduleInitializers: Seq[ModuleInitializer],
      output: WritableVirtualJSFile, logger: Logger): Unit
}

final class ClearableLinker(newLinker: () => Linker) extends Linker {
  def link(...): Unit
  def clear(): Unit
}

class LinkingException(...) extends Exception

object StandardLinker {
  def apply(config: Config): Linker

  final class Config private () {
    val semantics: Semantics
    val moduleKind: ModuleKind
    
    val sourceMap: Boolean
    val parallel: Boolean
    ...
    private[linker] val outputMode: OutputMode

    def withSourceMap(sourceMap: Boolean): Config
    ...
    private[linker] def withOutputMode(outputMode: OutputMode): Config
  }

  object Config {
    def apply(semantics: Semantics, moduleKind: ModuleKind): Config
  }
}

final class Semantics private () { ... }
object Semantics { ... }

abstract class ModuleKind private[linker] () { ... }
object ModuleKind { ... }
```
Some things to note:
* There is no `class StandardLinker`. That's a stable-ish API.
* `OutputMode` is `private[linker]` and will only be accessible/configurable through a stable-ish API (see below). The rationale is that it is tight to our current standard linker backend and emitter. But in practice we know it's not something we want to support for a very long time (we destroyed 3 `OutputMode`s already in our history!).
* The `Semantics` and `ModuleKind` configs receive official, stable default values (`Semantics.Defaults` and `ModuleKind.NoModule`). These configs are the ones that semantically define how the code behaves a) internally (`Semantics`) and b) externally (`ModuleKind`).
* Speaking of which, `Semantics` and `ModuleKind` are acquired by the `linker` package, instead of `sem` and `backend` respectively.
* `GenLinker` has basically become `Linker`. The old `Linker` does not exist in the super-stable API.
* `Linker` is an `abstract class` with a package-private constructor, so that we can hope to add additional methods in a binary compatible way. This would be necessary for an API that can generate *multiple* JS files in the future, for example.
* `ModuleKind` is not `sealed` in the super-stable API, because we will have to add new `ModuleKind`s in the future. It should be `sealed` "from the inside" so that we get exhaustivity warnings, but the best way to achieve that is unclear at this point. There is an idea in https://github.com/scala-js/scala-js/pull/2969#issuecomment-306689887.
* `ESLevel` is gone.

## Stable-ish API in `org.scalajs.core.tools.linker.standard`

This is the "standard" linker, which constitutes the stable-ish API. It is decomposed in a front-end and a back-end. The back-end has an `OutputMode`.

```scala
final class StandardLinker(frontend, backend) extends Linker { ... }

object StandardLinker {
  type Config = linker.StandardConfig.Config
}

type OutputMode = LinkerBackend.OutputMode
val OutputMode = LinkerBackend.OutputMode

implicit class StandardLinkerConfigStandardOps(
    val __self: StandardLinker.Config) extends AnyVal {
  def outputMode: OutputMode

  def withOutputMode(outputMode: OutputMode): StandardLinker.Config
}

abstract class LinkerFrontend {
  def link(irFiles: Seq[VirtualScalaJSIRFile],
      moduleInitializers: Seq[ModuleInitializer],
      symbolRequirements: SymbolRequirement, logger: Logger): LinkingUnit
}

object LinkerFrontend {
  final class Config private () { ... }
  object Config { ... }
}

abstract class LinkerBackend {
  def emit(unit: LinkingUnit, output: WritableVirtualJSFile, logger: Logger): Unit
}

object LinkerBackend {
  sealed abstract class OutputMode
  object OutputMode { ... }

  final class Config private () { ... }
  object Config { ... }
}

final class LinkingUnit { ... }

sealed abstract class SymbolRequirement
object SymbolRequirement { ... }
```
Notes:
* In the `standard._` subpackage, the decomposition front-end/back-end is standard and supported
* The `LinkingUnit` abstraction is standard and supported
* The `OutputMode` data type is exposed
* There are some additional operations on `StandardLinker.Config` available through an implicit class

## Unstable, private-ish API

Everything else. This includes the analyzer, IR checker, optimizer, the actual implementations of `LinkerFrontend` and `LinkerBackend` (including the `BaseLinker`, `Refiner` and `Emitter`).

## Path to get there

In 0.6.x: simply *add* enough of the super-stable API and stable-ish API so that simple linker usage (such as done in the CLI or the sbt plugin) can be written in a source-compatible way between 0.6.x and 1.x. This means

* `linker.StandardLinker._`
* `linker.{ModuleKind, Semantics}` (as aliases to `backend.ModuleKind` and `sem.Semantics`, resp.)
* `linker.standard.OutputMode`
* `linker.standard.StandardLinkerConfigStandardOps`

We also deprecate the parts of the existing old API that can directly be replaced by the above parts, i.e., `Linker.apply`.

We don't touch anything else in 0.6.x. In particular, we make no attempt to revisit/deprecate the front-end/back-end and their `Config`s.

In 1.x, we simply nuke everything and put the new API in place.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/standard/StandardLinkerImpl.scala [hunk 1]
```diff
@@ -16,15 +16,16 @@ import java.util.concurrent.atomic.AtomicBoolean
...
 import org.scalajs.linker.frontend.LinkerFrontend
 import org.scalajs.linker.frontend.optimizer.IncOptimizer
 import org.scalajs.linker.backend.{LinkerBackend, BasicLinkerBackend}
 import org.scalajs.linker.irio._
 
-/** The Scala.js linker */
-final class Linker private (frontend: LinkerFrontend, backend: LinkerBackend)
+/** Standard implementation of a Scala.js linker. */
+private[standard] final class StandardLinkerImpl private (
+    frontend: LinkerFrontend, backend: LinkerBackend)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/standard/StandardLinkerImpl.scala]: Can't you make this `private`? The companion should still see it, no?

File: linker/shared/src/main/scala/org/scalajs/linker/Linker.scala [hunk 2]
```diff
@@ -20,7 +20,7 @@ import org.scalajs.linker.irio._
  *  module initializers, link them together, and write the output to a writable
  *  .js file.
  */
-trait GenLinker {
+abstract class Linker {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/Linker.scala]: The constructor here should be private so that we can add abstract methods in minor versions.

File: linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala [hunk 3]
```diff
@@ -66,7 +66,37 @@ final class LinkedClass(
...
+      staticMethods: List[Versioned[MethodDef]],
+      memberMethods: List[Versioned[MethodDef]]
+  ): LinkedClass = {
+    copy(
+        staticMethods = staticMethods,
+        memberMethods = memberMethods
+    )
+  }
+
+  private def copy(
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala]: I'm OK with this change in principle, but I'm not sure we're on the same page here: We should be allowed to change `LinkingUnit` in a binary incompatible fashion in a minor version. So this is not a major concern (if it were, `ir.Trees` would be in a much worse position).

File: linker/shared/src/main/scala/org/scalajs/linker/standard/StandardLinkerImpl.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/standard/StandardLinkerImpl.scala]: Indeed. Probably came from a transient state.

File: linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala (hunk 3 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/standard/LinkedClass.scala]: We should be *allowed* to break it in a minor version (not a patch version), but we should *try* not to, as much as possible, in order to break (future) linker plugins.

That's the point of `standard.*` versus the rest: for the rest, we don't care. For `standard`, we try not to break stuff as long as we can avoid it, to preserve the ecosystem of linker plugins.

File: linker/shared/src/main/scala/org/scalajs/linker/Linker.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/Linker.scala]: Right, that's indeed what we designed in #2998. But eventually we should be allowed to open this up. We might want to allow users to write their own `Linker` (which would probably wrap an existing standard linker, not reimplement everything). For example that's what I had done in https://github.com/sjrd/scalajs-reflect.

**Comment by sjrd** [comment]
> I'm not sure the commit "Introduce abstract LinkerFrontend and LinkerBackend in standard.*." is necessary. All subpackages of linker except for irio should have the same compatibility guarantees than standard. Therefore, it is completely fine if they refer to each other.

In #2998 we had defined `standard.*` as the "stable-ish" API: something that should stay backward compatible as long as possible, but with allowed breakages:

> That API is supposed to stay backward source and binary compatible across minor releases unless maintaining compatibility would prevent progress. It should not be broken without a reasonably good reason.

Unlike `standard.*`, the other packages besides `linker.*` and `irio.*` are truly unstable, and can break any time without second thought. So `standard.*` does have strong compatibility rules, if not strict *guarantees*, and IMO that's enough not to refer to unstable stuff from the standard stuff.

Btw, the abstract `LinkerFrontend` and `LinkerBackend` were part of the plan laid out in #2998.

> `ClearableLinker` needs to consolidate the batch flag with `StandardLinker.Config` somehow. We can file this as a follow up, or do it in this PR.

We don't want `ClearableLinker` to depend on a whole `StandardLinker.Config`. We should be able to use `ClearableLinker` with non-standard `Linker`s, whose config might be completely different. I'm not sure what we could even change in `ClearableLinker`.

The only thing that comes to mind would be to introduce `StandardLinker.clearable(config: StandardLinker.Config): ClearableLinker`, which would wrap a `StandardLinker(config)` inside a `new ClearableLinker(_, config.batchMode)`.

> sealed on `ModuleIntializer` and `Semantics.RuntimeClassNameMapper` is odd, since all subclasses are private. Note that we explicitly do not give the guarantee that we will never add subclasses.

I'm not sure it's that weird. We have admittedly worse abuses of `sealed` in `js.*` itself: https://github.com/scala-js/scala-js/blob/bad76528021ee7489171e53fc36b4dff5a6b04a4/library/src/main/scala/scala/scalajs/js/UnicodeNormalizationForm.scala#L24. It would be quite annoying while writing the code inside the linker if they weren't sealed, as we wouldn't get the exhaustivity warnings. It's not a big deal for those two, though, as they're not deconstructed very often

> `linker.ModuleKind` is sealed, it shouldn't be.

Meh ... I wouldn't like that one not to be sealed. I can't count all the times I've followed the exhaustivity warnings about `ModuleKind` in the `emitter.*`. But I guess we don't really have a choice.

**Comment by sjrd** [comment]
Updated with:
* `private[linker]` constructor for `Linker`
* `private class StandardLinkerImpl`
* Unseal `ModuleKind` and `OutputMode`

I haven't unsealed `ModuleInitializer` nor `RuntimeClassNameMapper`. IMO it is perfectly fine to have a sealed class in public API, whose cases are not visible in the public API. There is no way for user code ever match on these things without exhaustivity warnings to begin with, so we can always add more cases. In fact, it could even considered the design pattern to follow for write-only data structures.

An alternative would be to use the following pattern:
```scala
abstract class ModuleInitializer private () {
  this: ModuleInitializer.ModuleInitializerImpl =>

  import ModuleInitializer._

  private[linker] def toImpl: ModuleInitializerImpl = this
}

/** Factory for [[ModuleInitializer]]s. */
object ModuleInitializer {
  private[linker] sealed abstract class ModuleInitializerImpl
      extends ModuleInitializer

  private[linker] final case class VoidMainMethod(moduleClassName: String,
      encodedMainMethodName: String)
      extends ModuleInitializerImpl

  private[linker] final case class MainMethodWithArgs(moduleClassName: String,
      encodedMainMethodName: String, args: List[String])
      extends ModuleInitializerImpl
}
```
but then the self type leaks to the public API (it is shown in the Scaladoc), even though it references a class that is not part of the public API.

I also haven't changed `ClearableLinker`, as it's not clear what, if anything, needs to done about it.

Do not merge, as #3277 should go in first.

**Comment by gzm0** [comment]
> In #2998 we had defined standard.* as the "stable-ish" API: something that should stay backward compatible as long as possible, but with allowed breakages:

Ah, I see how you meant this now. You essentially wanted these levels:

1. Stable
2. Stable-ish
3. Unstable
4. Private

I thought we'll only have:

1. Stable
2. Stable-ish
3. Private

While I'm fine with having more levels of compatibility guarantee, I don't think we're drawing the line at the right point: Taking a users perspective, we should answer the question: "What can you do with an API level".

Use cases I can think of from the top of my head:

- Use the linker: super stable API
- Use another output mode: stable-ish API
- Modify the linker (plugin, reporting plugin, etc): stable-ish API? With the current setup, you cannot really do this with the stable-ish API, because you would have to write your own Frontend and Backend, which nobody will.

Bottom-line being: We should either:
- Include a way to create the frontends and backends in the stable-ish API (and add IR etc. to stable-ish), or
- Remove everything except OutputMode from stable-ish.

> The only thing that comes to mind would be to introduce StandardLinker.clearable(config: StandardLinker.Config): ClearableLinker, which would wrap a StandardLinker(config) inside a new ClearableLinker(_, config.batchMode).

Yeah, that sounds reasonable. We can then make `ClearableLinker` abstract and move the implementation to `standard.WrappingClearableLinker` (or something the like)?

About `sealed`:
- I'm OK with keeping sealed for the types that only have private cases.
- For `ModuleKind`, I thought we agreed to make a subclass of `ModuleKind` in `standard._` which is sealed (and convertible to from the base by a private abstract member). Then a user (including our code) can chose against which API they want to build.

We should apply a similar strategy for `Linker`: `linker.Linker` should have a `private[linker]` constructor. However, we should have `linker.standard.Linker` (or similar) that extends `linker.Linker` and *is* open for inheritance. Again making it explicit against which API guarantee level something is written against.

**Comment by sjrd** [comment]
At the highest level, the way I see things is to specify things in terms of guarantees against breakage. Concretely,
* Breaking `linker._` or `irio._` requires a major version bump (basically, it's forbidden)
* Breaking `standard._` or `ir._` requires a minor version bump, and should be avoided if possible
* Breaking something else (the unstable parts) can happen in a patch version, although it should be avoided if it is easy to do so (deprecated forwarders, for example)
* `private[linker]` (or stronger) cannot be accessed anyway, so any breakage is allowed any time

The idea is that `standard._` and `ir._` should (eventually) be enough for someone who wants to write a linker plugin. *Currently*, it requires to write a "complete" front-end or back-end, but that *can* actually be practical if the front-end wraps an existing front-end, and just preprocesses or postprocesses the input/output. It is also enough to work around the disappearance of `linkUnit` in some very special use cases for it, for example, a plugin that reports a graph of dependencies in a `LinkedUnit`.

Something built on top of `standard._` and `ir._` would have a guarantee of working through patch versions, and some hope not to be broken at each minor version.

The unstable APIs are for things that can reasonably be used by "experiments", but said experiments should expect to only work for one specific patch release.

> Remove everything except OutputMode from stable-ish.

Or move `OutputMode` up inside `linker._`. That would mean we can never remove any of its alternatives, though.

**Comment by gzm0** [comment]
> Currently, it requires to write a "complete" front-end or back-end, but that can actually be practical if the front-end wraps an existing front-end, and just preprocesses or postprocesses the input/output.

Yes, indeed. However, in the current setup, IIUC, it is impossible to create a standalone frontend or backend with the stable-ish API (or retrieve it from a StandardLinker). So one cannot write a complete linker without depending on the unstable API or really writing a complete linker. I would argue that the second one is unlikely to happen (at least anytime soon), so we should move "writing a new linker" and "creating a standard frontend/backend" in the same compatibility domain (I'm fine with either stable-ish or unstable, although past experience suggests that this is actually something users want to do, so stable-ish?).

> Or move OutputMode up inside linker._. That would mean we can never remove any of its alternatives, though.

I wouldn't do that. The maintenance burden we risk is just too high.

**Comment by sjrd** [comment]
Rebased after the `OutputMode` -> `ESFeatures` refactoring, which somewhat changes the game.

Now `standard._` only contains stuff that I would later consider relevant when building linker plugins. Even though currently, the `standard` API is not enough to build anything meaningful, I think everything it contains would be part of the things necessary to build something meaningful.

Maybe one reasonable thing we could do to make the current `standard` API practical would be to add `standard.StandardFrontend` and `standard.StandardBackend` objects with a `def apply(config: StandardLinker.Config): ...`. That would then be enough to build a custom linker that has a front-end and/or a back-end that wraps a `StandardFrontend`/`StandardBackend` with some pre- or post-processing, which addresses all the use cases we know to exist so far.

File: linker/shared/src/main/scala/org/scalajs/linker/StandardLinker.scala [hunk 4]
```diff
@@ -46,6 +46,9 @@ object StandardLinker {
         LinkerBackendImpl(backendConfig))
   }
 
+  def clearable(config: Config): ClearableLinker =
+    new ClearableLinker(() => apply(config), config.batchMode)
+
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/StandardLinker.scala]: In that case, shouldn't we make the constructor of `ClearableLinker` private[linker]? IIUC the idea here was that they can share a config.

Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/StandardLinker.scala]: If we do that, there's no way to create a `ClearableLinker` wrapping a non-standard linker, is there?

Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/StandardLinker.scala]: Ah, indeed, we should allow this. Although wondering if it should be part of the super stable API :S

Maybe we should move the implementation of `ClearableLinker` to `standard._` as well and just have an abstract class in `linker`?

Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/StandardLinker.scala]: `ClearableLinker` only relies on a `() => Linker` function to create its linker, so only super-stable stuff. If we move it to `standard._`, and some API receives a `() => Linker`, it could not make a `ClearableLinker` out of it without relying on non-super-stable API.

For example, an alternative build plugin could be configured with a `() => Linker` rather than directly with a `ClearableLinker`. That build plugin might want to wrap that `() => Linker` inside a `ClearableLinker`, but to do that it would have to rely on `standard._` (currently sbt-scalajs only uses `linker._`).

Maybe we could make the constructor `private` and add an `apply` method in `ClearableLinker`'s companion object instead of exposing the constructor. And even make `ClearableLinker` a `trait`, that simply inherits from `Linker` and adds an abstract `def clear(): Unit`. The companion's `apply` would return an instance of a private class implementing that trait.

**Comment by sjrd** [comment]
Rebased and updated with the `ClearableLinker.apply` and `StandardLinker{Frontend,Backend}.apply` I was suggesting above.
