### PR TITLE
Fix #4593: Track askers of hasElidableModuleAccessor

### LINKED ISSUE #4593: Optimizer does not invalidate users of hasElidableModuleAccessor
How to reproduce:

```scala
object M {
  // remove comment later
  //println(1)
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    // Just something complicated so that the main method does not get inlined into its static forwarder.
    (1 to 100).map(_ + 1).foldLeft(0)(_ + _)
    M
  }
}
```

Then:

1. Run (no output, as expected)
2. Uncomment the `println(1)`
3. Run (no output, expected 1)
4. Clean
5. Run (`1` is printed)

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala [hunk 1]
```diff
@@ -348,15 +350,17 @@ final class IncOptimizer private[optimizer] (config: CommonPhaseConfig, collOps:
...
-    var interfaces: Set[InterfaceType] = Set.empty
+    var interfaces: Set[InterfaceType] = linkedClass.ancestors.map(getInterface).toSet
     var subclasses: collOps.ParIterable[Class] = collOps.emptyParIterable
-    var isInstantiated: Boolean = false
+    var isInstantiated: Boolean = linkedClass.hasInstances
 
     var hasElidableModuleAccessor: Boolean = false
 
-    var fields: List[AnyFieldDef] = Nil
+    var fields: List[AnyFieldDef] = linkedClass.fields
```
Comment (sjrd) [inline linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala:354]: The previous `setupAfterCreation` did not set `fields`. Is it intentional that, in this refactoring, we now set `fields` anyway? If yes, why? If not, should it stay `Nil` (at least in this commit)? Should it be in the next commit instead?

**Review by sjrd — CHANGES_REQUESTED** [review]

File: linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala (hunk 1 above)
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala:354]: I was concerned about initialization order: In this commit `MethodContainer#updateWith` will try to set `fields` during construction.

Probably I should simply invert this commit and the "update field in walkForChanges". That will be cleaner.

Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/frontend/optimizer/IncOptimizer.scala:354]: That, or initialize it with `= _`, which will make sure that there is no initialization code in this constructor that will override what `updateWith` already set before.

**Review by sjrd — APPROVED** [review]
