### PR TITLE
Fix #5064: Add `js.async { ... js.await(p) ... }`, and support JSPI on WebAssembly.

### LINKED ISSUE #5064: Wasm: Language feature for the JavaScript Promise Integration proposal (JSPI)
## Motivation

The [JavaScript Promise Integration proposal (JSPI)](https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md) for WebAssembly adds a superpower to WebAssembly, compared to JavaScript. It allows Wasm code to perform *synchronous* calls to `Promise`-returning JS functions, and *suspend* when the `Promise` is not resolved yet. This is a power basically equivalent to Virtual Threads (aka green threads, coroutines, etc.), something that is *not possible* to implement with JavaScript alone. Basically a non-blocking `await(promise)` function.

I successfully leveraged JSPI with Scala.js-on-Wasm in a hobby project to dramatically simplify the internal API :
https://github.com/sjrd/funlabyrinthe-scala/commit/18bc1f2b93e6e235087cbbd17bd344d055b6f32f
However, to achieve it, I had to textually post-process the `main.js` file generated by Scala.js, hacking and slashing its abstractions to build my own. I used my internal knowledge of how the linker generates code to do this. This is not something we're supposed to do, obviously, and it will likely break when I next uprade Scala.js.

It would be nice to have dedicated language support to leverage JSPI from Scala.js code.

## Proposal

There are two sides to JSPI : importing a `WebAssembly.Suspending` function, and wrapping an export into a `WebAssembly.promising` call.

### Promising Exports

We need a way to express that an exported `def` must be wrapped in a `WebAssembly.promising` call. Note that the Wasm function `f`itself must be given to `promising(f)`. Currently Scala.js wraps every exported function in a JavaScript-defined `function` to protect its abstractions. This is why we cannot currently call `promising` in user-space.

I propose a distinct `@JSExportPromising` annotation, to be used like `@JSExportTopLevel` on `def`s:
```scala
object Container {
  @JSExportPromising("name", "module.js")
  def myPromisingMethod(x: Int, y: String): String = ???
}
```
As seen from JavaScript, it would return a `js.Promise[String]`, following the API transformation applied by `WebAssembly.promising`.

### Suspending Imports

On the other side, we need a way to express that we *import* a JS function as wrapped into a `new WebAssembly.Suspending(f)` constructor. Here as well, the resulting `Suspending` instance must be directly `import`ed into Wasm. Since Scala.js generates custom arrow functions for all imports to protect its abstractions, once again this cannot be achieved in user-space.

I see two possibilities here.

The first one is simpler from the Scala.js language specification point of view. The second one is closer to the JSPI API design.

First option: offer a single primitive `await`:
```scala
def await[A](p: js.Promise[A]): A = throw new Error("stub")
```
This can be implemented as a unique JS helper of the form
```js
"await": new WebAssembly.Suspending((x) => x),
```
When calling any JS function that returns a `js.Promise` in its API, we can follow up with a call to this primitive to exploit JSPI and give us the result.

Second option: offer a generic `@JSImportSuspending` annotation for `@js.native def`s:
```scala
@js.native
@JSImportSuspending("readFile", "node:fs")
def readFile(f: String, charset: String): String = js.native
```
This is closer to the spirit of the JSPI API design, but it means we also need an `@JSGlobalSuspending`, a variant with a `globalFallback`, etc.

## Implementation concerns

On the call path between a promising export and a suspending import call, there cannot be any JavaScript frame. This cannot reasonably be checked statically nor dynamically. However, it will be checked by the engine at run-time, which will `trap` if the condition is not upheld. There is currently [no way to test ahead of time](https://github.com/WebAssembly/js-promise-integration/issues/29), and since a `trap` is not catchable from Wasm, we cannot recover from that. That is quite annoying, since otherwise in `fastLinkJS` our linker guarantees that the code it generates never traps. For example, even a testing framework would have no way of catching this condition; it will crash instead.

## Design concerns

This feature is unique to the *combination* of JavaScript and Wasm. JS alone cannot do it, nor can Wasm alone. Therefore, this feature would be unique to Scala.js-on-Wasm! Given the current experimental status of our Wasm backend, it's not something we can really do today. However, it gives such a new superpower that I believe we should already start considering how we could offer that superpower to our users.

### PR DESCRIPTION
**Pull request by sjrd**
We introduce a new pair of primitive methods, `js.async` and `js.await`. They correspond to JavaScript `async` functions and `await` expressions.

`js.await(p)` awaits a `Promise`, but it must be directly scoped within a `js.async { ... }` block.

---

At the IR level, `js.await(p)` directly translates to a dedicated IR node `JSAwait(arg)`. `js.async` blocks don't have a direct representation. Instead, the IR models `async function`s and `async =>`functions, as `Closure`s with an additionnal `async` flag. This corresponds to the JavaScript model for `async/await`.

A `js.async { body }` block therefore corresponds to an immediately-applied `async Closure`, which in JavaScript would be written as `(async () => body)()`.

---

On the JavaScript platform, async `Closure`s and `JSAwait` are directly compiled as their JavaScript equivalent.

On WebAssembly, we leverage the JavaScript Promise Integration feature (JSPI). We turn async `Closure`s into `WebAssembly.promising` functions. `js.await(p)` is compiled as a call to a unique `jsAwait` helper, which is declared as an "identity" `new WebAssembly.Suspending((x) => x)`. The static scoping rule of `js.await` guarantees that the suspending call is always performed in a valid context (one that will not throw a `WebAssembly.SuspendError`).

---

We then optionally allow orphan `js.await(p)` on WebAssembly.

With the JavaScript Promise Integration (JSPI), there can be as many frames as we want between a `WebAssembly.promising` function and the corresponding `WebAssembly.Suspending` calls. The former is introduced by our `js.async` blocks, and the latter by calls to `js.await`.

Normally, `js.await` must be directly enclosed within a `js.async` block. This ensures that it can be compiled to a JavaScript `async` function and `await` expression.

~~We introduce a compiler option to allow "orphan awaits". This way, we can decouple the `js.await` calls from their `js.async` blocks. The generated IR will then only link when targeting WebAssembly.~~
We introduce a sort of "language import" to allow "orphan awaits". This way, we can decouple the `js.await` calls from their `js.async` blocks. The generated IR will then only link when targeting WebAssembly. Technically, `js.await` requires an implicit `js.AwaitPermit`. The default one only allows `js.await` directly inside `js.async`, and we can import a stronger one that allows orphan awaits.

There must still be a `js.async` block *dynamically* enclosing any `js.await` call (on the call stack), without intervening JS frame. If that dynamic property is not satisfied, a `WebAssembly.SuspendError` gets thrown. This last point is not yet implemented in Node.js at the time of this commit; instead such a situation traps. The corresponding test is therefore currently ignored.

### CODE REVIEW

File: linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureAstTransformer.scala [hunk 1]
```diff
@@ -348,6 +348,12 @@ private class ClosureAstTransformer(featureSet: FeatureSet,
         new Node(Token.DELPROP, transformExpr(prop))
       case UnaryOp(op, lhs) =>
         mkUnaryOp(op, transformExpr(lhs))
+      case Await(arg) =>
+        new Node(Token.AWAIT, transformExpr(arg))
+      case Yield(arg, star) =>
+        val node = new Node(Token.YIELD, transformExpr(arg))
```
Comment (gzm0) [inline linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/ClosureAstTransformer.scala:354]: Unrelated to this PR?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Printers.scala [hunk 2]
```diff
@@ -441,6 +441,15 @@ object Printers {
           print(')')
           printSeparatorIfStat()
 
+        case Yield(expr, star) =>
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Printers.scala:444]: Unrelated to this PR?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Trees.scala [hunk 3]
```diff
@@ -374,6 +375,9 @@ object Trees {
 
   sealed case class Await(expr: Tree)(implicit val pos: Position) extends Tree
 
+  sealed case class Yield(expr: Tree, star: Boolean)(implicit val pos: Position)
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/javascript/Trees.scala:378]: Unrelated?

**Review by gzm0 — COMMENTED** [review]
I've done an initial pass, this looks really cool.

Overall design looks reasonable and simple enough.

Questions I have:
- Have you considered flagging orphans statically in the compilation stage already? (No idea if that ends up better, just a thought I had, current proposal doesn't look too terrible either).
- Are you confident we can eliminate top level async IIFEs in the emission stage (at a later point in time)? (IIUC, for both backbends they lead to unnecessary nesting ATM, the top level function could be async itself)

**Comment by gzm0** [comment]
Oh, sorry, my last comment wasn't clear: I have not looked at the code in detail yet, just the overall structure. I will follow up with a thorough review.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/LoaderContent.scala [hunk 4]
```diff
@@ -157,6 +157,13 @@ const scalaJSHelpers = {
   jsNewNoArg: (constr) => new constr(),
   jsImportCall: (s) => import(s),
   jsImportMeta: () => import.meta,
+  jsAwait: (WebAssembly.Suspending ? new WebAssembly.Suspending((x) => x) : ((x) => {
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/LoaderContent.scala:160]: Can we do this statically based on linking info rather than auto-detect?

- Less runtime magic
- Less code
- More eager failure

**Review by gzm0 — CHANGES_REQUESTED** [review]
Nice! This is cool. A pity we cannot use it for the html test runner :-/

File: library/src/main/scala/scala/scalajs/js/package.scala [hunk 5]
```diff
@@ -158,4 +158,64 @@ package object js {
...
+   *  <h2>Orphan `await`s in WebAssembly</h2>
+   *
+   *  When compiling for Scala.js-on-Wasm only, you can allow calls to
+   *  `js.await` anywhere, using the compiler option
+   *  `-P:scalajs:allowOrphanJSAwait`.
+   *
+   *  Calls to orphan `js.await`s are validated at run-time. There must exist
+   *  a dynamically enclosing `js.async { ... }` block on the call stack.
+   *  Moreover, there cannot be any JavaScript frame (function invocation) in
+   *  the call stack between the `js.async { ... }` block and the call to
```
Comment (tanishiking) [inline library/src/main/scala/scala/scalajs/js/package.scala:205]: Just out of curiosity, I believe this restriction comes from the JSPI specification https://github.com/WebAssembly/js-promise-integration/blob/main/proposals/js-promise-integration/Overview.md#restriction

Does this happen, for example, the invocation chain is something like:

- `A` wrapped by `WebAssembly.promising` →
- (non-suspending) JS function `B` →
- Wasm function `C`→ 
- suspending JS function `D`

?

Comment (sjrd) [reply library/src/main/scala/scala/scalajs/js/package.scala:205]: Yes, that is exactly the kind of invocation chain that is restricted by JSPI.

File: compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala [hunk 6]
```diff
@@ -43,6 +43,9 @@ trait ScalaJSOptions {
    *  See the warning itself or #4129 for context.
    */
   def warnGlobalExecutionContext: Boolean
+
+  /** Whether to tolerate orphan `js.await` calls for WebAssembly's JSPI. */
+  def allowOrphanJSAwait: Boolean
```
[the remark this answers is not in the document]
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala:48]: I don't think we have the *ability* to make something like a language import in a compiler plugin.

`import`s get removed very early in the compiler pipeline. We still see them at the `jsinterop` phase, but not later. We would have to record during that phase which `js.await` is allowed to be orphan, in a way that we can check in the backend. It's possible with a custom `scalajs.runtime` method, but it's a significant investment for something like that.

Also analyses for unused imports will not understand our magic import, so they will systematically report that import as unused.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/LoaderContent.scala (hunk 4 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/LoaderContent.scala:160]: We would have to add that information in the `Analysis`. Currently it doesn't have it.

My idea here was rather that eventually we'll remove the fallback altogether. JSPI will become part of standard Wasm-on-JS, so every JS host will have `WebAssembly.Suspending`. So spending extra effort to track something we eventually won't use at all is probably not worth it.

File: compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala (hunk 6 above)
[the remark this answers is not in the document]
Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala:48]: Yeah, I see. That seems too much effort.

Have you considered two different await methods, only one of them allowed in orphan position? Maybe, with some smart import organization, we could essentially have something like a language import, just with import shadowing. The `js` prefix makes this a bit tricky :-/ (implementing it in the compiler would be trivial though).

An alternative would be to have an implicit param `orphanMode` to `js.await` that defaults to `disallow` via low-prio implicit. However, then users could technically pass that type/value around, which we do not want.

**Review by gzm0 — CHANGES_REQUESTED** [review]
I'm still uneasy about the compiler flag. I've added some alternative suggestions.

It feels we're making it unergonomic for users to deal with code that needs orphans if we require a compiler flag for this.

File: compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala (hunk 6 above)
[the remark this answers is not in the document]
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/ScalaJSOptions.scala]: I added a commit (to be squashed if accepted) that uses the `implicit` trick to look like a language import. I'm not concerned about the fact that the value can be passed around. It allows global behavior, so moving passing it around is fine.

It would be a concern if we used the `AwaitPermit` to allow *non* orphan awaits in the first place, by giving having `js.await` synthesize an implicit permit given to its closure. But that would not be nearly good enough, since it could be captured and hence not reflect the directly enclosing requirement.

File: library/src/main/scala/scala/scalajs/js/package.scala [hunk 7]
```diff
@@ -192,6 +192,22 @@ package object js {
...
+   *  When compiling for Scala.js-on-Wasm only, you can allow calls to
+   *  `js.await` anywhere, by adding the following import:
+   *
+   *  {{{
+   *  import scala.scalajs.js.wasm.JSPI.allowOrphanJSAwait
+   *  }}}
+   *
+   *  Calls to orphan `js.await`s are validated at run-time. There must exist
+   *  a dynamically enclosing `js.async { ... }` block on the call stack.
+   *  Moreover, there cannot be any JavaScript frame (function invocation) in
```
Comment (gzm0) [inline library/src/main/scala/scala/scalajs/js/package.scala:207]:
```suggestion
   *  Moreover, there cannot be any JavaScript frame (JavaScript function invocation) in
```

Just saw this. Otherwise, one might interpret "JavaScript frame" = "function invocation" which is wrong (and would make the feature useless).

**Review by gzm0 — APPROVED** [review]
IMHO the proposed commit provides a better user interface. The changes to the library are bit more extensive, but IMO acceptable.

@sjrd if you agree with that sentiment, I feel we should go forward with the "language import" version.

**Comment by sjrd** [comment]
Yes, I agree. Squashed + added "JavaScript function invocation".

**Review by gzm0 — APPROVED** [review]
