### PR TITLE
Fix #4409: Do not emit abstract methods in non-native JS classes.

### LINKED ISSUE #4409: Compiler emits abstract methods for JS classes
Discovered while working on #4388.

Example that fails: https://github.com/scala-js/scala-js/blob/b3b964ccdf2dd79038eaca98ce89fa9f8fbdcf8a/test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala#L1520

### PR DESCRIPTION
**Pull request by sjrd**
@gzm0 Is this an appropriate way to fix this in 1.5? Throwing the exception would be moved to the `ClassDefChecker` in the future.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala [hunk 1]
```diff
@@ -1825,29 +1825,34 @@ abstract class GenJSCode[G <: Global with Singleton](val global: G)
...
-             */
-            val implClassSym = sym.owner.implClass
-            val implMethodSym = implClassSym.info.member(sym.name).suchThat { s =>
-              s.isMethod &&
-              s.tpe.params.size == sym.tpe.params.size + 1 &&
-              s.tpe.params.head.tpe =:= sym.owner.toTypeConstructor &&
-              s.tpe.params.tail.zip(sym.tpe.params).forall {
-                case (sParam, symParam) =>
-                  sParam.tpe =:= symParam.tpe
+          if (isNonNativeJSClass(currentClassSym)) {
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/nscplugin/GenJSCode.scala:1828]: Could we avoid the nesting? (maybe by checking `isAbstractMethod` twice or putting it into a lazy val)?

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala [hunk 2]
```diff
@@ -1194,9 +1194,26 @@ object Serializers {
...
+                  "Invalid abstract method in non-native JS class")
+            }
+            false
+          case _ =>
+            true
+        }
+      } else {
+        memberDefs0
+      }
+
```
Comment (gzm0) [inline ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1216]: Do this inside `readMemberDefs`?

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala [hunk 3]
```diff
@@ -1194,9 +1194,26 @@ object Serializers {
...
       val topLevelExportDefs = readTopLevelExportDefs(name.name, kind)
       val optimizerHints = OptimizerHints.fromBits(readInt())
+
+      // #4409: Filter out abstract methods in non-native JS classes for version < 1.5
+      val memberDefs = if (kind.isJSClass) {
+        memberDefs0.filter {
+          case m @ MethodDef(_, name, _, _, _, None) =>
+            if (!hacks.use14) {
+              throw new InvalidIRException(m,
+                  "Invalid abstract method in non-native JS class")
```
Comment (gzm0) [inline ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1207]: Add a comment referencing #4388 that this should be there but currently can't?

**Review by gzm0 — CHANGES_REQUESTED** [review]
>  Is this an appropriate way to fix this in 1.5? Throwing the exception would be moved to the ClassDefChecker in the future.

Absolutely. I only have minor comments.

**Comment by sjrd** [comment]
Updated.

In addition to addressing the comments, I had to rearrange the way the hack is done not to cause the Scala 2.11 compiler to crash. The upside is that it is easier to see exactly what will disappear when we can move the check to a ClassDefChecker.

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala [hunk 4]
```diff
@@ -1349,8 +1349,39 @@ object Serializers {
       }
     }
 
-    def readMemberDefs(owner: ClassName, ownerKind: ClassKind): List[MemberDef] =
-      List.fill(readInt())(readMemberDef(owner, ownerKind))
+    def readMemberDefs(owner: ClassName, ownerKind: ClassKind): List[MemberDef] = {
+      val memberDefs0 = List.fill(readInt())(readMemberDef(owner, ownerKind))
```
Comment (gzm0) [inline ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1353]: Not sure the `0` is still necessary. But up to you.

**Review by gzm0 — APPROVED** [review]
