### PR TITLE
FF ONLY Merge 0.6.x into master, May 9

### LINKED ISSUE #2749: When we update GCC: Try replacing mutable.Map by js.Dictionary in scalajs.reflect.Reflect

### LINKED ISSUE #3154: ArrayComparisonFailure calls into a constructor not available on JDK 6 nor our implem
It calls `AssertionError(String, Throwable)`, which is not available on JDK 6, nor in our implementation.

This causes 2 issues:
* On JDK 7+, linking errors if we attempt to merge to 1.x
* On JDK 6, auto-tupling kicks in and the wrong constructor is called

### LINKED ISSUE #3293: The JDK 6 and 7 builds are broken
An example log can be found here:
https://scala-webapps.epfl.ch/jenkins/job/scalajs-task-worker/213646/consoleFull
I have also archived it in the following gist, just to make sure it doesn't disappear:
https://gist.github.com/sjrd/53d5c65f8da54f97c8b98aa5fdffd401

Fetching the Scala sources from the GitHub git through HTTPS has started failing two weeks ago, it seems. The failure is:
```
[info] Fetching Scala source version 2.11.12
org.eclipse.jgit.api.errors.TransportException: https://github.com/scala/scala.git: cannot open git-upload-pack
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1750)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1733)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/scala/scala.git: cannot open git-upload-pack
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:499)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:308)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1750)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1733)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1943)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1059)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1294)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1321)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1305)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:515)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1299)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:167)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:462)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:308)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1111)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1750)
	at build.Build$$anonfun$partest$1$$anonfun$apply$183.apply(Build.scala:1733)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
[error] (partest/*:fetchScalaSource) org.eclipse.jgit.api.errors.TransportException: https://github.com/scala/scala.git: cannot open git-upload-pack
[error] Total time: 1 s, completed Mar 2, 2018 2:34:28 AM
```
I have traced this issue to https://stackoverflow.com/q/34283829/1829647 and the Oracle blog post at https://blogs.oracle.com/java-platform-group/diagnosing-tls,-ssl,-and-https. The bottom line is that JDK 6 and 7 do not support TLS v1.2.

I suspect that GitHub has changed their server configuration so that its HTTPS git server refuses to operate in TLS v1.0 or v1.1. This means that JGit has no hope to communicate with GitHub repos on JDK 6 and 7 anymore.

The proper fix would be to shell out and use the command-line `git` client to fetch the Scala sources. But right now we need to disable the JDK 6 and 7 builds to restore the CI.

### LINKED ISSUE #3611: Test failures are ignored when filename is null in the stack trace
Example test code (based on scala-js/scalajs-tutorial):
```
package tutorial.webapp

import utest._
import scala.scalajs.js

@js.native
trait Foo extends js.Object {
 var x: js.Dictionary[Int] = js.native
}

object TutorialTest extends TestSuite {

  def tests = Tests {
    'HelloWorld - {
      val foo = js.Dynamic.literal(x = null).asInstanceOf[Foo]
      assert(foo.x.values.exists(_ > 0))
    }
  }
}
```

and the result:

```
sbt:Scala.js Tutorial> test
-------------------------------- Running Tests --------------------------------
X tutorial.webapp.TutorialTest.HelloWorld 4ms
  utest.AssertionError: assert(foo.x.values.exists(_ > 0))
  foo: tutorial.webapp.Foo = [object Object]
  scala.scalajs.js.JavaScriptException: TypeError: Cannot convert undefined or null to object
    <jscode>.Function.keys@<anonymous>(Unknown)
    scala.scalajs.js.WrappedDictionary$DictionaryIterator.<init>(R:\scalajs-tutorial-0.6.x\target\sc
    ala-2.12\scala-js-tutorial-test-fastopt.js:23811)
    scala.scalajs.js.WrappedDictionary.iterator(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js
    -tutorial-test-fastopt.js:46729)
    scala.collection.MapLike$$anon$2.<init>(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tut
    orial-test-fastopt.js:26890)
    <jscode>.$c_sjs_js_WrappedDictionary.$c_sc_AbstractMap.valuesIterator__sc_Iterator(R:\scalajs-tu
    torial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:40509)
    <jscode>.{anonymous}()(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastop
    t.js:17605)
    scala.scalajs.runtime.AnonFunction1.apply(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-t
    utorial-test-fastopt.js:20908)
    utest.asserts.Util$.runAssertionEntry(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutor
    ial-test-fastopt.js:6632)
[error] scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'length' of null
[error]         at java.io.DataOutputStream.writeUTF(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:31125)
[error]         at org.scalajs.testcommon.Serializer$StackTraceElementSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13354)
[error]         at org.scalajs.testcommon.Serializer$StackTraceElementSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13346)
[error]         at org.scalajs.testcommon.Serializer$$anon$4.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:12834)
[error]         at org.scalajs.testcommon.Serializer$ThrowableSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13570)
[error]         at org.scalajs.testcommon.Serializer$ThrowableSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13577)
[error]         at org.scalajs.testcommon.Serializer$$anon$5.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:12887)
[error]         at org.scalajs.testcommon.Serializer$ThrowableSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13574)
[error]         at org.scalajs.testcommon.Serializer$OptionalThrowableSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:13199)
[error]         at org.scalajs.testcommon.Serializer$EventSerializer$.serialize(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:12985)
    <jscode>.{anonymous}()(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastop
    t.js:17635)
    scala.scalajs.runtime.AnonFunction0.apply(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-t
    utorial-test-fastopt.js:20880)
[info]
[success] Total time: 5 s, completed 2019/04/08 20:58:04
```

Example 2:

```
package tutorial.webapp

import utest._
import scala.scalajs.js

object TutorialTest extends TestSuite {

  def tests = Tests {
    'HelloWorld - {
      js.Dynamic.global.eval("throw new Error()")
      assert(true)
    }
  }
}
```

and the result:

```
...
-------------------------------- Running Tests --------------------------------
X tutorial.webapp.TutorialTest.HelloWorld 1ms
  scala.scalajs.js.JavaScriptException: Error
    <jscode>.eval(eval at <anonymous> (R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial
    -test-fastopt.js:17595:21), <anonymous>:1)
    <jscode>.eval@<anonymous>(Unknown)
    <jscode>.{anonymous}()(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastop
    t.js:17595)
    scala.scalajs.runtime.AnonFunction0.apply(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-t
    utorial-test-fastopt.js:20868)
[error] scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'length' of null
[error]         at java.io.DataOutputStream.writeUTF(R:\scalajs-tutorial-0.6.x\target\scala-2.12\scala-js-tutorial-test-fastopt.js:30907)
...
```

Although utest clearly prints about test failure, `test` task was finished as `[success]` and  TestsFailedException hasn't be thrown.

I think this JavaScriptException has a StackTraceElement with filename=null, and the filename (null) has been passed to DataOutputStream.writeUTF which doesn't expect null.

sbt 1.2.8 / scala 2.12.6 / sbt-scalajs 0.6.25 / utest 0.6.3

### LINKED ISSUE #3612: Scaladoc with Scala.js 0.6.x and Scala 2.13.0-RC1 emits a warning
which means it fails when a build has `-Xfatal-warnings`. A workaround is to add
```scala
scalacOptions in (Compile, doc) -= "-Xfatal-warnings"
```

The warning is:
```
[warn] dropping dependency on node with no phase object: mixin
```
The problem does not appear in Scala.js 1.x.

### PR DESCRIPTION
**Pull request by sjrd**
```
$ git checkout -b merge-0.6.x-into-master-may-9
Switched to a new branch 'merge-0.6.x-into-master-may-9'
```
```
$ export mb=$(git merge-base scalajs/0.6.x scalajs/master)
```
```
$ git log --graph --oneline --decorate $mb..scalajs/0.6.x | cat
*   d72b29287 (scalajs/0.6.x, origin/0.6.x) Merge pull request #3637 from sjrd/upgrade-gcc-v20190415
|\  
| * 5c8f04998 Upgrade to Google Closure Compiler (GCC) v20190415.
|/  
*   c31b1302a Merge pull request #3631 from exoego/test-file-name
|\  
| * ec0dd07ab Fix #3611: Serialize null file names in StackTraceElement as "".
* |   8c4e73eb6 Merge pull request #3625 from sjrd/no-java-converters
|\ \  
| |/  
|/|   
| * d3d67edc5 Do not rely on JavaConverters in our implementation of java.util.
| * b8f1f6631 Use a Java iterator explicitly in RPCCore instead of JavaConverters.
|/  
*   50738377a Merge pull request #3628 from sjrd/deprecate-niocharset-stdcharsets
|\  
| * d2f575337 [no-master] Simplify the definition of `Charset.CharsetMap`.
| * a2c9e0ec2 [no-master] Deprecate `scala.scalajs.niocharset.StandardCharsets`.
|/  
*   995ed7268 Merge pull request #3630 from sjrd/upgrade-gcc-0.6.x
|\  
| * 20fa9bc02 [no-master] Fix #2749: Use a `js.Dictionary` instead of a `Map` in `Reflect`.
| * f525410a7 [no-master] Upgrade to Google Closure Compiler v20181210.
* |   be5533703 Merge pull request #3629 from sjrd/remove-jdk8-build-hacks-0.6.x
|\ \  
| |/  
|/|   
| * bf5746cea [no-master] Revert "Fix #3154: Avoid calling `AssertionError(String, Throwable)`."
| * 265d54f97 [no-master] Use `Integer.{divide,remainder}Unsigned` in `RuntimeLong`.
| * ce66031d1 [no-master] Move `java.lang.AutoCloseable` to the `javalanglib/`.
| * a061b8dc4 [no-master] Get rid of the MathJDK8Bridge hack.
* |   ccdc1f00d Merge pull request #3627 from sjrd/unfork-gcc-0.6.x
|\ \  
| |/  
|/|   
| * bcb62fb38 [no-master] Unfork our dependency on the Google Closure Compiler.
|/  
*   29011f4fb Merge pull request #3626 from sjrd/drop-jdk-6-7
|\  
| * 772f62c85 [no-master] Don't fix #3293: Drop support for JDK 6 and 7.
|/  
*   ab49c8777 Merge pull request #3614 from sjrd/drop-scala-2.13.0-M5
|\  
| * 2b6edc3bf Drop support for Scala 2.13.0-M5, replace it in the CI by 2.13.0-RC1.
|/  
*   ed0526952 Merge pull request #3613 from sjrd/fix-scaladoc-warnings
|\  
| * 2027c36fd [no-master] Fix #3612: Fix the compat code for `forScaladoc`.
| * b5fb28961 Fix two Scaladoc warnings in the library.
|/  
* 3c36b4b4a Towards 0.6.28.
* 8590070e7 (tag: v0.6.27) Version 0.6.27.
```
```
$ git merge --no-commit b5fb28961
Auto-merging project/Build.scala
CONFLICT (content): Merge conflict in project/Build.scala
Auto-merging ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
CONFLICT (content): Merge conflict in ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
Automatic merge failed; fix conflicts and then commit the result.
```
```
$ git st
UU ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
M  library/src/main/scala-new-collections/scala/scalajs/js/ArrayOps.scala
UU project/Build.scala
```
```diff
$ git diff | cat
diff --cc ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
index e40fedf11,4d458ab1a..000000000
--- a/ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
+++ b/ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala
diff --cc project/Build.scala
index 0e86c5481,67cc51552..000000000
--- a/project/Build.scala
+++ b/project/Build.scala
@@@ -117,8 -62,7 +117,8 @@@ object Build 
    val shouldPartest = settingKey[Boolean](
      "Whether we should partest the current scala version (and fail if we can't)")
  
 +  /* MiMa configuration -- irrelevant while in 1.0.0-SNAPSHOT.
-   val previousVersion = "0.6.26"
+   val previousVersion = "0.6.27"
    val previousSJSBinaryVersion =
      ScalaJSCrossVersion.binaryScalaJSVersion(previousVersion)
    val previousBinaryCrossVersion =
```
```
$ git add -u
```
```
$ git commit
[merge-0.6.x-into-master-may-9 619d0b947] Merge '0.6.x' into 'master'.
```
```
$ git merge -s ours 2027c36fd
Merge made by the 'ours' strategy.
```
```
$ git show
commit bab8b208f31b6ebd69a2a1aeffc3d301b608e64f (HEAD -> merge-0.6.x-into-master-may-9)
Merge: 619d0b947 2027c36fd
Author: Sébastien Doeraene <sjrdoeraene@gmail.com>
Date:   Thu May 9 10:59:57 2019 +0200

    Skip the [no-master] commit 2027c36fd.

```
```
$ git merge --no-commit ab49c8777
Auto-merging test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/LongTest.scala
Auto-merging scripts/publish.sh
CONFLICT (content): Merge conflict in scripts/publish.sh
Auto-merging project/Build.scala
CONFLICT (content): Merge conflict in project/Build.scala
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala left in tree.
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala left in tree.
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala left in tree.
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala left in tree.
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala left in tree.
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala left in tree.
Removing library/src/main/scala-m5-collections/scala/scalajs/js/ArrayOps.scala
CONFLICT (modify/delete): library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala deleted in ab49c8777 and modified in HEAD. Version HEAD of library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala left in tree.
Auto-merging compiler/src/test/scala/org/scalajs/nscplugin/test/JSInteropTest.scala
Auto-merging compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
CONFLICT (content): Merge conflict in compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
Auto-merging ci/checksizes.sh
CONFLICT (content): Merge conflict in ci/checksizes.sh
Auto-merging Jenkinsfile
Automatic merge failed; fix conflicts and then commit the result.
```
```
$ git st
M  Jenkinsfile
UU ci/checksizes.sh
UU compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
M  compiler/src/test/scala/org/scalajs/nscplugin/test/JSInteropTest.scala
UD library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/ArrayOps.scala
UD library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala
UD library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala
UD library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala
UD library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala
UD library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala
UD library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala
UU project/Build.scala
UU scripts/publish.sh
M  test-suite/js/src/test/scala/org/scalajs/testsuite/library/ArrayOpsTest.scala
M  test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/LongTest.scala
```
```
$ git rm -rf library/src/main/scala-m5-collections/
library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala: needs merge
library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala: needs merge
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala'
rm 'library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala'
```
[...] Resolve conflicts.
```
$ git st
M  Jenkinsfile
UU ci/checksizes.sh
UU compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
M  compiler/src/test/scala/org/scalajs/nscplugin/test/JSInteropTest.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/Any.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/ArrayOps.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/IterableOps.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/JSConverters.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/WrappedArray.scala
D  library/src/main/scala-m5-collections/scala/scalajs/js/WrappedDictionary.scala
D  library/src/main/scala-m5-collections/scala/scalajs/runtime/Compat.scala
D  library/src/main/scala-m5-collections/scala/scalajs/runtime/WrappedVarArgs.scala
UU project/Build.scala
UU scripts/publish.sh
M  test-suite/js/src/test/scala/org/scalajs/testsuite/library/ArrayOpsTest.scala
M  test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/LongTest.scala
```
```
$ git diff | cat
diff --cc ci/checksizes.sh
index cedd80ee9,7a49f2378..000000000
--- a/ci/checksizes.sh
+++ b/ci/checksizes.sh
@@@ -11,10 -14,10 +11,10 @@@ case $FULLVER i
    2.12.8)
      VER=2.12
      ;;
-   2.13.0-M5)
-     VER=2.13.0-M5
+   2.13.0-RC1)
+     VER=2.13.0-RC1
      ;;
 -  2.10.3|2.10.4|2.10.5|2.10.6|2.10.7|2.11.0|2.11.1|2.11.2|2.11.4|2.11.5|2.11.6|2.11.7|2.11.8|2.11.11|2.12.0|2.12.1|2.12.2|2.12.3|2.12.4|2.12.5|2.12.6|2.12.7)
 +  2.11.0|2.11.1|2.11.2|2.11.4|2.11.5|2.11.6|2.11.7|2.11.8|2.11.11|2.12.1|2.12.2|2.12.3|2.12.4|2.12.5|2.12.6|2.12.7)
      echo "Ignoring checksizes for Scala $FULLVER"
      exit 0
      ;;
@@@ -33,23 -36,29 +33,23 @@@ REVERSI_PREOPT_GZ_SIZE=$(stat '-c%s' "$
  REVERSI_OPT_GZ_SIZE=$(stat '-c%s' "$REVERSI_OPT.gz")
  
  case $FULLVER in
 -  2.10.2)
 -    REVERSI_PREOPT_EXPECTEDSIZE=533000
 -    REVERSI_OPT_EXPECTEDSIZE=122000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=71000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=31000
 -    ;;
    2.11.12)
 -    REVERSI_PREOPT_EXPECTEDSIZE=530000
 -    REVERSI_OPT_EXPECTEDSIZE=124000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=72000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=32000
 +    REVERSI_PREOPT_EXPECTEDSIZE=510000
 +    REVERSI_OPT_EXPECTEDSIZE=112000
 +    REVERSI_PREOPT_GZ_EXPECTEDSIZE=68000
 +    REVERSI_OPT_GZ_EXPECTEDSIZE=29000
      ;;
    2.12.8)
 -    REVERSI_PREOPT_EXPECTEDSIZE=618000
 -    REVERSI_OPT_EXPECTEDSIZE=144000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=74000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=32000
 +    REVERSI_PREOPT_EXPECTEDSIZE=595000
 +    REVERSI_OPT_EXPECTEDSIZE=131000
 +    REVERSI_PREOPT_GZ_EXPECTEDSIZE=70000
 +    REVERSI_OPT_GZ_EXPECTEDSIZE=30000
      ;;
-   2.13.0-M5)
-     REVERSI_PREOPT_EXPECTEDSIZE=598000
-     REVERSI_OPT_EXPECTEDSIZE=134000
-     REVERSI_PREOPT_GZ_EXPECTEDSIZE=78000
-     REVERSI_OPT_GZ_EXPECTEDSIZE=34000
+   2.13.0-RC1)
 -    REVERSI_PREOPT_EXPECTEDSIZE=792000
 -    REVERSI_OPT_EXPECTEDSIZE=188000
 -    REVERSI_PREOPT_GZ_EXPECTEDSIZE=103000
 -    REVERSI_OPT_GZ_EXPECTEDSIZE=47000
++    REVERSI_PREOPT_EXPECTEDSIZE=621000
++    REVERSI_OPT_EXPECTEDSIZE=141000
++    REVERSI_PREOPT_GZ_EXPECTEDSIZE=83000
++    REVERSI_OPT_GZ_EXPECTEDSIZE=37000
      ;;
  esac
  
diff --cc compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
index 1fe4def54,6cc15e1cb..000000000
--- a/compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
+++ b/compiler/src/test/scala/org/scalajs/nscplugin/test/JSExportTest.scala
diff --cc project/Build.scala
index 8fee26e4b,392f84b75..000000000
--- a/project/Build.scala
+++ b/project/Build.scala
@@@ -1059,13 -1139,6 +1059,9 @@@ object Build 
                "-doc-version", scalaJSVersion
            ),
  
-           unmanagedSourceDirectories += {
-             val scalaV = scalaVersion.value
-             val sourceDir = sourceDirectory.value
-             if (scalaV == "2.13.0-M5") sourceDir / "scala-m5-collections"
-             else collectionsEraDependentDirectory(scalaV, sourceDir)
-           },
++          unmanagedSourceDirectories +=
++            collectionsEraDependentDirectory(scalaVersion.value, sourceDirectory.value),
 +
            // Filter doc sources to remove implementation details from doc.
            sources in doc := {
              val prev = (sources in doc).value
diff --cc scripts/publish.sh
index 09e82a63a,1f26a0de7..000000000
--- a/scripts/publish.sh
+++ b/scripts/publish.sh
@@@ -7,10 -7,10 +7,10 @@@ els
      CMD="echo sbt"
  fi
  
- COMPILER_VERSIONS="2.11.0 2.11.1 2.11.2 2.11.4 2.11.5 2.11.6 2.11.7 2.11.8 2.11.11 2.11.12 2.12.1 2.12.2 2.12.3 2.12.4 2.12.5 2.12.6 2.12.7 2.12.8 2.13.0-M5"
 -COMPILER_VERSIONS="2.10.2 2.10.3 2.10.4 2.10.5 2.10.6 2.10.7 2.11.0 2.11.1 2.11.2 2.11.4 2.11.5 2.11.6 2.11.7 2.11.8 2.11.11 2.11.12 2.12.0 2.12.1 2.12.2 2.12.3 2.12.4 2.12.5 2.12.6 2.12.7 2.12.8 2.13.0-RC1"
 -BIN_VERSIONS="2.10.7 2.11.12 2.12.8"
++COMPILER_VERSIONS="2.11.0 2.11.1 2.11.2 2.11.4 2.11.5 2.11.6 2.11.7 2.11.8 2.11.11 2.11.12 2.12.1 2.12.2 2.12.3 2.12.4 2.12.5 2.12.6 2.12.7 2.12.8 2.13.0-RC1"
 +BIN_VERSIONS="2.11.12 2.12.8"
- NO_TOOLS_BIN_VERSIONS="2.13.0-M5"
- JVM_BIN_VERSIONS="2.10.7 2.11.12 2.12.8 2.13.0-M5"
+ NO_TOOLS_BIN_VERSIONS="2.13.0-RC1"
 -CLI_VERSIONS="2.10.7 2.11.12 2.12.8"
++JVM_BIN_VERSIONS="2.10.7 2.11.12 2.12.8 2.13.0-RC1"
  SBT_VERSION="2.10.7"
  SBT1_VERSION="2.12.8"
  SBT1_SBTVERSION="1.0.0"
```
```
$ git add -u
```
```
$ git commit
[merge-0.6.x-into-master-may-9 069911c38] Merge '0.6.x' into 'master'.
```
```
$ git merge -s ours 50738377a
Merge made by the 'ours' strategy.
```
```
$ git show
commit ac2abde2927918e8c91b9f619753a941bd01b893 (HEAD -> merge-0.6.x-into-master-may-9)
Merge: 069911c38 50738377a
Author: Sébastien Doeraene <sjrdoeraene@gmail.com>
Date:   Thu May 9 11:17:10 2019 +0200

    Skip several [no-master] commits.
    
    Commits 772f62c85, bcb62fb38, a061b8dc4, ce66031d1, 265d54f97,
    bf5746cea, f525410a7, 20fa9bc02, a2c9e0ec2 and d2f575337.

```
```
$ git merge --no-commit scalajs/0.6.x 
Auto-merging test-common/src/test/scala/org/scalajs/testing/common/SerializerTest.scala
Auto-merging test-common/src/main/scala/org/scalajs/testing/common/Serializer.scala
Auto-merging test-common/src/main/scala/org/scalajs/testing/common/RPCCore.scala
Auto-merging project/build.sbt
Auto-merging project/Build.scala
CONFLICT (content): Merge conflict in project/Build.scala
Auto-merging project/BinaryIncompatibilities.scala
Auto-merging linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/LoggerErrorReportGenerator.scala
Auto-merging javalib/src/main/scala/java/util/Collections.scala
Automatic merge failed; fix conflicts and then commit the result.
```
```
$ git st
M  javalib/src/main/scala/java/util/AbstractCollection.scala
M  javalib/src/main/scala/java/util/AbstractList.scala
M  javalib/src/main/scala/java/util/AbstractMap.scala
M  javalib/src/main/scala/java/util/AbstractSet.scala
M  javalib/src/main/scala/java/util/Collections.scala
M  javalib/src/main/scala/java/util/Compat.scala
M  javalib/src/main/scala/java/util/HashSet.scala
M  javalib/src/main/scala/java/util/Hashtable.scala
M  javalib/src/main/scala/java/util/LinkedList.scala
M  javalib/src/main/scala/java/util/NavigableView.scala
M  javalib/src/main/scala/java/util/Properties.scala
A  javalib/src/main/scala/java/util/ScalaOps.scala
M  javalib/src/main/scala/java/util/TreeSet.scala
M  javalib/src/main/scala/java/util/concurrent/ConcurrentHashMap.scala
M  javalib/src/main/scala/java/util/concurrent/CopyOnWriteArrayList.scala
M  linker/jvm/src/main/scala/org/scalajs/linker/backend/closure/LoggerErrorReportGenerator.scala
M  project/BinaryIncompatibilities.scala
UU project/Build.scala
M  project/build.sbt
M  test-common/src/main/scala/org/scalajs/testing/common/RPCCore.scala
M  test-common/src/main/scala/org/scalajs/testing/common/Serializer.scala
M  test-common/src/test/scala/org/scalajs/testing/common/SerializerTest.scala
M  test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/HashtableTest.scala
```
[...] Resolve conflicts.
```diff
$ git diff | cat
diff --cc project/Build.scala
index f2678d711,fe22eeae1..000000000
--- a/project/Build.scala
+++ b/project/Build.scala
@@@ -636,178 -608,245 +636,178 @@@ object Build 
 +  lazy val linker: Project = (project in file("linker/jvm")).settings(
 +      commonLinkerSettings,
 +      libraryDependencies ++= Seq(
-           "com.google.javascript" % "closure-compiler" % "v20181210",
++          "com.google.javascript" % "closure-compiler" % "v20190415",
 +          "com.novocode" % "junit-interface" % "0.9" % "test"
 +      ) ++ (
 +          parallelCollectionsDependencies(scalaVersion.value)
```
```
$ git add -u
```
```
$ git commit
[merge-0.6.x-into-master-may-9 6196e8a17] Merge '0.6.x' into 'master'.
```

### CODE REVIEW

File: project/BinaryIncompatibilities.scala [hunk 1]
```diff
@@ -26,6 +26,9 @@ object BinaryIncompatibilities {
   )
 
   val TestCommon = Seq(
+      // private, not an issue
+      ProblemFilters.exclude[MissingClassProblem](
+          "org.scalajs.testcommon.RPCCore$JDKCollectionConvertersCompat$*")
```
Comment (gzm0) [inline project/BinaryIncompatibilities.scala]: This shouldn't be here I believe.

Comment (sjrd) [reply project/BinaryIncompatibilities.scala]: Indeed. Fixed.
