### PR TITLE
Fix #4604: Preserve side effects of div-by-zero in keepOnlySideEffects.

### LINKED ISSUE #4604: 0/0 should throw an exception
```
def f() = {
  0/0
  println("unreachable code")
}

f()
```
I expect `f()` should throw an exception, but it does not actually throw an exception.
https://scastie.scala-lang.org/fbBfZpNVTEqb9B3LLrKAeg

## Workaround
```
def zeroDivZero() = 0/0

def f() = {
  zeroDivZero()
  println("unreachable code")
}

f()
```
https://scastie.scala-lang.org/FIBOOIQhRHWS37Ze49szJg
Now the exception can be thrown as expected

## Scala.js version
1.7.0
## Scala version
This bug is reproducible in both Scala 3.1.0 and Scala 2.13.7

### PR DESCRIPTION
**Pull request by sjrd**
We were already correctly taking care of these effects in the optimizer's `finishTransformStat()`, as well as in the emitter. But we had forgotten one case in the optimizer's `keepOnlySideEffects()`.

### CODE REVIEW

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/OptimizerTest.scala [hunk 1]
```diff
@@ -432,6 +433,22 @@ class OptimizerTest {
...
+
+  @Test def divideByZero_Issue4604(): Unit = {
+    @noinline def divByZeroInExpressionPosition(): Int = {
+      0 / 0
+    }
+
+    @noinline def divByZeroInStatementPosition(): Unit = {
+      0 / 0
+      fail("should be unreachable")
+    }
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/OptimizerTest.scala:446]: Also add a test case for Longs?

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/OptimizerTest.scala (hunk 1 above)
Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/OptimizerTest.scala:448]: Ah yes, of course. I should have thought about that. Done.
