### PR TITLE
Fix #5165: Use defaultable types for the locals of TryFinallys.

### LINKED ISSUE #5165: Wasm: try..finally with non-nullable reference type produces invalid code
Reproduction:
```scala
  def test(): Unit = {
    var a = 1
    val some = try {
      Some(a)
    } finally {
      a = 2
    }
    assert(some.value == 1)
  }
```
produces invalid Wasm code. Trying to run the program yields
```
[CompileError: WebAssembly.instantiate():
Compiling function #165:"f.helloworld.Main$.test;V" failed:
uninitialized non-defaultable local: 2 @+28176]
```
The pretty-printed code for the function is
```wat
  (func $f.helloworld.Main$.test_V (type $128)
     (param $this (ref $c.helloworld.Main$))
     (local $a i32) (local $1 (ref $c.scala.Some)) (local $2 (ref $c.scala.Some)) (local $some (ref $c.scala.Some))
     i32.const 1
     local.set $a
     block $1
       block $2 (result exnref)
         try_table (catch_all_ref $2)
           call $new.scala.Some
           local.tee $2
           local.get $a
           call $bI
           call $ct.scala.Some.<init>_Ljava.lang.Object_V
           local.get $2
           local.set $1
         end
         ref.null exn
       end
       i32.const 2
       local.set $a
       br_on_null $1
       throw_ref
     end
     local.get $1
     local.set $some
     call $m.scala.Predef$
     ref.as_non_null
     local.get $some
     struct.get $c.scala.Some $f.scala.Some.value
     call $as.int
     i32.const 1
     i32.eq
     call $f.scala.Predef$.assert_Z_V)
```
Wasm cannot prove that, in all the code paths that lead to reading `local.get $1` after the big `block $1`, the variable was initialized. That's fair, since it wouldn't be initialized if we caught an exception; we know that we cannot reach there in that case (because of the re-throw) but Wasm validation cannot prove it. Since `$1` has a non-nullable reference type `(ref $c.Some)`, that is not valid code.

We have to always use a defaultable type for the partial results involved in `try..finally`s (which means we have to cast away nullability when we read them).

### PR DESCRIPTION
**Pull request by sjrd**
As well as for the locals of `Labeled` blocks whose `Return`s cross a `try..finally` boundary.

If their original type was not defaultable, we cast away nullability when reading them back.

### CODE REVIEW

**Review by tanishiking — APPROVED** [review]
LGTM from my side :+1:

File: linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala [hunk 1]
```diff
@@ -3622,6 +3622,12 @@ private class FunctionEmitter private (
    * we cannot use the stack for the `try_table` itself: each label has a
    * dedicated local for its result if it comes from such a crossing `return`.
    *
+   * Those locals must have defaultable types, because the control flow is too
+   * complicated for the Wasm validation algorithm to prove that they are
+   * always initialized before being used. If their natural type is not
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala:3627]: I have attempted to understand why this is happening based on the WASM GC spec, but was unsuccessful (so far). In fact, I did not find any mention of how `C.locals` behaves within blocks during the validation phase (notably w.r.t. initialization status).

https://webassembly.github.io/gc/core/valid/instructions.html#instruction-sequences shows how subsequent instructions "see" previously initialized variables (this is the trivial case).

However, the block validation specification:
https://webassembly.github.io/gc/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-block-xref-syntax-instructions-syntax-blocktype-mathit-blocktype-xref-syntax-instructions-syntax-instr-mathit-instr-ast-xref-syntax-instructions-syntax-instr-control-mathsf-end

does not even mention locals (no `x` at the arrow). The way I interpret this is setting a local inside a block doesn't "propagate" outside the block (as far as validation is concerned). That feels like it cannot be right: I would expect validation to fail in a lot more cases.

Any hints on what I'm getting wrong here?

**Review by gzm0 — APPROVED** [review]
Up to you whether to block on the validation validation comment (IMO we should address it, but need not block this PR).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala:3627]: I think your analysis and correct. From scanning through all `wa.Local*` in `FunctionEmitter`, I also think all other local variables that we use are either:

* defaultable by construction (destination tag locals, declared parameter types of methods), or
* set in the scope where they will be read or above (not inside an inner block).

So I think validation does not "fail in a lot more cases" because we don't have other cases like this at all.

Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/wasmemitter/FunctionEmitter.scala]: I updated comments to reflect this new understanding.
