### PR TITLE
Fix #5335: Throw a user-friendly exception on inconsistent config.

### LINKED ISSUE #5335: ModuleSplitStyle shouldn't affect ModuleKind.NoModule
I'm calling `withModuleKind(ModuleKind.NoModule)` for my tests, however I need to also call `withModuleSplitStyle(ModuleSplitStyle.FewestModules)` to avoid an error (see below). My understanding is that if I specify `NoModule`, it shouldn't matter what `ModuleSplitStyle` is specified.

### Reproduction

1. Clone https://github.com/japgolly/scalajs-react-19-prototype
2. Remove this line: https://github.com/japgolly/scalajs-react-19-prototype/blob/main/build.sbt#L39
3. `sbt test`
4. Observe error:

```
[error] java.util.concurrent.ExecutionException: Boxed Error
[error]         at scala.concurrent.impl.Promise$.resolver(Promise.scala:97)
[error]         at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:89)
[error]         at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:294)
[error]         at scala.concurrent.Promise.complete(Promise.scala:53)
[error]         at scala.concurrent.Promise.complete$(Promise.scala:52)
[error]         at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:197)
[error]         at scala.concurrent.impl.Promise.completeWithFailure(Promise.scala:32)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:55)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1750)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1742)
[error]         at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1659)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[error] Caused by: java.lang.AssertionError: non-public module in NoModule mode
[error]         at org.scalajs.linker.backend.emitter.VarGen.maybeExport(VarGen.scala:286)
[error]         at org.scalajs.linker.backend.emitter.VarGen.globalFunctionDef(VarGen.scala:71)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter.$anonfun$genStaticLikeMethod$2(ClassEmitter.scala:565)
[error]         at org.scalajs.linker.backend.emitter.WithGlobals.flatMap(WithGlobals.scala:84)
[error]         at org.scalajs.linker.backend.emitter.ClassEmitter.genStaticLikeMethod(ClassEmitter.scala:541)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$6(Emitter.scala:498)
[error]         at org.scalajs.linker.backend.emitter.Emitter$MethodCache.getOrElseUpdate(Emitter.scala:1069)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$genClass$5(Emitter.scala:499)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
[error]         at scala.collection.immutable.List.foreach(List.scala:431)
[error]         at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
[error]         at org.scalajs.linker.backend.emitter.Emitter.genClass(Emitter.scala:491)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$4(Emitter.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$2(Emitter.scala:226)
[error]         at scala.collection.immutable.List.map(List.scala:293)
[error]         at org.scalajs.linker.backend.emitter.Emitter.$anonfun$emitOnce$1(Emitter.scala:223)
[error]         at org.scalajs.logging.Logger.time(Logger.scala:42)
[error]         at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitOnce(Emitter.scala:227)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitAvoidGlobalClash(Emitter.scala:195)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emitInternal(Emitter.scala:161)
[error]         at org.scalajs.linker.backend.emitter.Emitter.emit(Emitter.scala:99)
[error]         at org.scalajs.linker.backend.BasicLinkerBackend.$anonfun$emit$1(BasicLinkerBackend.scala:85)
[error]         at org.scalajs.logging.Logger.time(Logger.scala:42)
[error]         at org.scalajs.logging.Logger.time$(Logger.scala:40)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:19)
[error]         at org.scalajs.linker.backend.BasicLinkerBackend.emit(BasicLinkerBackend.scala:85)
[error]         at org.scalajs.linker.standard.StandardLinkerImpl.$anonfun$link$2(StandardLinkerImpl.scala:47)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:51)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1750)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1742)
[error]         at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1659)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:511)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1450)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2019)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[error] (Test / fastLinkJS) java.util.concurrent.ExecutionException: Boxed Error
```

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: linker/shared/src/test/scala/org/scalajs/linker/IncompatibleConfigTest.scala [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+  @Test def inconsistentConfigTest(): Unit = {
+    // #5335 NoModule requires ModuleSplitStyle.FewestModules
+    val nonFewestModulesSplitStyles = List(
+      ModuleSplitStyle.SmallestModules,
+      ModuleSplitStyle.SmallModulesFor(List("foo"))
+    )
+    for (splitStyle <- nonFewestModulesSplitStyles) {
+      test(s"NoModule requires ModuleSplitStyle.FewestModules; was $splitStyle.",
+          baseC.withModuleSplitStyle(splitStyle))
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncompatibleConfigTest.scala]: Consider hard-coding the two expected strings to make sure the split style we report is actually readable.

File: linker/shared/src/test/scala/org/scalajs/linker/IncompatibleConfigTest.scala [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+  @deprecated("tests deprecated APIs", since = "forever")
+  @Test def configNotSupportedByWasmBackend(): Unit = {
+    val wasmC = baseC
+      .withExperimentalUseWebAssembly(true)
+      .withModuleKind(ModuleKind.ESModule)
+
+    // Unsupported ModuleKind
+    val supportedModuleKinds = Set[ModuleKind](ModuleKind.ESModule)
+    for (moduleKind <- ModuleKind.All if !supportedModuleKinds.contains(moduleKind)) {
+      test(s"The WebAssembly backend only supports ES modules; was $moduleKind.",
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/IncompatibleConfigTest.scala:47]: Here maybe the trade-off is different: being able to test everything is probably more important.

**Review by gzm0 — APPROVED** [review]
Just a nit (your discretion).
