### PR TITLE
Fix #1643: Fix handling of negative integers in String.lastIndexOf.

### LINKED ISSUE #1643: lastIndexOf does not correctly handle negative fromIndex
There appears to be a difference in the underlying implementation between Scala and JS, namely 

Scala:
```
> "/".lastIndexOf("/", -1)
res0: Int = -1
```

JS:
```
> "/".lastIndexOf("/", -1)
0
```

This can lead to infinite recursion in some Scala code where the behaviour depends on the correct handling of negative indexes

### PR DESCRIPTION
**Pull request by yawnt**
There appears to be a difference in the underlying implementation between Scala and JS,
namely 

Scala:
```
> "/".lastIndexOf("/", -1)
res0: Int = -1
```

JS:
```
> "/".lastIndexOf("/", -1)
0
```

This can lead to infinite recursion in some Scala code where the behaviour depends on the correct handling of negative indexes

### CODE REVIEW

**Comment by yawnt** [comment]
FWIW I think the JS behaviour doesn't make a whole lot of sense, but it's faster to fix this at the scala.js level

**Comment by sjrd** [comment]
Please first report an Issue, with the explanation of the problem that you give above. Then reference the issue in the commit message as `Fix #xxx: Fix handling of negative integers in String.lastIndexOf.`

File: library/src/main/scala/scala/scalajs/runtime/RuntimeString.scala [hunk 1]
```diff
@@ -160,7 +160,8 @@ private[runtime] object RuntimeString {
     thiz.lastIndexOf(fromCodePoint(ch))
 
   def lastIndexOf(thiz: String, ch: Int, fromIndex: Int): Int =
-    thiz.lastIndexOf(fromCodePoint(ch), fromIndex)
+    if(fromIndex < 0) -1
```
Comment (sjrd) [inline library/src/main/scala/scala/scalajs/runtime/RuntimeString.scala]: missing space after `if`

**Comment by sjrd** [comment]
This should also come with a test in https://github.com/scala-js/scala-js/blob/master/test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala

**Comment by sjrd** [comment]
You probably also want to fix the overload of `lastIndexOf` that takes a `String`.

**Comment by yawnt** [comment]
should be good to go, I also ran `testSuite/test` and they all passed

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala [hunk 2]
```diff
@@ -98,6 +98,7 @@ object StringTest extends JasmineTest {
       expect("Scala.js".lastIndexOf("Scala.js")).toBe(0)
       expect("ananas".lastIndexOf("na")).toBe(3)
       expect("Scala.js".lastIndexOf("Java")).toBe(-1)
+      expect("Negative index".lastIndexOf("N", -5)).toBe(-1)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala]: OK. Also add a similar test for `lastIndexOf(int)` just below.

**Comment by sjrd** [comment]
Finally, the commit message should end with a `.` (yes, we are quite pedantic here ;-) )

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala (hunk 2 above)
Comment (yawnt) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala]: what do you mean? to make sure that it actually searches backwards from the right index?

Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala]: I mean write a similar test for the overload of `lastIndexOf` that searches for an `Int` with a `fromIndex` (hence takes two `Int`s) -- as a separate `it`, below the one that says `it("should respond to `lastIndexOf(int)`") {`.

Comment (yawnt) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/StringTest.scala]: oh, already done, it's in the amended commit

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
test this please

**Comment by yawnt** [comment]
already tested in akka.js, tests would hang without this fix

**Comment by sjrd** [comment]
Ah, sorry, `test this please` is a "command" given to the bot that runs the Continuous Integration on our servers. It wasn't meant at you (usually I explain this to newcomers, I forgot).
