### PR TITLE
Fix #1582: Parsing hexadecimal Long that has 0x80000000 bit set fails

### LINKED ISSUE #1582: Parsing hexadecimal Long that has 0x80000000 bit set fails
```scala
java.lang.Long.parseLong("bfc94973", 16)
```
Throws `Uncaught java.lang.NumberFormatException: For input string: "bfc94973"` but should return 3217639795

### PR DESCRIPTION
**Pull request by InTheNow**

### CODE REVIEW

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 1]
```diff
@@ -43,6 +43,7 @@ object Long {
   final val MIN_VALUE = -9223372036854775808L
   final val MAX_VALUE = 9223372036854775807L
   final val SIZE = 64
+  final val DIGIT_FIT_IN_INT = Array.tabulate[Int](37)(i => maxExpForRadix(i))
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: `private lazy val DigitFitInInt = ...`
Also separated from the other (public) vals by a blank line.

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 2]
```diff
@@ -70,10 +71,10 @@ object Long {
         else if (exp % 2 == 0) fastPow(base*base, exp/2, acc)
         else fastPow(base, exp-1, acc*base)
 
+      val MaxLen = DIGIT_FIT_IN_INT(radix)
       @inline
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Add a blank line above this line (between `val MaxLen` and `@inline`)

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 3]
```diff
@@ -232,4 +233,22 @@ object Long {
     else if (mp != 0) Integer.toOctalString(mp) + padOctal10(lp)
     else Integer.toOctalString(lp)
   }
+
+  /**
+   * Holds the maximal number of digits for each radix, so that a number of that radix
+   * can be converted to an Integer
+   */
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: This comment belongs to `DigitFitInInt`, not this method.

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 4]
```diff
@@ -232,4 +233,22 @@ object Long {
...
+  private def maxExpForRadix(radix: Int): Int = {
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Put this method right after `parseLong`, since it belongs with it.

Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Why is the val named `DigitFitInInt` and this method `maxExpForRadix`? They should probably have related names.

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 5]
```diff
@@ -232,4 +233,22 @@ object Long {
...
+    @inline
+    @tailrec
+    def loop(exp: Int, m: Long): Int = {
+      val l: Long = m * radix
+      if (l <= Int.MaxValue) loop(exp+ 1, l)
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: space before `+`

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 6]
```diff
@@ -232,4 +233,22 @@ object Long {
...
+
+  /**
+   * Holds the maximal number of digits for each radix, so that a number of that radix
+   * can be converted to an Integer
+   */
+  private def maxExpForRadix(radix: Int): Int = {
+    @inline
+    @tailrec
+    def loop(exp: Int, m: Long): Int = {
+      val l: Long = m * radix
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: The type annotation is not necessary.

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 7]
```diff
@@ -232,4 +233,22 @@ object Long {
...
+      if (l <= Int.MaxValue) loop(exp+ 1, l)
+      else exp
+    }
+
+    if (radix < 2) -1
+    else if (radix == 2) 30
+    else loop(0, 1)
+  }
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Actually, I think this method should not even exist. I recommend pre-computing the array of 37 elements, and simply hard-code the values as such:
```scala
private lazy val DigitFitInInt = Array(-1, -1, 30, ...)
```

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala [hunk 8]
```diff
@@ -114,6 +114,36 @@ object LongTest extends JasmineTest {
...
+      test("bfc94973", 3217639795L)
+      test("bfc949733", 51482236723L)
+    }
+
+    it("should parse strings in bases 2 to 36") {
+      def test(radix: Int, s: String, v: Long): Unit = {
+        expect(JLong.parseLong(s, radix)).toEqual(v)
+        expect(JLong.valueOf(s, radix).longValue()).toEqual(v)
+      }
+      def testNumber(i: Int): Long = {
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: Blank line between defs.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala [hunk 9]
```diff
@@ -114,6 +114,36 @@ object LongTest extends JasmineTest {
...
+
+      val radices = Array.tabulate[Int](34)(_ + 2)
+      val aNums = Array.tabulate[Long](128)(testNumber(_))
+      for {
+        r <- radices
+        n <- aNums
+      } yield test(r, JLong.toString(n, r), n)
+    }
+
+    it("should reject parsing strings when 2 > base > 36") {
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: `2 > base > 36` is a bit strange. I would write `base < 2 || base > 36`

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala [hunk 10]
```diff
@@ -114,6 +114,36 @@ object LongTest extends JasmineTest {
...
+      test("bfc949733", 51482236723L)
+    }
+
+    it("should parse strings in bases 2 to 36") {
+      def test(radix: Int, s: String, v: Long): Unit = {
+        expect(JLong.parseLong(s, radix)).toEqual(v)
+        expect(JLong.valueOf(s, radix).longValue()).toEqual(v)
+      }
+      def testNumber(i: Int): Long = {
+        val result = Long.MaxValue / (if (i == 0) 1 else 1L << i)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: `1L << 0 == 1L`, so the `if (i == 0) 1` is superfluous.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala (hunk 8 above)
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: I don't understand what this method is supposed to compute, and how it is relevant?

**Comment by sjrd** [comment]
That's all.

**Comment by sjrd** [comment]
test this please

File: javalanglib/src/main/scala/java/lang/Long.scala (hunk 7 above)
Comment (InTheNow) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Yes, could do as hard-coded. This was sort-of listed from the BigNumerics where on a code review comment was to calc the array. I can see value in both, but now the code is there I'm not sure it is best to completely delete as it begs "where do the number come from" (btw also this is where I got the names from, but the method is actually slightly different.)

So what is best - to delete the code. comment it, leave it but hard code the values?

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala (hunk 8 above)
Comment (InTheNow) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: Is _should_ generate  test numbers with diff significant figures between  -MaxLong to +MaxLong so they can be tested for each radix

File: javalanglib/src/main/scala/java/lang/Long.scala (hunk 7 above)
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: I think the best is to delete the code, hard-code the values, and ScalaDoc-comment what these values are. It doesn't matter how they were computed in the first place.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala (hunk 8 above)
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: Ah. Then I'd call it `genTestValue`.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala [hunk 11]
```diff
@@ -114,6 +114,36 @@ object LongTest extends JasmineTest {
...
+        if (i > 63) -result
+        else result
+      }
+
+      val radices = Array.tabulate[Int](34)(_ + 2)
+      val aNums = Array.tabulate[Long](128)(testNumber(_))
+      for {
+        r <- radices
+        n <- aNums
+      } yield test(r, JLong.toString(n, r), n)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: This loop would be easier to read in this form:
```scala
for {
  radix <- 2 to 36
  i <- 0 until 128
} {
  val n = genTestValue(i)
  test(radix, JLong.toString(n, radix), n)
}
```
Note that there's no `yield`, btw.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala (hunk 8 above)
Comment (InTheNow) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LongTest.scala]: Ok. As a side note: When writing the test, and the fact you have suggested the name "gen", I could not get the thought of scalacheck from my mind. In fact, it's the perfect tool for all these sorts of base classes. Just a thought

**Comment by InTheNow** [comment]
fixes in

File: javalanglib/src/main/scala/java/lang/Long.scala [hunk 12]
```diff
@@ -44,6 +44,14 @@ object Long {
   final val MAX_VALUE = 9223372036854775807L
   final val SIZE = 64
 
+  /**
+   * Holds the maximal number of digits for each radix, so that a number of
+   * that radix can be converted to an Integer
+   */
```
Comment (sjrd) [inline javalanglib/src/main/scala/java/lang/Long.scala]: Just the ScalaDoc style:
```scala
  /** Maximal number digits for each radix, so that a number of
   *  that radix can be converted to an Int.
   */
```

**Comment by InTheNow** [comment]
done

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please
