### PR TITLE
Fix #4061: Report a linking error on export of non-JS ident in a Script.

### LINKED ISSUE #4061: @JSExportTopLevel("default") generates invalid JS code on Scala.js 1.0
Also reported in https://github.com/scalameta/scalameta/issues/2051

scalameta 4.3.12, published for Scala.js 1.0.1, seems broken on Scala.js 1.x project while running test:

See https://travis-ci.com/github/exoego/scalajs-util-types/jobs/339579547#L441
```
/home/travis/build/exoego/scalajs-util-types/macros/target/scala-2.12/macros-test-fastopt.js:1
let parseSource,default,parseStat;
                ^^^^^^^
```

Scalameta uses `@JSExportTopLevel("default")`, which was fine with Scala.js 0.6, in https://github.com/scalameta/scalameta/blob/master/scalameta/parsers/js/src/main/scala/scala/meta/parsers/JSFacade.scala#L111-

But it seems that Scala.js 1.0 generates JavaScript with a variable named `default` , which is [keyword in ECMAScript 2015](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/default).

### PR DESCRIPTION
**Pull request by sjrd**
When emitting a Script (`NoModule`), we cannot export on the top-level under a name that is not a valid JavaScript identifier. Such exports must be emitted as `var`s or `let`s, which is only possible for valid JS identifiers.

Previously, attempts at such invalid exports would silently result in invalid .js code, producing a `SyntaxError` at run-time. In this commit, we preemptively report a linking error instead (as a thrown `LinkingException`).

It can be argued that we might want fallback behaviors for these cases, as discussed in #4061. However, this commit is a definitive improvement over the status quo, and leaves the door open for fallbacks in the future, if they prove desirable/necessary.

### CODE REVIEW

**Comment by sjrd** [comment]
Alternative to #4077 that implements the check in the Analyzer.

This PR does *not* move the existing check for Imports without fallbacks, nor does it add tests for that. So it does not entirely supersede #4077. Doing that is left for another PR, since it was now unrelated to fixing #4061, and not trivial to add due to the fact that Infos do not know about Imports yet.

File: linker/shared/src/test/scala/org/scalajs/linker/AnalyzerTest.scala [hunk 1]
```diff
@@ -537,12 +576,13 @@ object AnalyzerTest {
 
   private def computeAnalysis(classDefs: Seq[ClassDef],
       symbolRequirements: SymbolRequirement = reqsFactory.none(),
+      config: CommonPhaseConfig = CommonPhaseConfig(),
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/AnalyzerTest.scala:579]: Consider taking a `StandardConfig` here. This hopefully makes the `config` helper above unnecessary.

Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/AnalyzerTest.scala]: Good point. Done.
