### PR TITLE
Fix #4875: Change our strategy for crossScalaVersions handling.

### LINKED ISSUE #4875: Nightly build is broken because sbt's ++ became stricter in 1.7.0
All minor versions of Scala except the default ones are now broken, because sbt's `++` refuses to set them where we need it to.

### PR DESCRIPTION
**Pull request by sjrd**
sbt 1.7.0 made `++` even stricter than before. It now only applies if the target version appears as is in `crossScalaVersions`, rather than a binary-compatible one.

We now introduce specific keys to hold a list of minor versions we support for each major version. As keys, they can be overridden with `set` commands if we want to test nightly versions of Scala.

We also make sure to apply the full `crossScalaVersions` list even in projects that should only build with the default 2.12 version, like the `javalib`. Otherwise, tests with other minor 2.12 versions refuse to resolve because it is not the same 2.12 version everywhere.

### CODE REVIEW

**Comment by sjrd** [comment]
Note that I ran the CI in `full` mode on this PR, which is what the nightly does.

File: project/Build.scala [hunk 1]
```diff
@@ -502,6 +514,12 @@ object Build {
       }
   )
 
+  private val defaultScalaVersionOnlySettings = Def.settings(
+    // We still need to support all cross versions, otherwise ++2.12.x creates inconsistent graphs
```
Comment (gzm0) [inline project/Build.scala:518]: Move the comment about 2.12 being the default because of sbt here?

**Review by gzm0 — APPROVED** [review]
Just one suggestion about a comment.
