### PR TITLE
[no-master] Fix #3082: Refuse to generate a launcher for new-style main.

### LINKED ISSUE #3082: Incorrect handling of main generates broken code
A minimal repro is:
Scala.Js 0.6.19
build.sbt:
```scala
lazy val root = project
  .in(file("."))
  .settings(
    scalaVersion := "2.12.2",
    scalaJSUseMainModuleInitializer in Global := true
  )
  .enablePlugins(ScalaJSPlugin)
```
Main.scala:
```scala
package ui

object Main {
  def main(args: Array[String]): Unit = {
    println("Hello world")
  }
}
```
running `sbt run` I got:
```
[info] Running ui.Main
[error] [stdin]:40
[error]          global["Object"] === Object) ? global : this)["ui"]["Main"]().main();
[error]                                                             ^
[error] 
[error] TypeError: Cannot read property 'Main' of undefined
[error]     at [stdin]:40:61
[error]     at ContextifyScript.Script.runInThisContext (vm.js:23:33)
[error]     at Object.runInThisContext (vm.js:95:38)
[error]     at Object.<anonymous> ([stdin]-wrapper:6:22)
[error]     at Module._compile (module.js:571:32)
[error]     at evalScript (bootstrap_node.js:391:27)
[error]     at Socket.<anonymous> (bootstrap_node.js:188:13)
[error]     at emitNone (events.js:91:20)
[error]     at Socket.emit (events.js:188:7)
[error]     at endReadableNT (_stream_readable.js:975:12)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:119)
	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:168)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:718)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$73$$anonfun$apply$50$$anonfun$apply$51.apply(ScalaJSPluginInternal.scala:860)
	at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$73$$anonfun$apply$50$$anonfun$apply$51.apply(ScalaJSPluginInternal.scala:854)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
```

### PR DESCRIPTION
**Pull request by sjrd**
When using a new-style main class (with a `main(Array[String])` method), it is not possible to use launchers. In particular, the setting `scalaJSUseMainModuleInitializer` must be true.

Previously the sbt plugin was not checking this and would simply generate a broken launcher, resulting in a run-time error. Now we report a meaningful error when trying to generate the launcher.

### CODE REVIEW

File: sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala [hunk 1]
```diff
@@ -380,6 +380,18 @@ object ScalaJSPluginInternal {
     Attributed.blank(results.result()).put(scalaJSSourceFiles, realFiles.result())
   }
 
+  private def ensureOldStyleMainClass(mainClass: String,
+      scalaJSDiscoveredMainClassesValue: Map[String, Boolean]): Unit = {
+    val newStyle = scalaJSDiscoveredMainClassesValue.getOrElse(mainClass, false)
+    if (newStyle) {
+      throw new MessageOnlyException(
+          s"The main class $mainClass uses the new style with an " +
+          "Array[String] argument, but scalaJSUseMainModuleInitiliazer is " +
```
Comment (gzm0) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Typo: `scalaJSUseMainModuleInitiliazer`

Comment (sjrd) [inline sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala]: Fixed.
