### PR TITLE
Fix #5048: Wasm: Emit no files when no modules are defined.

### LINKED ISSUE #5048: Wasm backend fails when no modules are defined
Was: **Improve error message for Wasm backend when no modules are defined**

The current error message in `WebAssemblyLinkerBackend` is not clear for users not very familiar with Scala.js when no modules are defined. It says: `"The WebAssembly backend does not support multiple modules. Found: "`.

https://github.com/scala-js/scala-js/blob/7c95972e30c9897440e4404515d05bf663639daa/linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala#L69-L72

This message can be confusing and doesn't provide actionable steps to resolve the issue. We may want to update the error message to clearly state the problem and provide guidance on how to fix it: such as

```
The WebAssembly backend requires exactly one module, but no modules were found. You can do either:
1. Set 'scalaJSUseMainModuleInitializer := true', or
2. Annotate exported functions with @JSExportTopLevel"
```

**What JS backend says?**

JS backend says nothing on `fastLinkJS` when no module is found. Instead it prompts users to set `jsEnvInput` manually when no `main` module is found.
Should we keep silence when no modules are found in Wasm backend? I don't think so: when no modules are exported, there's nothing we can do with the Wasm module.

### PR DESCRIPTION
**Pull request by tanishiking**
fix https://github.com/scala-js/scala-js/issues/5048

After the 1.17.0 release, I received several questions about the error message: `The WebAssembly backend does not support multiple modules. Found: `. This is caused by users not exporting anything and not setting `scalaJSUseMainModuleInitializer := true`. However, for those unfamiliar with Scala.js, the current error message seems somewhat misleading.

---

The current error message in `WebAssemblyLinkerBackend` is not clear for users not very familiar with Scala.js when no modules are defined. It says: `"The WebAssembly backend does not support multiple modules. Found: "`.

https://github.com/scala-js/scala-js/blob/7c95972e30c9897440e4404515d05bf663639daa/linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala#L69-L72

This behavior is not aligned with JS backend, and it can be confusing for users.
This commit changes the behavior of Wasm backend when no modules are defined: delete previous artifacts and emit no files.

### CODE REVIEW

File: linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala [hunk 1]
```diff
@@ -66,6 +66,12 @@ final class WebAssemblyLinkerBackend(config: LinkerBackendImpl.Config)
     val onlyModule = moduleSet.modules match {
       case onlyModule :: Nil =>
         onlyModule
+      case Nil =>
+        throw new UnsupportedOperationException(
+            "The WebAssembly backend requires exactly one module. " +
+            "No modules were found. You can either " +
+            "1. Set 'scalaJSUseMainModuleInitializer := true', or " +
+            "2. Annotate exported functions with @JSExportTopLevel")
```
Comment (tanishiking) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/WebAssemblyLinkerBackend.scala:74]: Is there anything we can do?

**Review by sjrd — CHANGES_REQUESTED** [review]
Let's add `irJS2_12/fastLinkJS` as a test in `Jenkinsfile` to make sure this works.

Regarding the commit message:

* Use `Wasm:` instead of `[Wasm]` to match what we've been using so far.
* Could you arrange the commit message so that lines fit more or less in 72 characters?

Thanks.

**Review by sjrd — APPROVED** [review]
Thanks.

I took the liberty to adjust the commit message a bit more, to make it more consistent with our usual commit message (notably: past tense for what was before the commit; present tense for what is after the commit).

**Comment by tanishiking** [comment]
> (notably: past tense for what was before the commit; present tense for what is after the commit).

Thanks! That's clear and easy-to-understand instruction ❤️
