### PR TITLE
Fix #1777: LinkedList.size when larger than Int.MaxValue.

### LINKED ISSUE #1775: LinkedList peek and poll methods
Peek and poll methods in LinkedList are bugged,
peekLast refer to peekFirst...
https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/LinkedList.scala#L217

and poll methods doesn't return ```null``` in case of empty list but they thorws exception.

I'm fixing this problems in the next PR.

### LINKED ISSUE #1777: Bug with java.util.LinkedList.size when larger than Int.MAX_VALUE.
If the size of the `LinkedList` is larger than `Int.MAX_VALUE` the then `size` should return `Int.MAX_VALUE`. 

The current implementation uses a `var _size: Int` to track the size and updates it with `_size += 1` which loops back to `Int.MIN_VALUE` when the list grows to a size of `Int.MAX_VALUE` + 1.

### PR DESCRIPTION
**Pull request by andreaTP**
first of all a separate pr for fixing LinkedList bugs.

### CODE REVIEW

**Comment by andreaTP** [comment]
btw will rebase if it is ok

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LinkedListTest.scala [hunk 1]
```diff
@@ -38,7 +38,7 @@ abstract class LinkedListTest[F <: LinkedListFactory](listFactory: F) extends Ab
       ll.addFirst(1)
       ll.removeLast()
       ll.addFirst(2)
-      expect(ll.peekLast()).toEqual(2)
+      expect(ll.peekLast()).toEqual(1)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LinkedListTest.scala]: Hum, no, don't change this. `clear()` the list in the middle, or better yet, create a new one.
Otherwise this test does not test the same thing as before.

**Comment by sjrd** [comment]
Review by @nicolasstucki 

Since there are two bugs, with two completely distinct fixes, the two fixes should be in separate commits (but they can definitely be in the same PR), with their respective tests. (I understand the fix for `size()` can hardly be tested.)

File: javalib/src/main/scala/java/util/LinkedList.scala [hunk 2]
```diff
@@ -16,17 +16,17 @@ class LinkedList[E]() extends AbstractSequentialList[E]
   private var head: Node[E] = null
   private var last: Node[E] = null
 
-  private var _size = 0
+  private var _size: Double = 0
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: It would be good to have a (non-ScalaDoc) comment above this declaration of `_size` explaining why it is a `Double`.

File: test-suite/src/test/scala/org/scalajs/testsuite/javalib/LinkedListTest.scala (hunk 1 above)
Comment (andreaTP) [inline test-suite/src/test/scala/org/scalajs/testsuite/javalib/LinkedListTest.scala]: ok

File: javalib/src/main/scala/java/util/LinkedList.scala [hunk 3]
```diff
@@ -344,7 +348,7 @@ class LinkedList[E]() extends AbstractSequentialList[E]
 
   def descendingIterator(): Iterator[E] = {
     new Iterator[E] {
-      private val iter = listIterator(_size)
+      private val iter = listIterator(_size.toInt)
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: This would not work if the list has effectively more than `Int.MaxValue` elements.

**Comment by andreaTP** [comment]
if this looks ok I go to rebase it in 2 commits as suggested

**Comment by andreaTP** [comment]
please check this and I will rebase it just now, it will be in 0.6.4 elsewhere LinkedList will be totally bugged for an entire release... :-S

**Comment by andreaTP** [comment]
:+1:  just to get noticed XD

File: javalib/src/main/scala/java/util/LinkedList.scala [hunk 4]
```diff
@@ -16,17 +16,20 @@ class LinkedList[E]() extends AbstractSequentialList[E]
   private var head: Node[E] = null
   private var last: Node[E] = null
 
-  private var _size = 0
+  /**Inner size is represented with a Double to satisfy Collection size method requirement:
+   * If this collection contains more than Integer.MAX_VALUE elements, returns Integer.MAX_VALUE.
+   */
+  private var _size: Double = 0
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: Don't make it a ScalaDoc comment. So replace the second `*` by a space.

Also, cut the lines at 80 characters.

File: javalib/src/main/scala/java/util/LinkedList.scala [hunk 5]
```diff
@@ -211,16 +214,20 @@ class LinkedList[E]() extends AbstractSequentialList[E]
...
 
   def pollFirst(): E =
-    removeFirst()
+    if (isEmpty()) null.asInstanceOf[E]
+    else removeFirst()
 
   def pollLast(): E =
-    removeLast()
+    if (isEmpty) null.asInstanceOf[E]
+    else removeLast()
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: OK for this set of changes, fixing `peek/poll`. Please create a separate PR with only these changes, in one commit, with its unit tests. This is good to go.

File: javalib/src/main/scala/java/util/LinkedList.scala (hunk 4 above)
Comment (andreaTP) [inline javalib/src/main/scala/java/util/LinkedList.scala]: ok

File: javalib/src/main/scala/java/util/LinkedList.scala (hunk 5 above)
Comment (andreaTP) [inline javalib/src/main/scala/java/util/LinkedList.scala]: ok doing that

File: javalib/src/main/scala/java/util/LinkedList.scala (hunk 4 above)
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: For the commit message, use: `Fix #1775: Fix LinkedList.{peek,poll}{First,Last}.`

File: javalib/src/main/scala/java/util/LinkedList.scala (hunk 5 above)
Comment (sjrd) [inline javalib/src/main/scala/java/util/LinkedList.scala]: For the commit message, use `Fix #1775: Fix LinkedList.{peek,poll}{First,Last}.`

**Comment by andreaTP** [comment]
here you are :-)

**Comment by andreaTP** [comment]
sorry, it's becoming late... should I have to split the PRs?

**Comment by sjrd** [comment]
OK but I need a PR with only the first commit. The complication of the iterator in the second commit still seems like too much to me at the moment, but this bug is virtually not reachable, so it's not important that it be fixed right now. However #1775 should be fixed ASAP

**Comment by andreaTP** [comment]
ok

**Comment by andreaTP** [comment]
done

**Comment by andreaTP** [comment]
just to not loose the hard job of me and @sjrd  of yesterday evening, this is the second PR for the bug pointed out by @nicolasstucki

File: javalib/src/main/scala/java/util/LinkedList.scala [hunk 6]
```diff
@@ -348,17 +353,55 @@ class LinkedList[E]() extends AbstractSequentialList[E]
...
   def descendingIterator(): Iterator[E] = {
     new Iterator[E] {
-      private val iter = listIterator(_size)
+
+      private var last: Double = -1
+      private var i: Double = _size
+
+      private var currentNode: Node[E] = null
+
+      private var lastNode: Node[E] = LinkedList.this.last
```
Comment (nicolasstucki) [inline javalib/src/main/scala/java/util/LinkedList.scala]: You could write this class using only the `currentNode`, there is no real need for the `lastNode`. If you initialize `private var currentNode: Node[E] = LinkedList.this.last` you can implement `next` as:
```scala
  ... // check hasNext, update i and last
  val nextVlaue = currentNode.vlaue
  currentNode = currentNode.prev
  nextVlaue
}
```
and `remove` with:
```scala
def remove(): Unit = {
  checkThatHasLast()
  val toBeRemoved = currentNode.next
  if (toBeRemoved.next eq null) removeLast()
  else removeNode(toBeRemoved)
  ... // update i and last
}
```

**Comment by nicolasstucki** [comment]
Thats all, otherwise LGTM

File: javalib/src/main/scala/java/util/LinkedList.scala (hunk 6 above)
Comment (andreaTP) [inline javalib/src/main/scala/java/util/LinkedList.scala]: fixed

**Comment by andreaTP** [comment]
review this please

**Comment by sjrd** [comment]
Just mentioning that, at this point, nothing should be merged, since we're in a release process. After the release is complete, all in-progress PRs must be rebased on top of the "Towards 0.6.5." commit (or later master). We have sort of a "policy" not to have merges across versions.

**Comment by andreaTP** [comment]
no problem, it is here just to close the "dev" part, and to not leave pending code review, on my side, it will be trivial to rebase this!
so please take a look at this trivial fix so we can manage it even if you are out.
(just a timing matter, I will be out for 2 weeks when you are going to be back ^^ )

**Comment by sjrd** [comment]
@nicolasstucki has all the necessary rights and authority to review and merge on his own. I'm the only core dev. You don't need me here ;-)

**Comment by nicolasstucki** [comment]
@andreaTP I'll merge this PR as soon as you rebase and the test pass on Jenkins.

**Comment by andreaTP** [comment]
@nicolasstucki  should be ok

**Comment by nicolasstucki** [comment]
Dear Jenkins, test this please.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by andreaTP** [comment]
Jenkins is on vacations? ;-)

**Comment by sjrd** [comment]
It might have been. It's back online.
Anyway, this will need to be rebased when #1789. Currently the build is actually broken, so there's no chance building this PR can succeed.

**Comment by andreaTP** [comment]
Doing it asap

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by nicolasstucki** [comment]
@andreaTP you still need to rebase once

**Comment by andreaTP** [comment]
hope this is enough

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
Jenkins, test this please

**Comment by sjrd** [comment]
retest this please

**Comment by nicolasstucki** [comment]
retest this please

**Comment by nicolasstucki** [comment]
@sjrd the build timed-out, could you reset this test

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
There are 3 commits in this PR. This is not normal. Something went wrong with a rebase, I guess.

**Comment by andreaTP** [comment]
To be honest I have to check how to do that... the order is the problem now...

**Comment by gzm0** [comment]
Note that GitHub orders commits based on the commit date, not their actual order in the commit graph. (Which is IMHO a pretty big fail...).

**Comment by andreaTP** [comment]
...hope this time is ok, please if you could check it today I'm available, otherwise I will be out 2 weeks

**Comment by nicolasstucki** [comment]
Now I only see one commit. Weren't there two before?

**Comment by sjrd** [comment]
The other commit that was initially in this PR was extracted in another PR merged before 0.6.4.

**Comment by sjrd** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
retest this please
