### PR TITLE
Fix #1804: Do binary compat checks only for published artifacts.

### LINKED ISSUE #1804: Binary compatibility check failing in nightly
The nightlies have been failing for a while. The later ones claim there is some kind of binary incompatibility issue.

This needs immediate attention. @sjrd, do you have a couple of cycles?

### PR DESCRIPTION
**Pull request by sjrd**
It is irrelevant, and wrong, to check binary compatibility checks with Scala versions that are not actually used to *publish* the artifacts. Doing them caused some checks to fail when testing with earlier versions of the Scala compiler, because more recent versions produce less private boilerplate members.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0 
Nightly: https://scala-webapps.epfl.ch/jenkins/job/scalajs-matrix-build/2531/

**Comment by sjrd** [comment]
retest this please

File: project/Build.scala [hunk 1]
```diff
@@ -51,14 +51,19 @@ object Build extends sbt.Build {
...
   val previousArtifactSetting: Setting[_] = {
     previousArtifact := {
       val scalaV = scalaVersion.value
       val scalaBinaryV = scalaBinaryVersion.value
-      if (newScalaBinaryVersionsInThisRelease.contains(scalaBinaryV)) {
+      if (!scalaVersionsUsedForPublishing.contains(scalaV)) {
+        // This artifact will not be published. Binary compatibility is irrelevant.
+        None
+      } else if (newScalaBinaryVersionsInThisRelease.contains(scalaBinaryV)) {
         // New in this release, no binary compatibility to comply to
```
Comment (gzm0) [inline project/Build.scala]: Hahaha, I like the two branches to execute a different comment :)

**Comment by gzm0** [comment]
LGTM
