### PR TITLE
Fix #3267: Always use the enclosing class type for this local vars.

### LINKED ISSUE #3267: Linking error with @tailrec method inside a trait with a self-type, on Scala 2.12+
We stumbled upon a case which the linker doesn't seem to handle while porting http4s ( https://github.com/http4s/http4s/pull/1412 ). 

I made an as minimal repro as I could manage in https://github.com/oyvindberg/scalajs-linker-repro/blob/master/src/main/scala/http4s/Tester.scala . 

As you can see there are several features at work here (macros (`rule`), self types, inheritance), and there are two acceptable workarounds to make it run. It's not a blocker for the port, but it certainly cost me enough headache to figure out that I figured I should report it properly.

Error message is
```
sbt:repro> run
[info] Compiling 1 Scala source to /home/olvind/pr/scalajs-linker-repro/target/scala-2.12/classes ...
[info] Done compiling.
[info] Fast optimizing /home/olvind/pr/scalajs-linker-repro/target/scala-2.12/repro-fastopt.js
[error] Referring to non-existent method http4s.Tester$$anon$2.b()org.parboiled2.Rule
[error]   called from http4s.Tester$Helpers.rec$2(scala.Int,scala.Long,scala.collection.immutable.VectorBuilder,scala.Int,scala.Int)scala.Boolean
[error]   called from http4s.Tester$$anon$1.rec$2(scala.Int,scala.Long,scala.collection.immutable.VectorBuilder,scala.Int,scala.Int)scala.Boolean
[error]   called from http4s.Tester$Helpers.a()org.parboiled2.Rule
[error]   called from http4s.Tester$$anon$1.a()org.parboiled2.Rule
[error]   called from http4s.Tester$.$$anonfun$one$1(http4s.Tester$$anon$1)org.parboiled2.Rule
[error]   called from http4s.Tester$.one(java.lang.String)scala.collection.Seq
[error]   called from http4s.Tester$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   http4s.Tester$$anon$1
[error]   http4s.Tester$
[error] Referring to non-existent method http4s.Tester$$anon$2.b()org.parboiled2.Rule
[error]   called from http4s.Tester$Helpers.rec$1(scala.Int,scala.Long,scala.collection.immutable.VectorBuilder,scala.Int,scala.Int)scala.Boolean
[error]   called from http4s.Tester$$anon$1.rec$1(scala.Int,scala.Long,scala.collection.immutable.VectorBuilder,scala.Int,scala.Int)scala.Boolean
[error]   called from http4s.Tester$Helpers.wrapped$2()scala.Boolean
[error]   called from http4s.Tester$$anon$1.wrapped$2()scala.Boolean
[error]   called from http4s.Tester$Helpers.a()org.parboiled2.Rule
[error]   called from http4s.Tester$$anon$1.a()org.parboiled2.Rule
[error]   called from http4s.Tester$.$$anonfun$one$1(http4s.Tester$$anon$1)org.parboiled2.Rule
[error]   called from http4s.Tester$.one(java.lang.String)scala.collection.Seq
[error]   called from http4s.Tester$.main([java.lang.String)scala.Unit
[error]   called from core module module initializers
[error] involving instantiated classes:
[error]   http4s.Tester$$anon$1
[error]   http4s.Tester$
[error] org.scalajs.core.tools.linker.LinkingException: There were linking errors
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:160)
[error]         at org.scalajs.core.tools.linker.frontend.BaseLinker.linkInternal(BaseLinker.scala:108)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.$anonfun$link$3(LinkerFrontend.scala:63)
[error]         at org.scalajs.core.tools.logging.Logger.time(Logger.scala:28)
[error]         at org.scalajs.core.tools.logging.Logger.time$(Logger.scala:26)
[error]         at org.scalajs.sbtplugin.Loggers$SbtLoggerWrapper.time(Loggers.scala:7)
[error]         at org.scalajs.core.tools.linker.frontend.LinkerFrontend.link(LinkerFrontend.scala:62)
[error]         at org.scalajs.core.tools.linker.Linker.$anonfun$link$1(Linker.scala:52)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at org.scalajs.core.tools.linker.Linker.guard(Linker.scala:69)
[error]         at org.scalajs.core.tools.linker.Linker.link(Linker.scala:50)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1(ClearableLinker.scala:52)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.$anonfun$link$1$adapted(ClearableLinker.scala:52)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.linkerOp(ClearableLinker.scala:63)
[error]         at org.scalajs.core.tools.linker.ClearableLinker.link(ClearableLinker.scala:52)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$11(ScalaJSPluginInternal.scala:310)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$10(ScalaJSPluginInternal.scala:315)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / fastOptJS) org.scalajs.core.tools.linker.LinkingException: There were linking errors
```

### PR DESCRIPTION
**Pull request by sjrd**
The fix for #3058 in 1518b704802ea95c3521831d91610905f022ca25 was wrong. It made things worse for cases where the self type S of the enclosing class C is not a subtype of C.

It turns out that, although scalac *declares* the `_$this` local variable with the self type S, it is in fact *used* everywhere as if had the type C. This is not very surprising, given that it compiles it down to `this` in the bytecode (yes, it *reassigns* `this` for tailrec methods).

In this commit, we therefore ignore the declared type of `_$this` and always patch it up to C, the enclosing class type. This means we need to adapt the right-hand-side of the initial declaration, and of reassignments in calls to the tailrec label. Everywhere else, a `This()` is used, which naturally translates to having the type C.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala [hunk 1]
```diff
@@ -2493,23 +2535,62 @@ abstract class GenJSCode extends plugins.PluginComponent
...
+                actualArg.tpe != tpe && tpe != jstpe.AnyType) {
+              /* See the comments in genMethodDef() for further details about
+               * the similar fixup.
+               */
+              actualArg match {
+                case js.AsInstanceOf(underlying, _) if underlying.tpe == tpe =>
+                  underlying
+                case _ =>
+                  js.AsInstanceOf(actualArg, tpe.asInstanceOf[jstpe.ClassType])
+              }
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala]: Have you considered factoring this in a helper? Maybe `stripOrInsertAsInstanceOf`?

**Comment by sjrd** [comment]
Updated.
