### PR TITLE
Fix #5026: Hash internal module names if they get too long

### LINKED ISSUE #5026: Linker cannot process code containing non-English identifiers (Windows-only)
In my project sometimes Russian names are used for class and object identifiers. For example:

```scala
package company.root_module.domain

object НазваниеКлассаНаРусскомЯзыке

object Main {
  def main(args: Array[String]): Unit = {
    println(НазваниеКлассаНаРусскомЯзыке)
  }
}
```
Unfortunately, this code is not processed by the ScalaJS linker if the linker is configured to generate ES modules, breaking them down into small modules within the application package to work effectively with bundlers like Parcel:

```scala
// Emit modules in the most Parcel-friendly way
scalaJSLinkerConfig ~= {
  _.withModuleKind(ModuleKind.ESModule)
    .withModuleSplitStyle(ModuleSplitStyle.SmallModulesFor(List("company.root_module")))
}
```

## How to reproduce

1. Clone repository `https://github.com/nartamonov/reproduce-scalajs-bug`
2. Run `sbt fastLinkJS`

The following error will appear:

```
C:\Dev\repoduce-js-bug\project_files (master -> origin)
λ sbt fastLinkJS
Picked up JAVA_TOOL_OPTIONS: -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
Picked up JAVA_TOOL_OPTIONS: -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
[info] welcome to sbt 1.10.1 (Eclipse Adoptium Java 22.0.1)
[info] loading settings for project project_files-build from plugins.sbt ...
[info] loading project definition from C:\Dev\repoduce-js-bug\project_files\project
[info] loading settings for project project_files from build.sbt ...
[info] set current project to root-module (in build file:/C:/Dev/repoduce-js-bug/project_files/)
[info] compiling 1 Scala source to C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\classes ...
[info] Fast optimizing C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt
[error] java.nio.file.FileSystemException: C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt\.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp: Синтаксическая ошибка в имени файла, имени папки или метке тома
[error]         at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error]         at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error]         at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234)
[error]         at java.base/java.nio.file.Files.newByteChannel(Files.java:379)
[error]         at java.base/java.nio.file.Files.createFile(Files.java:657)
[error]         at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
[error]         at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:159)
[error]         at java.base/java.nio.file.Files.createTempFile(Files.java:878)
[error]         at org.scalajs.linker.PathOutputDirectory$Impl.$anonfun$writeAtomic$2(PathOutputDirectory.scala:86)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
[error]         at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3977)
[error]         at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3959)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
[error]         at scala.concurrent.package$.blocking(package.scala:146)
[error]         at org.scalajs.linker.PathOutputDirectory$Impl.$anonfun$writeAtomic$1(PathOutputDirectory.scala:85)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:42)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1726)
[error]         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.compute(ForkJoinTask.java:1717)
[error]         at java.base/java.util.concurrent.ForkJoinTask$InterruptibleTask.exec(ForkJoinTask.java:1641)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[error] (Compile / fastLinkJS) java.nio.file.FileSystemException: C:\Dev\repoduce-js-bug\project_files\target\scala-2.13\root-module-fastopt\.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp: Синтаксическая ошибка в имени файла, имени папки или метке тома
[error] Total time: 3 s, completed 30 авг. 2024 г., 17:29:42
```

The error text is in Russian, as the operating system locale is Russian. Translated as "Syntax error in file name, folder name or volume label".

## Analysis

Presumably, the error occurs due to the way of encoding Unicode identifiers in a language other than English:

```
.tmp-company.root_module.domain.-u00041dН-u000430а-u000437з-u000432в-u000430а-u00043dн-u000438и-u000435е-u00041aК-u00043bл-u000430а-u000441с-u000441с-u000430а-u00041dН-u000430а-u000420Р-u000443у-u000441с-u000441с-u00043aк-u00043eо-u00043cм-u00042fЯ-u000437з-u00044bы-u00043aк-u000435е$.js3696010906854088543.tmp
```

As a result, the file length is 312 characters. I use Windows 10, and it was configured to supports long file paths. However, although the path itself has no length limit, the restriction still has a path component, [usually it cannot exceed 255 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation):

> The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the [GetVolumeInformation](https://learn.microsoft.com/en-us/windows/win32/api/FileAPI/nf-fileapi-getvolumeinformationa) function (this value is commonly 255 characters).

There is no way around this limitation, as far as I know. It would be nice to find a way to encode the identifiers in a more economical way.

### PR DESCRIPTION
**Pull request by gzm0**
We could improve on this later on, by allowing more non-ASCII characters. However, in any case we need an escape hatch like this.

### CODE REVIEW

File: linker/shared/src/test/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGeneratorTest.scala [hunk 1]
```diff
@@ -42,6 +47,10 @@ class InternalModuleIDGeneratorTest {
 
     test("test.-Public.", "test.Public")
     test("test.-Other-Public.", "test.OtherPublic")
+
+    // Too long resulting name (#5026)
+    test("-xb204ce10b523cf072bd79c3142cd349f155632b8", "НазваниеКлассаНаРусскомЯзыке")
+    test("-x4a1f096d13ea514c484d8604fd6984a699983e13.", "日本語でも長い名前になれます")
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/frontend/modulesplitter/InternalModuleIDGeneratorTest.scala:53]: Review by @tanishiking 😇?

**Review by sjrd — APPROVED** [review]

**Review by tanishiking — APPROVED** [review]
LGTM 😄
