### PR TITLE
Fix #4391: Give java.lang.Object.clone() its own IR node

### LINKED ISSUE #4391: java.lang.Object.clone() needs its own IR node
Currently, `java.lang.Object.clone()` is defined as follows:
https://github.com/scala-js/scala-js/blob/4263c9872729f1c13d391a7995aad0453e1bda68/project/JavaLangObject.scala#L95-L114
with a call to a helper method `java.lang.ObjectClone.clone(o: Object): Object`, defined in
https://github.com/scala-js/scala-js/blob/v1.4.0/javalanglib/src/main/scala/java/lang/ObjectClone.scala
The implementation of that method exploits undefined behavior to achieve its effect. It assumes that it can use JavaScript introspection tools to copy the object as a regular JS object, but our IR and our spec do not guarantee that this is possible.

For example, in an IR interpreter, this is incorrect, and we would have to intercept `Object.clone()` to behave in a special way. With a non-JavaScript implementation such as with Wasm, we would have the same issue. Actually, we *already* have issues with the existing implementation because it is not always safe to inline. See https://github.com/scala-js/scala-js/issues/3778 and its fix https://github.com/scala-js/scala-js/commit/56371e91ee38b0c9cd262803351b2e8c2baa0cff.

Therefore, just like we gave a dedicated IR node to `System.identityHashCode()`, I think we need to give a dedicated IR node to (the implementation of) `java.lang.Object.clone()`. That IR node would contain the spec of cloning regular objects and arrays alike, which would make things like #3778 non-issues.

The only open question is whether the semantics of that new IR node, let's call it `Clone(expr)`, should deal with the `java.lang.Cloneable` semantics itself, or whether it should leave that to the implementation in the IR of `java.lang.Object.clone()`. In other words, do we do:

1. Implement `java.lang.Object.clone()` as
   ```scala
   def clone(): Object =
     if (this.isInstanceOf[Cloneable]) <clone>(this)
     else throw new CloneNotSupportedException()
   ```
   and define the semantics of `<clone>(expr)` to *always* clone the value, regardless of whether it implements `Cloneable`. (This makes `<clone>` correspond to what `ObjectClone.clone(o)` does today.)
2. Implement `java.lang.Object.clone()` as
   ```scala
   def clone(): Object =
     if (this.isInstanceOf[Cloneable]) <clone>(this.asInstanceOf[Cloneable])
     else throw new CloneNotSupportedException()
   ```
   (note the `asInstanceOf`) and require in the type system of the IR that `<clone>` only accepts `Cloneable` values.
3. Implement `java.lang.Object.clone()` as
   ```scala
   def clone(): Object = <clone>(this)
   ```
   and make `<clone>` itself check for `isInstanceOf[Cloneable]` and throw `CloneNotSupportedException`.

The advantage of keeping the `isInstanceOf` check outside of `<clone>` is that it can be optimized away by the optimizer in many (if not all) cases. Indeed, since `Object.clone()` is `protected`, it is typically called as a super call, from an override of `clone()` that lives in a class that implements `Cloneable`. So when the optimizer inlines `Object.clone()` at that call site, it constant-folds the `isInstanceOf` test as `true`. (This happens today with the current implementation.)

If we do that, however, and we let `<clone>` accept any type of value, then the *implementation* of `<clone>` must indeed be able to deal with any value, including non-`Cloneable` ones. This may not be an issue for the existing JavaScript back-end, but who knows if it's going to be limiting in a Wasm back-end?

That's what solution 2 solves, by demanding in the type system that `<clone>` only be used with values that are statically known to be `Cloneable`.

Solution 3 has the same advantage as solution 2 wrt. that. However, it doesn't allow the optimizer to optimize away the instance test.

So IMO Solution 2 is the best one.

Thoughts?

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

**Comment by sjrd** [comment]
@gzm0 This can now be reviewed (the last two commits belong to this PR), although it will need a rebase once #4396 and #4382 are both merged.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala [hunk 1]
```diff
@@ -370,6 +371,105 @@ private[emitter] object CoreJSLib {
...
+                  const(getOwnPropertySymbols,
+                      genIdentBracketSelect(ObjectRef, "getOwnPropertySymbols") ||
+                      genArrowFunction(paramList(o), Return(ArrayConstr(Nil)))),
+                  ownKeysFun := genArrowFunction(paramList(o), Return {
+                    Apply(
+                        genIdentBracketSelect(
+                            Apply(genIdentBracketSelect(ObjectRef, "getOwnPropertyNames"), o :: Nil),
+                            "concat"),
+                        Apply(getOwnPropertySymbols, o :: Nil) :: Nil)
+                  })
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:442]: Indent by 2? (also below)?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala [hunk 2]
```diff
@@ -1251,8 +1251,9 @@ private[emitter] class FunctionEmitter(sjsGen: SJSGen) {
         case ArrayLength(array)      => test(array)
         case RecordSelect(record, _) => test(record)
         case IsInstanceOf(expr, _)   => test(expr)
-        case IdentityHashCode(expr)  => test(expr)
         case GetClass(arg)           => test(arg) // may NPE but that is UB.
+        case Clone(arg)              => test(arg) // may NPE but that is UB.
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala:1255]: Hum, maybe I'm not understanding the definition of "pureness" correctly here: Won't `Clone` return a different result every time it is called? Or in other words, if `Clone` is pure, why is `NewArray` not?

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala [hunk 3]
```diff
@@ -2597,6 +2603,31 @@ private[emitter] class FunctionEmitter(sjsGen: SJSGen) {
         case GetClass(expr) =>
           genCallHelper("objectGetClass", transformExprNoChar(expr))
 
+        case Clone(expr) =>
+          val newExpr = transformExprNoChar(expr)
+          expr.tpe match {
+            /* If the argument is known to be an array, directly call its
+             * `clone__O` method.
+             */
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala:2611]: Maybe document that this is a theoretical case that only happens if `Clone` is used outside of `java.lang.Object` (which is allowed, it just tripped me off).

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala [hunk 4]
```diff
@@ -19,14 +19,11 @@ private[emitter] object EmitterNames {
   val UndefinedBehaviorErrorClass =
     ClassName("org.scalajs.linker.runtime.UndefinedBehaviorError")
 
-  /* In theory, some of the following could be computed from the Class
+  /* In theory, java.lang.CharSequence could be computed from the Class
    * Hierarchy. However, that would be require dealing with incremental runs,
-   * which would be overkill since these things are in fact known to be static.
+   * which would be overkill since it is in fact known to be static.
    */
```
Comment (gzm0) [inline linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala:25]: Doesn't this comment also apply to the method names below?

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala [hunk 5]
```diff
@@ -1269,6 +1274,36 @@ object Serializers {
 
             MethodDef(flags, name, originalName, args, resultType, body)(
                 optimizerHints, optHash)
+          } else if ( // temp: test backward compat
+              flags.namespace == MemberNamespace.Public &&
+              owner == ObjectClass &&
```
Comment (gzm0) [inline ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1279]: Instead of replacing `clone_O` directly, have you considered replacing the implementation `ObjectClone.clone` with `Clone(AsInstanceOf(args(0).ref, cloneableClassType))`? It feels like this is less "invasive".

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala (hunk 5 above)
Comment (sjrd) [reply ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1279]: Hum, I had not considered that 🤔 It might be better, indeed. Although it means that the deserializer hack has to know about `java.lang.ObjectClone`, which was as a whole an implementation detail of the previous stdlib; whereas with the current implementation it only needs to know about `java.lang.Object`, which is specced.

I'm not sure which of the invasiveness argument or the has-to-know-implementation-details argument is strongest.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/CoreJSLib.scala:442]: Yes, indeed. I'll do that when I rebase on top of #4382.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala (hunk 4 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/EmitterNames.scala:25]: Ah, that's a good point. I'll revert the change.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala:1255]: Ah, well, you're understanding perfectly well that I made a basic mistake ^^ It is side-effect-free but it is not pure! I'll fix it.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala (hunk 3 above)
Comment (sjrd) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala:2611]: It's not just theoretical. This happens every time we call `clone()` on an array, in fact. For example, in
```scala
val a: Array[Int] = ...
val b = a.clone()
```
the second statement as the following IR
```
val b: int[] = a.clone__O().asInstanceOf[int[]]
```
The optimizer sees `a.clone__O()` and, unlike previously where it was explicitly told *not* to inline it, it will now be able to inline it from `java.lang.Object.clone()`. Since it knows that the array type is a `Cloneable`, it simplifies it as
```scala
val b: int[] = <clone>(a).asInstanceOf[int[]]
```
and since the `<clone>` opcode is "polymorphic", in the sense that its result type is the type of its argument, the optimizer knows that the type of `<clone>(a)` is an `int[]` and can further simplify as
```scala
val b: int[] = <clone>(a)
```
This reaches the emitter, and falls into this case, which we eventually compile as
```javascript
var b = a.clone__O();
```

---

By comparison, before this commit, we prevented the inlining, and that meant that the `asInstanceOf` had to stay, resulting in the following JavaScript:
```javascript
var b = $asArrayOf_I(a.clone__O(), 1);
```

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala (hunk 5 above)
Comment (gzm0) [reply ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1279]: But isn't this a good thing in this case? Because in the previous stdlib, `java.lang.Object` was not broken, `java.lang.ObjectClone` was. So we are fixing a thing that was knowingly broken. IMO this has nothing to do with specification but with history.

File: linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala (hunk 2 above)
Comment (gzm0) [reply linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/FunctionEmitter.scala:1255]: Maybe we should document what we mean by "pure" in `isPureExpression` :) (IIUC, referentially transparent n.b. with object identity and assignment).

File: ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala (hunk 5 above)
Comment (sjrd) [reply ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1279]: Yes, we can look at it that way. I don't have a strong opinion, so I'll go with yours. ;)

Comment (sjrd) [reply ir/shared/src/main/scala/org/scalajs/ir/Serializers.scala:1279]: So, I tried that, but it kind of blew off a bit, because, although `java.lang.ObjectClone.clone(o)` could be inlined, the `LoadModule(ObjectClone$)` remained (its constructor is not pure) and therefore the code size exploded (4 KB more in fastOpt). Of course it's "solved" with the last commit, but it still would have meant that the new linker would produce significantly worse code for the old stdlib.

I reverted to the solution where I patch `j.l.Object.clone()` directly. But if you want I can try and go one step further, and also patch the constructor to empty it out or something.

**Review by sjrd — COMMENTED** [review]
Updated.

**Review by gzm0 — CHANGES_REQUESTED** [review]
`ObjectClone` should also be removed from the minilib whitelist.

**Review by sjrd — COMMENTED** [review]
Rebased and updated.

**Review by gzm0 — APPROVED** [review]
