### PR TITLE
Fix #3939: Ignore methods in jl.Object in non-native JS classes

### LINKED ISSUE #3939: Compile error on a method with @JSName("finalize") in a non-native JS class
```scala
// based on https://github.com/scala-js/scalajs-tutorial/blob/0.6.x/src/main/scala/tutorial/webapp/TutorialApp.scala
package tutorial.webapp

import scala.scalajs.js

@js.annotation.ScalaJSDefined
class Test extends js.Object {
  @js.annotation.JSName("finalize")
  def foo(): Unit = {
    println("success")
  }
}

object TutorialApp {
  def main(args: Array[String]): Unit = {
    new Test().foo()
    println("hoge")
  }
}
```

This code should print "success" and "hoge", but it cannot be compiled:

Scala 2.12.10 / ScalaJS 0.6.31 (and 1.0.0-RC2)

```
sbt:Scala.js Tutorial> run
[info] Compiling 1 Scala source to D:\hoge\target\scala-2.12\classes ...
[warn] D:\hoge\src\main\scala\tutorial\webapp\TutorialApp.scala:5:2: @ScalaJSDefined is deprecated: add `-P:scalajs:sjsDefinedByDefault` to your scalac options and simply remove `@ScalaJSDefined`
[warn] @js.annotation.ScalaJSDefined
[warn]  ^
[error] D:\hoge\src\main\scala\tutorial\webapp\TutorialApp.scala:8:7: Cannot disambiguate overloads for method finalize with types
[error]   ()Unit
[error]   ()Unit
[error]   def foo(): Unit = {
[error]       ^
[warn] one warning found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed 2020/01/22 22:03:20
```

In ScalaFiddle, it can be compiled but it only prints "hoge": https://scalafiddle.io/sf/rPmTeX6/0

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

**Comment by gzm0** [comment]
Seems like the `has-pr` label died :)

**Comment by sjrd** [comment]
> Seems like the `has-pr` label died :)

Hum? What do you mean?

**Comment by gzm0** [comment]
> Hum? What do you mean?

There seems to be native support now via "Linked issues" / "Linked pull requests". So there's no need for a label anymore.

**Comment by sjrd** [comment]
Oh, I see. And yes, it's even shown in the issue list. So indeed, that sounds like this label is not useful anymore :)

File: compiler/src/test/scala/org/scalajs/core/compiler/test/ScalaJSDefinedTest.scala [hunk 1]
```diff
@@ -691,4 +691,39 @@ class ScalaJSDefinedTest extends DirectTest with TestHelpers {
...
+  def overrideJavaLangObjectMethod: Unit = {
+    val objs = List("class", "object")
+
+    for {
+      obj <- objs
+    } {
+      s"""
+      $obj A extends js.Object {
+        override def clone(): Object = null
+        override def finalize(): Unit = ()
```
Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/ScalaJSDefinedTest.scala]: I wonder if we shouldn't allow `clone()` and `finalize()` nevertheless. Since they are `protected`, they can never be called on an `Object`. They can only be called on a subclass that redefines them to be public. So in practice the "dangerous" behavior of an `override` not actually overriding some behavior cannot be observed. Therefore, it doesn't seem so dangerous.

The only real danger is overriding `hashCode()` and `equals(Any)`, because there the false overriding relationship can actually be observed. Perhaps we should target the warning at those two methods, and specifically mention them in the warning message?

File: compiler/src/test/scala/org/scalajs/core/compiler/test/ScalaJSDefinedTest.scala [hunk 2]
```diff
@@ -691,4 +691,39 @@ class ScalaJSDefinedTest extends DirectTest with TestHelpers {
     """
   }
 
+  @Test
+  def overrideJavaLangObjectMethod: Unit = {
+    val objs = List("class", "object")
```
Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/ScalaJSDefinedTest.scala]: We should also have a test for what we want to happen in a `trait` (with abstract methods, obviously). We probably also want to warn in that case.

Comment (sjrd) [reply compiler/src/test/scala/org/scalajs/core/compiler/test/ScalaJSDefinedTest.scala]: We should also decide whether we want to warn for such definitions in `@js.native` stuff.

**Comment by gzm0** [comment]
Updated. I have split the warning into a separate issue.
