### PR TITLE
Fix #4526: Find module accessor of nested private companions

### LINKED ISSUE #4526: Compiler crashes on nested JS class with default constructor params with private companion
```
package helloworld

import scala.scalajs.js
import js.annotation._

class A {
  class B(x: Int = 1) extends js.Object

  private object B
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    val a = new A
    val x = new a.B()
    println(x)
  }
}
```

Crashes:
```
[info] compiling 1 Scala source to /home/tos/gh/scala-js/examples/helloworld/.2.12/target/scala-2.12/classes ...
[error] Error while emitting HelloWorld.scala
[error] assertion failed: 
[error]   need default getter for method helloworld.A$B.<init>
[error]      while compiling: /home/tos/gh/scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala
[error]         during phase: jscode
[error]      library version: version 2.12.14
[error]     compiler version: version 2.12.14
[error]   reconstructed args: -bootclasspath /home/tos/.sbt/boot/scala-2.12.14/lib/scala-library.jar -deprecation -encoding utf8 -feature -unchecked -Xfatal-warnings -Wconf:cat=feature:w -Wconf:cat=unchecked:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath /home/tos/gh/scala-js/examples/helloworld/.2.12/target/scala-2.12/classes:/home/tos/gh/scala-js/library/.2.12/target/scala-2.12/scalajs-library_2.12-1.7.0-SNAPSHOT.jar -Xplugin:/home/tos/gh/scala-js/compiler/.2.12/target/scala-2.12/scalajs-compiler_2.12.14-1.7.0-SNAPSHOT.jar
[error] 
[error]   last tree to typer: TypeTree(class A$B)
[error]        tree position: line 20 of /home/tos/gh/scala-js/examples/helloworld/src/main/scala/helloworld/HelloWorld.scala
[error]             tree tpe: helloworld.A$B
[error]               symbol: class A$B in package helloworld
[error]    symbol definition: class A$B extends Object (a ClassSymbol)
[error]       symbol package: helloworld
[error]        symbol owners: class A$B
[error]            call site: object A$B in package helloworld in package helloworld
[error] 
[error] == Source file context for tree position ==
[error] 
[error]     17 object HelloWorld {
[error]     18   def main(args: Array[String]): Unit = {
[error]     19     val a = new A
[error]     20     val x = new a.B()
[error]     21     println(x)
[error]     22   }
[error]     23 }
[error] one error found
[error] (helloworld2_12 / Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Jul 10, 2021, 11:50:45 AM
```

This assertion triggers: https://github.com/scala-js/scala-js/blob/a73746b6a71e86b76c6926128b793ed11472e52a/compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala#L716-L717

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala [hunk 1]
```diff
@@ -697,57 +697,83 @@ trait GenJSExports[G <: Global with Singleton] extends SubComponent {
...
+              sym.isModule && sym.unexpandedName == name
+            }.getOrElse {
+              throw new AssertionError(
+                s"couldn't find module accessor for ${owner.fullName} at $pos")
+            }
+          }
+
+          val receiver = captures.head
+
+          val trgSym = modAccessor.tpe.resultType.typeSymbol
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala:752]: IIUC, these are the only lines that have an actual change of behavior. Perhaps it would be worth it to decompose this commit in two:
1. The refactoring that computes `(trgSym, trgTree)` in one go, but preserving the behavior, and then
2. This change of behavior.

That might help further bisecting if we have to come back to this area.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala [hunk 2]
```diff
@@ -697,57 +697,83 @@ trait GenJSExports[G <: Global with Singleton] extends SubComponent {
...
+           */
+          val trgSym = enteringPhase(currentRun.namerPhase) {
+            owner.linkedClassOfClass
+          }
+          (trgSym, genLoadModule(trgSym))
+        } else if (!isNested && static) {
+          assert(captures.isEmpty, "expected empty captures")
+          (owner, genLoadModule(owner))
+        } else if (sym.isClassConstructor || static) {
+          assert(isNested, "unexpected isNested")
```
[the remark this answers is not in the document]
Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: I have re-structured the flow and added some explanations. Is it clearer now?

(I refrained from using a match, because the tests would get too far away from their values, so it'd be hard to see what case `(true, true, false)` is).

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 1 above)
Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: Hrm... If I do that, then I need to duplicate the logic of `trgSym` in the `if (isNested)` block (or introduce a change in behavior there already). Or am I missing something?

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala [hunk 3]
```diff
@@ -697,24 +697,79 @@ trait GenJSExports[G <: Global with Singleton] extends SubComponent {
...
+          val modAccessor = {
+            val name = enteringPhase(currentRun.typerPhase) {
+              owner.unexpandedName.toTermName
+            }
+
+            outer.info.members.find { sym =>
+              sym.isModule && sym.unexpandedName == name
+            }.getOrElse {
+              throw new AssertionError(
+                s"couldn't find module accessor for ${owner.fullName} at $pos")
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala:739]:
```suggestion
              throw new AssertionError(
                  s"couldn't find module accessor for ${owner.fullName} at $pos")
```

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala [hunk 4]
```diff
@@ -697,24 +697,79 @@ trait GenJSExports[G <: Global with Singleton] extends SubComponent {
...
+          (trgSym, trgTree)
+        } else if (sym.isClassConstructor) {
+          assert(captures.isEmpty, "expected empty captures")
+
+          /* Get the companion module class.
+           * For classes nested inside modules the sym.owner.companionModule
+           * can be broken, therefore companionModule is fetched at
+           * uncurryPhase.
+           */
+          val trgSym = enteringPhase(currentRun.namerPhase) {
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala:762]: The comment says "at uncurryPhase" but the code says "at namerPhase". Should it be
```suggestion
           * can be broken, therefore companionModule is fetched at
           * uncurryPhase.
           */
          val trgSym = enteringPhase(currentRun.uncurryPhase) {
```
I know that the previous code was already using `namerPhase`, but that seems suspicious to me. Before `exitingPhase(typerPhase)`, relying on anything from the symbol table seems a bit random.

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 1 above)
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: Ah yes, you're right. Let's keep it as is, then.

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 2 above)
[the remark this answers is not in the document]
Comment (sjrd) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: Thank you; it's much clearer now.

File: compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala (hunk 4 above)
Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: I have added a separate commit before the main one.

Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/GenJSExports.scala]: I have added a separate commit before the main one.

**Review by sjrd — APPROVED** [review]
