### PR TITLE
Fix #4282: Unify handling of JS calling conventions

### LINKED ISSUE #4282: NonNative JS class "ref-check" does not special case no-JSName apply
Found while fiddling with #4281.

```scala
package helloworld

import scala.scalajs.js
import js.annotation._

@js.native
@JSGlobal("Object")
abstract class MyClass extends js.Object {
  def apply(): Int
}

object HelloWorld {
  def main(args: Array[String]): Unit = {
    val x = new MyClass {
      @JSName("apply")
      def apply(): Int = 1
    }

    println(x())
  }
}
```

This compiles and links, but fails because `x` is not callable.

Expected: error message similar to:

```
object creation impossible, since method apply in class MyClass of type ()Int is not defined
    val x = new MyClass {
                ^
```

### PR DESCRIPTION
**Pull request by gzm0**
This fixes a number of issues related to overriding checking.

As a bonus, we also wont crash (but display a nice error), if a
repeated parameter is used in a binary operation.

### CODE REVIEW

File: compiler/src/main/scala/org/scalajs/nscplugin/JSGlobalAddons.scala [hunk 1]
```diff
@@ -131,6 +132,122 @@ trait JSGlobalAddons extends JSDefinitions
...
+        } else if (isJSBracketCall(sym)) {
+          BracketCall
+        } else {
+          val jsNameAnnot = sym.getAnnotation(JSNameAnnotation)
+          lazy val pc = sym.paramss.map(_.size).sum
+
+          sym.name match {
+            case nme.apply if jsNameAnnot.isEmpty => Call
+
+            case JSUnaryOpMethodName(code) if pc == 0 && jsNameAnnot.isEmpty =>
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/nscplugin/JSGlobalAddons.scala:182]: Only doing this conditional on the parameter count is the current behavior. I wonder if we should keep it.

File: compiler/src/main/scala/org/scalajs/nscplugin/PrepJSInterop.scala [hunk 2]
```diff
@@ -641,17 +641,17 @@ abstract class PrepJSInterop[G <: Global with Singleton](val global: G)
           membSym.defStringSeenAs(sym.thisType.memberType(membSym))
 
         // Check for overrides with different JS names - issue #1983
-        if (jsInterop.jsNameOf(low) != jsInterop.jsNameOf(high)) {
+        if (jsInterop.JSCallingConvention.of(low) != jsInterop.JSCallingConvention.of(high)) {
```
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/nscplugin/PrepJSInterop.scala:644]: This change probably stretches our notion of source v.s. binary compatibility. IIUC, this could now fail at usage site of a library compiled with a older version of Scala.js.

Unsure though what to do about this (IIUC detecting if the current class is "the problem" is hard).

**Comment by gzm0** [comment]
I'm not super happy with this solution (it feels a bit bloated), but it's the best I could come up with so far.

**Review by sjrd — CHANGES_REQUESTED** [review]

File: compiler/src/main/scala/org/scalajs/nscplugin/JSGlobalAddons.scala [hunk 3]
```diff
@@ -131,6 +132,122 @@ trait JSGlobalAddons extends JSDefinitions
...
+        if (isJSBracketAccess(sym)) {
+          BracketAccess
+        } else if (isJSBracketCall(sym)) {
+          BracketCall
+        } else {
+          val jsNameAnnot = sym.getAnnotation(JSNameAnnotation)
+          lazy val pc = sym.paramss.map(_.size).sum
+
+          sym.name match {
+            case nme.apply if jsNameAnnot.isEmpty => Call
```
[the remark this answers is not in the document]
Comment (gzm0) [reply compiler/src/main/scala/org/scalajs/nscplugin/JSGlobalAddons.scala]: Yes. At first I thought it'll make property / method handling more complicated, but I found a solution that I like more.

**Review by sjrd — APPROVED** [review]
