### PR TITLE
Fix #3148: Make our test suite pass on Node.js 8.

### LINKED ISSUE #3148: Our test suite does not pass on Node.js 8
The following tests fail:
```
> testSuite/testOnly org.scalajs.testsuite.junit.JUnitAssertionsTest org.scalajs.testsuite.javalib.util.ThrowablesTest
[warn] javaOptions will be ignored, fork is set to false
[info] Test run started
[info] Test org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions started
[error] Test org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'getName__T' of null, took 3.224 sec
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_ju_IllegalFormatConversionException.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     at java.util.IllegalFormatConversionException.this(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:267)
[error]     at java.util.IllegalFormatConversionException.this(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalib/src/main/scala/java/util/Throwables.scala:48)
[error]     at org.scalajs.testsuite.javalib.util.ThrowablesTest.shouldDefineAllJavaUtilErrorsAndExceptions(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/util/ThrowablesTest.scala:23)
[info] Test run finished: 1 failed, 0 ignored, 1 total, 3.232s
[info] Test run started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEquals started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEquals failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 3.249000192 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsDouble started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsDouble failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 0.002000128 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsFloats started
[error] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertArrayEqualsFloats failed: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'head__O' of null, took 0.002000128 sec
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_O.toString(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/scalajs-test-suite-test-fastopt.js:15885)
[error]     at <jscode>.Function.prepareStackTrace(/localhome/doeraene/projects/scalajs/node_modules/source-map-support/source-map-support.js:377)
[error]     at <jscode>.Function.captureStackTrace@<anonymous>(Unknown Source)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:43)
[error]     at <jscode>.$c_Lorg_junit_internal_ArrayComparisonFailure.$c_jl_Throwable.init___T__jl_Throwable(/localhome/doeraene/projects/scalajs/test-suite/js/target/scala-2.11/file:/localhome/doeraene/projects/scalajs/javalanglib/src/main/scala/java/lang/Throwables.scala:12)
[error]     ...
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEquals started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsByte started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsChar started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsDouble started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsFloat started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsInt started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsLong started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertEqualsShort started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertNull started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertSame started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertThat started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertThrows started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testAssertTrueFalse started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testExpectThrows started
[info] Test org.scalajs.testsuite.junit.JUnitAssertionsTest.testIfAssertsTest_issue_2252 started
[info] Test run finished: 3 failed, 0 ignored, 18 total, 3.344s
[error] Failed: Total 19, Failed 4, Errors 0, Passed 15
[error] Failed tests:
[error]         org.scalajs.testsuite.junit.JUnitAssertionsTest
[error]         org.scalajs.testsuite.javalib.util.ThrowablesTest
[error] (testSuite/test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 17 s, completed Oct 6, 2017 12:54:10 PM
```
They pass if we deactivate `source-map-support`. It happens because, somehow, with source-map-support on Node.js 8, the `toString()` of exceptions can be called before their constructor has finished executing, which causes things like `NullPointerException`s due to `val`s not yet being initialized.

### PR DESCRIPTION
**Pull request by sjrd**
This commit adapts two classes of exceptions, namely `j.u.IllegalFormatConversionException` and
`org.junit.internal.ArrayComparisonFailure`, so that their `toString()` does not crash if it is called before their respective constructors have finished executing.

### CODE REVIEW

**Comment by sjrd** [comment]
The commit message is missing an "8" ...

File: javalib/src/main/scala/java/util/Throwables.scala [hunk 1]
```diff
@@ -42,16 +42,15 @@ class IllegalFormatCodePointException(private val c: Int) extends IllegalFormatE
...
-    if (arg == null)
-      throw new NullPointerException()
-    this.arg = arg
-  }
+class IllegalFormatConversionException(c: Char, arg: Class[_])
+    extends IllegalFormatException {
+
+  if (arg == null)
+    throw new NullPointerException()
+
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Throwables.scala]: So just to clarify: `toString` will still crash here if `arg` is null, no? The difference is just that the throw point comes after the assignment to arg.

File: junit-runtime/src/main/scala/org/junit/internal/ArrayComparisonFailure.scala [hunk 2]
```diff
@@ -5,24 +5,26 @@ package org.junit.internal
 
 object ArrayComparisonFailure
 
-class ArrayComparisonFailure(fMessage: String) extends AssertionError {
-  private var fIndices: List[Int] = Nil
+class ArrayComparisonFailure(message: String, cause: AssertionError, index: Int)
+    extends AssertionError(message, cause) {
```
Comment (gzm0) [inline junit-runtime/src/main/scala/org/junit/internal/ArrayComparisonFailure.scala]: Seems like I'm going to learn something about Scala today: How is using something from the constructor parameter list different than initializing it in the constructor?

File: javalib/src/main/scala/java/util/Throwables.scala (hunk 1 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Throwables.scala]: Yes, if `arg` is `null`, `toString` will crash, but so would the constructor. So that's not a big deal. The important part is that `toString` does not crash when called too early, but in a situation where it would not crash if were called later.

File: junit-runtime/src/main/scala/org/junit/internal/ArrayComparisonFailure.scala (hunk 2 above)
Comment (sjrd) [reply junit-runtime/src/main/scala/org/junit/internal/ArrayComparisonFailure.scala]: Seems like you will: assignments to *constructor arguments* are initialized *before* the call to the super constructor. This means that when the super constructor executes (which is when `toString` apparently gets called, at some point), constructor arguments are already initiliazed, but not `val`s in the body of the class.

Comment (gzm0) [reply junit-runtime/src/main/scala/org/junit/internal/ArrayComparisonFailure.scala]: Right... I didn't think about subclassing... Fair enough, that makes sense.
