### PR TITLE
Fix #3704 and #3705, two regressions when using Scala 2.13.0.

### LINKED ISSUE #3704: Implement java.util.Collection.removeIf
Scaladoc: https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#removeIf-java.util.function.Predicate-

It's used by `JSetWrapper.filterInPlace` upstream since https://github.com/scala/scala/commit/9fcbb851ad6634655eda0959b7cbc280a1731d42 (merged in 2.13.0-RC1).

Not having it prevents us from enabling the upstream JUnit test `scala/collection/convert/JSetWrapperTest.scala`, and is potentially a source of *new* linking errors when migrating to Scala 2.13.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: project/Build.scala [hunk 1]
```diff
@@ -1549,6 +1549,25 @@ object Build {
...
+      val needsTargetFlag = scalaVersion.value match {
+        case PartialVersion("2", "10", n) => n.toInt >= 7
+        case PartialVersion("2", "11", n) => n.toInt >= 12
+        case _                            => false
+      }
+      if (needsTargetFlag)
+        Seq("-target:jvm-1.8")
+      else
+        Nil
+    },
```
Comment (sjrd) [inline project/Build.scala]: Updated with the above chunk in the build. It's necessary for scalac to accept the calls to `Predicate.isEqual` in the test suite.

I locally tested with the change with 2.10.6, 2.10.7, 2.11.11 and 2.11.12.
