### PR TITLE
Fix #1917: Add -Xfatal-warnings for ScalaDoc generation

### LINKED ISSUE #1917: Add -Xfatal-warnings even for scaladoc generation
For some sub-projects, scaladoc generation emit warnings and since #1912 fails.

As a temporary solution #1916 disables fatal warnings for doc compilation.

### PR DESCRIPTION
**Pull request by gzm0**
Note that links to the JavaDoc are not yet correct (filed as #1970).

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @nicolasstucki
Review by @sjrd for the principle of fixing JavaDoc later and the changes to the doc of `js.UndefOr`

**Comment by nicolasstucki** [comment]
LGTM

**Comment by gzm0** [comment]
Updated. Add filter for `scalacOptions` in `javalibEx`

File: project/Build.scala [hunk 1]
```diff
@@ -114,7 +114,26 @@ object Build extends sbt.Build {
...
+      ),
+
+      // Scaladoc linking
+      apiURL := {
+        val name = normalizedName.value
+        Some(url(s"http://www.scala-js.org/api/$name/$scalaJSVersion/"))
+      },
+      autoAPIMappings := true,
+
+      // Add Java Scaldoc mapping (resulting links are broken, see #1970)
```
Comment (sjrd) [inline project/Build.scala]: typo Scaldoc

File: project/Build.scala [hunk 2]
```diff
@@ -114,7 +114,26 @@ object Build extends sbt.Build {
...
+      apiMappings += {
+        val rtJar: String = {
```
Comment (sjrd) [inline project/Build.scala]: Remove `: String`?

**Comment by sjrd** [comment]
> Review by @sjrd for the principle of fixing JavaDoc later and the changes to the doc of js.UndefOr

OK

**Comment by gzm0** [comment]
Updated. Review of `Build.scala` by @sjrd

File: project/Build.scala [hunk 3]
```diff
@@ -56,6 +56,16 @@ object Build extends sbt.Build {
...
     Set()
 
+  val javaVersion: Int = {
+    val v = System.getProperty("java.version")
+    v.substring(0, 3) match {
+      case "1.8" => 8
+      case "1.7" => 7
+      case "1.6" => 6
+      case _     => sys.error(s"Unknown JDK version $v")
+    }
```
Comment (sjrd) [inline project/Build.scala]: I think this val should be an `Option[Int]`, and we should do something meaningful if we have an unknown JDK, rather than blowing up (possibly printing a warning). What if someone wants to try out Scala.js on beta builds of JDK 9, for example? We recently had a similar problem with the community build (#1965), albeit with the Scala version.

Comment (sjrd) [inline project/Build.scala]: If we want to assert in our CI that we know the JDK version we're testing, we can add a *task* `ensureKnownJavaVersion` that will thrown if `javaVersion.isEmpty`, and we can call that task from the matrix.

File: project/Build.scala [hunk 4]
```diff
@@ -1003,14 +1054,19 @@ object Build extends sbt.Build {
           })),
 
           sources in Test ++= {
-            def listAllScalaFilesIf(testDir: String, condition: Boolean): Seq[File] =
+            def listAllScalaFilesIf(testDir: String, condition: Boolean): Seq[File] = {
```
Comment (sjrd) [inline project/Build.scala]: Why the `{`?

**Comment by sjrd** [comment]
That's all for `Build.scala`

File: project/Build.scala (hunk 4 above)
Comment (gzm0) [inline project/Build.scala]: Indeed... Thought we need this... :)

File: project/Build.scala (hunk 3 above)
Comment (gzm0) [inline project/Build.scala]: Ok. I wanted to issue a warning, but the I needed to make a setting out of it... Was too lazy :)

Comment (gzm0) [inline project/Build.scala]: Would the following be OK too?

```scala
            streams.value.log.warning(
                s"Unknown JDK version $v. Assuming maximal compatibility")
            Int.MaxValue
```

It is kind of hard to decide on something meaningful at usage site if you get a `None`. Thanks to the rock-solid backwards compatibility of the JDK, `Int.MinValue` and `Int.MaxValue` seem to actually be reasonable values here...

**Comment by gzm0** [comment]
Updated

**Comment by sjrd** [comment]
`Build.scala` LGTM

**Comment by gzm0** [comment]
Updated (ditched `patmatSafeFatalWarningsSettings`)

**Comment by sjrd** [comment]
Re-`Build.scala` LGTM

**Comment by gzm0** [comment]
@nicolasstucki this is likely to pass CI now. Does it still LGTY?

**Comment by gzm0** [comment]
@nicolasstucki would you mind taking a quick look? (Only `Build.scala` has changed since your last review).
Sorry for being pushy. I have another commit coming up behind this and this is likely to conflict with changes I am about to make (tools refactoring). Thanks!

**Comment by nicolasstucki** [comment]
LGTM
