### PR TITLE
Fix #2034: Fix Assert.expectThrows return value.

### LINKED ISSUE #2034: JUnit Assert.{assert|expect}Throws never succeed.

### PR DESCRIPTION
**Pull request by nicolasstucki**

### CODE REVIEW

**Comment by nicolasstucki** [comment]
Review by @sjrd

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 1]
```diff
@@ -326,4 +326,41 @@ class JUnitAssertionsTest {
     testIfAsserts(assertThat(0, instanceOf[Int](classOf[Double])), ShallNotPass)
   }
 
+  @Test
+  def testExpectThrows(): Unit = {
+    testIfAsserts(expectThrows(classOf[Exception],
+        throwingRunnable {throw new Exception}))
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: space inside braces

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 2]
```diff
@@ -326,4 +326,41 @@ class JUnitAssertionsTest {
...
+    testIfAsserts {
+      val ex = expectThrows(classOf[Exception],
+          throwingRunnable {throw new Exception("abc")})
+      assertEquals(ex.getMessage, "abc")
+    }
+
+    testIfAsserts(expectThrows(classOf[IndexOutOfBoundsException],
+        throwingRunnable {throw new Exception}), ShallNotPass)
+    testIfAsserts(expectThrows(classOf[IndexOutOfBoundsException],
+      throwingRunnable { }), ShallNotPass)
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: 4 spaces

**Comment by sjrd** [comment]
That's all.

File: junit-runtime/src/main/scala/org/junit/Assert.scala [hunk 3]
```diff
@@ -291,34 +291,37 @@ object Assert {
...
+  //          val assertionError = new AssertionError(mismatchMessage)
+  //          assertionError.initCause(actualThrown)
+  //          throw assertionError
+  //        }
+  //    }
+  //  }
+  //
+  //  trait ThrowingRunnable {
+  //    def run(): Unit
+  //  }
```
Comment (sjrd) [inline junit-runtime/src/main/scala/org/junit/Assert.scala]: I suggest using `/*` at the beginning and `*/` at the end, on separate lines, so that not all of these lines are affected by a diff. *Especially* since the actual fix that is in there is therefore completely invisible in the diff.

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala [hunk 4]
```diff
@@ -326,4 +326,81 @@ class JUnitAssertionsTest {
...
+    testIfAsserts(assertThrows(classOf[IndexOutOfBoundsException],
+        throwingRunnable { throw new Exception }), ShallNotPass)
+    testIfAsserts(assertThrows(classOf[IndexOutOfBoundsException],
+        throwingRunnable { }), ShallNotPass)
+  }
+
+  /** Dummy implementation of Assert.assertThrows to be used until JUnit 4.13 is
+   *  released. See org.junit.Assert.scala in jUnitRuntime.
+   */
+  private def assertThrows(expectedThrowable: Class[_ <: Throwable],
```
Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: We should put these in `org.scalajs.testsuite.util.AssertThrows` or something.
Also, they're *not* "dummy", that's not the right word. They're real implementations since they actually do their job.

Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/junit/JUnitAssertionsTest.scala]: Actually the right word is *backport*, I believe.

**Comment by sjrd** [comment]
LGTM
