### PR TITLE
Fix #2943: Fix quadratic behaviors in the optimizer and cap JS array virtualization

### LINKED ISSUE #2943: Regression in optimiser
I believe there is a regression in the optimiser of Scala.js v0.6.16. When upgrading to this version and running my test cases, I encountered an OOM on Travis-CI: https://travis-ci.org/sparsetech/pine/jobs/230421157

Locally, it does not compile the test cases, getting stuck at "Fast optimizing". It doesn't finish even after a couple of minutes. `publishLocal` works fine and I did not notice any regressions in the artifact's functionality.

I investigated this issue as per @ochrons' suggestion by looking at the activity in JVisualVM. Here are the results:

jvisualvm

Please let me know how I can further assist in tracking down this issue!

### PR DESCRIPTION
**Pull request by sjrd**
The first two commits do not change the emitted .js file for the test suite (not even by different names being used). The last commit slightly changes the generated code for [the test data array of `Base64Test`](https://github.com/scala-js/scala-js/blob/195452a76760584338949229a85c0e0f9301058b/test-suite/shared/src/test/require-jdk8/org/scalajs/testsuite/javalib/util/Base64Test.scala#L366).

In addition to the improvements seen on the pathological case of #2943, the first commit cuts the time it takes to optimize the test suite from 14 seconds down to ~3.7 s. The other two commits do not bring any measurable difference on the test suite.

### CODE REVIEW

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala [hunk 1]
```diff
@@ -80,20 +80,22 @@ private[optimizer] abstract class OptimizerCore(
 
   private val labelNameAllocator: FreshNameAllocator = new FreshNameAllocator
 
-  /** A list of the States that have been allocated so far, and must be saved.
+  /** A list of backups for all updates done to States so far (excluding
+   *  those done is rolled back optimistic branches).
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala]: is -> in

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala [hunk 2]
```diff
@@ -5002,4 +4991,45 @@ private[optimizer] object OptimizerCore {
...
+        base
+      } else {
+        var i = usedNamesToNextCounter(base)
+        var result = base + "$" + i
+        while (usedNamesToNextCounter.contains(result)) {
+          i += 1
+          result = base + "$" + i
+        }
+        usedNamesToNextCounter =
+          usedNamesToNextCounter.updated(base, i + 1).updated(result, 1)
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala]: `freshName` is very often called with a non-constant base, coming from the input IR. The archetypal example is [in `withNewLocalDef`](https://github.com/sjrd/scala-js/blob/84fc283c005e5fcfaf774b90f466edf7b4f75739/tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala#L3992). So we cannot rule out `$`s here, unfortunately.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala (hunk 1 above)
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/frontend/optimizer/OptimizerCore.scala]: Done. (also a couple typo fixes in the commit messages)

**Comment by sjrd** [comment]
I'm so glad I took this Advanced Algorithms course at EPFL 4 years ago! I would never have thought of this amortized solution, otherwise.

Btw, this also seems to fix #2827 to a large extent.
