### PR TITLE
Fix #1756: Use the linking info in ScalaJSClassEmitter.

### LINKED ISSUE #1756: run/t4171.scala is broken on Rhino
It still works with `--fastOpt` and `--fullOpt`.

### PR DESCRIPTION
**Pull request by sjrd**
The issue was caused by the following pattern:

```scala
class A
class B extends A
println(classOf[B])
```

In this case, `B` is retained by the linker because its runtime type info are required. But `A` is discarded because it is not used in any way, despite it being a superclass of `B`. This is normal.

The problem is that the Rhino runner, when lazy loading `B`, did not use the fact that `linkedClassB.hasInstances` is false, and therefore generated the (empty) class. This empty class *did*
reference its parent class `A`, so when the script was evaluated, it would look for `A`. However it could not find `A` at all because it has been completely eliminated by the linker.

This commit fixes this by making `ScalaJSClassEmitter` leverage the linking info available in the `LinkedClass` it prints to emit only the necessary parts, basically with the same tests as those used
by `Emitter`.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0, I guess.

File: tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala [hunk 1]
```diff
@@ -386,6 +390,13 @@ final class ScalaJSClassEmitter(semantics: Semantics, outputMode: OutputMode,
     case StringLiteral(value) => js.StringLiteral(value)(name.pos)
   }
 
+  private[tools] def needInstanceTests(tree: LinkedClass): Boolean = {
+    tree.hasInstanceTests || {
+      tree.hasRuntimeTypeInfo &&
+      ClassesWhoseDataReferToTheirInstanceTests.contains(tree.encodedName)
+    }
+  }
+
```
Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala]: Shouldn't this be on the companion? It doesn't need the instance IIUC.

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala]: Hmmm... It might depend on the semantics in the future, doesn't it :-/

**Comment by gzm0** [comment]
I'm wondering whether we should not move the checks for the individual `genX` methods inside the actual generators. This would allow us to remove the duplication of the checking logic. On the `Emitter` side we could just cache an `EmptyTree` if nothing is to be emitted...

WDYT?

**Comment by gzm0** [comment]
That's all.

File: tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala (hunk 1 above)
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala]: Yes, precisely ;-)

Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala]: Or, also likely, the `OutputMode`.

Comment (gzm0) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/ScalaJSClassEmitter.scala]: Yep... or the global info :P

**Comment by sjrd** [comment]
> I'm wondering whether we should not move the checks for the individual genX methods inside the actual generators.

It would make sense. But there are two complications:

* The [test for whether a class should be emitted](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/Emitter.scala#L154) guards quite a lot of code, which does not correspond to a single method in `ScalaJSClassEmitter`. (Not a big deal, we could repeat the test.)
* The [emission for Strong Mode](https://github.com/scala-js/scala-js/blob/master/tools/shared/src/main/scala/org/scalajs/core/tools/optimizer/Emitter.scala#L218) is dramatically different, and doesn't have exactly the same tests. For example, static methods in a class without instances are emitted in a special way.

This requires more thought than a simple "let's put the tests inside the methods". I'll try and come up with something as a follow up cleanup commit.

**Comment by gzm0** [comment]
Ok. LGTM
