### PR TITLE
Reduce the memory pressure of BackwardsCompatTest.

### LINKED ISSUE #4961: linkerJS2_13/test spuriously fails too often on the CI (Killed)
I've seen a notable increase of the following error on the `bootstrap 2.13.12` jobs on the CI in the past week or two:
```
[info] Unpacking scalajs-logging sources to .../linker-interface/js/.2.13/scalajs-logging-src...
[info] compiling 1 Scala source to .../junit-async/js/.2.13/target/scala-2.13/classes ...
[info] compiling 36 Scala sources to .../linker-interface/js/.2.13/target/scala-2.13/classes ...
[info] done compiling
[info] done compiling
[info] compiling 88 Scala sources to .../linker/js/.2.13/target/scala-2.13/classes ...
[info] done compiling
[info] compiling 28 Scala sources to .../linker/js/.2.13/target/scala-2.13/test-classes ...
[info] done compiling
[info] Fast optimizing .../linker/js/.2.13/target/scala-2.13/scalajs-linker-test-fastopt
.../sbt: line 272: 1577538 Killed                  "$@"
FAILED
Command was: sbt ++2.13.12 irJS2_13/test linkerJS2_13/test linkerInterfaceJS2_13/test
```

### PR DESCRIPTION
**Pull request by sjrd**
Previously, we were running the tests for *all* previous versions in parallel, because of the behavior of `Future.traverse`. While it can reduce the wall clock time of running that test, it comes at a huge memory consumption cost, increasing with every new release.

It seems we have recently hit the limit of what is reasonable, especially on JS. Even JS retains things in parallel in memory because the IO handling concurrently overlaps.

We now ensure a completely sequential behavior for this test. For each previous version, in sequence, we

1. create a new cache for the IR files of the version,
2. load the IR files,
3. execute the test,
4. free the cache.

Additionally, in the CI, we decompose the `ir`/`linkerInterface`/`linker` JS tests in separate processes.

This PR hopefully fixes #4961.

### CODE REVIEW

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala [hunk 1]
```diff
@@ -13,22 +13,54 @@
...
     Platform.loadJar(stdlibPath)
       .flatMap(globalIRCache.newCache.cached _)
   }
+
+  /** For each previous lib, calls `f(version, irFiles)`, and combines the result.
+   *
+   *  This method applies `f` *sequentially*. It waits until the returned
+   *  `Future` completes before moving on to the next iteration.
+   */
+  def sequentiallyForEachPreviousLib[A](f: (String, Seq[IRFile]) => Future[A])(
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala:39]: Seems a bit odd to me, that the sequential processing is in here.

I can see two options:
- Just expose the bare path.
- Instead of exposing `Future[Seq[IRFile]]`, expose `() => Future[Seq[IRFile]]`.

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala [hunk 2]
```diff
@@ -13,22 +13,54 @@
...
+      implicit ec: ExecutionContext): Future[List[A]] = {
+
+    def loop(previousLibs: List[(String, String)]): Future[List[A]] = {
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala:42]: Have you considered putting this into a helper that does just the sequential processing? IMO this is harder to read than it needs to be.

**Review by gzm0 — CHANGES_REQUESTED** [review]
Overall approach LG. Some comments RE readability.

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala:39]: The `() => Future[Seq[IRFile]]` was my first idea, but it did not allow to properly `free()` the caches. Exposing the paths would make that possible, although it would then be on the caller to make sure that this done safely. If we write any new test that iterates over previous versions, we'll have to duplicate that logic.

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala (hunk 2 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala]: Ah, indeed, that is definitely worth extracting.

File: linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala (hunk 1 above)
Comment (gzm0) [reply linker/shared/src/test/scala/org/scalajs/linker/testutils/TestIRRepo.scala:39]: Ah, right. I did not take caching into account.

**Review by gzm0 — APPROVED** [review]
