### PR TITLE
Fix #4621: Preserve the side effects of JS binary and unary ops.

### LINKED ISSUE #4621: The side effects of JS binary (and unary) operators can be lost
My environment:
 - scala: 2.13
 - scala.js: 1.8.0

The code:
```scala
import scala.scalajs.js

import scala.language.implicitConversions

object Test {

  import BN._

  def main(args: Array[String]): Unit = {
    println(js.BigInt(7) / js.BigInt(0))
  }
}

class BN(val self: js.BigInt) {
  import BN._
  def /(divisor: BN): BN = {
    divideImpl(this, divisor)
  }
}

object BN {
  implicit def wrap(bi: js.BigInt): BN =
    new BN(bi)

  implicit def unwrap(bi: BN): js.BigInt =
    bi.self

  def divideImpl(a: js.BigInt, b: js.BigInt): js.BigInt =
    try {
      (a.asInstanceOf[js.Dynamic] / b.asInstanceOf[js.Dynamic]).asInstanceOf[js.BigInt]
    } catch {
      case e: js.JavaScriptException =>
        throw new ArithmeticException(e.getMessage())
    }

}
```

When I built it via sbt as `fastLinkJS` it crashes as expected:
```
.../target/scala-2.13/benchjs-fastopt/main.js:899
      throw new $c_jl_ArithmeticException($dp_toString__T(e$3.sjs_js_JavaScriptException__f_exception))
      ^

<ref *1> java.lang.ArithmeticException: RangeError: Division by zero
    at $c_LBN$.divideImpl__sjs_js_BigInt__sjs_js_BigInt__sjs_js_BigInt (.../js/target/scala-2.13/benchjs-fastopt/main.js:899:13)
    at $c_LBN.$div__LBN__LBN (.../target/scala-2.13/benchjs-fastopt/main.js:871:22)
    at $c_LTest$.main__AT__V (.../js/target/scala-2.13/benchjs-fastopt/main.js:937:16)
    at $s_LTest__main__AT__V (.../js/target/scala-2.13/benchjs-fastopt/main.js:920:15)
    at Object.<anonymous> (.../js/target/scala-2.13/benchjs-fastopt/main.js:5706:1)
    at Object.<anonymous> (.../js/target/scala-2.13/benchjs-fastopt/main.js:5707:4)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  jl_Throwable__f_s: 'RangeError: Division by zero',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}

Node.js v17.3.0
```
but when I use `fullLinkJS` the crash looks like:
```
.../target/scala-2.13/benchjs-opt/main.js:82
e.$classData=y({Wc:0},"scala.collection.mutable.StringBuilder",{Wc:1,Fd:1,Da:1,pa:1,a:1,qa:1,y:1,sa:1,z:1,ra:1,ta:1,Ca:1,xa:1,ua:1,la:1,Od:1,Md:1,Pd:1,Id:1,ya:1,Nd:1,Gd:1,Jd:1,Hd:1,Kd:1,gb:1,hb:1,Ld:1,Sa:1,b:1});ca=new n(0,0);za.tb=ca;new (A(jd).t)([]);Da||(Da=new Ca);var Vd,Wd=new B(BigInt(7)),Xd=new B(BigInt(0));Ba||(Ba=new Aa);Vd=new B(Wd.Na/Xd.Na);var Zd;lc||(lc=new kc);Zd=lc.ab.db;
                                                                                                                                                                                                                                                                                                                                                          ^

RangeError: Division by zero
    at Object.<anonymous> (.../target/scala-2.13/benchjs-opt/main.js:82:347)
    at Object.<anonymous> (.../target/scala-2.13/benchjs-opt/main.js:84:4)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.3.0
```

Thus, moving `try .. catch` inside `/` like that:
```scala
  def /(divisor: BN): BN = try {
    divideImpl(this, divisor)
  } catch {
    case e: js.JavaScriptException =>
      throw new ArithmeticException(e.getMessage())
  }
...
  def divideImpl(a: js.BigInt, b: js.BigInt): js.BigInt =
    (a.asInstanceOf[js.Dynamic] / b.asInstanceOf[js.Dynamic]).asInstanceOf[js.BigInt]
```
solves an issue.

### PR DESCRIPTION
**Pull request by sjrd**
The emitter wrongly thought that these operators preserve pureness. However, they can have side effects in two cases:

* For BigInts, division by 0 and unary + throw.
* For custom objects, if their `valueOf()` method throws, it will be propagated by the JS binary and unary ops.

### CODE REVIEW

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/RegressionJSTest.scala [hunk 1]
```diff
@@ -96,6 +99,40 @@ class RegressionJSTest {
     assertEquals(6, obj2.bar)
   }
 
+  @Test def preserveSideEffectsOfJSOps_Issue4621(): Unit = {
+    if (jsBigInts) {
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/RegressionJSTest.scala:103]: Consider splitting the test case and assuming this.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/RegressionJSTest.scala [hunk 2]
```diff
@@ -96,6 +99,40 @@ class RegressionJSTest {
...
+      @noinline def bi(x: Int): js.BigInt = js.BigInt(x)
+
+      // These must be stored as `val`s first
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/RegressionJSTest.scala:106]: Consider adding " to trigger the original problem". (Arguably that duplicates context that exists, but IMO it is a bit hard to grok otherwise).

**Review by gzm0 — APPROVED** [review]

**Comment by sjrd** [comment]
Good points. Updated.
