### PR TITLE
Fix #4734: Implement ArrayDeque with a ring-buffer

### LINKED ISSUE #4734: `j.u.ArrayDeque#pollFirst` is `O(n)`
Specifically this method:

https://github.com/scala-js/scala-js/blob/639313922b7c203f5ce12fdac414cd1c5b786eb3/javalib/src/main/scala/java/util/ArrayDeque.scala#L84-L91

AFAIK there is no guarantee that `shift` is `O(1)`, apologies If I'm wrong about that.

According to the Javadoc this method (and others) should be amortized `O(1)`.

https://docs.oracle.com/javase/8/docs/api/java/util/ArrayDeque.html

### PR DESCRIPTION
**Pull request by gzm0**

### CODE REVIEW

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 1]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+   * @returns true if elements after the target index were shifted.
+   * Returns false, if elements before the target index were shifted.
+   */
+  private def removeAt(target: Int): Boolean = {
+    if (target == startIndex) {
+      pollFirst()
+      false
+    } else if (target == endIndex - 1) {
+      pollLast()
+      true
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:335]: I have a hard time understanding what this result means. In this case and the case above, no element was shifted. Why does this one return `true` but the above returns `false`? How that translate to the behavior of the iterator?

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 2]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
         checkStatus()
-        if (index < 0 || index >= inner.length) {
+        if (lastIndex == -1) {
           throw new IllegalStateException()
         } else {
-          arrayRemove(inner, index)
+          val laterShifted = removeAt(lastIndex)
+          expectedStatus = self.status
+          if (forward && laterShifted) {
+            nextIndex -= 1
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:258]: What if this makes `nextIndex < 0`?

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 3]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+          }
+
+          if (!forward && !laterShifted) {
+            nextIndex += 1
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:262]: Same here. What if `nextIndex` is incremented to `inner.length`?

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 4]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+      // Shift elements from endIndex towards target
+      var i = target
+      while (i != endIndex - 1) {
+        inner(i) = inner(i + 1)
+        i += 1
+      }
+      status += 1
+      endIndex -= 1
+      if (startIndex == endIndex)
+        empty = true
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:346]: If this happens, it means that there was exactly 1 element in the queue before `removeAt`. But then, it must have been the case that `target == startIndex` when entering the method, and therefore the `if (target == startIndex)` branch at the beginning would have been taken. So this will never happen.

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 5]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+      // assert(target > startIndex)
+      var i = target
+      while (i != startIndex) {
+        inner(i) = inner(i - 1)
+        i -= 1
+      }
+      status += 1
+      startIndex += 1
+      if (startIndex == endIndex)
+        empty = true
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:361]: Same here. This cannot happen.

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 6]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+
+  /* Removes the element at index [[target]]
+   *
+   * @returns true if elements after the target index were shifted.
+   * Returns false, if elements before the target index were shifted.
+   */
+  private def removeAt(target: Int): Boolean = {
+    if (target == startIndex) {
+      pollFirst()
+      false
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:332]: Perhaps add a comment that this branch is always taken when there is only one element in the queue before removal.

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 7]
```diff
@@ -171,55 +193,175 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+    if (isEmpty()) {
+      0
+    } else {
+      val capacity = inner.length // local copy
+      endIndex - startIndex + capacity % capacity
+    }
+  }
 
-  private def failFastIterator(startIndex: Int, nex: (Int) => Int) = {
+  private def failFastIterator(forward: Boolean) = {
```
Comment (sjrd) [inline javalib/src/main/scala/java/util/ArrayDeque.scala:205]: Perhaps, at this point, it would be easier to reason about this if we had separate implementations for forward and backward? The only meaningful logic left in common is the `status` checks.

**Review by sjrd — CHANGES_REQUESTED** [review]
Thanks for this :)

This is quite a tricky beast. I'm afraid I have quite a number of comments on it.

File: javalib/src/main/scala/java/util/ArrayDeque.scala (hunk 1 above)
Comment (gzm0) [reply javalib/src/main/scala/java/util/ArrayDeque.scala:335]: This should be clearer now: tl;dr if the result value here is such that it would trigger special behavior in the iterator, the iterator is done (so `nextIndex == -1`).

**Comment by gzm0** [comment]
Updated. I believe I have addressed all the comment.s

File: javalib/src/main/scala/java/util/ArrayDeque.scala (hunk 1 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/ArrayDeque.scala:394]: Indeed, this is much clearer now, thanks.

**Review by sjrd — COMMENTED** [review]
One indentation comment.

Also: I wonder if we should explicitly clear with `null` the cells that are "removed". For example, in `pollFirst()`, set `inner(startIndex) = null` before doing `startIndex += 1`. If we don't, we may maintain strong references to objects that could otherwise be reclaimed by the GC.

**Comment by gzm0** [comment]
>  If we don't, we may maintain strong references to objects that could otherwise be reclaimed by the GC.

:facepalm: of course we have to. Otherwise we'll leave a giant memory leak... Good catch!

**Review by sjrd — APPROVED** [review]

File: javalib/src/main/scala/java/util/ArrayDeque.scala [hunk 8]
```diff
@@ -22,24 +22,23 @@ class ArrayDeque[E] private (private val inner: js.Array[E])
...
+  private var empty = true
 
-  def this(initialCapacity: Int) = {
-    this(new js.Array[E])
-
-    if (initialCapacity < 0)
-      throw new IllegalArgumentException
-  }
+  def this(initialCapacity: Int) =
+    this(new js.Array[E](Math.max(initialCapacity, 16)))
```
[the remark this answers is not in the document]
Comment (armanbilge) [reply javalib/src/main/scala/java/util/ArrayDeque.scala]: Question: this (admittedly old) blog post seems to suggest that even if a newly created array is immediately filled with elements, it will still be treated as sparse by the runtime (due to its sparse construction). Is that an issue here?

```js
const array = new Array(3);
// The array is sparse at this point, so it gets marked as
// `HOLEY_SMI_ELEMENTS`, i.e. the most specific possibility given
// the current information.
array[0] = 'a';
// Hold up, that’s a string instead of a small integer… So the kind
// transitions to `HOLEY_ELEMENTS`.
array[1] = 'b';
array[2] = 'c';
// At this point, all three positions in the array are filled, so
// the array is packed (i.e. no longer sparse). However, we cannot
// transition to a more specific kind such as `PACKED_ELEMENTS`. The
// elements kind remains `HOLEY_ELEMENTS`.
```

https://v8.dev/blog/elements-kinds#avoid-creating-holes

[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/ArrayDeque.scala]: Hum, I thought that if we filled in the elements in order, we wouldn't be triggering holes. Do you know if Firefox' engine behaves similarly? If yes, we should probably also revisit how we initialize `Array`s.

[the remark this answers is not in the document]
Comment (armanbilge) [reply javalib/src/main/scala/java/util/ArrayDeque.scala]: Thanks for the response.

> Do you know if Firefox' engine behaves similarly?

Not really, no. I spent some time staring at SpiderMonkey sources. They do have a `NON_PACKED` flag and like V8 it _seems_ like it only transitions to `NON_PACKED`, never in the reverse (based on usage and lack of a helper method).

```cpp
    // If this flag is not set, the elements are guaranteed to contain no hole
    // values (the JS_ELEMENTS_HOLE MagicValue) in [0, initializedLength).
    NON_PACKED = 0x80,
```

https://searchfox.org/mozilla-central/source/js/src/vm/NativeObject.h#233

```cpp
  /*
   * Number of initialized elements. This is <= the capacity, and for arrays
   * is <= the length. Memory for elements above the initialized length is
   * uninitialized, but values between the initialized length and the proper
   * length are conceptually holes.
   */
  uint32_t initializedLength;
```

https://searchfox.org/mozilla-central/source/js/src/vm/NativeObject.h#278

```cpp
  void markNonPacked() { flags |= NON_PACKED; }
```
https://searchfox.org/mozilla-central/source/js/src/vm/NativeObject.h#329

```cpp
inline void NativeObject::markDenseElementsNotPacked() {
  MOZ_ASSERT(is<NativeObject>());
  getElementsHeader()->markNonPacked();
}
```
https://searchfox.org/mozilla-central/source/js/src/vm/NativeObject-inl.h#70

One place such a transition may happen is here.

```cpp
inline void NativeObject::ensureDenseInitializedLength(uint32_t index,
                                                       uint32_t extra) {
  // Ensure that the array's contents have been initialized up to index, and
  // mark the elements through 'index + extra' as initialized in preparation
  // for a write.
```

https://searchfox.org/mozilla-central/source/js/src/vm/NativeObject-inl.h#299

From there, tracing gets a lot harder, sorry. However based on the fact that `initializedLength` is tracked your assertion seems very plausible.

> Hum, I thought that if we filled in the elements in order, we wouldn't be triggering holes.

[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/ArrayDeque.scala]: Thanks for the trace. The `initializedLength` does suggest that I am right for Firefox, indeed. I'll keep this in mind, and maybe one day do benchmarks when we change how `Array`s are initialized.

[the remark this answers is not in the document]
Comment (armanbilge) [reply javalib/src/main/scala/java/util/ArrayDeque.scala]: One last follow-up: I installed d8 (debug v8) as suggested in the linked blog post.

```
$ ~/.jsvu/bin/v8-debug 
V8 version 11.1.192
d8> 
```

I was able to replicate their example:

```js
const array = [1, 2, 3];
array[3] = 4.56;
```

```
$ ~/.jsvu/bin/v8-debug --trace-elements-transitions test.js 
elements transition [PACKED_SMI_ELEMENTS -> PACKED_DOUBLE_ELEMENTS] in ~+15 at test.js:1 for 0x0e520010b461 <JSArray[3]> from 0x0e520025a3c1 <FixedArray[3]> to 0x0e520010b471 <FixedDoubleArray[22]>
```

But if I initialize elements one-by-one, then the initial state becomes `HOLEY_SMI_ELEMENTS`.

```js
const array = new Array(3);
array[0] = 1;
array[1] = 2;
array[2] = 3;
array[3] = 4.56;
```

```
elements transition [HOLEY_SMI_ELEMENTS -> HOLEY_DOUBLE_ELEMENTS] in ~+60 at test.js:1 for 0x02d60010b48d <JSArray[3]> from 0x02d60010b49d <FixedArray[3]> to 0x02d60010b4b1 <FixedDoubleArray[22]>
```

So unfortunately this is a sub-optimal initialization pattern on V8.
