### PR TITLE
Fix #1966: ChronoUnit and ChronoField

### LINKED ISSUE #1966: Some ChronoFields and ChronoUnits return wrong results for isDateBased and isTimeBased
In the ScalaJS implementation `java.time.temporal.ChronoField.INSTANT_SECONDS` and `java.time.ChronoField.EPOCH_SECONDS` return `true` for `isTimeBased` when they should return `false` according to the JavaDoc for `ChronoField`. Similarly, `java.time.temporal.ChronoUnit.FOREVER.isDateBased` returns `true` when it should return `false` according to the JavaDoc.

### PR DESCRIPTION
**Pull request by ummels**
This fixes the behavior of `isDateBased` and `isTimeBased` on `ChronoUnit.FOREVER` as well as `ChronoField.INSTANT_SECONDS` and `ChronoField.OFFSET_SECONDS`.

Fixes #1966.

~~Also fixes the behavior of `LocalTime.isSupported` on null argument (should return `false` instead of throw an exception).~~

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by sjrd** [comment]
Jenkins, test this please

**Comment by gzm0** [comment]
If this is a bug (which it seems like). Please file an issue with a reproduction and reference the issue in your commit.

File: javalib/src/main/scala/java/time/temporal/ChronoField.scala [hunk 1]
```diff
@@ -1,9 +1,9 @@
 package java.time.temporal
 
 final class ChronoField private (name: String, ordinal: Int,
-    _range: ValueRange, dateBased: Boolean, baseUnit: ChronoUnit,
-    rangeUnit: ChronoUnit) extends Enum[ChronoField](name, ordinal)
-    with TemporalField {
+    _range: ValueRange, dateBased: Boolean, timeBased: Boolean,
```
Comment (nicolasstucki) [inline javalib/src/main/scala/java/time/temporal/ChronoField.scala]: Rater than adding a new field you should repurpose the `dateBased` one as a flag container. You could have `basedOnFlags: Int` instead and then use them as:
```scala
private final val isTimeBasedFlag = 1
private final val isDateBasedFlag = 2

def isTimeBased(): Boolean = (basedOnFlags & isTimeBasedFlag) != 0

... ValueRange.of(0, 86399999), isTimeBasedFlag, MILLIS, DAYS)
```

File: javalib/src/main/scala/java/time/temporal/ChronoUnit.scala [hunk 2]
```diff
@@ -3,16 +3,16 @@ package java.time.temporal
 import java.time.Duration
 
 final class ChronoUnit private (name: String, ordinal: Int, duration: Duration,
-    dateBased: Boolean) extends Enum[ChronoUnit](name, ordinal)
-    with TemporalUnit {
+    dateBased: Boolean, timeBased: Boolean)
```
Comment (nicolasstucki) [inline javalib/src/main/scala/java/time/temporal/ChronoUnit.scala]: Same trick with flags.

File: test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/LocalTimeTest.scala [hunk 3]
```diff
@@ -13,6 +13,41 @@ object LocalTimeTest extends TemporalAccessorTest {
...
+      } {
+        expect(t.isSupported(u)).toBeFalsy
+      }
+
+      for (t <- Seq(MAX, MIN, NOON)) {
+        expect(t.isSupported(null: TemporalUnit)).toBeFalsy
+        expect(t.isSupported(null: TemporalField)).toBeFalsy
+      }
+    }
+
```
Comment (nicolasstucki) [inline test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/LocalTimeTest.scala]: You should also add some tests on `isTimeBased` and `isDateBased`. There are few cases, you could test them all.

**Comment by nicolasstucki** [comment]
That is all.

**Comment by ummels** [comment]
Updated and rebased.

**Comment by nicolasstucki** [comment]
Change the commit message to `Fix #1966: ...`

**Comment by nicolasstucki** [comment]
Otherwise LGTM

File: javalib/src/main/scala/java/time/temporal/ChronoUnit.scala [hunk 4]
```diff
@@ -24,41 +25,54 @@ final class ChronoUnit private (name: String, ordinal: Int, duration: Duration,
 }
 
 object ChronoUnit {
-  final val NANOS = new ChronoUnit("Nanos", 0, Duration.OneNano, false)
+  private final val isTimeBasedFlag = 1
+  private final val isDateBasedFlag = 2
+
+  final val NANOS =
+      new ChronoUnit("Nanos", 0, Duration.OneNano, isTimeBasedFlag)
```
Comment (gzm0) [inline javalib/src/main/scala/java/time/temporal/ChronoUnit.scala]: These should be indented by 2 spaces only (or new newline at all if they don't exceed 80)

Comment (ummels) [inline javalib/src/main/scala/java/time/temporal/ChronoUnit.scala]: Sure. Done.

**Comment by ummels** [comment]
Could you retest this please?

**Comment by sjrd** [comment]
Jenkins, retest this please

**Comment by ummels** [comment]
Fixed `ChronoUnitTest`. Please retest.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please

File: test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/temporal/ChronoUnitTest.scala [hunk 5]
```diff
@@ -8,6 +8,49 @@ object ChronoUnitTest extends JasmineTest {
...
+      expect(WEEKS.isTimeBased).toBeFalsy
+      expect(MONTHS.isTimeBased).toBeFalsy
+      expect(YEARS.isTimeBased).toBeFalsy
+      expect(DECADES.isTimeBased).toBeFalsy
+      expect(CENTURIES.isTimeBased).toBeFalsy
+      expect(MILLENNIA.isTimeBased).toBeFalsy
+      expect(ERAS.isTimeBased).toBeFalsy
+      expect(FOREVER.isTimeBased).toBeFalsy
+    }
+
```
Comment (nicolasstucki) [inline test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/temporal/ChronoUnitTest.scala]: Now that you modified `isDurationEstimated`, you should also add some tests for it.

**Comment by nicolasstucki** [comment]
Thats all. Otherwise LGTM.

File: test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/temporal/ChronoUnitTest.scala [hunk 6]
```diff
@@ -8,6 +8,49 @@ object ChronoUnitTest extends JasmineTest {
   import ChronoUnit._
 
   describe("java.time.temporal.ChronoUnit") {
+    it("should respond to `isDurationEstimated`") {
+      for (u <- ChronoUnit.values())
+        expect(u.isDurationEstimated != u.isTimeBased).toBeTruthy
+    }
```
Comment (ummels) [inline test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/temporal/ChronoUnitTest.scala]: @nicolasstucki The test for `isDurationEstimated` is here. `isDurationEstimated` always return the opposite of `isTimeBased`.

Comment (nicolasstucki) [inline test-suite/src/test/require-jdk8/org/scalajs/testsuite/javalib/time/temporal/ChronoUnitTest.scala]: Ok. I missed those.
