### PR TITLE
Fix #5276: Add ctors of IndexOutOfBoundsException taking an index.

### LINKED ISSUE #5276: Add JDK9+ constructors of `java.lang.IndexOutOfBoundsException`
Currently, `java.lang.IndexOutOfBoundsException` is defined as follows:

https://github.com/scala-js/scala-js/blob/37a2d9d4f5ffb434207c9215d7db879ee8756ecf/javalib/src/main/scala/java/lang/Throwables.scala#L400-L402

Additional constructors have been added in JDK 9 and JDK 16, see [javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/IndexOutOfBoundsException.html).
In https://github.com/scala/scala3/pull/24764, we make use of these new constructors in the stdlib but we unfortunately cannot make progress since the generated code cannot link in Scala.js.

### PR DESCRIPTION
**Pull request by sjrd**

### CODE REVIEW

File: javalib/src/main/scala/java/lang/Throwables.scala [hunk 1]
```diff
@@ -398,6 +398,8 @@ class IllegalThreadStateException(s: String) extends IllegalArgumentException(s)
 }
 
 class IndexOutOfBoundsException(s: String) extends RuntimeException(s) {
+  def this(index: Int) = this(s"Index out of range: $index")
+  def this(index: scala.Long) = this(s"Index out of range: $index")
```
Comment (ekrich) [inline javalib/src/main/scala/java/lang/Throwables.scala:402]: Is there a particular reason you use `scala.Long` vs `jl.Long` in the interface? They end up the same I would guess but you always have good reasons for everything.

Comment (sjrd) [reply javalib/src/main/scala/java/lang/Throwables.scala:402]: They're not the same at all. One is the primitive, the other is the boxed class. 😉

Comment (ekrich) [reply javalib/src/main/scala/java/lang/Throwables.scala:402]: Dang, I wasn't thinking about that mapping correctly - glad I asked. Thank-you.
