### PR TITLE
Fix #1647: Require explicit @JSExport("apply")

### LINKED ISSUE #1647: @JSExport on an `apply` method is confusing
Exporting a method named `apply`, like this:
```scala
@JSExport
def apply(...) = ...
```
is confusing. It exports a method named `apply` to JS, but the expected behavior would be to make the enclosing object callable (with the `()` syntax). The latter is not possible to implement, given the current state of JS. But we should emit a deprecation warning in this case. If exporting an `apply` method is really what's wanted, the following syntax should be used instead:
```scala
@JSExport("apply")
def apply(...) = ...
```
which would reconcile how `@JSName` and `@JSExport` view `apply` methods.

### LINKED ISSUE #1723: object cannot be exported as toString
The following causes a bizarre error:

```scala
@JSExport("toString")
object A
```

```
A.scala:1: You may not export a zero-argument method named other than 'toString' under the name 'toString'
@JSExport("toString")
 ^
```

Although exporting to "toString" is not necessarily a good idea, there is no reason we should prevent it.

### PR DESCRIPTION
**Pull request by gzm0**
Exporting a method named apply (without explicit name) should cause it
to be callable using call synatx in JavaScript. This is not doable. We
therefore require explicitly specifying the name of the method to be
"apply". This will cause the method to callable under the name apply.

As a side effect, the clean up in this commit also fixes #1723 (export
object under the name toString).

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala [hunk 1]
```diff
@@ -196,28 +200,43 @@ trait PrepJSExports { this: PrepJSInterop =>
...
+      if (isMember && !hasExplicitName && sym.name == nme.apply) {
+        if (isExportAll)
+          reporter.warning(sym.pos, "Exported methods named apply are not " +
+              "exported to function appliction in JavaScript, but to a member " +
+              "named apply. Add @JSExport(\"apply\") to silence this warning.")
+        else
+          reporter.warning(annot.pos, "Member cannot be exported to function " +
+            "application. It is available under the name apply instead. " +
+            "Specify the name \"apply\" explicitly to silence this warning. " +
+            "This will be enforced in 1.0.")
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala]: Indentation issue + missing braces.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala [hunk 2]
```diff
@@ -196,28 +200,43 @@ trait PrepJSExports { this: PrepJSInterop =>
...
             "method named other than 'toString' under the name 'toString'")
       }
 
-      if (named && jsInterop.isJSProperty(sym)) {
+      // Don't allow apply without explicit name
+      if (isMember && !hasExplicitName && sym.name == nme.apply) {
+        if (isExportAll)
+          reporter.warning(sym.pos, "Exported methods named apply are not " +
+              "exported to function appliction in JavaScript, but to a member " +
+              "named apply. Add @JSExport(\"apply\") to silence this warning.")
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala]: The "This will be enforced in 1.0" sentence is missing.

File: test-suite/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 3]
```diff
@@ -561,6 +561,10 @@ object ExportsTest extends JasmineTest {
       expect(obj.witness).toEqual("witness")
     }
 
+    it("should allow exporting an object as toString - #1723") {
+      expect(js.Dynamic.global.applyDynamic("toString")().x).toEqual(2)
```
Comment (sjrd) [inline test-suite/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: I don't like this test, because it actually pollutes the global object of the test suite with a `toString()` method that doesn't even return a string. I suggest writing this as a pos test in `compiler/test`.

**Comment by sjrd** [comment]
That's all.

**Comment by sjrd** [comment]
The failure looks spurious. One config in the matrix timed out twice, but the rest is fine.

**Comment by gzm0** [comment]
Updated

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala [hunk 4]
```diff
@@ -196,28 +200,44 @@ trait PrepJSExports { this: PrepJSInterop =>
...
             "method named other than 'toString' under the name 'toString'")
       }
 
-      if (named && jsInterop.isJSProperty(sym)) {
+      // Don't allow apply without explicit name
+      if (isMember && !hasExplicitName && sym.name == nme.apply) {
+        if (isExportAll) {
+          reporter.warning(sym.pos, "Exported methods named apply are not " +
+              "exported to function appliction in JavaScript, but to a member " +
+              "named apply. Add @JSExport(\"apply\") to silence this warning.")
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala]: "This will be enforced in 1.0." is still missing here.

**Comment by sjrd** [comment]
I think there should also be a test asserting that adding `@JSExport("apply")` in addition to `@JSExportAll` indeed silences the warning.

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala (hunk 4 above)
Comment (gzm0) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala]: Ohh, I see now. I thought you wanted this to always remain just a warning. Seemed better to me, don't really know why. Should we schedule it to become an error instead?

**Comment by gzm0** [comment]
Agree on the test... Reviews: Forcing lazy programmers to write tests :P

File: compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala (hunk 4 above)
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/PrepJSExports.scala]: Yes, we should also schedule that to become an error.
It should be an error at some point, because, if JavaScript ever offers a way to add callable capabilities to non-Function objects, then we can make it work (in ES 12 or something ^^)

**Comment by sjrd** [comment]
> Reviews: Forcing lazy programmers to write tests :P

You had me started on that ^^

**Comment by gzm0** [comment]
> You had me started on that ^^

True. I should have forced you to write tests on that `JSName` stuff as well :)

**Comment by gzm0** [comment]
Updated

**Comment by gzm0** [comment]
(the case you were insisting on being tested was actually buggy... wondering if you knew :P)

**Comment by sjrd** [comment]
I suspected ^^

**Comment by sjrd** [comment]
LGTM

**Comment by sjrd** [comment]
retest this please

**Comment by sjrd** [comment]
retest this please
