### PR TITLE
Fix #2118: InputStreamReader.read() after EOF

### LINKED ISSUE #2118: InputStreamReader.read() throws IllegalStateException when reading past EOF
This bug can be triggered with this code:
```scala
    val data = "Lorem ipsum".getBytes()
    val streamReader = new InputStreamReader(new ByteArrayInputStream(data))
    val bytes = new Array[Char](11)

    streamReader.read(bytes)
    streamReader.read(bytes)
    streamReader.read(bytes) // IllegalStateException
```

The expected behavior is to return -1

### PR DESCRIPTION
**Pull request by hmil**
Under certain circumstances, a call to InputStreamReader.read() may trigger an IllegalStateException when a previous call to read() returned -1.

see #2118 

This patch makes sure no processing happens at all in `read` when the end of the stream has been reached.

### CODE REVIEW

**Comment by sjrd** [comment]
Hi, and thanks.

Issues should be reported as such first, and a PR should mention "Fix #xxx: Action.". This is so that we can track issues and their fixes. 

Second, any bug fix should come with a test case in `test-suite/` that fails before the fix, and success afterwards. Otherwise we're bound to reintroduce the bug at some point.

Don't forget to read

**Comment by sjrd** [comment]
Sorry about the close/open. Fat fingers.

**Comment by nicolasstucki** [comment]
The tests should go in this file https://github.com/scala-js/scala-js/blob/master/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/ReadersTest.scala

**Comment by hmil** [comment]
Thanks for the pointers, everything should be in order now.

**Comment by nicolasstucki** [comment]
Jenkins, test this please

File: javalib/src/main/scala/java/io/InputStreamReader.scala [hunk 1]
```diff
@@ -65,6 +65,7 @@ class InputStreamReader(private[this] var in: InputStream,
 
   def read(cbuf: Array[Char], off: Int, len: Int): Int = {
     ensureOpen()
+    if (endOfInput) return -1
```
Comment (sjrd) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: My experiments show that this test should actually come after the `IndexOutOfBoundsException` test *and* the `len == 0` test:
```scala
$ scala
Welcome to Scala version 2.10.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_39).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import java.io._
import java.io._

scala> val data = "Lorem ipsum".getBytes()
data: Array[Byte] = Array(76, 111, 114, 101, 109, 32, 105, 112, 115, 117, 109)

scala> new InputStreamReader(new ByteArrayInputStream(data))
res0: java.io.InputStreamReader = java.io.InputStreamReader@686baa51

scala> val bytes = new Array[Char](11)
bytes: Array[Char] = Array(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
scala> streamReader.read(bytes)
<console>:12: error: not found: value streamReader
              streamReader.read(bytes)
              ^

scala> val streamReader = res0
streamReader: java.io.InputStreamReader = java.io.InputStreamReader@686baa51

scala> streamReader.read(bytes)
res2: Int = 11

scala> streamReader.read(bytes)
res3: Int = -1

scala> streamReader.read(new Array(0))
<console>:14: error: overloaded method value read with alternatives:
  (Array[Char])Int <and>
  (java.nio.CharBuffer)Int
 cannot be applied to (Array[Nothing])
              streamReader.read(new Array(0))
                           ^

scala> streamReader.read(new Array[Byte](0))
<console>:14: error: overloaded method value read with alternatives:
  (Array[Char])Int <and>
  (java.nio.CharBuffer)Int
 cannot be applied to (Array[Byte])
              streamReader.read(new Array[Byte](0))
                           ^

scala> streamReader.read(new Array[Char](0))
res6: Int = 0

scala> streamReader.read(new Array[Char](5))
res7: Int = -1

scala> streamReader.read(new Array[Char](5), 11, 3)
java.lang.IndexOutOfBoundsException
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:131)
        at java.io.InputStreamReader.read(InputStreamReader.java:167)
        at .<init>(<console>:14)
        at .<clinit>(<console>)
        at .<init>(<console>:7)
        at .<clinit>(<console>)
        at $print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:731)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:980)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:570)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:601)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:745)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:790)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:702)
        at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:566)
        at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:573)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:576)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:867)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:822)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:822)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

File: javalib/src/main/scala/java/io/InputStreamReader.scala [hunk 2]
```diff
@@ -90,6 +90,8 @@ class InputStreamReader(private[this] var in: InputStream,
          */
         readMoreThroughOutBuf(cbuf, off, len)
       }
+    } else {
+      return -1
```
Comment (sjrd) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: Our style checker will not like this. Just write `-1` and drop `return` (which is not need here).

**Comment by nicolasstucki** [comment]
As expected, the style checks failed. You can use `javalib/scalastyle` and `testSuite/test:scalastyle` to execute these checks locally.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.

File: javalib/src/main/scala/java/io/InputStreamReader.scala [hunk 3]
```diff
@@ -91,6 +91,8 @@ class InputStreamReader(private[this] var in: InputStream,
         readMoreThroughOutBuf(cbuf, off, len)
       }
     }
+    else
+      -1
```
Comment (nicolasstucki) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: The format for the ele branch should be:

```scala
   ...
} else {
  -1
}

Comment (hmil) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: Sorry I used bits of this file as styling reference instead of CODINGSTYLE.md. Though I don't understand why this is OK (l.149) when the above is not :/
```
if (decoder.flush(out).isOverflow)
  InputStreamReader.Overflow
else {
  ...
}
```

Comment (nicolasstucki) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: Oh, (l.149) is not ok, could you fix it, it should be:
```scala
if (decoder.flush(out).isOverflow) {
  InputStreamReader.Overflow
} else {
  ...
}
```

and I see that (l.72) has that same problem, it should be:
```scala
if (len == 0) { 
  0
} else if (outBuf.hasRemaining) {
  ...
```

Comment (hmil) [inline javalib/src/main/scala/java/io/InputStreamReader.scala]: Will do, thanks for the clarification!

**Comment by nicolasstucki** [comment]
Could you squash all the commits in one.

**Comment by hmil** [comment]
Done

**Comment by nicolasstucki** [comment]
LGTM.
Jenkins, retest this please.

**Comment by nicolasstucki** [comment]
Jenkins, retest this please.
