### PR TITLE
Fix #4850: Handle JS classes that survive only for their data.

### LINKED ISSUE #4850: ClassDef checker error after linking when only using the class data of a non-native JS class
In a project (non-public :( ) that uses [tapir](https://github.com/softwaremill/tapir), compilation with 1.13.0 worked fine, while the upgrade to 1.13.1 throws the following error:

```
[error] file:/home/runner/work/tapir/tapir/serverless/aws/lambda/src/main/scalajs/sttp/tapir/serverless/aws/lambda/js/AwsJsRequest.scala(29:7:ClassDef): JS classes and module classes must have a constructor
[error] java.util.concurrent.ExecutionException: Boxed Error
[error] 	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
[error] 	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
[error] 	at scala.concurrent.Promise.complete(Promise.scala:53)
[error] 	at scala.concurrent.Promise.complete$(Promise.scala:52)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[error] Caused by: java.lang.AssertionError: There were 1 ClassDef checking errors after optimizing. Please report this as a bug.
[error] 	at org.scalajs.linker.frontend.Refiner$ClassInfoCache.update(Refiner.scala:161)
[error] 	at org.scalajs.linker.frontend.Refiner$ClassInfoCache.$anonfun$loadInfo$2(Refiner.scala:147)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

The offending line seems to be this one:
https://github.com/softwaremill/tapir/blob/master/serverless/aws/lambda/src/main/scalajs/sttp/tapir/serverless/aws/lambda/js/AwsJsRequest.scala#L29

No idea how to minimize this, but since it's a public library, it should be possible to reproduce. This bug occurs when compiling tapir 1.2.12, which is also the most recent release, released last week (at the time of writing).

Please let me know if/what further information can help, or to test a possible fix! Really looking forward to those incremental-comp performance upgrades in 1.13.1 :) Thanks!

### PR DESCRIPTION
**Pull request by sjrd**
There were several interleaved issues with JS classes (native or not, module or not) that survived the base linker only for their class data:

- Non-native classes lose their `jsConstructorDef` (which is what caused the symptoms in the issue).
- Non-native non-module classes generate a `Class.isInstance` test that tries to access a never-declared `$a_C()` accessor.
- Module classes lose their module status, triggering the wrong conditions for the `Class.isInstance` tests later on.

Some related issues about module accessors were previously handled by patching `ClassKind`s. For module classes whose module accessor was not used, we patched the kind to a corresponding kind without module accessor. This was problematic as well: it caused the third issue above, as well as making the kind unstable over incremental runs (although we tend to assume that the kind is covered by the class version).

We solve all these issues at once, by taking a much more principled approach:

- We never change the kind of classes.
- After base linking, we tolerate `ClassDef`s without constructors even if they are module classes and/or non-native JS classes.
- In the emitter, we adjust the generation of module accessors and `Class.isInstance` tests to whether the class effectively has instances.

---

This is a revisit of #4854.

### CODE REVIEW

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala [hunk 1]
```diff
@@ -131,6 +133,103 @@ class ReflectionTest {
...
+    def testName(expectedShortName: String, cls: Class[_]): Unit = {
+      val prefix = "org.scalajs.testsuite.compiler.ReflectionTest$JSTypesKeptOnlyForTheirData$"
+      val expectedName = prefix + expectedShortName
+
+      assertEquals(expectedName, cls.getName()) // constant-folded
+      assertEquals(expectedName, nameOf(cls)) // evaluated at run-time
+    }
+
+    testName("NativeClass", classOf[NativeClass])
+    testName("NativeObject$", classOf[Array[NativeObject.type]].getComponentType())
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala:153]: Is there a reason the objects/modules are always in arrays or is this just by happenstance?

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala [hunk 2]
```diff
@@ -131,6 +133,103 @@ class ReflectionTest {
...
+      val e2 = assertThrows(classOf[js.JavaScriptException], isInstance(cls, x))
+      assertTrue(e2.toString(), js.special.instanceof(e2.exception, expected))
+    }
+
+    val jsDate: Any = new js.Date(1684246473882.0)
+
+    testIsInstance(false, classOf[NonNativeClass], jsDate)
+    testIsInstance(true, classOf[JSDateForIsInstance], jsDate)
+
+    testIsInstanceThrows(js.constructorOf[js.ReferenceError], classOf[NativeClass], jsDate)
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala:199]: To check my understanding: This throws ReferenceError, because `NativeClass` isn't actually defined, right?

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala [hunk 3]
```diff
@@ -131,6 +133,103 @@ class ReflectionTest {
...
+
+    testIsInstanceThrows(js.constructorOf[js.TypeError],
+        classOf[Array[NativeObject.type]].getComponentType(), jsDate)
+    testIsInstanceThrows(js.constructorOf[js.TypeError], classOf[NativeTrait], jsDate)
+    testIsInstanceThrows(js.constructorOf[js.TypeError],
+        classOf[Array[NonNativeObject.type]].getComponentType(), jsDate)
+    testIsInstanceThrows(js.constructorOf[js.TypeError], classOf[NonNativeTrait], jsDate)
+    testIsInstanceThrows(js.constructorOf[js.TypeError],
+        classOf[Array[JSDateForIsInstance.type]].getComponentType(), jsDate)
```
Comment (gzm0) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala:208]: To check my understanding: These throw TypeError, because instance checking on traits and modules isn't supported? (FWIW: Why isn't instance checking on a module not just reference equality?)

**Review by gzm0 — CHANGES_REQUESTED** [review]

File: test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala (hunk 2 above)
Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/compiler/ReflectionTest.scala:207]: Yes, indeed. I added a comment.

**Review by gzm0 — APPROVED** [review]
