### PR TITLE
A portion of the new linker API of #2998

### LINKED ISSUE #2998: New Linker API
This is a summary extracted from the discussion in #2969, along with some small refinements I came up with while actually trying to implement that stuff.

## Goal

We want a new, simplified Linker API with one core "feature": a decomposition into 3 levels of API stability:

1. Super-stable API: always backward source and binary compatible across minor versions (except in the event of a catastrophic failure :P). It provides a reference point for people who "just want to link" their codebase, possibly with some configuration, but only configs that are meant to be supported "forever".
2. Stable-ish API: the API used by people who want to write their own linker plugins, or to compose some custom linkers, etc. It also exposes some less-stable configs. That API is supposed to stay backward source and binary compatible across minor releases unless maintaining compatibility would prevent progress. It should not be broken without a reasonably good reason.
3. Unstable, private-ish API: some things that we can freely break in minor releases, but that are technically *public* because they can be useful for some tools, e.g., the IR checker.

## Super-stable API, in `org.scalajs.core.tools.linker`

It is trimmed down to the bare minimum. The complete API surface looks like this:
```scala
abstract class Linker private[linker] () {
  def link(irFiles: Seq[VirtualScalaJSIRFile],
      moduleInitializers: Seq[ModuleInitializer],
      output: WritableVirtualJSFile, logger: Logger): Unit
}

final class ClearableLinker(newLinker: () => Linker) extends Linker {
  def link(...): Unit
  def clear(): Unit
}

class LinkingException(...) extends Exception

object StandardLinker {
  def apply(config: Config): Linker

  final class Config private () {
    val semantics: Semantics
    val moduleKind: ModuleKind
    
    val sourceMap: Boolean
    val parallel: Boolean
    ...
    private[linker] val outputMode: OutputMode

    def withSourceMap(sourceMap: Boolean): Config
    ...
    private[linker] def withOutputMode(outputMode: OutputMode): Config
  }

  object Config {
    def apply(semantics: Semantics, moduleKind: ModuleKind): Config
  }
}

final class Semantics private () { ... }
object Semantics { ... }

abstract class ModuleKind private[linker] () { ... }
object ModuleKind { ... }
```
Some things to note:
* There is no `class StandardLinker`. That's a stable-ish API.
* `OutputMode` is `private[linker]` and will only be accessible/configurable through a stable-ish API (see below). The rationale is that it is tight to our current standard linker backend and emitter. But in practice we know it's not something we want to support for a very long time (we destroyed 3 `OutputMode`s already in our history!).
* The `Semantics` and `ModuleKind` configs receive official, stable default values (`Semantics.Defaults` and `ModuleKind.NoModule`). These configs are the ones that semantically define how the code behaves a) internally (`Semantics`) and b) externally (`ModuleKind`).
* Speaking of which, `Semantics` and `ModuleKind` are acquired by the `linker` package, instead of `sem` and `backend` respectively.
* `GenLinker` has basically become `Linker`. The old `Linker` does not exist in the super-stable API.
* `Linker` is an `abstract class` with a package-private constructor, so that we can hope to add additional methods in a binary compatible way. This would be necessary for an API that can generate *multiple* JS files in the future, for example.
* `ModuleKind` is not `sealed` in the super-stable API, because we will have to add new `ModuleKind`s in the future. It should be `sealed` "from the inside" so that we get exhaustivity warnings, but the best way to achieve that is unclear at this point. There is an idea in https://github.com/scala-js/scala-js/pull/2969#issuecomment-306689887.
* `ESLevel` is gone.

## Stable-ish API in `org.scalajs.core.tools.linker.standard`

This is the "standard" linker, which constitutes the stable-ish API. It is decomposed in a front-end and a back-end. The back-end has an `OutputMode`.

```scala
final class StandardLinker(frontend, backend) extends Linker { ... }

object StandardLinker {
  type Config = linker.StandardConfig.Config
}

type OutputMode = LinkerBackend.OutputMode
val OutputMode = LinkerBackend.OutputMode

implicit class StandardLinkerConfigStandardOps(
    val __self: StandardLinker.Config) extends AnyVal {
  def outputMode: OutputMode

  def withOutputMode(outputMode: OutputMode): StandardLinker.Config
}

abstract class LinkerFrontend {
  def link(irFiles: Seq[VirtualScalaJSIRFile],
      moduleInitializers: Seq[ModuleInitializer],
      symbolRequirements: SymbolRequirement, logger: Logger): LinkingUnit
}

object LinkerFrontend {
  final class Config private () { ... }
  object Config { ... }
}

abstract class LinkerBackend {
  def emit(unit: LinkingUnit, output: WritableVirtualJSFile, logger: Logger): Unit
}

object LinkerBackend {
  sealed abstract class OutputMode
  object OutputMode { ... }

  final class Config private () { ... }
  object Config { ... }
}

final class LinkingUnit { ... }

sealed abstract class SymbolRequirement
object SymbolRequirement { ... }
```
Notes:
* In the `standard._` subpackage, the decomposition front-end/back-end is standard and supported
* The `LinkingUnit` abstraction is standard and supported
* The `OutputMode` data type is exposed
* There are some additional operations on `StandardLinker.Config` available through an implicit class

## Unstable, private-ish API

Everything else. This includes the analyzer, IR checker, optimizer, the actual implementations of `LinkerFrontend` and `LinkerBackend` (including the `BaseLinker`, `Refiner` and `Emitter`).

## Path to get there

In 0.6.x: simply *add* enough of the super-stable API and stable-ish API so that simple linker usage (such as done in the CLI or the sbt plugin) can be written in a source-compatible way between 0.6.x and 1.x. This means

* `linker.StandardLinker._`
* `linker.{ModuleKind, Semantics}` (as aliases to `backend.ModuleKind` and `sem.Semantics`, resp.)
* `linker.standard.OutputMode`
* `linker.standard.StandardLinkerConfigStandardOps`

We also deprecate the parts of the existing old API that can directly be replaced by the above parts, i.e., `Linker.apply`.

We don't touch anything else in 0.6.x. In particular, we make no attempt to revisit/deprecate the front-end/back-end and their `Config`s.

In 1.x, we simply nuke everything and put the new API in place.

### PR DESCRIPTION
**Pull request by sjrd**
This is part of #2998, though there is still a bunch of things to do. In particular, the `linker._` package still need to be cleaned up, with things renamed and/or moved to `standard._`. Nevertheless, it is a substantial step in the direction of the new API.

### CODE REVIEW

**Comment by sjrd** [comment]
Rebased + new commit (at the top) that removes `RuntimeClassNameMapper.custom()`.

**Comment by sjrd** [comment]
@gzm0 Any chance you could have a look at this PR, one of these days?

**Comment by gzm0** [comment]
Yep, will do. I have a couple of comments pending that I'll release.

**Comment by gzm0** [comment]
In case that wasn't clear, that's not everything :)

File: tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackendPlatformExtensions.scala [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+**  __\ \/ /__/ __ |/ /__/ __ |/_// /_\ \    http://scala-js.org/       **
+** /____/\___/_/ |_/____/_/ | |__/ /____/                               **
+**                          |/____/                                     **
+\*                                                                      */
+
+package org.scalajs.core.tools.linker.backend
+
+import org.scalajs.core.tools.linker.backend.closure.ClosureLinkerBackend
+
+object LinkerBackendPlatformExtensions {
```
Comment (sjrd) [inline tools/jvm/src/main/scala/org/scalajs/core/tools/linker/backend/LinkerBackendPlatformExtensions.scala]: No, there's no need to. The `implicit def` that converts a `LinkerBackend.Config` into a `LinkerBackendPlatformExtensions.ConfigExt` is defined in the companion object of `LinkerBackend.Config`. So even though the target type is not in the import scope, the implicit conversion itself is in the implicit scope, so the implicit pimp works without import. The same mechanism is already applied for `StandardConfig.closureCompiler`.

File: ir/src/main/scala/org/scalajs/core/ir/Trees.scala [hunk 2]
```diff
@@ -965,9 +965,11 @@ object Trees {
...
 
-  /** A hash of a tree (usually a MethodDef). Contains two SHA-1 hashes */
-  final class TreeHash(val treeHash: Array[Byte], val posHash: Array[Byte]) {
-    assert(treeHash.length == 20)
-    assert(posHash.length == 20)
+  /** A hash of a tree (usually a MethodDef).
+   *
+   *  Contains a SHA-1 hash.
+   */
+  final class TreeHash(val hash: Array[Byte]) {
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Trees.scala]: It can probably be `AnyVal`, indeed. I'll have to check whether it would be boxed more often than not, but I don't think so.

Inlining would make it more annoying to ensure invariants, not to mention being typesafe for methods like `hashesEqual` and `hashAsVersion`.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala [hunk 3]
```diff
@@ -75,83 +70,12 @@ final class Linker(frontend: LinkerFrontend, backend: LinkerBackend)
...
-          optimizer = optimizer,
-          parallel = parallel,
-          closureCompilerIfAvailable = closureCompilerIfAvailable,
-          frontendConfig = frontendConfig,
-          backendConfig = backendConfig)
-    }
+object Linker {
+  def apply(frontendConfig: LinkerFrontend.Config,
+      backendConfig: LinkerBackend.Config): Linker = {
+    apply(LinkerFrontend(frontendConfig), LinkerBackend(backendConfig))
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala]: Probably useless, indeed.

File: tools/jvm/src/main/scala/org/scalajs/core/tools/linker/frontend/LinkerFrontendPlatformExtensions.scala [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+**  __\ \/ /__/ __ |/ /__/ __ |/_// /_\ \    http://scala-js.org/       **
+** /____/\___/_/ |_/____/_/ | |__/ /____/                               **
+**                          |/____/                                     **
+\*                                                                      */
+
+package org.scalajs.core.tools.linker.frontend
+
+import org.scalajs.core.tools.linker.frontend.optimizer._
+
+private[frontend] object LinkerFrontendPlatformExtensions {
```
Comment (sjrd) [inline tools/jvm/src/main/scala/org/scalajs/core/tools/linker/frontend/LinkerFrontendPlatformExtensions.scala]: Idk. Some possible alternatives:
* `LinkerFrontendPlatform`
* Just `Platform`, and throw everything platform-specific from the `frontend` package in it.

**Comment by gzm0** [comment]
I don't understand why you want to remove `ESLevel`. Now the backend is leaking the `OutputMode` and the `ModuleKind` into the frontend. I think it is a valuable separation of concerns to hide things the frontend doesn't need to know from it.

File: tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala [hunk 5]
```diff
@@ -75,83 +70,12 @@ final class Linker(frontend: LinkerFrontend, backend: LinkerBackend)
...
-      new Config(
-          optimizer = true,
-          parallel = true,
-          closureCompilerIfAvailable = false,
-          frontendConfig = LinkerFrontend.Config(),
-          backendConfig = LinkerBackend.Config())
-    }
-  }
+  def apply(frontend: LinkerFrontend, backend: LinkerBackend): Linker =
+    new Linker(frontend, backend)
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/linker/Linker.scala]: Yes. The `class Linker` in this file is actually what will eventually become the class `standard.StandardLinker`, and this `apply` method will be moved to the object `standard.StandardLinker`. And the current `linker.GenLinker` will become `linker.Linker`.

File: tools/jvm/src/main/scala/org/scalajs/core/tools/linker/frontend/LinkerFrontendPlatformExtensions.scala (hunk 4 above)
Comment (sjrd) [inline tools/jvm/src/main/scala/org/scalajs/core/tools/linker/frontend/LinkerFrontendPlatformExtensions.scala]: Yes, indeed. `Extensions` are ultimately part of the public API because they are inherited. Whereas this thing is an implementation detail that need never be seen.

**Comment by sjrd** [comment]
> I don't understand why you want to remove ESLevel. Now the backend is leaking the OutputMode and the ModuleKind into the frontend. I think it is a valuable separation of concerns to hide things the frontend doesn't need to know from it.

The problem is that it is not completely clear that the frontend does not need to know about the output mode and module kind. For example, if we add an output mode that technically *assumes* ES2015+, but is optimized for speed rather than "for exploiting ES2015 features as much as possible", the frontend phases, and the optimizer in particular, could have to make different decisions in that mode versus `ECMAScript6`.

Similarly, the frontend may need to know things about the module kind. For example, we might want the Analyzer to report linking errors if an `@JSImport` class/object without `globalFallback` is reachable, but the module kind is `NoModule`.

I can reintroduce `ESLevel` under `standard._` if you want. But in the presence of `OutputMode`, it is redundant. Its only use case would be to write custom phases (in plugins) that want to take decisions only depending on the assumed ES version, without being affected by the addition or removal of `OutputMode`s in the future. But for that use case `ESLevel` should have an `Ordering`, so that I can take decisions based on "Is it ES2015 *or later*"?

**Comment by gzm0** [comment]
Ok, fair enough, I buy this. We can introduce `ESLevel` again if plugins actually start proliferating.

File: ir/src/main/scala/org/scalajs/core/ir/Trees.scala (hunk 2 above)
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Trees.scala]: So, actually, `TreeHash`es are always inside an `Option`, so making them `AnyVal`s would not improve anything. On the other hand, it would slightly degrade our ability to evolve them in binary compatible ways. So I'd say we keep them as is.

Does that make sense?

**Comment by sjrd** [comment]
Updated with:
* Removal of `Linker.apply(frontendConfig, backendConfig)`
* `LinkerFrontendPlatform` and `LinkerBackendPlatform`

and also changed the PR description so that it won't close automatically the issue. (there was no *commit* with such a message)

File: ir/src/main/scala/org/scalajs/core/ir/Trees.scala (hunk 2 above)
Comment (gzm0) [inline ir/src/main/scala/org/scalajs/core/ir/Trees.scala]: SG.
