### PR TITLE
Fix #3538: Ignore mixin forwarders when looking for export alternatives.

### LINKED ISSUE #3538: @JSExport on method with variable arguments in trait behaves different from class
In Scala.js 0.6.26 the from JavaScript accessible method `possiblyBroken` throws an Exception when being called from JavaScript. A look in the compiled code shows, that it lacks the code for handling variable arguments that `notBroken1` and `notBroken2` have.

```scala
trait Foo {
  @JSExport def possiblyBroken(args: Int*): Unit = ???
}

class Foo2 {
  @JSExport def notBroken1(args: Int*): Unit = ???
}

@JSExportTopLevel("bar")
object Bar extends Foo2 with Foo {
  @JSExport def notBroken2(args: Int*): Unit = ???
}
```

### PR DESCRIPTION
**Pull request by sjrd**
Mixin forwarders are cloned with a type history that does not go far enough back in time to see varargs. By skipping them when looking for the alternatives of an export, we look further in the class hierarchy to the original definition in the trait, which does expose the entire type history that we need.

Inspired by the discussion at https://github.com/scala/scala/pull/7843.
Supersedes https://github.com/scala/scala/pull/7752.

### CODE REVIEW

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 1]
```diff
@@ -356,6 +356,34 @@ class ExportsTest {
     assertEquals(4, bar.method(2))
   }
 
+  @Test def should_inherit_exports_from_traits_with_value_classes(): Unit = {
```
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: This test already passes before the changes in this commit. It's only related because it also relies on the type history of export bridges.

Comment (sjrd) [reply test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: Well, turns out it *doesn't* pass in 2.10. It seems to be an independent issue, though, so I filed it as #3585.
