### PR TITLE
Fix #2265 and #2741: Look for repeated args in all parameter lists.

### LINKED ISSUE #2265: The varargs optimization of the compiler does not work for AnyVal methods
``` scala
object MyJSArrayOps {
  implicit class MyJSArray(val self: js.Array.type) extends AnyVal {
    @inline
    def make[A](elems: A*): js.Array[A] = elems.toJSArray
  }
}

object HelloWorld extends js.JSApp {
  def main(): Unit = {
    import MyJSArrayOps._

    val a = js.Array.make("hello", 7, 12)
  }
}
```

gives

``` scala
  def main__V() {
    val a: any = mod:Lhelloworld_MyJSArrayOps$MyJSArray$.make$extension__sjs_js_Array$__sc_Seq__sjs_js_Array(mod:Lhellow
orld_MyJSArrayOps$.MyJSArray__sjs_js_Array$__sjs_js_Array$(<envinfo>["global"]["Array"]), mod:s_Predef$.genericWrapArray
__O__scm_WrappedArray(O[]("hello", 7, 12)));
    ...
  }
```

but if it is not an `AnyVal`, it gives, as expected:

``` scala
  def main__V() {
    val a: any = mod:Lhelloworld_MyJSArrayOps$.MyJSArray__sjs_js_Array$__Lhelloworld_MyJSArrayOps$MyJSArray(<envinfo>["g
lobal"]["Array"]).make__sc_Seq__sjs_js_Array(new sjs_js_WrappedArray().init___sjs_js_Array(["hello", 7, 12]));
    ...
```

### PR DESCRIPTION
**Pull request by sjrd**
Usually, in the compiler back-end, we use `methodTpe.params` to read the list of all parameters. This works because multiple parameter lists are flattened. The code that optimizes varargs as `new js.WrappedArray(js.Array(...))` was reading parameters right after `typer` in the type history. It has to use `.paramss.flatten` in that case, because `.params` represents only the first parameter list.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0 
/cc @chandu0101

**Comment by chandu0101** [comment]
@sjrd  thanks alot :) , i just tested in my local working perfect 👍

File: compiler/src/test/scala/org/scalajs/core/compiler/test/OptimizationTest.scala [hunk 1]
```diff
@@ -56,21 +58,58 @@ class OptimizationTest extends JSASTTest {
...
       val e = List(new VC(151189))
+
+      def single(x: Int, ys: Int*): Int = x + ys.size
+      def multiple(x: Int)(ys: Int*): Int = x + ys.size
+    }
+    """.
+    hasNot("any of the wrapArray methods") {
+      case js.Apply(_, js.Ident(name, _), _)
+          if name.startsWith("wrap") && name.endsWith("__scm_WrappedArray") =>
+    }
```
Comment (gzm0) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/OptimizationTest.scala]: It seems like this is duplicate

Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/OptimizationTest.scala]: Oops, indeed.

**Comment by sjrd** [comment]
Updated.
