### PR TITLE
Fix #2821: Adapt column pos in source maps for printEscapeJS

### LINKED ISSUE #2821: Source Maps bug - wrong column in the generated file
There seems to be a bug in the class `JSTreePrinterWithSourceMap` causing that the source maps does not exactly match the generated file.
The class has two purposes:
1. it generates the output javascript code using its base class `JSTreePrinter`
2. it maintains the position in the javascript (in `private var column`) and uses it to generate source map (using `sourceMap: SourceMapWriter`)
To serve well for both these functions, there is necessary to keep `var column` synchronized with the position in `out` stream (see `override protected def print(s: String): Unit`). However, in the function `override protected def print(ident: Ident): Unit` (and one similar place) there is some writing to `out` without change of `var column`.

### PR DESCRIPTION
**Pull request by Gralfim**
When investigating issue #2795, we found that there are situations when javascript code was written, but column field used by the source map writer to point where in javascript you are was not updated.

### CODE REVIEW

**Comment by gzm0** [comment]
@Gralfim thanks for the contribution.
Could you please [sign the CLA](http://www.lightbend.com/contribute/cla/scala)? We cannot look at your code before that.

**Comment by Gralfim** [comment]
Signed.

**Comment by sjrd** [comment]
Thanks. Could you also open an issue that describes the problem, so that you can reference it in your commit message? This is useful to refer to closed issue when, e.g., duplicates come up.

Also, administrative detail: since we're in the middle of the release process, I'll delay running the CI on your PR until we have a Towards 0.6.16 commit. Otherwise our CI gets confused.

**Comment by Gralfim** [comment]
We have added commit message referencing to the original issue (#2795). Is it sufficient?

**Comment by gzm0** [comment]
> We have added commit message referencing to the original issue (#2795). Is it sufficient?

It is probably neater to open a new issue describing the exact problem with the source map writer. #2795 is more of a catch-all "source maps are not super easy to use" issue.

Also, note the [guidelines on commit messages][1] (TL;DR: Start with "Fix #1234: ..." if you are fixing something).

[1]: https://github.com/scala-js/scala-js/blob/master/CONTRIBUTING.md#first-line-of-the-commit-message

**Comment by Gralfim** [comment]
Commit message format fixed, pointing to the new issue #2821.

**Comment by sjrd** [comment]
@Gralfim We're done with our release process for 0.6.15. Since now we have 2 main branches (master for 1.x, and 0.6.x for 0.6.x), could you rebase the branch of this PR on top of the 0.6.x branch, please? I have already updated the PR itself so that it aims to be merged in the 0.6.x branch.

**Comment by sjrd** [comment]
The [introduction of `printEscapeJS`](https://github.com/scala-js/scala-js/commit/b5200df4861ff761c4ffd1cba6e2ec1329e9d6a4) was part of [a series of PRs](https://github.com/scala-js/scala-js/issues/1926) by @nicolasstucki aimed at reducing allocations and improving speed in the emitter (a performance-sensitive part). It would be good not to annihilate those gains.

I suggest declaring a `protected def printEscapeJS` in `JSTreePrinter`, called by the two locations that you modified. In `JSTreePrinter` it can simply call `Utils.printEscapeJS`. Overridden in `JSTreePrinterWithSourceMap`, it won't be that easy. Maybe we need to duplicate some of the code from `Utils` :s

**Comment by Gralfim** [comment]
I tried to re-implement the fix based on your suggestion, but tried to keep it DRY. Please check if it is acceptable for you now.

File: tools/shared/src/main/scala/org/scalajs/core/tools/javascript/Printers.scala [hunk 1]
```diff
@@ -555,8 +554,11 @@ object Printers {
       }
     }
 
+    protected def printEscapeJS(s: String): Int =
```
Comment (sjrd) [inline tools/shared/src/main/scala/org/scalajs/core/tools/javascript/Printers.scala]: It seems that this one can return `Unit`

File: ir/src/main/scala/org/scalajs/core/ir/Utils.scala [hunk 2]
```diff
@@ -75,12 +75,13 @@ object Utils {
     sb.toString
   }
 
-  def printEscapeJS(str: String, out: java.lang.Appendable): Unit = {
+  def printEscapeJS(str: String, out: java.lang.Appendable): Int = {
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/Utils.scala]: I like your solution a lot, it's a lot DRYer than I had thought possible.

However you'll have some difficulty with our binary compat checker, because this method is not binary-compatible with its previous incarnation. You can run it locally with
```
> ir/mimaReportBinaryIssues
```
I think we'll just have to break bin-compat of the tools, here. You can whitelist this method in `project/BinaryIncompatibilities.scala`. See for example [here](https://github.com/scala-js/scala-js/blob/v0.6.15/project/BinaryIncompatibilities.scala#L5-L18) how we do it, and the formatting/comments we use.

**Comment by sjrd** [comment]
Jenkins, test this please

**Comment by Gralfim** [comment]
Requested changes (binary incompatibilities, return type in Printers.scala) committed. Please, check it once more.

File: project/BinaryIncompatibilities.scala [hunk 3]
```diff
@@ -3,6 +3,9 @@ import com.typesafe.tools.mima.core.ProblemFilters._
 
 object BinaryIncompatibilities {
   val IR = Seq(
+    // Breaking: Utils.printEscapeJS now returns Int
+    ProblemFilters.exclude[IncompatibleResultTypeProblem](
+      "org.scalajs.core.ir.Utils.printEscapeJS")
   )
```
Comment (sjrd) [inline project/BinaryIncompatibilities.scala]: According to our coding style, the indentation inside `()` is 4 spaces, not 2. So to be pedantic (because we are), this should be:
```scala
  val IR = Seq(
      // Breaking: Utils.printEscapeJS now returns Int
      ProblemFilters.exclude[IncompatibleResultTypeProblem](
          "org.scalajs.core.ir.Utils.printEscapeJS")
  )
```

**Comment by Gralfim** [comment]
Indentation fixed, commit message updated.

**Comment by sjrd** [comment]
Jenkins, retest this please

**Comment by sjrd** [comment]
Sorry for the long delay in replying here.
It seems this PR has tipped the bootstrap test just above its allocated memory. Could you increase the available memory to 3072 [in `ci/matrix.xml`](https://github.com/scala-js/scala-js/blob/385487abda38fc8d17447e7b13a399341b2f2a0b/ci/matrix.xml#L206-L210)? (in the same commit)

**Comment by sjrd** [comment]
Jenkins, retest this please
