### PR TITLE
Fix #2799: Don't use `equals` for comparing java.lang.Double/Float.

### LINKED ISSUE #2799: `==` between `j.l.{Float,Double}` gives incorrect results for zeros and NaNs.
Scala/JVM had the same issue. It was fixed in https://github.com/scala/scala/pull/5761 for 2.12.2+.

### PR DESCRIPTION
**Pull request by sjrd**
This is essentially a port of the fix for scala-dev#329, which was implemented in scala/scala#5761.

To remain bug-compatible with the JVM, we explicitly look at the version of the Scala compiler that we run on to determine whether or not the fix should be applied.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @gzm0. Locally tested on 2.12.2-bin-3fadf69 (both JVM and JS).

File: test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/RegressionTest.scala [hunk 1]
```diff
@@ -435,6 +435,98 @@ class RegressionTest {
     assertEquals((Nil, 10), result)
   }
 
+  @Test def eqEqJLDouble(): Unit = {
+    // Taken from run/sd329.scala in scala/scala
+
+    val v = Platform.scalaVersion
+    assumeFalse("Bug scala-dev#329, #2799 on this version of Scala",
+        v.startsWith("2.10.") || v.startsWith("2.11.") ||
+        v == "2.12.0" || v == "2.12.1")
```
Comment (gzm0) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/RegressionTest.scala]: Shouldn't we also add tests for the other case? I.e. when this assume is true? Seems simple enough and guards us against not being really bug compatible.

Comment (sjrd) [inline test-suite/shared/src/test/scala/org/scalajs/testsuite/compiler/RegressionTest.scala]: Ah ah, indeed.

**Comment by sjrd** [comment]
Updated. Re-tested locally with 2.12.2-bin-3fadf69.

**Comment by sjrd** [comment]
Dear Jenkins, retest this please
