### PR TITLE
Fix #2631: Gracefully fail if UndefinedParam slips

### LINKED ISSUE #2631: js.UndefinedParam interacts badly with compiler plugins
I have a cross project and when using the "test" command in SBT, I get the following error:

```
org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing Lsome_
package_AbstractAjaxLoader.init___T__T: java.lang.RuntimeException: Invalid tree in transform of class org.scalajs.core.ir.Trees$UndefinedParam: UndefinedParam()
Methods attempted to inline:
* O.init___
* s_concurrent_Promise$.apply__s_concurrent_Promise
* s_concurrent_impl_Promise$DefaultPromise.future__s_concurrent_Future
* s_concurrent_impl_Promise$DefaultPromise.future__s_concurrent_impl_Promise
[error] * static s_concurrent_impl_Promise$class.future__s_concurrent_impl_Promise__s_concurrent_impl_Promise
```

The strange thing is that this only happens with the "test" command. fastOptJS works perfectly !

Here's the full class where the error seems to happen:

```
abstract class AbstractAjaxLoader(val path: String, val responseType: String) extends Loader {

    type Data = dom.XMLHttpRequest

    protected override val data: Future[Data] = {
        val promise = Promise[Data]()

        val request = new XMLHttpRequest()
        request.open(method = "GET", url = path)
        request.responseType = responseType
        request.onload = (_: dom.Event) => promise.success(request)
        request.onerror =
                (e: ErrorEvent) => promise.failure(new Exception(s"Failed to load $path: ${e.message}"))

        request.send()
        promise.future
    }

    def dataText: Future[String] = data.map(_.responseText)

}
```

And the full stack:

```
[info] Fast optimizing /.../js/target/scala-2.11/project-test-fastopt.js
org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing Lsome_package_AbstractAjaxLoader.init___T__T: java.lang.RuntimeException: Invalid tree in transform of class org.scalajs.core.ir.Trees$UndefinedParam: UndefinedParam()
Methods attempted to inline:
* O.init___
* s_concurrent_Promise$.apply__s_concurrent_Promise
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.optimize(OptimizerCore.scala:150)
    at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer$MethodImpl.process(GenIncOptimizer.scala:921)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:87)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:86)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:145)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:138)
    at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
    at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:183)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
    at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Invalid tree in transform of class org.scalajs.core.ir.Trees$UndefinedParam: UndefinedParam()
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:677)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:701)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.transformBlock(OptimizerCore.scala:722)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:313)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformExpr(OptimizerCore.scala:283)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformExprOrSpread(OptimizerCore.scala:291)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$34.apply(OptimizerCore.scala:626)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$34.apply(OptimizerCore.scala:626)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:626)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.transformStat(OptimizerCore.scala:271)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:715)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1$1$$anonfun$apply$9$$anonfun$apply$10.apply(OptimizerCore.scala:708)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1$1$$anonfun$apply$9$$anonfun$apply$10.apply(OptimizerCore.scala:707)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withBinding$1.apply(OptimizerCore.scala:3774)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withBinding$1.apply(OptimizerCore.scala:3773)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.withDedicatedVar$1(OptimizerCore.scala:3850)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.apply(OptimizerCore.scala:3882)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.apply(OptimizerCore.scala:3806)
    at scala.util.control.TailCalls$TailRec.loop$1(TailCalls.scala:37)
    at scala.util.control.TailCalls$TailRec.result(TailCalls.scala:40)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$trampoline(OptimizerCore.scala:3975)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:704)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1$1$$anonfun$apply$9$$anonfun$apply$10.apply(OptimizerCore.scala:708)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1$1$$anonfun$apply$9$$anonfun$apply$10.apply(OptimizerCore.scala:707)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withBinding$1.apply(OptimizerCore.scala:3774)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withBinding$1.apply(OptimizerCore.scala:3773)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.withDedicatedVar$1(OptimizerCore.scala:3850)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.apply(OptimizerCore.scala:3882)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$withNewLocalDef$1.apply(OptimizerCore.scala:3806)
    at scala.util.control.TailCalls$TailRec.loop$1(TailCalls.scala:37)
    at scala.util.control.TailCalls$TailRec.result(TailCalls.scala:40)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$trampoline(OptimizerCore.scala:3975)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:704)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.transformBlock(OptimizerCore.scala:722)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:313)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformExpr(OptimizerCore.scala:283)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$9.apply(OptimizerCore.scala:357)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$9.apply(OptimizerCore.scala:322)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformSelectCommon(OptimizerCore.scala:1070)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformSelectCommon$1.apply(OptimizerCore.scala:1003)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformSelectCommon$1.apply(OptimizerCore.scala:1001)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExpr$1.apply(OptimizerCore.scala:793)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExpr$1.apply(OptimizerCore.scala:774)
    at scala.util.control.TailCalls$TailRec.loop$1(TailCalls.scala:37)
    at scala.util.control.TailCalls$TailRec.result(TailCalls.scala:40)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$trampoline(OptimizerCore.scala:3975)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:360)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:701)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transformList$1(OptimizerCore.scala:717)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.transformBlock(OptimizerCore.scala:722)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$transform(OptimizerCore.scala:313)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.transformIsolatedBody(OptimizerCore.scala:3617)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.liftedTree1$1(OptimizerCore.scala:131)
    at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.optimize(OptimizerCore.scala:130)
    at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer$MethodImpl.process(GenIncOptimizer.scala:921)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:87)
    at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:86)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:145)
    at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:138)
    at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
    at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
    at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:183)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
    at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by gzm0**
In Scala, default parameters are resolved at call site. Therefore, it is valid for a macro or a compiler plugin to move them around or even completely decouple from the function call they originated from.

However, for Scala.js' facade types, this is not the case, mainly because in JavaScript, default parameters are resolved at definition site. Macros and compiler plugins must (to some extent) be aware of this restriction when running together with the Scala.js compiler plugin.

With this commit, we gracefully report if we cannot compile a tree we received due to this restriction. Before this fix, the compiler emitted invalid IR.

### CODE REVIEW

**Comment by gzm0** [comment]
Review by @sjrd

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+}
+
+// scalastyle:off line.size.limit
+
+class JSUndefinedParamTest extends DirectTest with TestHelpers {
+
+  override def classpath: List[String] = {
+    // Make JSUndefinedParamTest available to the code we compile in the test
+    val loader =
+      JSUndefinedParamTest.getClass.getClassLoader.asInstanceOf[URLClassLoader]
```
Comment (gzm0) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala]: Nah... That's the lazy way. I haven't looked how scalac does this.

I could inject the classpath via system property as well, but I'm not sure that's much cleaner...

Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala]: Well my concern is mostly that we put the entire classpath of the compiler testing code (which includes the entire compiler) in this. Isn't there a way to actually compile in 2 steps with `DirectTest`, simulating separate compilation?

Comment (gzm0) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala]: This is not scalac's `DirectTest`. It's our own. So, no, it is not able to do that. But we can implement it if we want :)

**Comment by gzm0** [comment]
I like your alternate proposal. The only concern I have is whether we'll be able to recover the position (`global.Position` -> `ir.Position` conversion is non-trivial, especially for virtual positions).

We can of course also report without position, but that will make debugging hard. Maybe it is enough to report the `ir.Position` at an arbitrary other position :S

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala (hunk 1 above)
Comment (gzm0) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala]: I don't know. I'll have a look :)

**Comment by sjrd** [comment]
> We can of course also report without position, but that will make debugging hard. Maybe it is enough to report the ir.Position at an arbitrary other position :S

TBH Even a compiler crash with a decent exception `message` would be enough, IMO. So yes, I think it's fine to report with the enclosing method's position, and mention the `ir.Position` in the text of the error.

**Comment by sjrd** [comment]
I have another potential alternative. We have to traverse the entire `js.MethodDef` in `Infos` anyway. We could throw an exception if `Infos.genMethodInfo` encounters a `js.UndefinedParam`. That's sensible to some extent because there is no meaningful Info that can be created for a method that does not IR-check to begin with. We could catch this exception from `genJSCode` and translate it into a `reporter.error` for the benefit of readability.

Much simpler and 0 cost, but potentially a bit ugly?

**Comment by gzm0** [comment]
Yeah, I like this. It has the drawback that it won't report all the `UndefinedParams` exhaustively, but that's fine. The culprit is probably only a single macro / compiler plugin anyways.

**Comment by gzm0** [comment]
Updated.

File: ir/src/main/scala/org/scalajs/core/ir/InvalidIRException.scala [hunk 2]
```diff
@@ -0,0 +1,6 @@
+package org.scalajs.core.ir
+
+import java.io.IOException
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/core/ir/InvalidIRException.scala]: Useless import.

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSFiles.scala [hunk 3]
```diff
@@ -29,6 +29,19 @@ trait GenJSFiles extends SubComponent { self: GenJSCode =>
     try {
       ir.InfoSerializers.serialize(output, Infos.generateClassInfo(tree))
       ir.Serializers.serialize(output, tree)
+    } catch {
+      case e: ir.InvalidIRException =>
+        e.tree match {
+          case ir.Trees.UndefinedParam() =>
+            reporter.error(NoPosition, "Found a dangling UndefinedParam at " +
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSFiles.scala]: Consider using `sym.pos`. That would at least give an anchor for IDEs to display the error.

File: compiler/src/main/scala/org/scalajs/core/compiler/GenJSFiles.scala [hunk 4]
```diff
@@ -29,6 +29,19 @@ trait GenJSFiles extends SubComponent { self: GenJSCode =>
...
+                s"${e.tree.pos}. This is likely due to a bad interaction " +
+                "between a macro or a compiler plugin and the Scala.js " +
+                "compiler plugin. If you hit this, please let us know.")
+
+          case _ =>
+            reporter.error(NoPosition, "The Scala.js compiler generated " +
```
Comment (sjrd) [inline compiler/src/main/scala/org/scalajs/core/compiler/GenJSFiles.scala]: Same here.

File: compiler/src/test/scala/org/scalajs/core/compiler/test/util/DirectTest.scala [hunk 5]
```diff
@@ -26,7 +28,7 @@ abstract class DirectTest {
         List(
             "-d", testOutputPath,
             "-bootclasspath", scalaLibPath,
-            "-classpath", scalaJSLibPath) ++
+            "-classpath", classpath.mkString(":")) ++
```
Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/util/DirectTest.scala]: This doesn't work on Windows (I tested). You need to use `File.pathSeparator` (I tested that it fixes the issue).

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala [hunk 6]
```diff
@@ -0,0 +1,87 @@
...
+ *  This test contains a macro that generates a tree we cannot handle and
+ *  verifies that the compiler bails out.
+ */
+class JSUndefinedParamTest extends DirectTest with TestHelpers {
+
+  /* We need a macro in the test. Therefore, we add scala-reflect and the
+   * compiler's output path itself to the classpath.
+   */
+  override def classpath: List[String] =
+    super.classpath ++ List(scalaReflectPath, testOutputPath)
```
Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSUndefinedParamTest.scala]: Now that's much better!

File: compiler/src/test/scala/org/scalajs/core/compiler/test/util/DirectTest.scala (hunk 5 above)
Comment (gzm0) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/util/DirectTest.scala]: Ah, yes. I knew when wrote it and forgot to fix it. Good you caught it.

**Comment by gzm0** [comment]
Updated.
