### PR TITLE
Fix #4949: Always wrap object literals with `()`.

### LINKED ISSUE #4949: Wrong pretty-printing of JS tree that *starts* with an object lit
Building up on #1627, we still have an issue when a statement *textually starts* with an object literal, although the tree node is not directly an `ObjectLiteral`. Test cases:
```scala
    js.Dynamic.literal(foo = "bar").foo
    js.Dynamic.literal(foo = () => "bar").foo()
    js.Dynamic.literal(foo = "bar").foo = "babar"
    js.Dynamic.literal(foo = "foo").selectDynamic(dynProp())
    js.Dynamic.literal(foo = "foo").updateDynamic(dynProp())("babar")
    js.Dynamic.literal(foo = "bar") + js.Dynamic.literal(foobar = "babar")
```
(the `+` is fine at the moment, but still a good test case)

### PR DESCRIPTION
**Pull request by sjrd**
Yet another alternative to #4950 and #4951. This time just always wrapping object literals. No tracking overhead whatsoever, and marginal code size overhead that will be removed by JS minifiers anyway.

### CODE REVIEW

File: linker/shared/src/test/scala/org/scalajs/linker/backend/javascript/PrintersTest.scala [hunk 1]
```diff
@@ -159,6 +159,33 @@ class PrintersTest {
     )
   }
 
+  @Test def objectLitAtStartOfStatement_Issue4949(): Unit = {
```
Comment (gzm0) [inline linker/shared/src/test/scala/org/scalajs/linker/backend/javascript/PrintersTest.scala:162]: IMO here it makes more sense to simply test the expected behavior for individual trees. (somewhat whitebox testing, depending on how you look at it).

We do not need to test the specific issues we encountered on a global level: We have way better ways of testing these (end-to-end).

As it stands now, IMHO the test is hard to understand and provides little value (it's likely to be brittle in fact).

I would simply add the following two test cases:

```scala
@Test def emptyObjectLiteral(): Unit = {
  assertPrintEquals("({})", ObjectConstr(Nil))
}

@Test def objectLiteral(): Unit = {
  assertPrintEquals(
      """
        |({
        |  "foo": 1
        |})
       """,
       ObjectConstr(List(StringLiteral("foo") -> IntLiteral(1)))
  )
}
```

We might even go as far and say the `emptyObjectLiteral` test is not really useful. It is obvious that the code is doing this so why test it (that what the code is doing works on a JS level is tested elsewhere).

Further, we might say that the `objectLiteral` test should go into a different commit before: The addition / removal of the parenthesis does not really warrant unit testing IMO, but the overall object literal code does (it is non-obvious what it does and a test can help).

Does that make sense?

**Review by gzm0 — CHANGES_REQUESTED** [review]
I think we should go with this approach.

When we look at `javascript.Printers`, there are plenty of places where we put potentially unnecessary parens to make our life easier. So I don't think we should treat object literals special.

General purpose minifiers (or even formatters) will be able to get rid of these parens, so there seems little use to complicate our code for it.

All-in-all LG, just some comment about testing.

File: linker/shared/src/test/scala/org/scalajs/linker/backend/javascript/PrintersTest.scala (hunk 1 above)
Comment (sjrd) [reply linker/shared/src/test/scala/org/scalajs/linker/backend/javascript/PrintersTest.scala]: Yes, OK, that makes sense. Updated accordingly.

**Review by gzm0 — APPROVED** [review]

**Comment by gzm0** [comment]
Before I merge this: @sjrd, you agree that we should chose this PR over #4950 and #4951, right?

**Comment by gzm0** [comment]
Ah, maybe you also want to wait for #4945 because of all the checksizes.

**Comment by sjrd** [comment]
Yes, given that this is fairly niche, let's wait for #4945 to be finished and merged. It doesn't seem like any of the comments in #4945 will lead to changing the output code (other than source maps) so the checksizes shouldn't need to be re-done.
