### PR TITLE
Fix #2513: Annotate `@JSExport` with `@field @getter @setter`.

### LINKED ISSUE #2513: @JSExport does not work for abstract vals and vars
Similar to the issue #2197 which was about `@JSName`.

### PR DESCRIPTION
**Pull request by sjrd**
In addition, the compiler and the `js.use(x).as[T]` macro need to look for `@JSExport` on the getter/setter itself, if there is no accessed field. In theory, it should do so unconditionally, but backward binary compatibility demand that we still recognize exports built with a previous version of the library.

Incidentally, this provides a better fix to the old issue #970. It is not necessary to use `@(JSExport @meta.field)` for constructor parameter fields anymore.

### CODE REVIEW

**Comment by sjrd** [comment]
Review by @nicolasstucki

**Comment by nicolasstucki** [comment]
The issue number of the fix seems to be wrong, #2515 is a PR.

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSExportTest.scala [hunk 1]
```diff
@@ -291,20 +291,6 @@ class JSExportTest extends DirectTest with TestHelpers {
...
   @Test
-  def infoExportLocal: Unit = {
-
-    """
-    class A(@JSExport val x: Int)
-    """ hasErrors
-    """
-      |newSource1.scala:3: error: You may not export a local definition. To export a (case) class field, use the meta-annotation scala.annotation.meta.field like this: @(JSExport @field).
-      |    class A(@JSExport val x: Int)
-      |             ^
```
Comment (nicolasstucki) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSExportTest.scala]: Should we not keep this test with the new error message?

Comment (sjrd) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSExportTest.scala]: There is no error anymore. It now compiles. There are new positive tests for this in `ExportsTest`.

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala [hunk 2]
```diff
@@ -153,6 +153,46 @@ class ExportsTest {
...
+
+    class Bar extends Foo {
+      val x: Int = 5
+      var y: Int = 6
+    }
+
+    val bar = (new Bar).asInstanceOf[js.Dynamic]
+    assertEquals(5, bar.x)
+    assertEquals(6, bar.y)
+    bar.y = 7
```
Comment (nicolasstucki) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: What do we expect when we do `bar.x = 8`? Does this call a setter that will throw?

**Comment by nicolasstucki** [comment]
That is all.

File: compiler/src/test/scala/org/scalajs/core/compiler/test/JSExportTest.scala (hunk 1 above)
Comment (nicolasstucki) [inline compiler/src/test/scala/org/scalajs/core/compiler/test/JSExportTest.scala]: Ok

File: test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala (hunk 2 above)
Comment (sjrd) [inline test-suite/js/src/test/scala/org/scalajs/testsuite/jsinterop/ExportsTest.scala]: It depends on strict mode. Basically for a `val` the JS property has a getter but no setter. Under strict mode, trying to assign a property that has no setter causes a `TypeError`. In sloppy mode this silently fails.

It's true that we don't really have tests for that, but that's orthogonal to this PR, IMO. I've filed #2519

**Comment by sjrd** [comment]
> The issue number of the fix seems to be wrong, #2515 is a PR.

Indeed. It should be #2513.

**Comment by sjrd** [comment]
Updated the commit message to reference #2513.

**Comment by nicolasstucki** [comment]
LGTM
