### PR TITLE
Fix #3202: Format doubles exactly like on the JVM.

### LINKED ISSUE #3202: Formatter's output for e, f and g conversions differs from the JVM in some cases
As reported by @ArturSoler on Gitter:
```scala
val x = 66380.788125
"%.11f".format(x)
```
prints `66380.78812500000` on the JVM but `66380.78812500001` on JS.

JS is "more right" than the JVM in the sense that the true value of `x` is indeed closer to `...01` than `...00`. However it seems that the JVM behavior is spec'ed [in the JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html#dndec), which says:

> If the precision is less than the number of digits which would appear after the decimal point in the string returned by `Float.toString(float)` or `Double.toString(double)` respectively, then the value will be rounded using the round half up algorithm. Otherwise, zeros may be appended to reach the precision.

I think it would be possible for us to take that sentence into account to reproduce the behavior of the JVM.

### PR DESCRIPTION
**Pull request by sjrd**
We address the differences by implementing the notations ourselves, based on a decimal representation of numbers. We convert the Double values to our Decimal representation based on the native `toString()` method, which guarantees that its result contains as few digits in the significand as necessary. Once we have a `Decimal` value, we can round/rescale it as required, using the round-half-up strategy, and finally format it.

We use the opportunity to reorder the notation functions to be in the same order as the conversions they implement.

### CODE REVIEW

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 1]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+   *  `Decimal` is similar to `BigDecimal`, with some differences:
+   *
+   *  - `Decimal` distinguishes +0 from -0.
+   *  - The unscaled value of `Decimal` is stored in base 10.
+   *
+   *  The methods it exposes have the same meaning as for BigDecimal, with the
+   *  only rounding mode being HALF_UP.
+   */
+  private final class Decimal(val negative: Boolean, val unscaledValue: String,
+      val scale: Int) {
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1117]: There is one thing I do not understand here: Don't we have a degree of freedom too much? Wouldn't it be better to disallow *trailing* zeroes as well in `unscaledValue`?

**Review by gzm0 — COMMENTED** [review]
Started to look at this, just a higher level comment for now. Detailed review is *very* pending :P

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 1 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1117]: There is a degree of freedom, absolutely, and it is intentional. It is very helpful in the `decimalNotation`, for example, to be able to set the scale of Decimal to an arbitrary value, even if that requires to add trailing zeros. It is also helpful in `numberToDecimal`, where we do not have to deal with removing trailing zeros (only to perhaps add them back in the notation function). In the next PR, it is also helpful because trailing zeros are not forbidden in `BigDecimal`, which means that the conversion is easier if we accept trailing zeros as well.

Also, looking at it in the other direction: forbidding trailing zeros would not make anything simpler: there is no code path that we could simplify with the knowledge that there are no trailing zeros.

**Comment by sjrd** [comment]
> Started to look at this, just a higher level comment for now. Detailed review is _very_ pending :P

Ah ah! No problem. Take your time.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 2]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+        val rounded = roundDigitsAtPos(unscaledValue, precision)
+        val roundedLen = rounded.length()
+
+        if (roundedLen > precision) {
+          // the carry expanded all the way to a new digit
+          if (rounded.charAt(roundedLen - 1) != '0')
+            throw new AssertionError(s"$this.round($precision) caused an invalid rounding")
+          val amendedDigits = rounded.substring(0, roundedLen - 1)
+          val newScale = scale - diff - 1
+          new Decimal(negative, amendedDigits, newScale)
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1150]: Why do we do the whole string un-mangling here? IIUC `round` doesn't give any guarantees about the resulting scale (and doesn't need to).

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 3]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+  private final class Decimal(val negative: Boolean, val unscaledValue: String,
+      val scale: Int) {
+
+    def isZero: Boolean = unscaledValue == "0"
+
+    /** The number of digits in the unscaled value.
+     *
+     *  The precision of a zero value is 1.
+     */
+    def precision: Int = unscaledValue.length()
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1125]: Instead of exposing `precision` here, consider exposing `orderOfMagnitude`. This is the only usage, but it is a value that does not depend on the internal representation (scale v.s. trailing zeroes).

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 4]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+
+    /** Returns a new Decimal instance with the same value, possibly rounded,
+     *  with the given scale.
+     *
+     *  If this is a zero value, the same value is returned (a zero value must
+     *  always have a 0 scale). Rounding may also cause the result to be a zero
+     *  value, in which case its scale must be 0 as well. Otherwise, the result
+     *  is non-zero and is guaranteed to have exactly the given new scale.
+     */
+    def setScale(newScale: Int): Decimal = {
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1166]: Have you considered something like this?

```scala
val newPrecision = unscaledValue.length() - scale + newScale

if (newPrecision <= 0) {
  Decimal.zero(negative)
} else {
  val rounded = round(newPrecision)
  assert(rounded.scale <= newScale)
  if (rounded.scale < newScale)
    new Decimal(negative, rounded.unscaledValue + strOfZeros(newScale - rounded.scale), newScale)
  else
    rounded
}
```

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 1 above)
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1117]: I still do not really have a good intuition of where the abstraction boundary of a `Decimal` lies :-/ I have added a bunch of comments of what I'm thinking, but I'm not super convinced that they are in the right direction.

Maybe my confusion comes from the different meaning of `precision` based on context (but IIUC, this is out of our hands, it's essentially `Formatter` spec).

I'll try to give this another look later today.

Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1117]: > I still do not really have a good intuition of where the abstraction boundary of a `Decimal` lies :-/

Perhaps it helps *not* to think too much about it as an *abstraction*. In this context, it's not more of an abstraction over the digits/scale than `Double` is an abstraction over mantissa/exponent. We need to break the abstraction to properly format Doubles (in `formatHexFloatingPoint`) as much as `Decimal`s (with this PR). Consider it more as a mere struct that encapsulates related values, but that doesn't give a real abstraction; the same way we consider Double as a struct of (sign, mantissa, exponent).

> Maybe my confusion comes from the different meaning of `precision` based on context (but IIUC, this is out of our hands, it's essentially `Formatter` spec).

Perhaps. Just as a recap:
* For `%e`, the precision is the number of digits after the `.`, knowing that only exactly 1 digit will be before; it therefore corresponds to `unscaledValue.length() - 1` of a `Decimal`.
* For `%f`, the precision is the number of digits *after* the `.`; it therefore directly corresponds the notion of *scale* of a `Decimal`.
* For `%g`, the precision is the total number of significant digits, whether they appear on the left or on the right of a `.`. It therefore corresponds to `unscaledValue.length()` of a `Decimal`.

`setScale` can be used to fix the scale. `round` can be used to fix the `unscaledValue.length` (which is called `precision` in `Decimal` because that's its name in `BigDecimal`).

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 3 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1125]: I wanted to stick to the concepts that `BigDecimal` defines. I can expose `orderOfMagnitude`, but I still need to talk about the concept of `precision` to specify `round`, for example. So I'm not sure hiding it is going to help.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 5]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+    def precision: Int = unscaledValue.length()
+
+    /** Rounds the number so that it has at most the given precision, i.e., at
+     *  most the given number of digits in its `unscaledValue`.
+     *
+     *  The given `precision` must be greater than 0.
+     */
+    def round(precision: Int): Decimal = {
+      if (precision <= 0)
+        throw new AssertionError("Decimal.round() called with non-positive precision")
```
[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1134]: We don't have `Predef` and we're not supposed to use more Scala APIs in the javalib. ;)

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 2 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1150]: It does give a guarantee about the `precision`, though. If we don't do this, it can return a `Decimal` whose `precision` (`unscaledValue.length()`) is > the `precision` parameter, breaking the spec of this method.

That spec is useful in `scientificNotation` because it means we only ever need to *pad* with missing zeros at the end, and not to truncate the `unscaledValue`.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 6]
```diff
@@ -1014,6 +1043,201 @@ object Formatter {
...
+          // the carry expanded all the way to a new digit
+          if (rounded.charAt(roundedLen - 1) != '0')
+            throw new AssertionError(s"$this.round($precision) caused an invalid rounding")
+          val amendedDigits = rounded.substring(0, roundedLen - 1)
+          val newScale = scale - diff - 1
+          new Decimal(negative, amendedDigits, newScale)
+        } else {
+          val newScale = scale - diff
+          new Decimal(negative, rounded, newScale)
+        }
```
[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1154]: I'll play around with that suggestion.

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 4 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1166]: Hum, I have not. I'll play around with that as well.

Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1166]: This is the simplest I could make `setScale` to be if implemented on top of `round`:
```scala
    def setScale(newScale: Int): Decimal = {
      val targetPrecision = precision + newScale - scale

      if (targetPrecision < 0) {
        Decimal.zero(negative)
      } else if (targetPrecision == 0) {
        // Weird case: handle 0.3 -> 0 and 0.7 -> 1 (round cannot do this)
        if (unscaledValue.charAt(0) < '5')
          Decimal.zero(negative)
        else
          new Decimal(negative, "1", newScale)
      } else {
        val rounded = this.round(targetPrecision)
        // Assert: rounded.isZero || rounded.scale <= newScale
        if (rounded.isZero || rounded.scale == newScale)
          rounded
        else
          new Decimal(negative, rounded.unscaledValue + strOfZeros(newScale - rounded.scale), newScale)
      }
    }
```
I am not sure at all that this is simpler than the previous version.

Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1166]: Hmmm... It is definitely not. Would it get simpler if we made an internal `roundAtPos` that allowed at `0`? (and `round` could basically forward to that one).

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1134]: Should we create a helper? IMO it is much easier to understand.

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 1 above)
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1117]: Yeah, I think that makes sense. So let's keep it as is.

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 3 above)
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1125]: Yeah, that's fair. Maybe consider simply not defining this helper and use `unscaledValue.length()` at the call site (not 100% sure this is better).

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 4 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1156]: Well, that required quite a bit of refactoring, but it worked. I pushed a new commit with a simplified implementation of `round` and `setScale` in terms of a `roundAtPos`.

In addition, I renamed the `precision` parameter of `scientificNotation` and `decimalNotation` to make them clearer, so that we don't overload `precision`.

Does it help?

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 7]
```diff
@@ -945,6 +946,34 @@ object Formatter {
...
+      var result = ""
+      var remaining = count
+      while (count > StrsOfZerosMax) {
+        result += StrsOfZeros(StrsOfZerosMax)
+        remaining -= StrsOfZerosMax
+      }
+      result + StrsOfZeros(remaining)
+    }
+  }
+
```
[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:985]: We can't have a single constant string here, because there is no reasonable bound on the number of zeros that we need. Consider for example `String.format("%.1000f", 1.0)`, which would need 1000 zeros.

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 3 above)
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:1134]: Hopefully, now that I've renamed the conflicting uses of "precision", this shouldn't be an issue anymore.

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 7 above)
[the remark this answers is not in the document]
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:985]: Ah sorry, I meant the `StrsOfZeroes` more specifically. Wouldn't it be sufficient to create a single zero string with `StrsOfZerosMax` zeroes? (we'll still need `strOfZeroes` of course).

[the remark this answers is not in the document]
Comment (sjrd) [reply javalib/src/main/scala/java/util/Formatter.scala:985]: Yes, we could do that as well, indeed.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 8]
```diff
@@ -693,8 +703,8 @@ final class Formatter private (private[this] var dest: Appendable,
         val padded = "0000000000000".substring(baseStr.length()) + baseStr // 13 zeros
 
         // Assert: padded.length == 13 == mbits / 4
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:705]: Not sure the comment is still needed.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 9]
```diff
@@ -945,6 +955,27 @@ object Formatter {
...
+      result + twentyZeros.substring(0, remaining)
+    }
+  }
+
+  @inline
+  private def assert(condition: Boolean, msg: => String): Unit = {
+    if (!condition)
+      throw new AssertionError(msg)
+  }
+
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:978]: For now this is fine, but I think it should go into some util, just like for javalanglib.

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 10]
```diff
@@ -1014,6 +1045,182 @@ object Formatter {
...
+     *
+     *  If this is a zero value, the same value is returned (a zero value must
+     *  always have a 0 scale). Rounding may also cause the result to be a zero
+     *  value, in which case its scale must be 0 as well. Otherwise, the result
+     *  is non-zero and is guaranteed to have exactly the given new scale.
+     */
+    def setScale(newScale: Int): Decimal = {
+      val roundingPos = unscaledValue.length() + newScale - scale
+      val rounded = roundAtPos(roundingPos)
+      // Assert: rounded.isZero || rounded.scale <= newScale
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1151]: Actually assert?

File: javalib/src/main/scala/java/util/Formatter.scala (hunk 4 above)
Comment (gzm0) [reply javalib/src/main/scala/java/util/Formatter.scala:1148]: Yes. TY :)

File: javalib/src/main/scala/java/util/Formatter.scala [hunk 11]
```diff
@@ -1014,6 +1045,182 @@ object Formatter {
...
+          // Find the position of the last non-9 digit in the truncated digits (can be -1)
+          var lastNonNinePos = roundingPos - 1
+          while (lastNonNinePos >= 0 && digits.charAt(lastNonNinePos) == '9')
+            lastNonNinePos -= 1
+
+          val newUnscaledValue =
+            if (lastNonNinePos < 0) "1"
+            else digits.substring(0, lastNonNinePos) + (digits.charAt(lastNonNinePos) + 1).toChar
+
+          val newScale = scaleAtPos(lastNonNinePos + 1)
```
Comment (gzm0) [inline javalib/src/main/scala/java/util/Formatter.scala:1207]: Hah, it's kind of cool that the underflow at `-1` is actually meaningful here :)

**Review by gzm0 — APPROVED** [review]
