### PR TITLE
Fix #3880: Align ScalaJSCrossVersion with ScalaJSVersions

### LINKED ISSUE #3880: ScalaJSCrossVersion is inconsistent with ScalaJSVersions
ScalaJSVersions does not have a patch part in the binary version, however ScalaJSCrossVersion wants one.

Further, it seems that with the current setup, we'd emit `sjs1.0` as a suffix. IIUC this is wrong and we should emit simply `sjs1` as the minor part should be backwards compatible.

### PR DESCRIPTION
**Pull request by gzm0**
Since we dropped the patch version in the `binaryEmitted` version, the regex parsing in `ScalaJSCrossVersion` was wrong.

We move the entire parsing and translation logic into `VersionChecks` where we can properly test it and it is more easily available to non-sbt consumers.

Note that this introduces a behavioral change: Minor pre-release versions are cross versioned with their full version, not their major version only.

### CODE REVIEW

File: ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala [hunk 1]
```diff
@@ -34,6 +34,11 @@ class VersionChecks private[ir] (
 
   private val (binaryMajor, binaryMinor, binaryPreRelease) = parseBinary(binaryEmitted)
 
+  /** The binary version as advertised in released artifacts. */
+  final val binaryVersion =
```
Comment (sjrd) [inline ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala]: This does not strike me as a very good name. Essentially this is the version of the ecosystem of libraries. Perhaps name it `ecosystemVersion`? Or `artifactsVersion`?

Comment (gzm0) [reply ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala]: I guess `binaryVersion` is sbt jargon (`CrossVersion.binary` vs `CrossVersion.full`). How would you feel about `binaryCross`? (the `Version` suffix is pointless anyways; everything is a version in this class...).

Comment (sjrd) [reply ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala]: Yeah `binaryCross` sounds reasonable.

Comment (gzm0) [reply ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala]: What shall we do about `ScalaJSCrossVersion.currentBinaryVersion`? Remove?

**Comment by gzm0** [comment]
Oh, also I just noticed that this PR changes the behavior for minor pre-release versions. I guess one could argue both ways:

- Pre-release *should* be binary compatible.
- Pre-release is not stable enough and errors could be there.

WDYT?

File: ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala (hunk 1 above)
Comment (sjrd) [reply ir/src/main/scala/org/scalajs/ir/ScalaJSVersions.scala]: Yes. Google and GitHub searches say that no one uses that.

**Comment by sjrd** [comment]
> Oh, also I just noticed that this PR changes the behavior for minor pre-release versions. I guess one could argue both ways:
>
> * Pre-release should be binary compatible.
> * Pre-release is not stable enough and errors could be there.
>
> WDYT?

Hum, I don't think this change is desirable. When working with 1.2.0-SNAPSHOT, I expect to be able to resolve libraries published with 1.1.x. I shouldn't *publish* myself from that version, but that's not specific to Scala.js.

**Comment by gzm0** [comment]
Updated and fully documented what I think the reasons for all these things are :P
