### PR TITLE
Fix #2927: Fail on assertEquals on floats/doubles

### LINKED ISSUE #2927: JUnit assertEquals(_: Double, _:Double) not failing for JS, only for JVM
For JVM it gives:

`Use assertEquals(expected, actual, delta) to compare floating-point numbers`

but it does not fail for the Scala.Js version.

### PR DESCRIPTION
**Pull request by gzm0**
#2960 needs to go in first and the issues discussed in https://github.com/scala-js/scala-js/issues/2927#issuecomment-302926675 need to be solved.

### CODE REVIEW

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 1]
```diff
@@ -47,35 +55,131 @@ abstract class JUnitTest {
...
+    lazy val logExceptionClass: Boolean = !args.contains("-c")
+    lazy val logAssert: Boolean = args.contains("-a")
 
-    lazy val verbose: Boolean = frameworkArgs.contains("-v")
-    lazy val noColor: Boolean = frameworkArgs.contains("-n")
-    lazy val quiet: Boolean = frameworkArgs.contains("-q")
-    lazy val decodeScalaNames: Boolean = frameworkArgs.contains("-s")
-    lazy val notLogExceptionClass: Boolean = frameworkArgs.contains("-c")
-    lazy val logAssert: Boolean = frameworkArgs.contains("-a")
+    override def toString: String = args.mkString("[", ", ", "]")
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: `toString()` with `()`, as per https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#method-definition

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 2]
```diff
@@ -47,35 +55,131 @@ abstract class JUnitTest {
...
+        testIgnoredOutput(testName),
+        skippedEvent
+    )
+
+    def ignoredClass(): OutputBuilder = append(0, 1, 0)(
+        testIgnoredClassOutput,
+        skippedEvent
+    )
+
+    def assumptionViolated(testName: String) = append(1, 0, 0)(
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Public method needs explicit result type.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 3]
```diff
@@ -90,27 +194,26 @@ abstract class JUnitTest {
     def testIgnoredClassOutput: Output =
       Info(s"Test $formattedTestClass ignored")
 
-    def testExceptionMsgOutput(method: String, msg: String, exPack: String,
+    def testExceptionMsgOutput(method: String, msg: String,
         exClass: String): Output = {
-      val exClassStr =
-        if (notLogExceptionClass) ""
-        else ' ' + exPack + '.' + red(exClass) + ':'
+      val exClassStr = exceptionClassInfo(logExceptionClass,  exClass)
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Double space after `,`

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 4]
```diff
@@ -137,12 +241,22 @@ abstract class JUnitTest {
...
+    def formattedTestClass: String = formatClass(suiteUnderTestName, yellow)
+
+    private def exceptionClassInfo(show: Boolean, fullName: String) = {
+      if (show) formatClass(fullName, red) + ": "
+      else ""
+    }
+
+    private def formatClass(fullName: String, color: String => String) = {
+      val (pack, cls) = fullName.splitAt(fullName.lastIndexOf('.'))
+      pack + '.' + color(cls.tail)
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: If you split right after the dot rather than right before it, it's a bit easier:
```scala
val (packAndDot, cls) = fullName.splitAt(fullName.lastIndexOf('.') + 1)
packAndDot + color(cls)
```

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 5]
```diff
@@ -47,35 +55,131 @@ abstract class JUnitTest {
...
+    private def append(t: Int, i: Int, f: Int)(out: Output*) = {
+      new OutputBuilder(argInfo, total + t, ignored + i, failed + f, output ++ out)
+    }
+
+    // Test method.
+
+    private[JUnitTest] def checkOutput(actual: List[Output]): Unit = {
+      val expected = (
+          testRunStartedOutput :: output :::
+          List(testRunFinishedOutput(total, ignored, failed), done)
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Consider using `::`s all the way, instead of using the `List()` constructor for part of it. Maybe format it as follows?
```scala
      val expected = (
          testRunStartedOutput ::
          output :::
          testRunFinishedOutput(total, ignored, failed) ::
          done ::
          Nil
      )
```

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 6]
```diff
@@ -47,35 +55,131 @@ abstract class JUnitTest {
...
+        appendElems(actual, actualMinimized)
+        msg.append(")")
+  
+        throw new Exception(msg.result())
+      }
+    }
+
+    // Text builders.
 
     def done: Output = Done("")
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Looks like the methods returning `Output`s could become private, couldn't they? Maybe even `Output` itself can become private?

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 7]
```diff
@@ -90,27 +194,26 @@ abstract class JUnitTest {
...
-          s"failed:$exClassStr $msg, took $TIME_TAG sec")
+          s"failed: $exClassStr$msg, took $TIME_TAG sec")
     }
 
     def testAssertionErrorMsgOutput(method: String, msg: String): Output = {
-      val assertClass =
-        if (notLogExceptionClass || !logAssert) ""
-        else  " java.lang." + red("AssertionError") + ':'
-      Error(s"Test $formattedTestClass.${red(method)} failed:$assertClass " +
+      val assertClass = exceptionClassInfo(logExceptionClass && logAssert,
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Consider explicitly writing `show =`.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 8]
```diff
@@ -90,27 +194,26 @@ abstract class JUnitTest {
...
+          "java.lang.AssertionError")
+      Error(s"Test $formattedTestClass.${red(method)} failed: $assertClass" +
           s"$msg, took $TIME_TAG sec")
     }
 
     def testAssumptionViolatedOutput(method: String): Output = {
+      val exceptionStr = exceptionClassInfo(logExceptionClass,
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Consider explicitly writing `show =`.

File: junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala [hunk 9]
```diff
@@ -1,25 +0,0 @@
...
-    import context._
-    List(
-        testRunStartedOutput,
-        testStartedOutput("onlyTest"),
-        testFinishedOutput("onlyTest"),
-        successEvent,
-        testRunFinishedOutput,
-        done
-    )
-  }
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala]: Why is this test removed?

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 10]
```diff
@@ -130,55 +130,94 @@ abstract class JUnitTest {
...
+        }
+
+        msg.append("but got: List(\n")
+
+        val maxLen = expecteds.map(_.size).max
+
+        matched.takeRight(3).foreach(out =>
+          msg.append(GREY + "  " + withoutColor(out.toString) + NORMAL + "\n"))
+        remaining.take(maxLen).foreach(appendOut)
         msg.append(")")
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: What does this look like, once rendered?

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala [hunk 11]
```diff
@@ -130,55 +130,94 @@ abstract class JUnitTest {
...
+          expected.foreach(appendOut)
+          msg.append(")\n\n")
+        }
+
+        msg.append("but got: List(\n")
+
+        val maxLen = expecteds.map(_.size).max
+
+        matched.takeRight(3).foreach(out =>
+          msg.append(GREY + "  " + withoutColor(out.toString) + NORMAL + "\n"))
```
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Consider a for:
```scala
for (out <- matched.takeRight(3))
  msg.append(GREY + "  " + withoutColor(out.toString) + NORMAL + "\n")
```
According to https://github.com/scala-js/scala-js/blob/master/CODINGSTYLE.md#method-call-style, the `()`+`=>` association only works if it fits entirely on the same line.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 5 above)
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Well, since that disappears in a subsequent commit anyway, never mind that comment.

File: junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala (hunk 9 above)
Comment (gzm0) [inline junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala]: It is useless because:

- Testing a tests is something that is rarely done (when do you stop?)
- It doesn't even do this. Testing a test would mean to verify that a test fails if the code under test doesn't satisfy the conditions. This test definitely doesn't do that.
- Other tests test this as well.

I'm having the impression that this is just a relic from when the JUnit testing harness got bootstrapped.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 4 above)
Comment (gzm0) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Hum... This swallows the first letter of `cls`...

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 10 above)
Comment (gzm0) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: This is what it looks when I change an `assertTrue(false)` to `assertTrue(true)`.

screen shot 2017-05-21 at 1 55 55 am

**Comment by gzm0** [comment]
Updated. I still need to fix all the places in our test suite where we use the `assertEquals` that now fails.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 4 above)
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Huh!? Did you forget to remove the `.tail` of `cls.tail`? If not I don't know why my suggestion is wrong :s

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 10 above)
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Ah nice :)

File: junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala (hunk 9 above)
Comment (sjrd) [inline junit-test/shared/src/test/scala/org/scalajs/junit/TestTest.scala]: OK makes sense.

File: junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala (hunk 4 above)
Comment (gzm0) [inline junit-test/shared/src/test/scala/org/scalajs/junit/utils/JUnitTest.scala]: Duh... of course I did :P

**Comment by gzm0** [comment]
This is ready for review now.

**Comment by gzm0** [comment]
Updated (adjusted failing tests).
